### Fide historical calculation for sample playes

In [ ]:
import pandas as pd
import numpy as np
import re
import time
from pathlib import Path
from bs4 import BeautifulSoup
from io import StringIO
from playwright.async_api import async_playwright

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 2000)
pd.set_option("display.max_colwidth", None)

#### Test extraction from Fide website

In [97]:

fide_id = "25977890"   # Amartya
rating_type = 0        # 0 = Standard, 1 = Rapid, 2 = Blitz

start_period = "2024-01-01"
end_period = "2026-05-01"

periods = pd.date_range(start_period, end_period, freq="MS")

output_dir = Path.home() / "Downloads" / "fide_history" / "amartya_calculations"
output_dir.mkdir(parents=True, exist_ok=True)

print("Months to process:", len(periods))
print(periods)

Months to process: 29
DatetimeIndex(['2024-01-01', '2024-02-01', '2024-03-01', '2024-04-01', '2024-05-01', '2024-06-01', '2024-07-01', '2024-08-01', '2024-09-01', '2024-10-01', '2024-11-01', '2024-12-01', '2025-01-01', '2025-02-01', '2025-03-01', '2025-04-01', '2025-05-01', '2025-06-01', '2025-07-01', '2025-08-01', '2025-09-01', '2025-10-01', '2025-11-01', '2025-12-01', '2026-01-01', '2026-02-01', '2026-03-01', '2026-04-01', '2026-05-01'], dtype='datetime64[ns]', freq='MS')

In [23]:
def extract_event_metadata_from_text(text_lines):
    """
    Finds tournament blocks before each Rc/Ro/w/n/chg/K/K*chg table.
    Expected pattern:
    tournament_name
    CITY FED
    start_date
    end_date
    Rc
    Ro
    ...
    """
    events = []

    for i, line in enumerate(text_lines):
        if line == "Rc":
            if i >= 4:
                event_name = text_lines[i - 4]
                location_fed = text_lines[i - 3]
                start_date = text_lines[i - 2]
                end_date = text_lines[i - 1]

                # Validate dates lightly
                if re.match(r"^\d{4}-\d{2}-\d{2}$", start_date) and re.match(r"^\d{4}-\d{2}-\d{2}$", end_date):
                    events.append({
                        "tournament_name": event_name,
                        "event_location_fed": location_fed,
                        "event_start_date": start_date,
                        "event_end_date": end_date
                    })

    return events


def clean_fide_calculation_table(table, event_meta, fide_id, period, rating_type=0):
    """
    Cleans one FIDE calculation table from rendered page.
    Output = one row per opponent game.
    """

    df = table.copy()

    # Keep first 10 useful columns only
    df = df.iloc[:, :10].copy()

    # Need at least summary + opponent rows
    if df.shape[0] < 4:
        return pd.DataFrame()

    # Row 1 usually contains event summary
    summary = df.iloc[1]

    event_rc = pd.to_numeric(summary.iloc[0], errors="coerce")
    event_ro = pd.to_numeric(summary.iloc[1], errors="coerce")
    event_score = pd.to_numeric(summary.iloc[5], errors="coerce")
    event_games = pd.to_numeric(summary.iloc[6], errors="coerce")
    event_chg = pd.to_numeric(summary.iloc[7], errors="coerce")
    event_k = pd.to_numeric(summary.iloc[8], errors="coerce")
    event_kchg = pd.to_numeric(summary.iloc[9], errors="coerce")

    # Opponent rows generally start after header, summary, blank row
    opponent_df = df.iloc[3:].copy()

    opponent_df.columns = [
        "opponent_name",
        "opponent_title_1",
        "opponent_title_2",
        "opponent_rating_raw",
        "opponent_fed",
        "score",
        "n",
        "chg",
        "k",
        "k_chg"
    ]

    # Remove empty rows
    opponent_df = opponent_df[opponent_df["opponent_name"].notna()].copy()

    # Remove footnote rows
    opponent_df = opponent_df[
        ~opponent_df["opponent_name"].astype(str).str.contains(
            "Rating difference", case=False, na=False
        )
    ].copy()

    # Federation must be valid 3-letter code
    opponent_df["opponent_fed"] = opponent_df["opponent_fed"].astype(str).str.strip()

    opponent_df = opponent_df[
        opponent_df["opponent_fed"].str.match(r"^[A-Z]{3}$", na=False)
    ].copy()

    if opponent_df.empty:
        return pd.DataFrame()

    # Combine title columns
    opponent_df["opponent_title"] = (
        opponent_df[["opponent_title_1", "opponent_title_2"]]
        .astype(str)
        .replace("nan", "", regex=False)
        .agg(" ".join, axis=1)
        .str.strip()
    )

    opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

    # Flag 400+ rating difference note
    opponent_df["rating_difference_over_400_flag"] = (
        opponent_df["opponent_rating_raw"]
        .astype(str)
        .str.contains(r"\*", regex=True, na=False)
    )

    # Clean opponent rating
    opponent_df["opponent_rating"] = (
        opponent_df["opponent_rating_raw"]
        .astype(str)
        .str.replace("*", "", regex=False)
        .str.strip()
    )

    opponent_df["opponent_rating"] = pd.to_numeric(
        opponent_df["opponent_rating"], errors="coerce"
    )

    # Numeric columns
    for col in ["score", "n", "chg", "k", "k_chg"]:
        opponent_df[col] = pd.to_numeric(opponent_df[col], errors="coerce")

    # Add player/month/event fields
    opponent_df["fide_id"] = str(fide_id)
    opponent_df["period"] = period
    opponent_df["rating_type"] = rating_type

    opponent_df["tournament_name"] = event_meta.get("tournament_name")
    opponent_df["event_location_fed"] = event_meta.get("event_location_fed")
    opponent_df["event_start_date"] = event_meta.get("event_start_date")
    opponent_df["event_end_date"] = event_meta.get("event_end_date")

    opponent_df["event_rc"] = event_rc
    opponent_df["event_ro"] = event_ro
    opponent_df["event_score"] = event_score
    opponent_df["event_games"] = event_games
    opponent_df["event_chg"] = event_chg
    opponent_df["event_k"] = event_k
    opponent_df["event_k_chg"] = event_kchg

    keep_cols = [
        "fide_id", "period", "rating_type",
        "tournament_name", "event_location_fed",
        "event_start_date", "event_end_date",
        "event_rc", "event_ro", "event_score", "event_games",
        "event_chg", "event_k", "event_k_chg",
        "opponent_name", "opponent_title", "opponent_rating",
        "rating_difference_over_400_flag",
        "opponent_fed", "score", "n", "chg", "k", "k_chg"
    ]

    return opponent_df[keep_cols].reset_index(drop=True)

In [4]:
all_months_clean = []
month_status = []

async with async_playwright() as p:
    browser = await p.chromium.launch(headless=True)
    page = await browser.new_page()

    for period in periods:
        period_str = period.strftime("%Y-%m-%d")

        url = (
            "https://ratings.fide.com/calculations.phtml"
            f"?id_number={fide_id}&period={period_str}&rating={rating_type}"
        )

        print("\nProcessing:", period_str)
        print(url)

        try:
            await page.goto(url, wait_until="networkidle", timeout=60000)
            await page.wait_for_timeout(3000)

            html = await page.content()

            # Save rendered HTML for audit/debug
            html_path = output_dir / f"rendered_{period_str}_standard.html"
            html_path.write_text(html, encoding="utf-8")

            # Optional screenshot for months with data/debugging
            # screenshot_path = output_dir / f"rendered_{period_str}_standard.png"
            # await page.screenshot(path=str(screenshot_path), full_page=True)

            soup = BeautifulSoup(html, "html.parser")

            text_lines = [
                line.strip()
                for line in soup.get_text("\n", strip=True).split("\n")
                if line.strip()
            ]

            try:
                tables = pd.read_html(StringIO(html))
            except ValueError:
                tables = []

            events = extract_event_metadata_from_text(text_lines)

            print("Tables found:", len(tables))
            print("Events found:", len(events))

            clean_tables = []

            for i, table in enumerate(tables):
                event_meta = events[i] if i < len(events) else {}

                clean_one = clean_fide_calculation_table(
                    table=table,
                    event_meta=event_meta,
                    fide_id=fide_id,
                    period=period_str,
                    rating_type=rating_type
                )

                if not clean_one.empty:
                    clean_tables.append(clean_one)

            if clean_tables:
                month_clean = pd.concat(clean_tables, ignore_index=True)

                all_months_clean.append(month_clean)

                print("Clean opponent rows:", month_clean.shape[0])
                print(month_clean[[
                    "period", "tournament_name", "opponent_name",
                    "opponent_rating", "opponent_fed", "score", "chg", "k_chg"
                ]].head(10).to_string(index=False))

                month_status.append({
                    "period": period_str,
                    "url": url,
                    "tables_found": len(tables),
                    "events_found": len(events),
                    "clean_rows": month_clean.shape[0],
                    "status": "data_found"
                })

            else:
                print("No clean rows for this month.")

                month_status.append({
                    "period": period_str,
                    "url": url,
                    "tables_found": len(tables),
                    "events_found": len(events),
                    "clean_rows": 0,
                    "status": "no_data_or_no_clean_rows"
                })

            await page.wait_for_timeout(1500)

        except Exception as e:
            print("Failed:", period_str, repr(e))

            month_status.append({
                "period": period_str,
                "url": url,
                "tables_found": None,
                "events_found": None,
                "clean_rows": 0,
                "status": "failed",
                "error": repr(e)
            })

    await browser.close()

Processing: 2024-01-01
https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2024-01-01&rating=0
Tables found: 3
Events found: 3
Clean opponent rows: 24
    period                                                     tournament_name    opponent_name  opponent_rating opponent_fed  score   chg  k_chg
2024-01-01 Bijnor Open FIDE Rated Chess Tournament - UP Booster Series (Vol I)  Kshitika, Tyagi           1010.0          IND    1.0  0.10   2.90
2024-01-01 Bijnor Open FIDE Rated Chess Tournament - UP Booster Series (Vol I)     Dhruv, Gupta           1191.0          IND    1.0  0.26   7.54
2024-01-01 Bijnor Open FIDE Rated Chess Tournament - UP Booster Series (Vol I)   Nikhil, Chopra           1197.0          IND    1.0  0.27   7.83
2024-01-01 Bijnor Open FIDE Rated Chess Tournament - UP Booster Series (Vol I)    Vatsal, Makol           1477.0          IND    0.5  0.14   4.06
2024-01-01 Bijnor Open FIDE Rated Chess Tournament - UP Booster Series (Vol I)      Rahul, Suri           1185.0          IND    1.0  0.25   7.25
2024-01-01 Bijnor Open FIDE Rated Chess Tournament - UP Booster Series (Vol I) Mohammad, Sameed           1468.0          IND    0.5  0.13   3.77
2024-01-01                      36th National Under-13 Chess Championship-2023 Chinmay, Kowshik           1760.0          IND    0.0 -0.09  -2.61
2024-01-01                      36th National Under-13 Chess Championship-2023    Agham, Surana           1137.0          IND    1.0  0.20   5.80
2024-01-01                      36th National Under-13 Chess Championship-2023       Haridev, S           1722.0          IND    1.0  0.89  25.81
2024-01-01                      36th National Under-13 Chess Championship-2023    Sagnik, Dutta           1520.0          IND    0.0 -0.31  -8.99

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_87612/1844044716.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_87612/1844044716.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_87612/1844044716.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan)

Processing: 2024-02-01
https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2024-02-01&rating=0
Tables found: 1
Events found: 1
Clean opponent rows: 8
    period                                            tournament_name      opponent_name  opponent_rating opponent_fed  score   chg  k_chg
2024-02-01 2nd Matrix International Open FIDE Rating Chess Tournament     Kavyansh, Jain           1125.0          IND    1.0  0.11    4.4
2024-02-01 2nd Matrix International Open FIDE Rating Chess Tournament Anant, Singh Dagar           1217.0          IND    1.0  0.19    7.6
2024-02-01 2nd Matrix International Open FIDE Rating Chess Tournament       Aansh, Gupta           1991.0          IND    1.0  0.97   38.8
2024-02-01 2nd Matrix International Open FIDE Rating Chess Tournament    Pradeep, Tiwari           1809.0          IND    0.5  0.38   15.2
2024-02-01 2nd Matrix International Open FIDE Rating Chess Tournament     Ashok, Gajwani           1853.0          IND    0.0 -0.09   -3.6
2024-02-01 2nd Matrix International Open FIDE Rating Chess Tournament       Parth, Gupta           1285.0          IND    0.0 -0.74  -29.6
2024-02-01 2nd Matrix International Open FIDE Rating Chess Tournament   Viaan, Jai Singh           1181.0          IND    1.0  0.15    6.0
2024-02-01 2nd Matrix International Open FIDE Rating Chess Tournament     Aditya, Saxena           1231.0          IND    1.0  0.20    8.0

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_87612/1844044716.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan)

Processing: 2024-03-01
https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2024-03-01&rating=0
Tables found: 2
Events found: 2
Clean opponent rows: 16
    period                                                 tournament_name     opponent_name  opponent_rating opponent_fed  score   chg  k_chg
2024-03-01               National School Chess Championship 2023-24 (U13O)     Reddi, Satwik           1114.0          IND    1.0  0.08    3.2
2024-03-01               National School Chess Championship 2023-24 (U13O)     Nikhil, Kumar           1284.0          IND    0.5 -0.29  -11.6
2024-03-01               National School Chess Championship 2023-24 (U13O)  Tejas, Shandilya           1216.0          IND    1.0  0.14    5.6
2024-03-01               National School Chess Championship 2023-24 (U13O)  Swapnabha, Neogi           1239.0          IND    0.5 -0.34  -13.6
2024-03-01               National School Chess Championship 2023-24 (U13O)  Devansh, Rathore           1206.0          IND    1.0  0.14    5.6
2024-03-01               National School Chess Championship 2023-24 (U13O)     Mahir, Taneja           1591.0          IND    0.5  0.10    4.0
2024-03-01               National School Chess Championship 2023-24 (U13O)    Joe, Gladson L           1147.0          IND    1.0  0.10    4.0
2024-03-01               National School Chess Championship 2023-24 (U13O)        Reyan, Md.           1836.0          IND    0.0 -0.13   -5.2
2024-03-01 11th National Amateur Chess Championship 2023-24 for Below 2300     Dawda, Vihaan           1715.0          IND    1.0  0.75   30.0
2024-03-01 11th National Amateur Chess Championship 2023-24 for Below 2300 Chaudhari, Ashish           1667.0          IND    0.0 -0.30  -12.0

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_87612/1844044716.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_87612/1844044716.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan)

Processing: 2024-04-01
https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2024-04-01&rating=0
Tables found: 1
Events found: 1
Clean opponent rows: 8
    period                                                    tournament_name        opponent_name  opponent_rating opponent_fed  score   chg  k_chg
2024-04-01 Bijnor Open FIDE Rated Chess Tournament  UP Booster Series (Vol-2)       Tulsani, Manas           1527.0          IND    1.0  0.24    9.6
2024-04-01 Bijnor Open FIDE Rated Chess Tournament  UP Booster Series (Vol-2)      Rakshak, Ruhela           1617.0          IND    1.0  0.34   13.6
2024-04-01 Bijnor Open FIDE Rated Chess Tournament  UP Booster Series (Vol-2)        Balkishan, A.           2107.0          IND    0.0 -0.10   -4.0
2024-04-01 Bijnor Open FIDE Rated Chess Tournament  UP Booster Series (Vol-2)        Srikar, G V B           1571.0          IND    0.5 -0.21   -8.4
2024-04-01 Bijnor Open FIDE Rated Chess Tournament  UP Booster Series (Vol-2)      Abhibhav, Kumar           1582.0          IND    0.5 -0.20   -8.0
2024-04-01 Bijnor Open FIDE Rated Chess Tournament  UP Booster Series (Vol-2)  Ravi, Prakash Singh           1658.0          IND    0.5 -0.10   -4.0
2024-04-01 Bijnor Open FIDE Rated Chess Tournament  UP Booster Series (Vol-2)      Abheesth, Khare           1510.0          IND    1.0  0.22    8.8
2024-04-01 Bijnor Open FIDE Rated Chess Tournament  UP Booster Series (Vol-2) Vinayak, Singh Yadav           1696.0          IND    0.0 -0.55  -22.0

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_87612/1844044716.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan)

Processing: 2024-05-01
https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2024-05-01&rating=0
Tables found: 2
Events found: 2
Clean opponent rows: 17
    period                                                    tournament_name         opponent_name  opponent_rating opponent_fed  score   chg  k_chg
2024-05-01                      43rd National Team Chess Championship 2023-24    Jval, Saurin Patel           1934.0          IND    0.0 -0.24   -9.6
2024-05-01                      43rd National Team Chess Championship 2023-24        Shivraj, Meena           1546.0          IND    0.0 -0.74  -29.6
2024-05-01                      43rd National Team Chess Championship 2023-24      Jess, Ruchandani           1733.0          IND    1.0  0.50   20.0
2024-05-01                      43rd National Team Chess Championship 2023-24      Arshpreet, Singh           1902.0          IND    1.0  0.72   28.8
2024-05-01                      43rd National Team Chess Championship 2023-24         Gourav, Nigam           1995.0          IND    0.0 -0.18   -7.2
2024-05-01                      43rd National Team Chess Championship 2023-24    Jashanpreet, Singh           1830.0          IND    0.5  0.13    5.2
2024-05-01                      43rd National Team Chess Championship 2023-24   Ashutosh, Mohapatra           1924.0          IND    0.0 -0.25  -10.0
2024-05-01                      43rd National Team Chess Championship 2023-24     Srinivasa Rao, M.           2059.0          IND    0.5  0.37   14.8
2024-05-01                      43rd National Team Chess Championship 2023-24 Sriram, Adarsh Uppala           2133.0          IND    0.0 -0.08   -3.2
2024-05-01 3rd Matrix Cup International Open Fide Rated Chess Tournament 2024          Dhruv, Kumar           1423.0          IND    1.0  0.15    6.0

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_87612/1844044716.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan)

Processing: 2024-06-01
https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2024-06-01&rating=0
Tables found: 1
Events found: 1
Clean opponent rows: 8
    period                     tournament_name       opponent_name  opponent_rating opponent_fed  score   chg  k_chg
2024-06-01 Delhi State Chess Championship-2024     Mayank, Jaiswal           1456.0          IND    1.0  0.18    7.2
2024-06-01 Delhi State Chess Championship-2024       Jayesh, Gupta           1519.0          IND    1.0  0.24    9.6
2024-06-01 Delhi State Chess Championship-2024       Mikki, Jhuria           1617.0          IND    0.0 -0.64  -25.6
2024-06-01 Delhi State Chess Championship-2024     Arhaan, Agrawal           1523.0          IND    1.0  0.25   10.0
2024-06-01 Delhi State Chess Championship-2024       Atharv, Vohra           1561.0          IND    0.5 -0.21   -8.4
2024-06-01 Delhi State Chess Championship-2024               Manav           1502.0          IND    0.5 -0.28  -11.2
2024-06-01 Delhi State Chess Championship-2024 Rawat, Rakesh Singh           1527.0          IND    1.0  0.25   10.0
2024-06-01 Delhi State Chess Championship-2024   Shaurya, Chaudhry           1609.0          IND    1.0  0.35   14.0

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_87612/1844044716.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan)

Processing: 2024-07-01
https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2024-07-01&rating=0
Tables found: 2
Events found: 2
Clean opponent rows: 17
    period                                                                  tournament_name           opponent_name  opponent_rating opponent_fed  score   chg  k_chg
2024-07-01                                     Jaipur Open Classical FIDE rating Tournament  Aarav, Neelkamal Gupta           1527.0          IND    0.5 -0.25  -10.0
2024-07-01                                     Jaipur Open Classical FIDE rating Tournament Nikhil, Kumar Chaudhary           1499.0          IND    1.0  0.22    8.8
2024-07-01                                     Jaipur Open Classical FIDE rating Tournament           Dahale, Rajas           1608.0          IND    0.5 -0.15   -6.0
2024-07-01                                     Jaipur Open Classical FIDE rating Tournament         Pratyush, Kumar           1590.0          IND    1.0  0.33   13.2
2024-07-01                                     Jaipur Open Classical FIDE rating Tournament     Shrivastava, Manish           1572.0          IND    1.0  0.30   12.0
2024-07-01                                     Jaipur Open Classical FIDE rating Tournament       Sudhanshu, Ranjan           1915.0          IND    0.0 -0.25  -10.0
2024-07-01                                     Jaipur Open Classical FIDE rating Tournament           Puneet, Verma           1606.0          IND    0.0 -0.65  -26.0
2024-07-01                                     Jaipur Open Classical FIDE rating Tournament  Sameer, Singh Shergill           1565.0          IND    1.0  0.30   12.0
2024-07-01 Summer Cup Classical Below 1800 FIDE Rating Lake City Open Chess Tournament 2024       Bighneswar, Joshi           1478.0          IND    1.0  0.19    7.6
2024-07-01 Summer Cup Classical Below 1800 FIDE Rating Lake City Open Chess Tournament 2024       Piyush, Chaurasia           1570.0          IND    1.0  0.29   11.6

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_87612/1844044716.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_87612/1844044716.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan)

Processing: 2024-08-01
https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2024-08-01&rating=0
Tables found: 1
Events found: 1
Clean opponent rows: 7
    period                                               tournament_name                  opponent_name  opponent_rating opponent_fed  score   chg  k_chg
2024-08-01 1st AFCA International Open Classical Rating Chess Tournament Sivabhargav, Gorugantu Venkata           1401.0          IND    0.5 -0.37  -14.8
2024-08-01 1st AFCA International Open Classical Rating Chess Tournament                  Soham, Mittal           1451.0          IND    1.0  0.17    6.8
2024-08-01 1st AFCA International Open Classical Rating Chess Tournament           Ateeksh, Singh Jeena           1531.0          IND    0.0 -0.75  -30.0
2024-08-01 1st AFCA International Open Classical Rating Chess Tournament                 Devansh, Gupta           1455.0          IND    0.0 -0.83  -33.2
2024-08-01 1st AFCA International Open Classical Rating Chess Tournament               Viaan, Jai Singh           1454.0          IND    1.0  0.17    6.8
2024-08-01 1st AFCA International Open Classical Rating Chess Tournament                          Somya           1510.0          IND    1.0  0.23    9.2
2024-08-01 1st AFCA International Open Classical Rating Chess Tournament                  Vitasta, Koul           1578.0          IND    0.5 -0.20   -8.0

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_87612/1844044716.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan)

Processing: 2024-09-01
https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2024-09-01&rating=0
Tables found: 2
Events found: 2
Clean opponent rows: 19
    period                                                     tournament_name         opponent_name  opponent_rating opponent_fed  score   chg  k_chg
2024-09-01 Shri Dhanpat Rai Sachdeva Memorial Open FIDE Rated Chess Tournament       Mishra, Sanjeev           1875.0          IND    0.0 -0.25  -9.00
2024-09-01 Shri Dhanpat Rai Sachdeva Memorial Open FIDE Rated Chess Tournament          Dhinesh, K A           1517.0          IND    1.0  0.28  10.08
2024-09-01 Shri Dhanpat Rai Sachdeva Memorial Open FIDE Rated Chess Tournament   Sinha, Sudhir Kumar           2012.0          IND    0.5  0.37  13.32
2024-09-01 Shri Dhanpat Rai Sachdeva Memorial Open FIDE Rated Chess Tournament      Manna, Chiranjit           1895.0          IND    0.0 -0.23  -8.28
2024-09-01 Shri Dhanpat Rai Sachdeva Memorial Open FIDE Rated Chess Tournament         Yati, Agarwal           1573.0          IND    0.5 -0.15  -5.40
2024-09-01 Shri Dhanpat Rai Sachdeva Memorial Open FIDE Rated Chess Tournament    Aaradhya, Upadhyay           1554.0          IND    1.0  0.32  11.52
2024-09-01 Shri Dhanpat Rai Sachdeva Memorial Open FIDE Rated Chess Tournament      Arshpreet, Singh           1995.0          IND    0.5  0.36  12.96
2024-09-01 Shri Dhanpat Rai Sachdeva Memorial Open FIDE Rated Chess Tournament              Hevak, V           1486.0          IND    0.5 -0.26  -9.36
2024-09-01                               61st National Chess Championship 2024 Dishank, Sachin Bajaj           1971.0          IND    0.5  0.34  12.24
2024-09-01                               61st National Chess Championship 2024          Vijay, Kumar           1885.0          IND    0.0 -0.24  -8.64

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_87612/1844044716.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan)

Processing: 2024-10-01
https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2024-10-01&rating=0
Tables found: 1
Events found: 1
Clean opponent rows: 11
    period                                         tournament_name                opponent_name  opponent_rating opponent_fed  score   chg  k_chg
2024-10-01 53rd National Junior (Under-19) Chess Championship-2024           Sharnarthi, Viresh           2147.0          IND    0.0 -0.08   -3.2
2024-10-01 53rd National Junior (Under-19) Chess Championship-2024                Viraj, Sharma           1507.0          IND    1.0  0.19    7.6
2024-10-01 53rd National Junior (Under-19) Chess Championship-2024                    Rohith, S           2031.0          IND    0.0 -0.17   -6.8
2024-10-01 53rd National Junior (Under-19) Chess Championship-2024          Pratik, Lalit Tambi           1598.0          IND    1.0  0.29   11.6
2024-10-01 53rd National Junior (Under-19) Chess Championship-2024       Mrithyunjay, Mahadevan           2073.0          IND    0.0 -0.13   -5.2
2024-10-01 53rd National Junior (Under-19) Chess Championship-2024               Logeshwaran, R           1618.0          IND    1.0  0.32   12.8
2024-10-01 53rd National Junior (Under-19) Chess Championship-2024             Gokula, Vishnu R           1908.0          IND    0.0 -0.30  -12.0
2024-10-01 53rd National Junior (Under-19) Chess Championship-2024         Mohammad, Aayan Khan           1575.0          IND    1.0  0.26   10.4
2024-10-01 53rd National Junior (Under-19) Chess Championship-2024 Chukka, Vineel Radha Karthik           1910.0          IND    0.5  0.21    8.4
2024-10-01 53rd National Junior (Under-19) Chess Championship-2024                     Tarun, V           1907.0          IND    0.0 -0.30  -12.0

Processing: 2024-11-01
https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2024-11-01&rating=0
Tables found: 0
Events found: 0
No clean rows for this month.

Processing: 2024-12-01
https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2024-12-01&rating=0
Tables found: 1
Events found: 1
Clean opponent rows: 9
    period                                                         tournament_name      opponent_name  opponent_rating opponent_fed  score   chg  k_chg
2024-12-01 1st Skillcraft International Open Classical FIDE Rated Chess Tournament       Vritti, Jain           1405.0          IND    1.0  0.09    3.6
2024-12-01 1st Skillcraft International Open Classical FIDE Rated Chess Tournament      Tanveer, Bahl           1518.0          IND    1.0  0.18    7.2
2024-12-01 1st Skillcraft International Open Classical FIDE Rated Chess Tournament Shrivastava, Aditi           1590.0          IND    1.0  0.25   10.0
2024-12-01 1st Skillcraft International Open Classical FIDE Rated Chess Tournament         Arpan, Das           2084.0          IND    0.5  0.36   14.4
2024-12-01 1st Skillcraft International Open Classical FIDE Rated Chess Tournament      Kanav, Bansal           1512.0          IND    0.5 -0.33  -13.2
2024-12-01 1st Skillcraft International Open Classical FIDE Rated Chess Tournament     Kavyansh, Jain           1637.0          IND    0.5 -0.19   -7.6
2024-12-01 1st Skillcraft International Open Classical FIDE Rated Chess Tournament     Krishna, Kundu           1627.0          IND    0.5 -0.21   -8.4
2024-12-01 1st Skillcraft International Open Classical FIDE Rated Chess Tournament    Gurmehar, Singh           1613.0          IND    1.0  0.28   11.2
2024-12-01 1st Skillcraft International Open Classical FIDE Rated Chess Tournament       Dishita, Dey           1654.0          IND    1.0  0.33   13.2

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_87612/1844044716.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan)

Processing: 2025-01-01
https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2025-01-01&rating=0
Tables found: 1
Events found: 1
Clean opponent rows: 11
    period                                 tournament_name            opponent_name  opponent_rating opponent_fed  score   chg  k_chg
2025-01-01 37th National U-13 Open Chess Championship 2024             Hriday, Garg           1534.0          IND    1.0  0.17    6.8
2025-01-01 37th National U-13 Open Chess Championship 2024              Vaishnav, S           1655.0          IND    1.0  0.29   11.6
2025-01-01 37th National U-13 Open Chess Championship 2024           Nimay, Agrawal           2005.0          IND    1.0  0.75   30.0
2025-01-01 37th National U-13 Open Chess Championship 2024      Advik, Amit Agrawal           2064.0          IND    0.5  0.31   12.4
2025-01-01 37th National U-13 Open Chess Championship 2024        Siddhanth, Poonja           2042.0          IND    0.0 -0.21   -8.4
2025-01-01 37th National U-13 Open Chess Championship 2024            Aditya, Kayet           1749.0          IND    1.0  0.41   16.4
2025-01-01 37th National U-13 Open Chess Championship 2024         Madhesh, Kumar S           1944.0          IND    0.0 -0.32  -12.8
2025-01-01 37th National U-13 Open Chess Championship 2024 Shree, Hari Palaniappa S           1741.0          IND    1.0  0.40   16.0
2025-01-01 37th National U-13 Open Chess Championship 2024     Aarav, Saish Amonkar           1910.0          IND    1.0  0.64   25.6
2025-01-01 37th National U-13 Open Chess Championship 2024         Premshankar, B U           1931.0          IND    0.5  0.16    6.4

Processing: 2025-02-01
https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2025-02-01&rating=0
Tables found: 1
Events found: 1
Clean opponent rows: 9
    period                                                    tournament_name          opponent_name  opponent_rating opponent_fed  score   chg  k_chg
2025-02-01 4th Matrix Cup International Open Fide Rated Chess Tournament 2024         Aayann, K Jain             1523          IND    1.0  0.08    3.2
2025-02-01 4th Matrix Cup International Open Fide Rated Chess Tournament 2024          Viraj, Sharma             1527          IND    1.0  0.08    3.2
2025-02-01 4th Matrix Cup International Open Fide Rated Chess Tournament 2024 Pazhany, Kaushal Kohli             1631          IND    1.0  0.15    6.0
2025-02-01 4th Matrix Cup International Open Fide Rated Chess Tournament 2024    Ujaan, Bhattacharya             1704          IND    1.0  0.22    8.8
2025-02-01 4th Matrix Cup International Open Fide Rated Chess Tournament 2024          Bhavya, Gupta             1742          IND    0.5 -0.24   -9.6
2025-02-01 4th Matrix Cup International Open Fide Rated Chess Tournament 2024       Medhansh, Saxena             1769          IND    0.5 -0.21   -8.4
2025-02-01 4th Matrix Cup International Open Fide Rated Chess Tournament 2024      Sameer, Choudhary             1778          IND    0.5 -0.19   -7.6
2025-02-01 4th Matrix Cup International Open Fide Rated Chess Tournament 2024        Vaibhav, Gautam             1714          IND    0.5 -0.27  -10.8
2025-02-01 4th Matrix Cup International Open Fide Rated Chess Tournament 2024        Ramanuj, Mishra             1767          IND    0.5 -0.21   -8.4

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_87612/1844044716.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan)

Processing: 2025-03-01
https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2025-03-01&rating=0
Tables found: 1
Events found: 1
Clean opponent rows: 9
    period                                                    tournament_name              opponent_name  opponent_rating opponent_fed  score   chg  k_chg
2025-03-01 New Delhi Open International FIDE Rated Classical Chess Tournament      Ishaan, Mukund Laddha             1523          IND    1.0  0.08    3.2
2025-03-01 New Delhi Open International FIDE Rated Classical Chess Tournament    Gupta, Vihaan Kamalkant             1523          IND    1.0  0.08    3.2
2025-03-01 New Delhi Open International FIDE Rated Classical Chess Tournament                  Sahana, S             1636          IND    1.0  0.16    6.4
2025-03-01 New Delhi Open International FIDE Rated Classical Chess Tournament               Maaz, Iqubal             1718          IND    1.0  0.24    9.6
2025-03-01 New Delhi Open International FIDE Rated Classical Chess Tournament    Adhrit, Das Purkayastha             1755          IND    1.0  0.28   11.2
2025-03-01 New Delhi Open International FIDE Rated Classical Chess Tournament            Sharsha, Backer             1975          IND    0.5  0.07    2.8
2025-03-01 New Delhi Open International FIDE Rated Classical Chess Tournament Ramnathan, Balasubramaniam             2001          IND    0.0 -0.39  -15.6
2025-03-01 New Delhi Open International FIDE Rated Classical Chess Tournament                Gorli, Nyna             1766          IND    0.5 -0.21   -8.4
2025-03-01 New Delhi Open International FIDE Rated Classical Chess Tournament             Rishabh, Kumar             1775          IND    0.0 -0.70  -28.0

Processing: 2025-04-01
https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2025-04-01&rating=0
Tables found: 2
Events found: 2
Clean opponent rows: 18
    period                                       tournament_name       opponent_name  opponent_rating opponent_fed  score   chg  k_chg
2025-04-01            44th National Team Chess Championship 2025 Jyotshnav, Talukdar           2030.0          IND    0.0 -0.30 -11.40
2025-04-01            44th National Team Chess Championship 2025        Majhi, Fakir           1926.0          IND    1.0  0.56  21.28
2025-04-01            44th National Team Chess Championship 2025          Karan, J P           2018.0          IND    0.0 -0.32 -12.16
2025-04-01            44th National Team Chess Championship 2025    Vrandesh, Parekh           1920.0          IND    0.0 -0.45 -17.10
2025-04-01            44th National Team Chess Championship 2025      Avnish, Borker           1564.0          IND    1.0  0.13   4.94
2025-04-01            44th National Team Chess Championship 2025      Devansh, Singh           1809.0          IND    0.5 -0.10  -3.80
2025-04-01            44th National Team Chess Championship 2025      Jani, Kushal R           2270.0          IND    0.0 -0.09  -3.42
2025-04-01            44th National Team Chess Championship 2025      Jain, Kushagra           2138.0          IND    0.5  0.31  11.78
2025-04-01            44th National Team Chess Championship 2025    Bhosale, Shriraj           2099.0          IND    0.0 -0.22  -8.36
2025-04-01 National Amateur Chess Championship Below 2300 (Open)     Ayaan, Chettiar           1718.0          IND    1.0  0.28  10.64

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_87612/1844044716.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan)

Processing: 2025-05-01
https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2025-05-01&rating=0
Tables found: 1
Events found: 1
Clean opponent rows: 9
    period                                                             tournament_name             opponent_name  opponent_rating opponent_fed  score   chg  k_chg
2025-05-01 2nd Maharashtra Chess Festival Below 2200 FIDE Rating Chess Tournament 2025              Zad, Reyansh           1588.0          IND    1.0  0.18    7.2
2025-05-01 2nd Maharashtra Chess Festival Below 2200 FIDE Rating Chess Tournament 2025 Guhan, Nelamangala Harsha           1737.0          IND    1.0  0.35   14.0
2025-05-01 2nd Maharashtra Chess Festival Below 2200 FIDE Rating Chess Tournament 2025         Anadkat, Kartavya           2187.0          IND    0.0 -0.12   -4.8
2025-05-01 2nd Maharashtra Chess Festival Below 2200 FIDE Rating Chess Tournament 2025            Hrudhan, Moghe           1743.0          IND    0.5 -0.14   -5.6
2025-05-01 2nd Maharashtra Chess Festival Below 2200 FIDE Rating Chess Tournament 2025            Chavan, Aditya           1760.0          IND    0.5 -0.12   -4.8
2025-05-01 2nd Maharashtra Chess Festival Below 2200 FIDE Rating Chess Tournament 2025           Sundar, Divij P           1770.0          IND    0.0 -0.60  -24.0
2025-05-01 2nd Maharashtra Chess Festival Below 2200 FIDE Rating Chess Tournament 2025      Rashmika, Maringanti           1681.0          IND    1.0  0.28   11.2
2025-05-01 2nd Maharashtra Chess Festival Below 2200 FIDE Rating Chess Tournament 2025        Advik, Reddy Moate           1735.0          IND    1.0  0.35   14.0
2025-05-01 2nd Maharashtra Chess Festival Below 2200 FIDE Rating Chess Tournament 2025           Drishtee, Ghosh           1723.0          IND    0.5 -0.17   -6.8

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_87612/1844044716.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan)

Processing: 2025-06-01
https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2025-06-01&rating=0
Tables found: 2
Events found: 2
Clean opponent rows: 19
    period                                          tournament_name         opponent_name  opponent_rating opponent_fed  score   chg  k_chg
2025-06-01          DELHI STATE OPEN RATING CHESS CHAMPIONSHIP 2025          Som, Agarwal           1445.0          IND    1.0  0.08   2.88
2025-06-01          DELHI STATE OPEN RATING CHESS CHAMPIONSHIP 2025           Ansh, Patel           1492.0          IND    1.0  0.11   3.96
2025-06-01          DELHI STATE OPEN RATING CHESS CHAMPIONSHIP 2025 Shivesh, Nalin Sharma           1609.0          IND    1.0  0.20   7.20
2025-06-01          DELHI STATE OPEN RATING CHESS CHAMPIONSHIP 2025        Reyansh, Arora           1664.0          IND    0.5 -0.24  -8.64
2025-06-01          DELHI STATE OPEN RATING CHESS CHAMPIONSHIP 2025       Abhibhav, Kumar           1694.0          IND    0.5 -0.20  -7.20
2025-06-01          DELHI STATE OPEN RATING CHESS CHAMPIONSHIP 2025         Darsh, Ilwadi           1651.0          IND    1.0  0.25   9.00
2025-06-01          DELHI STATE OPEN RATING CHESS CHAMPIONSHIP 2025         Krish, Jaidka           1671.0          IND    1.0  0.27   9.72
2025-06-01          DELHI STATE OPEN RATING CHESS CHAMPIONSHIP 2025    Shaurya, Chaudhary           1844.0          IND    0.5  0.00   0.00
2025-06-01          DELHI STATE OPEN RATING CHESS CHAMPIONSHIP 2025            Arun, Wahi           1569.0          IND    1.0  0.17   6.12
2025-06-01 16th KIIT International Chess Festival (Category A Open)          Sunetra, Dey           1722.0          IND    0.5 -0.17  -6.12

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_87612/1844044716.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_87612/1844044716.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan)

Processing: 2025-07-01
https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2025-07-01&rating=0
Tables found: 1
Events found: 1
Clean opponent rows: 10
    period                                                                 tournament_name      opponent_name  opponent_rating opponent_fed  score   chg  k_chg
2025-07-01 21st Delhi International Open Grandmasters Chess Tournament-2025 (Category 'A')    Praveenkumar, K           1488.0          IND    1.0  0.09    3.6
2025-07-01 21st Delhi International Open Grandmasters Chess Tournament-2025 (Category 'A')   Chinmay, Kowshik           2070.0          IND    0.5  0.25   10.0
2025-07-01 21st Delhi International Open Grandmasters Chess Tournament-2025 (Category 'A')  Sharnarthi, Shlok           2138.0          IND    0.0 -0.18   -7.2
2025-07-01 21st Delhi International Open Grandmasters Chess Tournament-2025 (Category 'A') Patodekar, Samarth           1664.0          IND    1.0  0.23    9.2
2025-07-01 21st Delhi International Open Grandmasters Chess Tournament-2025 (Category 'A')   Ziatdinov, Raset           2065.0          USA    0.0 -0.25  -10.0
2025-07-01 21st Delhi International Open Grandmasters Chess Tournament-2025 (Category 'A')    Rihansh, Pandey           1611.0          IND    1.0  0.18    7.2
2025-07-01 21st Delhi International Open Grandmasters Chess Tournament-2025 (Category 'A')   Premshankar, B U           1999.0          IND    0.0 -0.33  -13.2
2025-07-01 21st Delhi International Open Grandmasters Chess Tournament-2025 (Category 'A') Rudradaman, Mertia           1741.0          IND    0.5 -0.18   -7.2
2025-07-01 21st Delhi International Open Grandmasters Chess Tournament-2025 (Category 'A')       Sunetra, Dey           1757.0          IND    0.5 -0.16   -6.4
2025-07-01 21st Delhi International Open Grandmasters Chess Tournament-2025 (Category 'A')    Pratyasha, Jena           1768.0          IND    1.0  0.35   14.0

Processing: 2025-08-01
https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2025-08-01&rating=0
Tables found: 1
Events found: 1
Clean opponent rows: 9
    period                                                         tournament_name                  opponent_name  opponent_rating opponent_fed  score   chg  k_chg
2025-08-01 3rd UINSports International Open FIDE Rating Chess Tournament Pune 2025          Ghate, Tanmaiee Rahul           1519.0          IND    1.0  0.11    4.4
2025-08-01 3rd UINSports International Open FIDE Rating Chess Tournament Pune 2025           Raghav, Renuk Pawade           1622.0          IND    0.0 -0.81  -32.4
2025-08-01 3rd UINSports International Open FIDE Rating Chess Tournament Pune 2025            Pradyumna, Deshmane           1534.0          IND    1.0  0.12    4.8
2025-08-01 3rd UINSports International Open FIDE Rating Chess Tournament Pune 2025                Jathar, Rishabh           1642.0          IND    1.0  0.21    8.4
2025-08-01 3rd UINSports International Open FIDE Rating Chess Tournament Pune 2025 Bathina, Mokshatra Sri Abhiram           1594.0          IND    1.0  0.16    6.4
2025-08-01 3rd UINSports International Open FIDE Rating Chess Tournament Pune 2025                Amey, Chowdhury           1755.0          IND    0.5 -0.16   -6.4
2025-08-01 3rd UINSports International Open FIDE Rating Chess Tournament Pune 2025              Jagadale, Ishwari           1755.0          IND    0.5 -0.16   -6.4
2025-08-01 3rd UINSports International Open FIDE Rating Chess Tournament Pune 2025                 Vivaan, Mittal           1690.0          IND    1.0  0.26   10.4
2025-08-01 3rd UINSports International Open FIDE Rating Chess Tournament Pune 2025                   Patil, Sudip           1743.0          IND    0.5 -0.18   -7.2

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_87612/1844044716.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan)

Processing: 2025-09-01
https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2025-09-01&rating=0
Tables found: 1
Events found: 1
Clean opponent rows: 9
    period                                                                   tournament_name          opponent_name  opponent_rating opponent_fed  score   chg  k_chg
2025-09-01 SHRI DHANPAT RAI SACHDEVA MEMORIAL OPEN INTERNATIONAL FIDE RATED CHESS TOURNAMENT          Dheekshika, G           1542.0          IND    1.0  0.13    5.2
2025-09-01 SHRI DHANPAT RAI SACHDEVA MEMORIAL OPEN INTERNATIONAL FIDE RATED CHESS TOURNAMENT         Sharma, Pankaj           1661.0          IND    0.5 -0.25  -10.0
2025-09-01 SHRI DHANPAT RAI SACHDEVA MEMORIAL OPEN INTERNATIONAL FIDE RATED CHESS TOURNAMENT            Rahul, Suri           1645.0          IND    1.0  0.23    9.2
2025-09-01 SHRI DHANPAT RAI SACHDEVA MEMORIAL OPEN INTERNATIONAL FIDE RATED CHESS TOURNAMENT        Rituraj, Tamuli           1748.0          IND    1.0  0.35   14.0
2025-09-01 SHRI DHANPAT RAI SACHDEVA MEMORIAL OPEN INTERNATIONAL FIDE RATED CHESS TOURNAMENT Sameer, Singh Shergill           1788.0          IND    0.5 -0.10   -4.0
2025-09-01 SHRI DHANPAT RAI SACHDEVA MEMORIAL OPEN INTERNATIONAL FIDE RATED CHESS TOURNAMENT         Krishna, Kundu           1748.0          IND    0.5 -0.15   -6.0
2025-09-01 SHRI DHANPAT RAI SACHDEVA MEMORIAL OPEN INTERNATIONAL FIDE RATED CHESS TOURNAMENT           Aarav, Gupta           1754.0          IND    0.5 -0.14   -5.6
2025-09-01 SHRI DHANPAT RAI SACHDEVA MEMORIAL OPEN INTERNATIONAL FIDE RATED CHESS TOURNAMENT       Buxy, Rajanikant           1736.0          IND    1.0  0.33   13.2
2025-09-01 SHRI DHANPAT RAI SACHDEVA MEMORIAL OPEN INTERNATIONAL FIDE RATED CHESS TOURNAMENT          Vitasta, Koul           1678.0          IND    1.0  0.26   10.4

Processing: 2025-10-01
https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2025-10-01&rating=0
Tables found: 0
Events found: 0
No clean rows for this month.

Processing: 2025-11-01
https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2025-11-01&rating=0
Tables found: 1
Events found: 1
Clean opponent rows: 11
    period                        tournament_name            opponent_name  opponent_rating opponent_fed  score   chg  k_chg
2025-11-01 62nd National Chess Championship -2025            Harsh, Suresh             2284          IND    0.5  0.42   16.8
2025-11-01 62nd National Chess Championship -2025            Das, Sayantan             2284          IND    0.0 -0.08   -3.2
2025-11-01 62nd National Chess Championship -2025            Heet, Baldawa             1698          IND    0.0 -0.74  -29.6
2025-11-01 62nd National Chess Championship -2025               Virat, J S             1613          IND    1.0  0.17    6.8
2025-11-01 62nd National Chess Championship -2025  Akella, Sankalparuthvik             1669          IND    1.0  0.23    9.2
2025-11-01 62nd National Chess Championship -2025 Simhadri, Sai Hrushikesh             2029          IND    0.0 -0.31  -12.4
2025-11-01 62nd National Chess Championship -2025                  Vibhaan             1734          IND    1.0  0.30   12.0
2025-11-01 62nd National Chess Championship -2025         Shadhursshaan, R             2127          IND    0.0 -0.20   -8.0
2025-11-01 62nd National Chess Championship -2025       Sathvik, Gulakaram             1747          IND    1.0  0.32   12.8
2025-11-01 62nd National Chess Championship -2025        Vijay, Shreeram P             2118          IND    0.0 -0.21   -8.4

Processing: 2025-12-01
https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2025-12-01&rating=0
Tables found: 1
Events found: 1
Clean opponent rows: 10
    period                                        tournament_name               opponent_name  opponent_rating opponent_fed  score   chg  k_chg
2025-12-01 50th National Sub Junior Chess Championship 2025(Open)               Manish, Yadav             1513          IND    0.5 -0.40  -16.0
2025-12-01 50th National Sub Junior Chess Championship 2025(Open)                Parth, Gupta             1473          IND    1.0  0.08    3.2
2025-12-01 50th National Sub Junior Chess Championship 2025(Open)                  Ankit, Das             2063          IND    1.0  0.75   30.0
2025-12-01 50th National Sub Junior Chess Championship 2025(Open)                    Gokul, G             2021          IND    0.5  0.20    8.0
2025-12-01 50th National Sub Junior Chess Championship 2025(Open)     Banik, Hrishikesh Kumar             2109          IND    0.0 -0.20   -8.0
2025-12-01 50th National Sub Junior Chess Championship 2025(Open)              Divit, Gangwal             1659          IND    1.0  0.23    9.2
2025-12-01 50th National Sub Junior Chess Championship 2025(Open)               Puneet, Verma             2010          IND    0.0 -0.32  -12.8
2025-12-01 50th National Sub Junior Chess Championship 2025(Open)              Vivaan, Mittal             1689          IND    1.0  0.26   10.4
2025-12-01 50th National Sub Junior Chess Championship 2025(Open) Ekaaksha, Partap Singh Negi             2011          IND    0.5  0.19    7.6
2025-12-01 50th National Sub Junior Chess Championship 2025(Open)                 Kirthika, B             2010          IND    1.0  0.68   27.2

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_87612/1844044716.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan)

Processing: 2026-01-01
https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2026-01-01&rating=0
Tables found: 1
Events found: 1
Clean opponent rows: 9
    period                                                 tournament_name    opponent_name  opponent_rating opponent_fed  score   chg  k_chg
2026-01-01 1st Arunachal Pradesh International Chess Festival 2025 (Cat-B)      Tania, Arki           1541.0          IND    1.0  0.09    3.6
2026-01-01 1st Arunachal Pradesh International Chess Festival 2025 (Cat-B)  Abhibhav, Kumar           1724.0          IND    0.5 -0.27  -10.8
2026-01-01 1st Arunachal Pradesh International Chess Festival 2025 (Cat-B)     Talin, Nimpu           1768.0          IND    1.0  0.28   11.2
2026-01-01 1st Arunachal Pradesh International Chess Festival 2025 (Cat-B)     Saikat, Nath           1798.0          IND    0.5 -0.18   -7.2
2026-01-01 1st Arunachal Pradesh International Chess Festival 2025 (Cat-B)      C,r, Ritvik           1823.0          IND    1.0  0.35   14.0
2026-01-01 1st Arunachal Pradesh International Chess Festival 2025 (Cat-B)   Silkam, Sangma           1788.0          IND    0.5 -0.19   -7.6
2026-01-01 1st Arunachal Pradesh International Chess Festival 2025 (Cat-B)  Rituraj, Tamuli           1775.0          IND    1.0  0.29   11.6
2026-01-01 1st Arunachal Pradesh International Chess Festival 2025 (Cat-B)      Arav, Vinod           1815.0          IND    1.0  0.34   13.6
2026-01-01 1st Arunachal Pradesh International Chess Festival 2025 (Cat-B) Adalja, Vanssh A           1946.0          IND    1.0  0.52   20.8

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_87612/1844044716.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan)

Processing: 2026-02-01
https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2026-02-01&rating=0
Tables found: 3
Events found: 3
Clean opponent rows: 26
    period                                          tournament_name                   opponent_name  opponent_rating opponent_fed  score   chg  k_chg
2026-02-01              VI Open Internacional de Ajedrez Dama Negra           Santos Anton, Armando           1532.0          ESP    1.0  0.08   2.08
2026-02-01              VI Open Internacional de Ajedrez Dama Negra                  Doman, Richard           1652.0          ENG    1.0  0.16   4.16
2026-02-01              VI Open Internacional de Ajedrez Dama Negra                  Prabhu, Aadith           1831.0          SCO    1.0  0.36   9.36
2026-02-01              VI Open Internacional de Ajedrez Dama Negra          Peixoto, Sergio Dantas           1778.0          BRA    1.0  0.29   7.54
2026-02-01              VI Open Internacional de Ajedrez Dama Negra           Troshchenko, Vladimir           2099.0          UKR    1.0  0.72  18.72
2026-02-01              VI Open Internacional de Ajedrez Dama Negra                   Goluch, Piotr           2249.0          POL    0.5  0.37   9.62
2026-02-01              VI Open Internacional de Ajedrez Dama Negra           Romera Carrion, Ruben           1947.0          ESP    1.0  0.52  13.52
2026-02-01              VI Open Internacional de Ajedrez Dama Negra Sanchez Negreiros, Jose Alberto           2055.0          PER    0.0 -0.33  -8.58
2026-02-01 Roquetas Chess Festival 2026 - XXXVII International Open                Povshednyi, Ivan           2357.0          UKR    0.0 -0.09  -2.34
2026-02-01 Roquetas Chess Festival 2026 - XXXVII International Open         Ibanez Guillen, Enrique           1795.0          ESP    1.0  0.26   6.76

Processing: 2026-03-01
https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2026-03-01&rating=0
Tables found: 0
Events found: 0
No clean rows for this month.

Processing: 2026-04-01
https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2026-04-01&rating=0
Tables found: 0
Events found: 0
No clean rows for this month.

Processing: 2026-05-01
https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2026-05-01&rating=0
Tables found: 2
Events found: 2
Clean opponent rows: 18
    period                                                        tournament_name            opponent_name  opponent_rating opponent_fed  score   chg  k_chg
2026-05-01            Championnat International d'Echecs de Lyon Henri Rinck 2026        Hanriot, Frederik           1684.0          FRA    1.0  0.08   3.04
2026-05-01            Championnat International d'Echecs de Lyon Henri Rinck 2026       Bazzazi, Abdulaziz           1811.0          FRA    1.0  0.17   6.46
2026-05-01            Championnat International d'Echecs de Lyon Henri Rinck 2026      Sanket, Chakravarty           2355.0          IND    1.0  0.83  31.54
2026-05-01            Championnat International d'Echecs de Lyon Henri Rinck 2026          Boraso, Alessio           2267.0          ITA    0.5  0.24   9.12
2026-05-01            Championnat International d'Echecs de Lyon Henri Rinck 2026          Nottola, Adrien           2226.0          FRA    0.0 -0.31 -11.78
2026-05-01            Championnat International d'Echecs de Lyon Henri Rinck 2026         Morelle, Laurent           1858.0          FRA    1.0  0.21   7.98
2026-05-01            Championnat International d'Echecs de Lyon Henri Rinck 2026          Gennari, Jacopo           2182.0          ITA    0.5  0.13   4.94
2026-05-01            Championnat International d'Echecs de Lyon Henri Rinck 2026        Dubourg, Pierrick           2252.0          FRA    1.0  0.72  27.36
2026-05-01            Championnat International d'Echecs de Lyon Henri Rinck 2026  Bocquenet-Drouode, Hugo           2225.0          FRA    0.5  0.19   7.22
2026-05-01 11eme Open International d'Echecs de Noisiel 2026 - Open A (p2000 Elo) Jacobsen, Mikkel Manosri           2391.0          DEN    0.5  0.36  13.68

In [5]:
# Combine and save
month_status_df = pd.DataFrame(month_status)

status_path = output_dir / "amartya_month_status.csv"
month_status_df.to_csv(status_path, index=False)

print("Saved status:", status_path)
print(month_status_df.to_string(index=False))

Saved status: /Users/arunkumar/Downloads/fide_history/amartya_calculations/amartya_month_status.csv
    period                                                                                       url  tables_found  events_found  clean_rows                   status
2024-01-01 https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2024-01-01&rating=0             3             3          24               data_found
2024-02-01 https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2024-02-01&rating=0             1             1           8               data_found
2024-03-01 https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2024-03-01&rating=0             2             2          16               data_found
2024-04-01 https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2024-04-01&rating=0             1             1           8               data_found
2024-05-01 https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2024-05-01&rating=0             2             2          17               data_found
2024-06-01 https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2024-06-01&rating=0             1             1           8               data_found
2024-07-01 https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2024-07-01&rating=0             2             2          17               data_found
2024-08-01 https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2024-08-01&rating=0             1             1           7               data_found
2024-09-01 https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2024-09-01&rating=0             2             2          19               data_found
2024-10-01 https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2024-10-01&rating=0             1             1          11               data_found
2024-11-01 https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2024-11-01&rating=0             0             0           0 no_data_or_no_clean_rows
2024-12-01 https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2024-12-01&rating=0             1             1           9               data_found
2025-01-01 https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2025-01-01&rating=0             1             1          11               data_found
2025-02-01 https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2025-02-01&rating=0             1             1           9               data_found
2025-03-01 https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2025-03-01&rating=0             1             1           9               data_found
2025-04-01 https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2025-04-01&rating=0             2             2          18               data_found
2025-05-01 https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2025-05-01&rating=0             1             1           9               data_found
2025-06-01 https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2025-06-01&rating=0             2             2          19               data_found
2025-07-01 https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2025-07-01&rating=0             1             1          10               data_found
2025-08-01 https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2025-08-01&rating=0             1             1           9               data_found
2025-09-01 https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2025-09-01&rating=0             1             1           9               data_found
2025-10-01 https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2025-10-01&rating=0             0             0           0 no_data_or_no_clean_rows
2025-11-01 https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2025-11-01&rating=0             1             1          11               data_found
2025-12-01 https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2025-12-01&rating=0             1             1          10               data_found
2026-01-01 https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2026-01-01&rating=0             1             1           9               data_found
2026-02-01 https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2026-02-01&rating=0             3             3          26               data_found
2026-03-01 https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2026-03-01&rating=0             0             0           0 no_data_or_no_clean_rows
2026-04-01 https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2026-04-01&rating=0             0             0           0 no_data_or_no_clean_rows
2026-05-01 https://ratings.fide.com/calculations.phtml?id_number=25977890&period=2026-05-01&rating=0             2             2          18               data_found

In [6]:
#
if all_months_clean:
    amartya_all_calc = pd.concat(all_months_clean, ignore_index=True)

    output_csv = output_dir / "amartya_all_months_standard_calculations_clean.csv"
    amartya_all_calc.to_csv(output_csv, index=False)

    print("Saved clean calculations:", output_csv)
    print("Shape:", amartya_all_calc.shape)
    print(amartya_all_calc.head(30).to_string(index=False))
else:
    amartya_all_calc = pd.DataFrame()
    print("No clean calculation data found for any month.")

Saved clean calculations: /Users/arunkumar/Downloads/fide_history/amartya_calculations/amartya_all_months_standard_calculations_clean.csv
Shape: (321, 24)
 fide_id     period  rating_type                                                                 tournament_name event_location_fed event_start_date event_end_date  event_rc  event_ro  event_score  event_games  event_chg  event_k  event_k_chg              opponent_name opponent_title  opponent_rating  rating_difference_over_400_flag opponent_fed  score  n   chg  k  k_chg
25977890 2024-01-01            0             Bijnor Open FIDE Rated Chess Tournament - UP Booster Series (Vol I)         Bijnor IND       2023-11-30     2023-12-03      1255      1376          5.0            6       1.15       29        33.35            Kshitika, Tyagi            NaN           1010.0                            False          IND    1.0  1  0.10 29   2.90
25977890 2024-01-01            0             Bijnor Open FIDE Rated Chess Tournament - UP Booster Series (Vol I)         Bijnor IND       2023-11-30     2023-12-03      1255      1376          5.0            6       1.15       29        33.35               Dhruv, Gupta            NaN           1191.0                            False          IND    1.0  1  0.26 29   7.54
25977890 2024-01-01            0             Bijnor Open FIDE Rated Chess Tournament - UP Booster Series (Vol I)         Bijnor IND       2023-11-30     2023-12-03      1255      1376          5.0            6       1.15       29        33.35             Nikhil, Chopra            NaN           1197.0                            False          IND    1.0  1  0.27 29   7.83
25977890 2024-01-01            0             Bijnor Open FIDE Rated Chess Tournament - UP Booster Series (Vol I)         Bijnor IND       2023-11-30     2023-12-03      1255      1376          5.0            6       1.15       29        33.35              Vatsal, Makol            NaN           1477.0                            False          IND    0.5  1  0.14 29   4.06
25977890 2024-01-01            0             Bijnor Open FIDE Rated Chess Tournament - UP Booster Series (Vol I)         Bijnor IND       2023-11-30     2023-12-03      1255      1376          5.0            6       1.15       29        33.35                Rahul, Suri            NaN           1185.0                            False          IND    1.0  1  0.25 29   7.25
25977890 2024-01-01            0             Bijnor Open FIDE Rated Chess Tournament - UP Booster Series (Vol I)         Bijnor IND       2023-11-30     2023-12-03      1255      1376          5.0            6       1.15       29        33.35           Mohammad, Sameed            NaN           1468.0                            False          IND    0.5  1  0.13 29   3.77
25977890 2024-01-01            0                                  36th National Under-13 Chess Championship-2023      Hyderabad IND       2023-12-04     2023-12-10      1464      1376          6.0           10       2.03       29        58.87           Chinmay, Kowshik            NaN           1760.0                            False          IND    0.0  1 -0.09 29  -2.61
25977890 2024-01-01            0                                  36th National Under-13 Chess Championship-2023      Hyderabad IND       2023-12-04     2023-12-10      1464      1376          6.0           10       2.03       29        58.87              Agham, Surana            NaN           1137.0                            False          IND    1.0  1  0.20 29   5.80
25977890 2024-01-01            0                                  36th National Under-13 Chess Championship-2023      Hyderabad IND       2023-12-04     2023-12-10      1464      1376          6.0           10       2.03       29        58.87                 Haridev, S            NaN           1722.0                            False          IND    1.0  1  0.89 29  25.81
25977890 2024-01-01            0                                  36th National Under-13 Chess Championship-2023      Hyderabad IND       2023-12-04     2023-12-10      1464      1376          6.0           10       2.03       29        58.87              Sagnik, Dutta            NaN           1520.0                            False          IND    0.0  1 -0.31 29  -8.99
25977890 2024-01-01            0                                  36th National Under-13 Chess Championship-2023      Hyderabad IND       2023-12-04     2023-12-10      1464      1376          6.0           10       2.03       29        58.87            Pooru, Lakshith            NaN           1141.0                            False          IND    1.0  1  0.21 29   6.09
25977890 2024-01-01            0                                  36th National Under-13 Chess Championship-2023      Hyderabad IND       2023-12-04     2023-12-10      1464      1376          6.0           10       2.03       29        58.87 Kandi, Santosh Sai Karthik            NaN           1530.0                            False          IND    0.5  1  0.21 29   6.09
25977890 2024-01-01            0                                  36th National Under-13 Chess Championship-2023      Hyderabad IND       2023-12-04     2023-12-10      1464      1376          6.0           10       2.03       29        58.87         Shaurya, Chaudhary            NaN           1505.0                            False          IND    0.0  1 -0.33 29  -9.57
25977890 2024-01-01            0                                  36th National Under-13 Chess Championship-2023      Hyderabad IND       2023-12-04     2023-12-10      1464      1376          6.0           10       2.03       29        58.87           Gautam, Chintala            NaN           1182.0                            False          IND    1.0  1  0.25 29   7.25
25977890 2024-01-01            0                                  36th National Under-13 Chess Championship-2023      Hyderabad IND       2023-12-04     2023-12-10      1464      1376          6.0           10       2.03       29        58.87             Oishik, Mondal            NaN           1628.0                            False          IND    1.0  1  0.81 29  23.49
25977890 2024-01-01            0                                  36th National Under-13 Chess Championship-2023      Hyderabad IND       2023-12-04     2023-12-10      1464      1376          6.0           10       2.03       29        58.87       Sree, Shaunak Chanda            NaN           1517.0                            False          IND    0.5  1  0.19 29   5.51
25977890 2024-01-01            0 Winter Cup Classical Below 1600 FIDE Rating Lakecity Open Chess Tournament 2023        Udaipur IND       2023-12-22     2023-12-24      1248      1376          5.5            8       0.14       29         4.06              Gaurav, Saini            NaN           1187.0                            False          IND    1.0  1  0.25 29   7.25
25977890 2024-01-01            0 Winter Cup Classical Below 1600 FIDE Rating Lakecity Open Chess Tournament 2023        Udaipur IND       2023-12-22     2023-12-24      1248      1376          5.5            8       0.14       29         4.06             Mehul, Paliwal            NaN           1253.0                            False          IND    0.0  1 -0.67 29 -19.43
25977890 2024-01-01            0 Winter Cup Classical Below 1600 FIDE Rating Lakecity Open Chess Tournament 2023        Udaipur IND       2023-12-22     2023-12-24      1248      1376          5.5            8       0.14       29         4.06        Krishav, Kavit Shah            NaN           1159.0                            False          IND    1.0  1  0.22 29   6.38
25977890 2024-01-01            0 Winter Cup Classical Below 1600 FIDE Rating Lakecity Open Chess Tournament 2023        Udaipur IND       2023-12-22     2023-12-24      1248      1376          5.5            8       0.14       29         4.06          Raghav, Badrinath            NaN           1246.0                            False          IND    0.0  1 -0.68 29 -19.72
25977890 2024-01-01            0 Winter Cup Classical Below 1600 FIDE Rating Lakecity Open Chess Tournament 2023        Udaipur IND       2023-12-22     2023-12-24      1248      1376          5.5            8       0.14       29         4.06          Kuldeep, Sahajlan            NaN           1164.0                            False          IND    1.0  1  0.23 29   6.67
25977890 2024-01-01            0 Winter Cup Classical Below 1600 FIDE Rating Lakecity Open Chess Tournament 2023        Udaipur IND       2023-12-22     2023-12-24      1248      1376          5.5            8       0.14       29         4.06              Yati, Agarwal            NaN           1185.0                            False          IND    1.0  1  0.25 29   7.25
25977890 2024-01-01            0 Winter Cup Classical Below 1600 FIDE Rating Lakecity Open Chess Tournament 2023        Udaipur IND       2023-12-22     2023-12-24      1248      1376          5.5            8       0.14       29         4.06            Murali, Mohan Y            NaN           1200.0                            False          IND    1.0  1  0.27 29   7.83
25977890 2024-01-01            0 Winter Cup Classical Below 1600 FIDE Rating Lakecity Open Chess Tournament 2023        Udaipur IND       2023-12-22     2023-12-24      1248      1376          5.5            8       0.14       29         4.06            Bharat, Bhushan            NaN           1587.0                            False          IND    0.5  1  0.27 29   7.83
25977890 2024-02-01            0                      2nd Matrix International Open FIDE Rating Chess Tournament          Delhi IND       2024-01-03     2024-01-07      1462      1472          5.5            8       1.17       40        46.80             Kavyansh, Jain            NaN           1125.0                            False          IND    1.0  1  0.11 40   4.40
25977890 2024-02-01            0                      2nd Matrix International Open FIDE Rating Chess Tournament          Delhi IND       2024-01-03     2024-01-07      1462      1472          5.5            8       1.17       40        46.80         Anant, Singh Dagar            NaN           1217.0                            False          IND    1.0  1  0.19 40   7.60
25977890 2024-02-01            0                      2nd Matrix International Open FIDE Rating Chess Tournament          Delhi IND       2024-01-03     2024-01-07      1462      1472          5.5            8       1.17       40        46.80               Aansh, Gupta            NaN           1991.0                            False          IND    1.0  1  0.97 40  38.80
25977890 2024-02-01            0                      2nd Matrix International Open FIDE Rating Chess Tournament          Delhi IND       2024-01-03     2024-01-07      1462      1472          5.5            8       1.17       40        46.80            Pradeep, Tiwari            NaN           1809.0                            False          IND    0.5  1  0.38 40  15.20
25977890 2024-02-01            0                      2nd Matrix International Open FIDE Rating Chess Tournament          Delhi IND       2024-01-03     2024-01-07      1462      1472          5.5            8       1.17       40        46.80             Ashok, Gajwani            NaN           1853.0                            False          IND    0.0  1 -0.09 40  -3.60
25977890 2024-02-01            0                      2nd Matrix International Open FIDE Rating Chess Tournament          Delhi IND       2024-01-03     2024-01-07      1462      1472          5.5            8       1.17       40        46.80               Parth, Gupta            NaN           1285.0                            False          IND    0.0  1 -0.74 40 -29.60

In [7]:
#Check monthly summary
if not amartya_all_calc.empty:
    monthly_summary = (
        amartya_all_calc
        .groupby("period", as_index=False)
        .agg(
            tournaments=("tournament_name", "nunique"),
            games=("opponent_name", "count"),
            avg_opponent_rating=("opponent_rating", "mean"),
            total_score=("score", "sum"),
            total_rating_change=("k_chg", "sum"),
            avg_chg=("chg", "mean")
        )
    )

    print(monthly_summary.to_string(index=False))

    period  tournaments  games  avg_opponent_rating  total_score  total_rating_change   avg_chg
2024-01-01            3     24          1339.625000         16.5         9.628000e+01  0.138333
2024-02-01            1      8          1461.500000          5.5         4.680000e+01  0.146250
2024-03-01            2     16          1479.375000          9.5         3.640000e+01  0.056875
2024-04-01            1      8          1658.500000          4.5        -1.440000e+01 -0.045000
2024-05-01            2     17          1775.941176          7.5        -8.000000e-01 -0.001176
2024-06-01            1      8          1539.250000          6.0         5.600000e+00  0.017500
2024-07-01            2     17          1616.647059         11.5         2.440000e+01  0.035882
2024-08-01            1      7          1482.857143          4.0        -6.320000e+01 -0.225714
2024-09-01            2     19          1790.368421          9.0         6.984000e+01  0.102105
2024-10-01            1     11          1811.818182          5.5         2.600000e+01  0.059091
2024-12-01            1      9          1626.666667          7.0         3.040000e+01  0.084444
2025-01-01            1     11          1866.727273          7.5         1.120000e+02  0.254545
2025-02-01            1      9          1683.888889          6.5        -2.360000e+01 -0.065556
2025-03-01            1      9          1741.333333          6.0        -1.560000e+01 -0.043333
2025-04-01            2     18          1909.222222          7.5        -3.838000e+01 -0.056111
2025-05-01            1      9          1769.333333          5.5         4.000000e-01  0.001111
2025-06-01            2     19          1734.842105         13.0         3.096000e+01  0.045263
2025-07-01            1     10          1830.100000          5.5        -3.552714e-15  0.000000
2025-08-01            1      9          1650.444444          6.5        -1.800000e+01 -0.050000
2025-09-01            1      9          1700.000000          7.0         2.640000e+01  0.073333
2025-11-01            1     11          1914.000000          5.0        -1.120000e+01 -0.025455
2025-12-01            1     10          1855.800000          6.5         5.880000e+01  0.147000
2026-01-01            1      9          1775.333333          7.5         4.920000e+01  0.136667
2026-02-01            3     26          2015.615385         15.5         1.027000e+02  0.151923
2026-05-01            2     18          2089.111111         10.5         6.384000e+01  0.093333

In [ ]:
#Check tournament summary
if not amartya_all_calc.empty:
    tournament_summary = (
        amartya_all_calc
        .groupby(["period", "tournament_name"], as_index=False)
        .agg(
            event_location_fed=("event_location_fed", "first"),
            event_start_date=("event_start_date", "first"),
            event_end_date=("event_end_date", "first"),
            event_rc=("event_rc", "first"),
            event_ro=("event_ro", "first"),
            event_score=("event_score", "first"),
            event_games=("event_games", "first"),
            event_k_chg=("event_k_chg", "first"),
            games=("opponent_name", "count"),
            avg_opponent_rating=("opponent_rating", "mean"),
            score_sum=("score", "sum"),
            k_chg_sum=("k_chg", "sum")
        )
    )

    print(tournament_summary.to_string(index=False))

In [ ]:
tournament_view = tournament_summary.copy()

# Shorten long tournament names for display only
tournament_view["tournament_name_short"] = (
    tournament_view["tournament_name"]
    .astype(str)
    .str.slice(0, 55)
)

cols = [
    "period",
    "tournament_name_short",
    "event_location_fed",
    "event_start_date",
    "event_end_date",
    "event_ro",
    "event_rc",
    "event_score",
    "event_games",
    "avg_opponent_rating",
    "k_chg_sum"
]

display(tournament_view[cols])

#### Extraction for 1000 sample players

#### 1. Load the 1,000-player sample

Use whichever sample you selected, representative or balanced.

In [1]:
import pandas as pd
import numpy as np
import re
import time
import math
from pathlib import Path
from bs4 import BeautifulSoup
from io import StringIO
from playwright.async_api import async_playwright

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 2000)
pd.set_option("display.max_colwidth", 80)

In [7]:
#sample_path = Path.home() / "Downloads" / "fide_history" / "indian_youth_1000_balanced_sample.csv"
# Or use representative sample:
# sample_path = Path.home() / "Downloads" / "fide_history" / "indian_youth_1000_player_features.csv"
player_sample_1000_output_path = Path.home() / "Downloads" / "fide_history" / "player_sample_1000.csv"

player_sample = pd.read_csv(player_sample_1000_output_path)

player_sample.columns = player_sample.columns.str.strip()
player_sample["ID Number"] = player_sample["ID Number"].astype(str).str.strip()

player_ids = player_sample["ID Number"].dropna().drop_duplicates().tolist()

print("Players:", len(player_ids))
print(player_ids[:10])

Players: 1000
['558016627', '531075452', '537082728', '25789783', '45056404', '531047971', '48773603', '558008276', '88138674', '48724211']

#### 2. Set extraction period

For your feature window, use Apr 2024 to Apr 2025.

In [5]:
rating_type = 0  # 0 = Standard, 1 = Rapid, 2 = Blitz

start_period = "2024-05-01"
end_period = "2025-04-01"

periods = pd.date_range(start_period, end_period, freq="MS")

print("Months:", len(periods))
print([p.strftime("%Y-%m-%d") for p in periods])

Months: 12
['2024-05-01', '2024-06-01', '2024-07-01', '2024-08-01', '2024-09-01', '2024-10-01', '2024-11-01', '2024-12-01', '2025-01-01', '2025-02-01', '2025-03-01', '2025-04-01']

#### 3. Output folders

In [31]:
base_output_dir = Path.home() / "Downloads" / "fide_history" / "fide_calculation_pages"

raw_html_dir = base_output_dir / "raw_html"
clean_dir = base_output_dir / "clean_player_months"
log_dir = base_output_dir / "logs"

raw_html_dir.mkdir(parents=True, exist_ok=True)
clean_dir.mkdir(parents=True, exist_ok=True)
log_dir.mkdir(parents=True, exist_ok=True)

print(base_output_dir)

/Users/arunkumar/Downloads/fide_history/fide_calculation_pages

#### 4. Helper functions

In [9]:
def extract_event_metadata_from_text(text_lines):
    events = []

    for i, line in enumerate(text_lines):
        if line == "Rc":
            if i >= 4:
                event_name = text_lines[i - 4]
                location_fed = text_lines[i - 3]
                start_date = text_lines[i - 2]
                end_date = text_lines[i - 1]

                if (
                    re.match(r"^\d{4}-\d{2}-\d{2}$", start_date)
                    and re.match(r"^\d{4}-\d{2}-\d{2}$", end_date)
                ):
                    events.append({
                        "tournament_name": event_name,
                        "event_location_fed": location_fed,
                        "event_start_date": start_date,
                        "event_end_date": end_date
                    })

    return events


def clean_fide_calculation_table(table, event_meta, fide_id, period, rating_type=0):
    df = table.copy()

    if df.shape[1] < 10 or df.shape[0] < 4:
        return pd.DataFrame()

    df = df.iloc[:, :10].copy()

    summary = df.iloc[1]

    event_rc = pd.to_numeric(summary.iloc[0], errors="coerce")
    event_ro = pd.to_numeric(summary.iloc[1], errors="coerce")
    event_score = pd.to_numeric(summary.iloc[5], errors="coerce")
    event_games = pd.to_numeric(summary.iloc[6], errors="coerce")
    event_chg = pd.to_numeric(summary.iloc[7], errors="coerce")
    event_k = pd.to_numeric(summary.iloc[8], errors="coerce")
    event_kchg = pd.to_numeric(summary.iloc[9], errors="coerce")

    opponent_df = df.iloc[3:].copy()

    opponent_df.columns = [
        "opponent_name",
        "opponent_title_1",
        "opponent_title_2",
        "opponent_rating_raw",
        "opponent_fed",
        "score",
        "n",
        "chg",
        "k",
        "k_chg"
    ]

    opponent_df = opponent_df[opponent_df["opponent_name"].notna()].copy()

    opponent_df = opponent_df[
        ~opponent_df["opponent_name"].astype(str).str.contains(
            "Rating difference", case=False, na=False
        )
    ].copy()

    opponent_df["opponent_fed"] = opponent_df["opponent_fed"].astype(str).str.strip()

    opponent_df = opponent_df[
        opponent_df["opponent_fed"].str.match(r"^[A-Z]{3}$", na=False)
    ].copy()

    if opponent_df.empty:
        return pd.DataFrame()

    opponent_df["opponent_title"] = (
        opponent_df[["opponent_title_1", "opponent_title_2"]]
        .astype(str)
        .replace("nan", "", regex=False)
        .agg(" ".join, axis=1)
        .str.strip()
    )

    opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

    opponent_df["rating_difference_over_400_flag"] = (
        opponent_df["opponent_rating_raw"]
        .astype(str)
        .str.contains(r"\*", regex=True, na=False)
    )

    opponent_df["opponent_rating"] = (
        opponent_df["opponent_rating_raw"]
        .astype(str)
        .str.replace("*", "", regex=False)
        .str.strip()
    )

    opponent_df["opponent_rating"] = pd.to_numeric(
        opponent_df["opponent_rating"],
        errors="coerce"
    )

    for col in ["score", "n", "chg", "k", "k_chg"]:
        opponent_df[col] = pd.to_numeric(opponent_df[col], errors="coerce")

    opponent_df["fide_id"] = str(fide_id)
    opponent_df["period"] = period
    opponent_df["rating_type"] = rating_type

    opponent_df["tournament_name"] = event_meta.get("tournament_name")
    opponent_df["event_location_fed"] = event_meta.get("event_location_fed")
    opponent_df["event_start_date"] = event_meta.get("event_start_date")
    opponent_df["event_end_date"] = event_meta.get("event_end_date")

    opponent_df["event_rc"] = event_rc
    opponent_df["event_ro"] = event_ro
    opponent_df["event_score"] = event_score
    opponent_df["event_games"] = event_games
    opponent_df["event_chg"] = event_chg
    opponent_df["event_k"] = event_k
    opponent_df["event_k_chg"] = event_kchg

    keep_cols = [
        "fide_id", "period", "rating_type",
        "tournament_name", "event_location_fed",
        "event_start_date", "event_end_date",
        "event_rc", "event_ro", "event_score", "event_games",
        "event_chg", "event_k", "event_k_chg",
        "opponent_name", "opponent_title", "opponent_rating",
        "rating_difference_over_400_flag",
        "opponent_fed", "score", "n", "chg", "k", "k_chg"
    ]

    return opponent_df[keep_cols].reset_index(drop=True)

#### 5. Function to process one player-month

In [11]:
async def extract_player_month(page, fide_id, period_str, rating_type=0, save_html=False):
    url = (
        "https://ratings.fide.com/calculations.phtml"
        f"?id_number={fide_id}&period={period_str}&rating={rating_type}"
    )

    await page.goto(url, wait_until="networkidle", timeout=60000)
    await page.wait_for_timeout(2000)

    html = await page.content()

    if save_html:
        player_html_dir = raw_html_dir / str(fide_id)
        player_html_dir.mkdir(parents=True, exist_ok=True)

        html_path = player_html_dir / f"{fide_id}_{period_str}_standard.html"
        html_path.write_text(html, encoding="utf-8")

    soup = BeautifulSoup(html, "html.parser")

    text_lines = [
        line.strip()
        for line in soup.get_text("\n", strip=True).split("\n")
        if line.strip()
    ]

    try:
        tables = pd.read_html(StringIO(html))
    except ValueError:
        tables = []

    events = extract_event_metadata_from_text(text_lines)

    clean_tables = []

    for i, table in enumerate(tables):
        event_meta = events[i] if i < len(events) else {}

        clean_one = clean_fide_calculation_table(
            table=table,
            event_meta=event_meta,
            fide_id=fide_id,
            period=period_str,
            rating_type=rating_type
        )

        if not clean_one.empty:
            clean_tables.append(clean_one)

    if clean_tables:
        clean_df = pd.concat(clean_tables, ignore_index=True)
    else:
        clean_df = pd.DataFrame()

    status = {
        "fide_id": str(fide_id),
        "period": period_str,
        "rating_type": rating_type,
        "url": url,
        "tables_found": len(tables),
        "events_found": len(events),
        "clean_rows": clean_df.shape[0],
        "status": "data_found" if clean_df.shape[0] > 0 else "no_data_or_no_clean_rows"
    }

    return clean_df, status

#### 6. Run for all players with resume support

Start with a small test first, for example 10 players.

In [25]:
test_player_ids = player_ids[:2]
print(test_player_ids)

['558016627', '531075452']

In [17]:
async def run_extraction_for_players(
    player_ids_to_run,
    periods,
    rating_type=0,
    save_html=False,
    delay_ms=1500
):
    all_status = []

    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()

        for idx, fide_id in enumerate(player_ids_to_run, start=1):
            print(f"\n===== Player {idx}/{len(player_ids_to_run)}: {fide_id} =====")

            player_clean_parts = []

            for period in periods:
                period_str = period.strftime("%Y-%m-%d")

                output_file = clean_dir / f"{fide_id}_{period_str}_standard_clean.csv"

                # Resume support: skip if already processed
                if output_file.exists():
                    print("Skipping existing:", output_file.name)

                    try:
                        existing_df = pd.read_csv(output_file)
                        clean_rows = existing_df.shape[0]
                    except Exception:
                        clean_rows = None

                    all_status.append({
                        "fide_id": str(fide_id),
                        "period": period_str,
                        "rating_type": rating_type,
                        "status": "skipped_existing",
                        "clean_rows": clean_rows
                    })
                    continue

                print("Processing:", fide_id, period_str)

                try:
                    clean_df, status = await extract_player_month(
                        page=page,
                        fide_id=fide_id,
                        period_str=period_str,
                        rating_type=rating_type,
                        save_html=save_html
                    )

                    # Save even if empty, so resume knows it was processed
                    clean_df.to_csv(output_file, index=False)

                    all_status.append(status)

                    if not clean_df.empty:
                        player_clean_parts.append(clean_df)
                        print("Rows:", clean_df.shape[0])
                    else:
                        print("No rows.")

                except Exception as e:
                    print("Failed:", fide_id, period_str, repr(e))

                    all_status.append({
                        "fide_id": str(fide_id),
                        "period": period_str,
                        "rating_type": rating_type,
                        "status": "failed",
                        "clean_rows": 0,
                        "error": repr(e)
                    })

                await page.wait_for_timeout(delay_ms)

            # Save player-level combined file
            if player_clean_parts:
                player_all = pd.concat(player_clean_parts, ignore_index=True)
                player_output = clean_dir / f"{fide_id}_all_months_standard_clean.csv"
                player_all.to_csv(player_output, index=False)
                print("Saved player file:", player_output, "Rows:", player_all.shape[0])

            # Save status after every player
            status_df = pd.DataFrame(all_status)
            status_path = log_dir / "fide_calculation_extraction_status.csv"
            status_df.to_csv(status_path, index=False)

        await browser.close()

    return pd.DataFrame(all_status)

In [27]:
status_test = await run_extraction_for_players(
    player_ids_to_run=test_player_ids,
    periods=periods,
    rating_type=0,
    save_html=False,
    delay_ms=1500
)

display(status_test)

===== Player 1/2: 558016627 =====
Skipping existing: 558016627_2024-05-01_standard_clean.csv
Skipping existing: 558016627_2024-06-01_standard_clean.csv
Skipping existing: 558016627_2024-07-01_standard_clean.csv
Skipping existing: 558016627_2024-08-01_standard_clean.csv
Skipping existing: 558016627_2024-09-01_standard_clean.csv
Skipping existing: 558016627_2024-10-01_standard_clean.csv
Skipping existing: 558016627_2024-11-01_standard_clean.csv
Skipping existing: 558016627_2024-12-01_standard_clean.csv
Skipping existing: 558016627_2025-01-01_standard_clean.csv
Skipping existing: 558016627_2025-02-01_standard_clean.csv
Skipping existing: 558016627_2025-03-01_standard_clean.csv
Skipping existing: 558016627_2025-04-01_standard_clean.csv

===== Player 2/2: 531075452 =====
Skipping existing: 531075452_2024-05-01_standard_clean.csv
Skipping existing: 531075452_2024-06-01_standard_clean.csv
Skipping existing: 531075452_2024-07-01_standard_clean.csv
Skipping existing: 531075452_2024-08-01_standard_clean.csv
Skipping existing: 531075452_2024-09-01_standard_clean.csv
Skipping existing: 531075452_2024-10-01_standard_clean.csv
Skipping existing: 531075452_2024-11-01_standard_clean.csv
Skipping existing: 531075452_2024-12-01_standard_clean.csv
Skipping existing: 531075452_2025-01-01_standard_clean.csv
Skipping existing: 531075452_2025-02-01_standard_clean.csv
Skipping existing: 531075452_2025-03-01_standard_clean.csv
Skipping existing: 531075452_2025-04-01_standard_clean.csv

      fide_id      period  rating_type            status  clean_rows
0   558016627  2024-05-01            0  skipped_existing         NaN
1   558016627  2024-06-01            0  skipped_existing         NaN
2   558016627  2024-07-01            0  skipped_existing         NaN
3   558016627  2024-08-01            0  skipped_existing         NaN
4   558016627  2024-09-01            0  skipped_existing         NaN
5   558016627  2024-10-01            0  skipped_existing         NaN
6   558016627  2024-11-01            0  skipped_existing         NaN
7   558016627  2024-12-01            0  skipped_existing         NaN
8   558016627  2025-01-01            0  skipped_existing         NaN
9   558016627  2025-02-01            0  skipped_existing         NaN
10  558016627  2025-03-01            0  skipped_existing         NaN
11  558016627  2025-04-01            0  skipped_existing         NaN
12  531075452  2024-05-01            0  skipped_existing         NaN
13  531075452  2024-06-01            0  skipped_existing         NaN
14  531075452  2024-07-01            0  skipped_existing         NaN
15  531075452  2024-08-01            0  skipped_existing         NaN
16  531075452  2024-09-01            0  skipped_existing         NaN
17  531075452  2024-10-01            0  skipped_existing         NaN
18  531075452  2024-11-01            0  skipped_existing         NaN
19  531075452  2024-12-01            0  skipped_existing         NaN
20  531075452  2025-01-01            0  skipped_existing         NaN
21  531075452  2025-02-01            0  skipped_existing         6.0
22  531075452  2025-03-01            0  skipped_existing         NaN
23  531075452  2025-04-01            0  skipped_existing         NaN

In [21]:
status_test.tail()

      fide_id      period  rating_type                                                                              url  tables_found  events_found  clean_rows                    status
115  48724211  2024-12-01            0  https://ratings.fide.com/calculations.phtml?id_number=48724211&period=2024-1...             0             0           0  no_data_or_no_clean_rows
116  48724211  2025-01-01            0  https://ratings.fide.com/calculations.phtml?id_number=48724211&period=2025-0...             0             0           0  no_data_or_no_clean_rows
117  48724211  2025-02-01            0  https://ratings.fide.com/calculations.phtml?id_number=48724211&period=2025-0...             1             1           4                data_found
118  48724211  2025-03-01            0  https://ratings.fide.com/calculations.phtml?id_number=48724211&period=2025-0...             0             0           0  no_data_or_no_clean_rows
119  48724211  2025-04-01            0  https://ratings.fide.com/calculations.phtml?id_number=48724211&period=2025-0...             0             0           0  no_data_or_no_clean_rows

In [ ]:
#7. If test works, run all 1,000 players

In [29]:
status_all = await run_extraction_for_players(
    player_ids_to_run=player_ids,
    periods=periods,
    rating_type=0,
    save_html=False,
    delay_ms=2000
)

display(status_all)

===== Player 1/1000: 558016627 =====
Skipping existing: 558016627_2024-05-01_standard_clean.csv
Skipping existing: 558016627_2024-06-01_standard_clean.csv
Skipping existing: 558016627_2024-07-01_standard_clean.csv
Skipping existing: 558016627_2024-08-01_standard_clean.csv
Skipping existing: 558016627_2024-09-01_standard_clean.csv
Skipping existing: 558016627_2024-10-01_standard_clean.csv
Skipping existing: 558016627_2024-11-01_standard_clean.csv
Skipping existing: 558016627_2024-12-01_standard_clean.csv
Skipping existing: 558016627_2025-01-01_standard_clean.csv
Skipping existing: 558016627_2025-02-01_standard_clean.csv
Skipping existing: 558016627_2025-03-01_standard_clean.csv
Skipping existing: 558016627_2025-04-01_standard_clean.csv

===== Player 2/1000: 531075452 =====
Skipping existing: 531075452_2024-05-01_standard_clean.csv
Skipping existing: 531075452_2024-06-01_standard_clean.csv
Skipping existing: 531075452_2024-07-01_standard_clean.csv
Skipping existing: 531075452_2024-08-01_standard_clean.csv
Skipping existing: 531075452_2024-09-01_standard_clean.csv
Skipping existing: 531075452_2024-10-01_standard_clean.csv
Skipping existing: 531075452_2024-11-01_standard_clean.csv
Skipping existing: 531075452_2024-12-01_standard_clean.csv
Skipping existing: 531075452_2025-01-01_standard_clean.csv
Skipping existing: 531075452_2025-02-01_standard_clean.csv
Skipping existing: 531075452_2025-03-01_standard_clean.csv
Skipping existing: 531075452_2025-04-01_standard_clean.csv

===== Player 3/1000: 537082728 =====
Skipping existing: 537082728_2024-05-01_standard_clean.csv
Skipping existing: 537082728_2024-06-01_standard_clean.csv
Skipping existing: 537082728_2024-07-01_standard_clean.csv
Skipping existing: 537082728_2024-08-01_standard_clean.csv
Skipping existing: 537082728_2024-09-01_standard_clean.csv
Skipping existing: 537082728_2024-10-01_standard_clean.csv
Skipping existing: 537082728_2024-11-01_standard_clean.csv
Skipping existing: 537082728_2024-12-01_standard_clean.csv
Skipping existing: 537082728_2025-01-01_standard_clean.csv
Skipping existing: 537082728_2025-02-01_standard_clean.csv
Skipping existing: 537082728_2025-03-01_standard_clean.csv
Skipping existing: 537082728_2025-04-01_standard_clean.csv

===== Player 4/1000: 25789783 =====
Skipping existing: 25789783_2024-05-01_standard_clean.csv
Skipping existing: 25789783_2024-06-01_standard_clean.csv
Skipping existing: 25789783_2024-07-01_standard_clean.csv
Skipping existing: 25789783_2024-08-01_standard_clean.csv
Skipping existing: 25789783_2024-09-01_standard_clean.csv
Skipping existing: 25789783_2024-10-01_standard_clean.csv
Skipping existing: 25789783_2024-11-01_standard_clean.csv
Skipping existing: 25789783_2024-12-01_standard_clean.csv
Skipping existing: 25789783_2025-01-01_standard_clean.csv
Skipping existing: 25789783_2025-02-01_standard_clean.csv
Skipping existing: 25789783_2025-03-01_standard_clean.csv
Skipping existing: 25789783_2025-04-01_standard_clean.csv

===== Player 5/1000: 45056404 =====
Skipping existing: 45056404_2024-05-01_standard_clean.csv
Skipping existing: 45056404_2024-06-01_standard_clean.csv
Skipping existing: 45056404_2024-07-01_standard_clean.csv
Skipping existing: 45056404_2024-08-01_standard_clean.csv
Skipping existing: 45056404_2024-09-01_standard_clean.csv
Skipping existing: 45056404_2024-10-01_standard_clean.csv
Skipping existing: 45056404_2024-11-01_standard_clean.csv
Skipping existing: 45056404_2024-12-01_standard_clean.csv
Skipping existing: 45056404_2025-01-01_standard_clean.csv
Skipping existing: 45056404_2025-02-01_standard_clean.csv
Skipping existing: 45056404_2025-03-01_standard_clean.csv
Skipping existing: 45056404_2025-04-01_standard_clean.csv

===== Player 6/1000: 531047971 =====
Skipping existing: 531047971_2024-05-01_standard_clean.csv
Skipping existing: 531047971_2024-06-01_standard_clean.csv
Skipping existing: 531047971_2024-07-01_standard_clean.csv
Skipping existing: 531047971_2024-08-01_standard_clean.csv
Skipping existing: 531047971_2024-09-01_standard_clean.csv
Skipping existing: 531047971_2024-10-01_standard_clean.csv
Skipping existing: 531047971_2024-11-01_standard_clean.csv
Skipping existing: 531047971_2024-12-01_standard_clean.csv
Skipping existing: 531047971_2025-01-01_standard_clean.csv
Skipping existing: 531047971_2025-02-01_standard_clean.csv
Skipping existing: 531047971_2025-03-01_standard_clean.csv
Skipping existing: 531047971_2025-04-01_standard_clean.csv

===== Player 7/1000: 48773603 =====
Skipping existing: 48773603_2024-05-01_standard_clean.csv
Skipping existing: 48773603_2024-06-01_standard_clean.csv
Skipping existing: 48773603_2024-07-01_standard_clean.csv
Skipping existing: 48773603_2024-08-01_standard_clean.csv
Skipping existing: 48773603_2024-09-01_standard_clean.csv
Skipping existing: 48773603_2024-10-01_standard_clean.csv
Skipping existing: 48773603_2024-11-01_standard_clean.csv
Skipping existing: 48773603_2024-12-01_standard_clean.csv
Skipping existing: 48773603_2025-01-01_standard_clean.csv
Skipping existing: 48773603_2025-02-01_standard_clean.csv
Skipping existing: 48773603_2025-03-01_standard_clean.csv
Skipping existing: 48773603_2025-04-01_standard_clean.csv

===== Player 8/1000: 558008276 =====
Skipping existing: 558008276_2024-05-01_standard_clean.csv
Skipping existing: 558008276_2024-06-01_standard_clean.csv
Skipping existing: 558008276_2024-07-01_standard_clean.csv
Skipping existing: 558008276_2024-08-01_standard_clean.csv
Skipping existing: 558008276_2024-09-01_standard_clean.csv
Skipping existing: 558008276_2024-10-01_standard_clean.csv
Skipping existing: 558008276_2024-11-01_standard_clean.csv
Skipping existing: 558008276_2024-12-01_standard_clean.csv
Skipping existing: 558008276_2025-01-01_standard_clean.csv
Skipping existing: 558008276_2025-02-01_standard_clean.csv
Skipping existing: 558008276_2025-03-01_standard_clean.csv
Skipping existing: 558008276_2025-04-01_standard_clean.csv

===== Player 9/1000: 88138674 =====
Skipping existing: 88138674_2024-05-01_standard_clean.csv
Skipping existing: 88138674_2024-06-01_standard_clean.csv
Skipping existing: 88138674_2024-07-01_standard_clean.csv
Skipping existing: 88138674_2024-08-01_standard_clean.csv
Skipping existing: 88138674_2024-09-01_standard_clean.csv
Skipping existing: 88138674_2024-10-01_standard_clean.csv
Skipping existing: 88138674_2024-11-01_standard_clean.csv
Skipping existing: 88138674_2024-12-01_standard_clean.csv
Skipping existing: 88138674_2025-01-01_standard_clean.csv
Skipping existing: 88138674_2025-02-01_standard_clean.csv
Skipping existing: 88138674_2025-03-01_standard_clean.csv
Skipping existing: 88138674_2025-04-01_standard_clean.csv

===== Player 10/1000: 48724211 =====
Skipping existing: 48724211_2024-05-01_standard_clean.csv
Skipping existing: 48724211_2024-06-01_standard_clean.csv
Skipping existing: 48724211_2024-07-01_standard_clean.csv
Skipping existing: 48724211_2024-08-01_standard_clean.csv
Skipping existing: 48724211_2024-09-01_standard_clean.csv
Skipping existing: 48724211_2024-10-01_standard_clean.csv
Skipping existing: 48724211_2024-11-01_standard_clean.csv
Skipping existing: 48724211_2024-12-01_standard_clean.csv
Skipping existing: 48724211_2025-01-01_standard_clean.csv
Skipping existing: 48724211_2025-02-01_standard_clean.csv
Skipping existing: 48724211_2025-03-01_standard_clean.csv
Skipping existing: 48724211_2025-04-01_standard_clean.csv

===== Player 11/1000: 33462232 =====
Processing: 33462232 2024-05-01
No rows.
Processing: 33462232 2024-06-01
No rows.
Processing: 33462232 2024-07-01
No rows.
Processing: 33462232 2024-08-01
No rows.
Processing: 33462232 2024-09-01
No rows.
Processing: 33462232 2024-10-01
No rows.
Processing: 33462232 2024-11-01
No rows.
Processing: 33462232 2024-12-01
No rows.
Processing: 33462232 2025-01-01
No rows.
Processing: 33462232 2025-02-01
No rows.
Processing: 33462232 2025-03-01
No rows.
Processing: 33462232 2025-04-01
No rows.

===== Player 12/1000: 88195082 =====
Processing: 88195082 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 88195082 2024-06-01
No rows.
Processing: 88195082 2024-07-01
No rows.
Processing: 88195082 2024-08-01
No rows.
Processing: 88195082 2024-09-01
No rows.
Processing: 88195082 2024-10-01
No rows.
Processing: 88195082 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 88195082 2024-12-01
No rows.
Processing: 88195082 2025-01-01
No rows.
Processing: 88195082 2025-02-01
No rows.
Processing: 88195082 2025-03-01
No rows.
Processing: 88195082 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88195082_all_months_standard_clean.csv Rows: 6

===== Player 13/1000: 25926330 =====
Processing: 25926330 2024-05-01
No rows.
Processing: 25926330 2024-06-01
No rows.
Processing: 25926330 2024-07-01
No rows.
Processing: 25926330 2024-08-01
No rows.
Processing: 25926330 2024-09-01
No rows.
Processing: 25926330 2024-10-01
No rows.
Processing: 25926330 2024-11-01
No rows.
Processing: 25926330 2024-12-01
No rows.
Processing: 25926330 2025-01-01
No rows.
Processing: 25926330 2025-02-01
No rows.
Processing: 25926330 2025-03-01
No rows.
Processing: 25926330 2025-04-01
No rows.

===== Player 14/1000: 33320829 =====
Processing: 33320829 2024-05-01
No rows.
Processing: 33320829 2024-06-01
Rows: 4
Processing: 33320829 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33320829 2024-08-01
No rows.
Processing: 33320829 2024-09-01
No rows.
Processing: 33320829 2024-10-01
No rows.
Processing: 33320829 2024-11-01
No rows.
Processing: 33320829 2024-12-01
No rows.
Processing: 33320829 2025-01-01
No rows.
Processing: 33320829 2025-02-01
No rows.
Processing: 33320829 2025-03-01
No rows.
Processing: 33320829 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33320829_all_months_standard_clean.csv Rows: 9

===== Player 15/1000: 33434905 =====
Processing: 33434905 2024-05-01
No rows.
Processing: 33434905 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 33434905 2024-07-01
No rows.
Processing: 33434905 2024-08-01
No rows.
Processing: 33434905 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 33434905 2024-10-01
No rows.
Processing: 33434905 2024-11-01
No rows.
Processing: 33434905 2024-12-01
No rows.
Processing: 33434905 2025-01-01
No rows.
Processing: 33434905 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33434905 2025-03-01
No rows.
Processing: 33434905 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33434905_all_months_standard_clean.csv Rows: 22

===== Player 16/1000: 25158910 =====
Processing: 25158910 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 14
Processing: 25158910 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 12
Processing: 25158910 2024-07-01
No rows.
Processing: 25158910 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 25158910 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 25158910 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 25158910 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 25158910 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 16
Processing: 25158910 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 25158910 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 17
Processing: 25158910 2025-03-01
No rows.
Processing: 25158910 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25158910_all_months_standard_clean.csv Rows: 90

===== Player 17/1000: 429028167 =====
Processing: 429028167 2024-05-01
No rows.
Processing: 429028167 2024-06-01
No rows.
Processing: 429028167 2024-07-01
No rows.
Processing: 429028167 2024-08-01
No rows.
Processing: 429028167 2024-09-01
No rows.
Processing: 429028167 2024-10-01
No rows.
Processing: 429028167 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 429028167 2024-12-01
No rows.
Processing: 429028167 2025-01-01
No rows.
Processing: 429028167 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 429028167 2025-03-01
No rows.
Processing: 429028167 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429028167_all_months_standard_clean.csv Rows: 9

===== Player 18/1000: 25987453 =====
Processing: 25987453 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 25987453 2024-06-01
No rows.
Processing: 25987453 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 25987453 2024-08-01
No rows.
Processing: 25987453 2024-09-01
No rows.
Processing: 25987453 2024-10-01
No rows.
Processing: 25987453 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 25987453 2024-12-01
No rows.
Processing: 25987453 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 25987453 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 17
Processing: 25987453 2025-03-01
No rows.
Processing: 25987453 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25987453_all_months_standard_clean.csv Rows: 47

===== Player 19/1000: 33429804 =====
Processing: 33429804 2024-05-01
No rows.
Processing: 33429804 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 33429804 2024-07-01
No rows.
Processing: 33429804 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 33429804 2024-09-01
No rows.
Processing: 33429804 2024-10-01
No rows.
Processing: 33429804 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 33429804 2024-12-01
No rows.
Processing: 33429804 2025-01-01
No rows.
Processing: 33429804 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33429804 2025-03-01
No rows.
Processing: 33429804 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33429804_all_months_standard_clean.csv Rows: 22

===== Player 20/1000: 429065534 =====
Processing: 429065534 2024-05-01
No rows.
Processing: 429065534 2024-06-01
No rows.
Processing: 429065534 2024-07-01
No rows.
Processing: 429065534 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 429065534 2024-09-01
No rows.
Processing: 429065534 2024-10-01
No rows.
Processing: 429065534 2024-11-01
No rows.
Processing: 429065534 2024-12-01
No rows.
Processing: 429065534 2025-01-01
No rows.
Processing: 429065534 2025-02-01
No rows.
Processing: 429065534 2025-03-01
No rows.
Processing: 429065534 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429065534_all_months_standard_clean.csv Rows: 7

===== Player 21/1000: 25751948 =====
Processing: 25751948 2024-05-01
No rows.
Processing: 25751948 2024-06-01
No rows.
Processing: 25751948 2024-07-01
No rows.
Processing: 25751948 2024-08-01
No rows.
Processing: 25751948 2024-09-01
No rows.
Processing: 25751948 2024-10-01
No rows.
Processing: 25751948 2024-11-01
No rows.
Processing: 25751948 2024-12-01
No rows.
Processing: 25751948 2025-01-01
No rows.
Processing: 25751948 2025-02-01
No rows.
Processing: 25751948 2025-03-01
No rows.
Processing: 25751948 2025-04-01
No rows.

===== Player 22/1000: 547072237 =====
Processing: 547072237 2024-05-01
No rows.
Processing: 547072237 2024-06-01
No rows.
Processing: 547072237 2024-07-01
No rows.
Processing: 547072237 2024-08-01
No rows.
Processing: 547072237 2024-09-01
No rows.
Processing: 547072237 2024-10-01
No rows.
Processing: 547072237 2024-11-01
No rows.
Processing: 547072237 2024-12-01
No rows.
Processing: 547072237 2025-01-01
No rows.
Processing: 547072237 2025-02-01
No rows.
Processing: 547072237 2025-03-01
No rows.
Processing: 547072237 2025-04-01
No rows.

===== Player 23/1000: 48713740 =====
Processing: 48713740 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 48713740 2024-06-01
No rows.
Processing: 48713740 2024-07-01
No rows.
Processing: 48713740 2024-08-01
No rows.
Processing: 48713740 2024-09-01
No rows.
Processing: 48713740 2024-10-01
No rows.
Processing: 48713740 2024-11-01
No rows.
Processing: 48713740 2024-12-01
No rows.
Processing: 48713740 2025-01-01
No rows.
Processing: 48713740 2025-02-01
No rows.
Processing: 48713740 2025-03-01
No rows.
Processing: 48713740 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48713740_all_months_standard_clean.csv Rows: 7

===== Player 24/1000: 33315167 =====
Processing: 33315167 2024-05-01
No rows.
Processing: 33315167 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 33315167 2024-07-01
No rows.
Processing: 33315167 2024-08-01
No rows.
Processing: 33315167 2024-09-01
No rows.
Processing: 33315167 2024-10-01
No rows.
Processing: 33315167 2024-11-01
No rows.
Processing: 33315167 2024-12-01
No rows.
Processing: 33315167 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 33315167 2025-02-01
No rows.
Processing: 33315167 2025-03-01
No rows.
Processing: 33315167 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33315167_all_months_standard_clean.csv Rows: 8

===== Player 25/1000: 531044026 =====
Processing: 531044026 2024-05-01
No rows.
Processing: 531044026 2024-06-01
No rows.
Processing: 531044026 2024-07-01
No rows.
Processing: 531044026 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 531044026 2024-09-01
No rows.
Processing: 531044026 2024-10-01
No rows.
Processing: 531044026 2024-11-01
No rows.
Processing: 531044026 2024-12-01
No rows.
Processing: 531044026 2025-01-01
No rows.
Processing: 531044026 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 531044026 2025-03-01
No rows.
Processing: 531044026 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531044026_all_months_standard_clean.csv Rows: 10

===== Player 26/1000: 88131920 =====
Processing: 88131920 2024-05-01
No rows.
Processing: 88131920 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 88131920 2024-07-01
No rows.
Processing: 88131920 2024-08-01
No rows.
Processing: 88131920 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 88131920 2024-10-01
No rows.
Processing: 88131920 2024-11-01
No rows.
Processing: 88131920 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 88131920 2025-01-01
No rows.
Processing: 88131920 2025-02-01
No rows.
Processing: 88131920 2025-03-01
No rows.
Processing: 88131920 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88131920_all_months_standard_clean.csv Rows: 18

===== Player 27/1000: 48738107 =====
Processing: 48738107 2024-05-01
No rows.
Processing: 48738107 2024-06-01
No rows.
Processing: 48738107 2024-07-01
No rows.
Processing: 48738107 2024-08-01
No rows.
Processing: 48738107 2024-09-01
No rows.
Processing: 48738107 2024-10-01
No rows.
Processing: 48738107 2024-11-01
No rows.
Processing: 48738107 2024-12-01
No rows.
Processing: 48738107 2025-01-01
No rows.
Processing: 48738107 2025-02-01
No rows.
Processing: 48738107 2025-03-01
No rows.
Processing: 48738107 2025-04-01
No rows.

===== Player 28/1000: 33341800 =====
Processing: 33341800 2024-05-01
No rows.
Processing: 33341800 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 12
Processing: 33341800 2024-07-01
Rows: 7
Processing: 33341800 2024-08-01
No rows.
Processing: 33341800 2024-09-01
No rows.
Processing: 33341800 2024-10-01
No rows.
Processing: 33341800 2024-11-01
No rows.
Processing: 33341800 2024-12-01
No rows.
Processing: 33341800 2025-01-01
No rows.
Processing: 33341800 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 17
Processing: 33341800 2025-03-01
No rows.
Processing: 33341800 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33341800_all_months_standard_clean.csv Rows: 36

===== Player 29/1000: 429090164 =====
Processing: 429090164 2024-05-01
No rows.
Processing: 429090164 2024-06-01
No rows.
Processing: 429090164 2024-07-01
No rows.
Processing: 429090164 2024-08-01
No rows.
Processing: 429090164 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 429090164 2024-10-01
No rows.
Processing: 429090164 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 429090164 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 429090164 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 14
Processing: 429090164 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 429090164 2025-03-01
No rows.
Processing: 429090164 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429090164_all_months_standard_clean.csv Rows: 26

===== Player 30/1000: 429091047 =====
Processing: 429091047 2024-05-01
No rows.
Processing: 429091047 2024-06-01
No rows.
Processing: 429091047 2024-07-01
No rows.
Processing: 429091047 2024-08-01
No rows.
Processing: 429091047 2024-09-01
No rows.
Processing: 429091047 2024-10-01
No rows.
Processing: 429091047 2024-11-01
No rows.
Processing: 429091047 2024-12-01
No rows.
Processing: 429091047 2025-01-01
No rows.
Processing: 429091047 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 429091047 2025-03-01
No rows.
Processing: 429091047 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429091047_all_months_standard_clean.csv Rows: 8

===== Player 31/1000: 531030858 =====
Processing: 531030858 2024-05-01
No rows.
Processing: 531030858 2024-06-01
No rows.
Processing: 531030858 2024-07-01
No rows.
Processing: 531030858 2024-08-01
No rows.
Processing: 531030858 2024-09-01
No rows.
Processing: 531030858 2024-10-01
No rows.
Processing: 531030858 2024-11-01
No rows.
Processing: 531030858 2024-12-01
No rows.
Processing: 531030858 2025-01-01
No rows.
Processing: 531030858 2025-02-01
No rows.
Processing: 531030858 2025-03-01
No rows.
Processing: 531030858 2025-04-01
No rows.

===== Player 32/1000: 429040213 =====
Processing: 429040213 2024-05-01
No rows.
Processing: 429040213 2024-06-01
No rows.
Processing: 429040213 2024-07-01
No rows.
Processing: 429040213 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 429040213 2024-09-01
No rows.
Processing: 429040213 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 429040213 2024-11-01
No rows.
Processing: 429040213 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 10
Processing: 429040213 2025-01-01
No rows.
Processing: 429040213 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 429040213 2025-03-01
No rows.
Processing: 429040213 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429040213_all_months_standard_clean.csv Rows: 24

===== Player 33/1000: 537026844 =====
Processing: 537026844 2024-05-01
No rows.
Processing: 537026844 2024-06-01
No rows.
Processing: 537026844 2024-07-01
No rows.
Processing: 537026844 2024-08-01
No rows.
Processing: 537026844 2024-09-01
No rows.
Processing: 537026844 2024-10-01
No rows.
Processing: 537026844 2024-11-01
No rows.
Processing: 537026844 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 537026844 2025-01-01
No rows.
Processing: 537026844 2025-02-01
No rows.
Processing: 537026844 2025-03-01
No rows.
Processing: 537026844 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537026844_all_months_standard_clean.csv Rows: 2

===== Player 34/1000: 48726621 =====
Processing: 48726621 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 48726621 2024-06-01
No rows.
Processing: 48726621 2024-07-01
No rows.
Processing: 48726621 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 15
Processing: 48726621 2024-09-01
No rows.
Processing: 48726621 2024-10-01
No rows.
Processing: 48726621 2024-11-01
No rows.
Processing: 48726621 2024-12-01
No rows.
Processing: 48726621 2025-01-01
No rows.
Processing: 48726621 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 22
Processing: 48726621 2025-03-01
No rows.
Processing: 48726621 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48726621_all_months_standard_clean.csv Rows: 43

===== Player 35/1000: 429040531 =====
Processing: 429040531 2024-05-01
No rows.
Processing: 429040531 2024-06-01
No rows.
Processing: 429040531 2024-07-01
No rows.
Processing: 429040531 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 13
Processing: 429040531 2024-09-01
No rows.
Processing: 429040531 2024-10-01
No rows.
Processing: 429040531 2024-11-01
No rows.
Processing: 429040531 2024-12-01
No rows.
Processing: 429040531 2025-01-01
No rows.
Processing: 429040531 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 429040531 2025-03-01
No rows.
Processing: 429040531 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429040531_all_months_standard_clean.csv Rows: 16

===== Player 36/1000: 48742406 =====
Processing: 48742406 2024-05-01
No rows.
Processing: 48742406 2024-06-01
No rows.
Processing: 48742406 2024-07-01
No rows.
Processing: 48742406 2024-08-01
No rows.
Processing: 48742406 2024-09-01
No rows.
Processing: 48742406 2024-10-01
No rows.
Processing: 48742406 2024-11-01
No rows.
Processing: 48742406 2024-12-01
No rows.
Processing: 48742406 2025-01-01
No rows.
Processing: 48742406 2025-02-01
No rows.
Processing: 48742406 2025-03-01
No rows.
Processing: 48742406 2025-04-01
No rows.

===== Player 37/1000: 564013138 =====
Processing: 564013138 2024-05-01
No rows.
Processing: 564013138 2024-06-01
No rows.
Processing: 564013138 2024-07-01
No rows.
Processing: 564013138 2024-08-01
No rows.
Processing: 564013138 2024-09-01
No rows.
Processing: 564013138 2024-10-01
No rows.
Processing: 564013138 2024-11-01
No rows.
Processing: 564013138 2024-12-01
No rows.
Processing: 564013138 2025-01-01
No rows.
Processing: 564013138 2025-02-01
No rows.
Processing: 564013138 2025-03-01
No rows.
Processing: 564013138 2025-04-01
No rows.

===== Player 38/1000: 531009433 =====
Processing: 531009433 2024-05-01
No rows.
Processing: 531009433 2024-06-01
No rows.
Processing: 531009433 2024-07-01
No rows.
Processing: 531009433 2024-08-01
No rows.
Processing: 531009433 2024-09-01
No rows.
Processing: 531009433 2024-10-01
No rows.
Processing: 531009433 2024-11-01
No rows.
Processing: 531009433 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 531009433 2025-01-01
No rows.
Processing: 531009433 2025-02-01
No rows.
Processing: 531009433 2025-03-01
No rows.
Processing: 531009433 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531009433_all_months_standard_clean.csv Rows: 1

===== Player 39/1000: 25163248 =====
Processing: 25163248 2024-05-01
No rows.
Processing: 25163248 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 25163248 2024-07-01
No rows.
Processing: 25163248 2024-08-01
No rows.
Processing: 25163248 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 25163248 2024-10-01
No rows.
Processing: 25163248 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 25163248 2024-12-01
No rows.
Processing: 25163248 2025-01-01
No rows.
Processing: 25163248 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 25163248 2025-03-01
No rows.
Processing: 25163248 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25163248_all_months_standard_clean.csv Rows: 12

===== Player 40/1000: 25960164 =====
Processing: 25960164 2024-05-01
No rows.
Processing: 25960164 2024-06-01
No rows.
Processing: 25960164 2024-07-01
No rows.
Processing: 25960164 2024-08-01
No rows.
Processing: 25960164 2024-09-01
No rows.
Processing: 25960164 2024-10-01
No rows.
Processing: 25960164 2024-11-01
No rows.
Processing: 25960164 2024-12-01
No rows.
Processing: 25960164 2025-01-01
No rows.
Processing: 25960164 2025-02-01
No rows.
Processing: 25960164 2025-03-01
No rows.
Processing: 25960164 2025-04-01
No rows.

===== Player 41/1000: 429030064 =====
Processing: 429030064 2024-05-01
No rows.
Processing: 429030064 2024-06-01
No rows.
Processing: 429030064 2024-07-01
No rows.
Processing: 429030064 2024-08-01
No rows.
Processing: 429030064 2024-09-01
No rows.
Processing: 429030064 2024-10-01
No rows.
Processing: 429030064 2024-11-01
No rows.
Processing: 429030064 2024-12-01
No rows.
Processing: 429030064 2025-01-01
No rows.
Processing: 429030064 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 429030064 2025-03-01
No rows.
Processing: 429030064 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429030064_all_months_standard_clean.csv Rows: 4

===== Player 42/1000: 48760013 =====
Processing: 48760013 2024-05-01
No rows.
Processing: 48760013 2024-06-01
No rows.
Processing: 48760013 2024-07-01
No rows.
Processing: 48760013 2024-08-01
No rows.
Processing: 48760013 2024-09-01
No rows.
Processing: 48760013 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 48760013 2024-11-01
No rows.
Processing: 48760013 2024-12-01
No rows.
Processing: 48760013 2025-01-01
No rows.
Processing: 48760013 2025-02-01
No rows.
Processing: 48760013 2025-03-01
No rows.
Processing: 48760013 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48760013_all_months_standard_clean.csv Rows: 4

===== Player 43/1000: 531040535 =====
Processing: 531040535 2024-05-01
No rows.
Processing: 531040535 2024-06-01
No rows.
Processing: 531040535 2024-07-01
No rows.
Processing: 531040535 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 531040535 2024-09-01
No rows.
Processing: 531040535 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 531040535 2024-11-01
No rows.
Processing: 531040535 2024-12-01
No rows.
Processing: 531040535 2025-01-01
No rows.
Processing: 531040535 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 531040535 2025-03-01
No rows.
Processing: 531040535 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531040535_all_months_standard_clean.csv Rows: 15

===== Player 44/1000: 25600362 =====
Processing: 25600362 2024-05-01
No rows.
Processing: 25600362 2024-06-01
No rows.
Processing: 25600362 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 25600362 2024-08-01
No rows.
Processing: 25600362 2024-09-01
No rows.
Processing: 25600362 2024-10-01
No rows.
Processing: 25600362 2024-11-01
No rows.
Processing: 25600362 2024-12-01
No rows.
Processing: 25600362 2025-01-01
No rows.
Processing: 25600362 2025-02-01
No rows.
Processing: 25600362 2025-03-01
No rows.
Processing: 25600362 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25600362_all_months_standard_clean.csv Rows: 4

===== Player 45/1000: 25723804 =====
Processing: 25723804 2024-05-01
No rows.
Processing: 25723804 2024-06-01
No rows.
Processing: 25723804 2024-07-01
No rows.
Processing: 25723804 2024-08-01
No rows.
Processing: 25723804 2024-09-01
No rows.
Processing: 25723804 2024-10-01
No rows.
Processing: 25723804 2024-11-01
No rows.
Processing: 25723804 2024-12-01
No rows.
Processing: 25723804 2025-01-01
No rows.
Processing: 25723804 2025-02-01
No rows.
Processing: 25723804 2025-03-01
No rows.
Processing: 25723804 2025-04-01
No rows.

===== Player 46/1000: 33444390 =====
Processing: 33444390 2024-05-01
No rows.
Processing: 33444390 2024-06-01
No rows.
Processing: 33444390 2024-07-01
No rows.
Processing: 33444390 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 33444390 2024-09-01
No rows.
Processing: 33444390 2024-10-01
No rows.
Processing: 33444390 2024-11-01
No rows.
Processing: 33444390 2024-12-01
No rows.
Processing: 33444390 2025-01-01
No rows.
Processing: 33444390 2025-02-01
No rows.
Processing: 33444390 2025-03-01
No rows.
Processing: 33444390 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33444390_all_months_standard_clean.csv Rows: 6

===== Player 47/1000: 537047590 =====
Processing: 537047590 2024-05-01
No rows.
Processing: 537047590 2024-06-01
No rows.
Processing: 537047590 2024-07-01
No rows.
Processing: 537047590 2024-08-01
No rows.
Processing: 537047590 2024-09-01
No rows.
Processing: 537047590 2024-10-01
No rows.
Processing: 537047590 2024-11-01
No rows.
Processing: 537047590 2024-12-01
No rows.
Processing: 537047590 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 537047590 2025-02-01
No rows.
Processing: 537047590 2025-03-01
No rows.
Processing: 537047590 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537047590_all_months_standard_clean.csv Rows: 8

===== Player 48/1000: 564033694 =====
Processing: 564033694 2024-05-01
No rows.
Processing: 564033694 2024-06-01
No rows.
Processing: 564033694 2024-07-01
No rows.
Processing: 564033694 2024-08-01
No rows.
Processing: 564033694 2024-09-01
No rows.
Processing: 564033694 2024-10-01
No rows.
Processing: 564033694 2024-11-01
No rows.
Processing: 564033694 2024-12-01
No rows.
Processing: 564033694 2025-01-01
No rows.
Processing: 564033694 2025-02-01
No rows.
Processing: 564033694 2025-03-01
No rows.
Processing: 564033694 2025-04-01
No rows.

===== Player 49/1000: 33477434 =====
Processing: 33477434 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33477434 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 10
Processing: 33477434 2024-07-01
No rows.
Processing: 33477434 2024-08-01
No rows.
Processing: 33477434 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 14
Processing: 33477434 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33477434 2024-11-01
No rows.
Processing: 33477434 2024-12-01
No rows.
Processing: 33477434 2025-01-01
No rows.
Processing: 33477434 2025-02-01
No rows.
Processing: 33477434 2025-03-01
No rows.
Processing: 33477434 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33477434_all_months_standard_clean.csv Rows: 34

===== Player 50/1000: 33439869 =====
Processing: 33439869 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 33439869 2024-06-01
No rows.
Processing: 33439869 2024-07-01
No rows.
Processing: 33439869 2024-08-01
No rows.
Processing: 33439869 2024-09-01
No rows.
Processing: 33439869 2024-10-01
No rows.
Processing: 33439869 2024-11-01
No rows.
Processing: 33439869 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33439869 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33439869 2025-02-01
No rows.
Processing: 33439869 2025-03-01
No rows.
Processing: 33439869 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33439869_all_months_standard_clean.csv Rows: 23

===== Player 51/1000: 558023917 =====
Processing: 558023917 2024-05-01
No rows.
Processing: 558023917 2024-06-01
No rows.
Processing: 558023917 2024-07-01
No rows.
Processing: 558023917 2024-08-01
No rows.
Processing: 558023917 2024-09-01
No rows.
Processing: 558023917 2024-10-01
No rows.
Processing: 558023917 2024-11-01
No rows.
Processing: 558023917 2024-12-01
No rows.
Processing: 558023917 2025-01-01
No rows.
Processing: 558023917 2025-02-01
No rows.
Processing: 558023917 2025-03-01
No rows.
Processing: 558023917 2025-04-01
No rows.

===== Player 52/1000: 25137506 =====
Processing: 25137506 2024-05-01
No rows.
Processing: 25137506 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 25137506 2024-07-01
No rows.
Processing: 25137506 2024-08-01
No rows.
Processing: 25137506 2024-09-01
No rows.
Processing: 25137506 2024-10-01
No rows.
Processing: 25137506 2024-11-01
No rows.
Processing: 25137506 2024-12-01
No rows.
Processing: 25137506 2025-01-01
No rows.
Processing: 25137506 2025-02-01
No rows.
Processing: 25137506 2025-03-01
No rows.
Processing: 25137506 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25137506_all_months_standard_clean.csv Rows: 7

===== Player 53/1000: 531084737 =====
Processing: 531084737 2024-05-01
No rows.
Processing: 531084737 2024-06-01
No rows.
Processing: 531084737 2024-07-01
No rows.
Processing: 531084737 2024-08-01
No rows.
Processing: 531084737 2024-09-01
No rows.
Processing: 531084737 2024-10-01
No rows.
Processing: 531084737 2024-11-01
No rows.
Processing: 531084737 2024-12-01
No rows.
Processing: 531084737 2025-01-01
No rows.
Processing: 531084737 2025-02-01
No rows.
Processing: 531084737 2025-03-01
No rows.
Processing: 531084737 2025-04-01
No rows.

===== Player 54/1000: 537074431 =====
Processing: 537074431 2024-05-01
No rows.
Processing: 537074431 2024-06-01
No rows.
Processing: 537074431 2024-07-01
No rows.
Processing: 537074431 2024-08-01
No rows.
Processing: 537074431 2024-09-01
No rows.
Processing: 537074431 2024-10-01
No rows.
Processing: 537074431 2024-11-01
No rows.
Processing: 537074431 2024-12-01
No rows.
Processing: 537074431 2025-01-01
No rows.
Processing: 537074431 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 537074431 2025-03-01
No rows.
Processing: 537074431 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537074431_all_months_standard_clean.csv Rows: 1

===== Player 55/1000: 25727613 =====
Processing: 25727613 2024-05-01
No rows.
Processing: 25727613 2024-06-01
No rows.
Processing: 25727613 2024-07-01
No rows.
Processing: 25727613 2024-08-01
No rows.
Processing: 25727613 2024-09-01
No rows.
Processing: 25727613 2024-10-01
No rows.
Processing: 25727613 2024-11-01
No rows.
Processing: 25727613 2024-12-01
No rows.
Processing: 25727613 2025-01-01
No rows.
Processing: 25727613 2025-02-01
No rows.
Processing: 25727613 2025-03-01
No rows.
Processing: 25727613 2025-04-01
No rows.

===== Player 56/1000: 33477299 =====
Processing: 33477299 2024-05-01
No rows.
Processing: 33477299 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 33477299 2024-07-01
No rows.
Processing: 33477299 2024-08-01
No rows.
Processing: 33477299 2024-09-01
No rows.
Processing: 33477299 2024-10-01
No rows.
Processing: 33477299 2024-11-01
No rows.
Processing: 33477299 2024-12-01
No rows.
Processing: 33477299 2025-01-01
No rows.
Processing: 33477299 2025-02-01
No rows.
Processing: 33477299 2025-03-01
No rows.
Processing: 33477299 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33477299_all_months_standard_clean.csv Rows: 3

===== Player 57/1000: 547044276 =====
Processing: 547044276 2024-05-01
No rows.
Processing: 547044276 2024-06-01
No rows.
Processing: 547044276 2024-07-01
No rows.
Processing: 547044276 2024-08-01
No rows.
Processing: 547044276 2024-09-01
No rows.
Processing: 547044276 2024-10-01
No rows.
Processing: 547044276 2024-11-01
No rows.
Processing: 547044276 2024-12-01
No rows.
Processing: 547044276 2025-01-01
No rows.
Processing: 547044276 2025-02-01
No rows.
Processing: 547044276 2025-03-01
No rows.
Processing: 547044276 2025-04-01
No rows.

===== Player 58/1000: 558015388 =====
Processing: 558015388 2024-05-01
No rows.
Processing: 558015388 2024-06-01
No rows.
Processing: 558015388 2024-07-01
No rows.
Processing: 558015388 2024-08-01
No rows.
Processing: 558015388 2024-09-01
No rows.
Processing: 558015388 2024-10-01
No rows.
Processing: 558015388 2024-11-01
No rows.
Processing: 558015388 2024-12-01
No rows.
Processing: 558015388 2025-01-01
No rows.
Processing: 558015388 2025-02-01
No rows.
Processing: 558015388 2025-03-01
No rows.
Processing: 558015388 2025-04-01
No rows.

===== Player 59/1000: 25631250 =====
Processing: 25631250 2024-05-01
No rows.
Processing: 25631250 2024-06-01
No rows.
Processing: 25631250 2024-07-01
No rows.
Processing: 25631250 2024-08-01
No rows.
Processing: 25631250 2024-09-01
No rows.
Processing: 25631250 2024-10-01
No rows.
Processing: 25631250 2024-11-01
No rows.
Processing: 25631250 2024-12-01
No rows.
Processing: 25631250 2025-01-01
No rows.
Processing: 25631250 2025-02-01
No rows.
Processing: 25631250 2025-03-01
No rows.
Processing: 25631250 2025-04-01
No rows.

===== Player 60/1000: 429083923 =====
Processing: 429083923 2024-05-01
No rows.
Processing: 429083923 2024-06-01
No rows.
Processing: 429083923 2024-07-01
No rows.
Processing: 429083923 2024-08-01
No rows.
Processing: 429083923 2024-09-01
No rows.
Processing: 429083923 2024-10-01
No rows.
Processing: 429083923 2024-11-01
No rows.
Processing: 429083923 2024-12-01
No rows.
Processing: 429083923 2025-01-01
No rows.
Processing: 429083923 2025-02-01
No rows.
Processing: 429083923 2025-03-01
No rows.
Processing: 429083923 2025-04-01
No rows.

===== Player 61/1000: 429024722 =====
Processing: 429024722 2024-05-01
No rows.
Processing: 429024722 2024-06-01
No rows.
Processing: 429024722 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 429024722 2024-08-01
No rows.
Processing: 429024722 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 429024722 2024-10-01
No rows.
Processing: 429024722 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 429024722 2024-12-01
No rows.
Processing: 429024722 2025-01-01
No rows.
Processing: 429024722 2025-02-01
No rows.
Processing: 429024722 2025-03-01
No rows.
Processing: 429024722 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429024722_all_months_standard_clean.csv Rows: 14

===== Player 62/1000: 25697897 =====
Processing: 25697897 2024-05-01
No rows.
Processing: 25697897 2024-06-01
No rows.
Processing: 25697897 2024-07-01
No rows.
Processing: 25697897 2024-08-01
No rows.
Processing: 25697897 2024-09-01
No rows.
Processing: 25697897 2024-10-01
No rows.
Processing: 25697897 2024-11-01
No rows.
Processing: 25697897 2024-12-01
No rows.
Processing: 25697897 2025-01-01
No rows.
Processing: 25697897 2025-02-01
No rows.
Processing: 25697897 2025-03-01
No rows.
Processing: 25697897 2025-04-01
No rows.

===== Player 63/1000: 531064426 =====
Processing: 531064426 2024-05-01
No rows.
Processing: 531064426 2024-06-01
No rows.
Processing: 531064426 2024-07-01
No rows.
Processing: 531064426 2024-08-01
No rows.
Processing: 531064426 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 531064426 2024-10-01
No rows.
Processing: 531064426 2024-11-01
No rows.
Processing: 531064426 2024-12-01
No rows.
Processing: 531064426 2025-01-01
No rows.
Processing: 531064426 2025-02-01
No rows.
Processing: 531064426 2025-03-01
No rows.
Processing: 531064426 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531064426_all_months_standard_clean.csv Rows: 4

===== Player 64/1000: 25926314 =====
Processing: 25926314 2024-05-01
No rows.
Processing: 25926314 2024-06-01
No rows.
Processing: 25926314 2024-07-01
No rows.
Processing: 25926314 2024-08-01
No rows.
Processing: 25926314 2024-09-01
No rows.
Processing: 25926314 2024-10-01
No rows.
Processing: 25926314 2024-11-01
No rows.
Processing: 25926314 2024-12-01
No rows.
Processing: 25926314 2025-01-01
No rows.
Processing: 25926314 2025-02-01
No rows.
Processing: 25926314 2025-03-01
No rows.
Processing: 25926314 2025-04-01
No rows.

===== Player 65/1000: 48713155 =====
Processing: 48713155 2024-05-01
No rows.
Processing: 48713155 2024-06-01
No rows.
Processing: 48713155 2024-07-01
No rows.
Processing: 48713155 2024-08-01
No rows.
Processing: 48713155 2024-09-01
No rows.
Processing: 48713155 2024-10-01
No rows.
Processing: 48713155 2024-11-01
No rows.
Processing: 48713155 2024-12-01
No rows.
Processing: 48713155 2025-01-01
No rows.
Processing: 48713155 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 48713155 2025-03-01
No rows.
Processing: 48713155 2025-04-01
Rows: 4
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48713155_all_months_standard_clean.csv Rows: 9

===== Player 66/1000: 33330697 =====
Processing: 33330697 2024-05-01
No rows.
Processing: 33330697 2024-06-01
No rows.
Processing: 33330697 2024-07-01
No rows.
Processing: 33330697 2024-08-01
No rows.
Processing: 33330697 2024-09-01
No rows.
Processing: 33330697 2024-10-01
No rows.
Processing: 33330697 2024-11-01
No rows.
Processing: 33330697 2024-12-01
No rows.
Processing: 33330697 2025-01-01
No rows.
Processing: 33330697 2025-02-01
No rows.
Processing: 33330697 2025-03-01
No rows.
Processing: 33330697 2025-04-01
No rows.

===== Player 67/1000: 33409650 =====
Processing: 33409650 2024-05-01
No rows.
Processing: 33409650 2024-06-01
No rows.
Processing: 33409650 2024-07-01
No rows.
Processing: 33409650 2024-08-01
No rows.
Processing: 33409650 2024-09-01
No rows.
Processing: 33409650 2024-10-01
No rows.
Processing: 33409650 2024-11-01
No rows.
Processing: 33409650 2024-12-01
No rows.
Processing: 33409650 2025-01-01
No rows.
Processing: 33409650 2025-02-01
No rows.
Processing: 33409650 2025-03-01
No rows.
Processing: 33409650 2025-04-01
No rows.

===== Player 68/1000: 33490716 =====
Processing: 33490716 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 33490716 2024-06-01
No rows.
Processing: 33490716 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33490716 2024-08-01
No rows.
Processing: 33490716 2024-09-01
No rows.
Processing: 33490716 2024-10-01
No rows.
Processing: 33490716 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33490716 2024-12-01
No rows.
Processing: 33490716 2025-01-01
No rows.
Processing: 33490716 2025-02-01
No rows.
Processing: 33490716 2025-03-01
No rows.
Processing: 33490716 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33490716_all_months_standard_clean.csv Rows: 19

===== Player 69/1000: 74601768 =====
Processing: 74601768 2024-05-01
No rows.
Processing: 74601768 2024-06-01
No rows.
Processing: 74601768 2024-07-01
No rows.
Processing: 74601768 2024-08-01
No rows.
Processing: 74601768 2024-09-01
No rows.
Processing: 74601768 2024-10-01
No rows.
Processing: 74601768 2024-11-01
No rows.
Processing: 74601768 2024-12-01
No rows.
Processing: 74601768 2025-01-01
No rows.
Processing: 74601768 2025-02-01
No rows.
Processing: 74601768 2025-03-01
No rows.
Processing: 74601768 2025-04-01
No rows.

===== Player 70/1000: 531070000 =====
Processing: 531070000 2024-05-01
No rows.
Processing: 531070000 2024-06-01
No rows.
Processing: 531070000 2024-07-01
No rows.
Processing: 531070000 2024-08-01
No rows.
Processing: 531070000 2024-09-01
No rows.
Processing: 531070000 2024-10-01
No rows.
Processing: 531070000 2024-11-01
No rows.
Processing: 531070000 2024-12-01
No rows.
Processing: 531070000 2025-01-01
No rows.
Processing: 531070000 2025-02-01
No rows.
Processing: 531070000 2025-03-01
No rows.
Processing: 531070000 2025-04-01
No rows.

===== Player 71/1000: 531038891 =====
Processing: 531038891 2024-05-01
No rows.
Processing: 531038891 2024-06-01
No rows.
Processing: 531038891 2024-07-01
No rows.
Processing: 531038891 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 531038891 2024-09-01
No rows.
Processing: 531038891 2024-10-01
No rows.
Processing: 531038891 2024-11-01
No rows.
Processing: 531038891 2024-12-01
No rows.
Processing: 531038891 2025-01-01
No rows.
Processing: 531038891 2025-02-01
No rows.
Processing: 531038891 2025-03-01
No rows.
Processing: 531038891 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531038891_all_months_standard_clean.csv Rows: 5

===== Player 72/1000: 429096979 =====
Processing: 429096979 2024-05-01
No rows.
Processing: 429096979 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 429096979 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 429096979 2024-08-01
No rows.
Processing: 429096979 2024-09-01
No rows.
Processing: 429096979 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 429096979 2024-11-01
No rows.
Processing: 429096979 2024-12-01
No rows.
Processing: 429096979 2025-01-01
No rows.
Processing: 429096979 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 429096979 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 429096979 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429096979_all_months_standard_clean.csv Rows: 15

===== Player 73/1000: 48722979 =====
Processing: 48722979 2024-05-01
No rows.
Processing: 48722979 2024-06-01
No rows.
Processing: 48722979 2024-07-01
No rows.
Processing: 48722979 2024-08-01
No rows.
Processing: 48722979 2024-09-01
No rows.
Processing: 48722979 2024-10-01
No rows.
Processing: 48722979 2024-11-01
No rows.
Processing: 48722979 2024-12-01
No rows.
Processing: 48722979 2025-01-01
No rows.
Processing: 48722979 2025-02-01
No rows.
Processing: 48722979 2025-03-01
No rows.
Processing: 48722979 2025-04-01
No rows.

===== Player 74/1000: 25960121 =====
Processing: 25960121 2024-05-01
No rows.
Processing: 25960121 2024-06-01
No rows.
Processing: 25960121 2024-07-01
No rows.
Processing: 25960121 2024-08-01
No rows.
Processing: 25960121 2024-09-01
No rows.
Processing: 25960121 2024-10-01
No rows.
Processing: 25960121 2024-11-01
No rows.
Processing: 25960121 2024-12-01
No rows.
Processing: 25960121 2025-01-01
No rows.
Processing: 25960121 2025-02-01
No rows.
Processing: 25960121 2025-03-01
No rows.
Processing: 25960121 2025-04-01
No rows.

===== Player 75/1000: 531022626 =====
Processing: 531022626 2024-05-01
No rows.
Processing: 531022626 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 531022626 2024-07-01
No rows.
Processing: 531022626 2024-08-01
No rows.
Processing: 531022626 2024-09-01
No rows.
Processing: 531022626 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 531022626 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 531022626 2024-12-01
No rows.
Processing: 531022626 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 531022626 2025-02-01
No rows.
Processing: 531022626 2025-03-01
No rows.
Processing: 531022626 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531022626_all_months_standard_clean.csv Rows: 11

===== Player 76/1000: 531035760 =====
Processing: 531035760 2024-05-01
No rows.
Processing: 531035760 2024-06-01
No rows.
Processing: 531035760 2024-07-01
No rows.
Processing: 531035760 2024-08-01
No rows.
Processing: 531035760 2024-09-01
No rows.
Processing: 531035760 2024-10-01
No rows.
Processing: 531035760 2024-11-01
No rows.
Processing: 531035760 2024-12-01
No rows.
Processing: 531035760 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 531035760 2025-02-01
No rows.
Processing: 531035760 2025-03-01
No rows.
Processing: 531035760 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531035760_all_months_standard_clean.csv Rows: 4

===== Player 77/1000: 537031341 =====
Processing: 537031341 2024-05-01
No rows.
Processing: 537031341 2024-06-01
No rows.
Processing: 537031341 2024-07-01
No rows.
Processing: 537031341 2024-08-01
No rows.
Processing: 537031341 2024-09-01
No rows.
Processing: 537031341 2024-10-01
No rows.
Processing: 537031341 2024-11-01
No rows.
Processing: 537031341 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 537031341 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 537031341 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 537031341 2025-03-01
No rows.
Processing: 537031341 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537031341_all_months_standard_clean.csv Rows: 8

===== Player 78/1000: 531037739 =====
Processing: 531037739 2024-05-01
No rows.
Processing: 531037739 2024-06-01
No rows.
Processing: 531037739 2024-07-01
No rows.
Processing: 531037739 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 531037739 2024-09-01
No rows.
Processing: 531037739 2024-10-01
No rows.
Processing: 531037739 2024-11-01
No rows.
Processing: 531037739 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 531037739 2025-01-01
No rows.
Processing: 531037739 2025-02-01
No rows.
Processing: 531037739 2025-03-01
No rows.
Processing: 531037739 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531037739_all_months_standard_clean.csv Rows: 5

===== Player 79/1000: 547086580 =====
Processing: 547086580 2024-05-01
No rows.
Processing: 547086580 2024-06-01
No rows.
Processing: 547086580 2024-07-01
No rows.
Processing: 547086580 2024-08-01
No rows.
Processing: 547086580 2024-09-01
No rows.
Processing: 547086580 2024-10-01
No rows.
Processing: 547086580 2024-11-01
No rows.
Processing: 547086580 2024-12-01
No rows.
Processing: 547086580 2025-01-01
No rows.
Processing: 547086580 2025-02-01
No rows.
Processing: 547086580 2025-03-01
No rows.
Processing: 547086580 2025-04-01
No rows.

===== Player 80/1000: 429054338 =====
Processing: 429054338 2024-05-01
No rows.
Processing: 429054338 2024-06-01
No rows.
Processing: 429054338 2024-07-01
No rows.
Processing: 429054338 2024-08-01
No rows.
Processing: 429054338 2024-09-01
No rows.
Processing: 429054338 2024-10-01
No rows.
Processing: 429054338 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 429054338 2024-12-01
No rows.
Processing: 429054338 2025-01-01
No rows.
Processing: 429054338 2025-02-01
No rows.
Processing: 429054338 2025-03-01
No rows.
Processing: 429054338 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429054338_all_months_standard_clean.csv Rows: 2

===== Player 81/1000: 88108406 =====
Processing: 88108406 2024-05-01
No rows.
Processing: 88108406 2024-06-01
No rows.
Processing: 88108406 2024-07-01
No rows.
Processing: 88108406 2024-08-01
No rows.
Processing: 88108406 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 88108406 2024-10-01
No rows.
Processing: 88108406 2024-11-01
No rows.
Processing: 88108406 2024-12-01
No rows.
Processing: 88108406 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 88108406 2025-02-01
No rows.
Processing: 88108406 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 88108406 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88108406_all_months_standard_clean.csv Rows: 8

===== Player 82/1000: 531066798 =====
Processing: 531066798 2024-05-01
No rows.
Processing: 531066798 2024-06-01
No rows.
Processing: 531066798 2024-07-01
No rows.
Processing: 531066798 2024-08-01
No rows.
Processing: 531066798 2024-09-01
No rows.
Processing: 531066798 2024-10-01
No rows.
Processing: 531066798 2024-11-01
No rows.
Processing: 531066798 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 531066798 2025-01-01
No rows.
Processing: 531066798 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 531066798 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 531066798 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531066798_all_months_standard_clean.csv Rows: 5

===== Player 83/1000: 547009772 =====
Processing: 547009772 2024-05-01
No rows.
Processing: 547009772 2024-06-01
No rows.
Processing: 547009772 2024-07-01
No rows.
Processing: 547009772 2024-08-01
No rows.
Processing: 547009772 2024-09-01
No rows.
Processing: 547009772 2024-10-01
No rows.
Processing: 547009772 2024-11-01
No rows.
Processing: 547009772 2024-12-01
No rows.
Processing: 547009772 2025-01-01
No rows.
Processing: 547009772 2025-02-01
No rows.
Processing: 547009772 2025-03-01
No rows.
Processing: 547009772 2025-04-01
No rows.

===== Player 84/1000: 547050462 =====
Processing: 547050462 2024-05-01
No rows.
Processing: 547050462 2024-06-01
No rows.
Processing: 547050462 2024-07-01
No rows.
Processing: 547050462 2024-08-01
No rows.
Processing: 547050462 2024-09-01
No rows.
Processing: 547050462 2024-10-01
No rows.
Processing: 547050462 2024-11-01
No rows.
Processing: 547050462 2024-12-01
No rows.
Processing: 547050462 2025-01-01
No rows.
Processing: 547050462 2025-02-01
No rows.
Processing: 547050462 2025-03-01
No rows.
Processing: 547050462 2025-04-01
No rows.

===== Player 85/1000: 48799688 =====
Processing: 48799688 2024-05-01
No rows.
Processing: 48799688 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 48799688 2024-07-01
No rows.
Processing: 48799688 2024-08-01
No rows.
Processing: 48799688 2024-09-01
No rows.
Processing: 48799688 2024-10-01
No rows.
Processing: 48799688 2024-11-01
No rows.
Processing: 48799688 2024-12-01
No rows.
Processing: 48799688 2025-01-01
No rows.
Processing: 48799688 2025-02-01
No rows.
Processing: 48799688 2025-03-01
No rows.
Processing: 48799688 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48799688_all_months_standard_clean.csv Rows: 3

===== Player 86/1000: 88183432 =====
Processing: 88183432 2024-05-01
No rows.
Processing: 88183432 2024-06-01
No rows.
Processing: 88183432 2024-07-01
No rows.
Processing: 88183432 2024-08-01
No rows.
Processing: 88183432 2024-09-01
No rows.
Processing: 88183432 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 88183432 2024-11-01
No rows.
Processing: 88183432 2024-12-01
No rows.
Processing: 88183432 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 88183432 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 88183432 2025-03-01
No rows.
Processing: 88183432 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88183432_all_months_standard_clean.csv Rows: 13

===== Player 87/1000: 33319782 =====
Processing: 33319782 2024-05-01
Rows: 9
Processing: 33319782 2024-06-01
No rows.
Processing: 33319782 2024-07-01
Rows: 9
Processing: 33319782 2024-08-01
Rows: 11
Processing: 33319782 2024-09-01
Rows: 9
Processing: 33319782 2024-10-01
Rows: 18
Processing: 33319782 2024-11-01
No rows.
Processing: 33319782 2024-12-01
Rows: 8
Processing: 33319782 2025-01-01
Rows: 10
Processing: 33319782 2025-02-01
Rows: 20
Processing: 33319782 2025-03-01
No rows.
Processing: 33319782 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33319782_all_months_standard_clean.csv Rows: 94

===== Player 88/1000: 537082531 =====
Processing: 537082531 2024-05-01
No rows.
Processing: 537082531 2024-06-01
No rows.
Processing: 537082531 2024-07-01
No rows.
Processing: 537082531 2024-08-01
No rows.
Processing: 537082531 2024-09-01
No rows.
Processing: 537082531 2024-10-01
No rows.
Processing: 537082531 2024-11-01
No rows.
Processing: 537082531 2024-12-01
No rows.
Processing: 537082531 2025-01-01
No rows.
Processing: 537082531 2025-02-01
No rows.
Processing: 537082531 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 537082531 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537082531_all_months_standard_clean.csv Rows: 4

===== Player 89/1000: 88163156 =====
Processing: 88163156 2024-05-01
No rows.
Processing: 88163156 2024-06-01
No rows.
Processing: 88163156 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 88163156 2024-08-01
No rows.
Processing: 88163156 2024-09-01
No rows.
Processing: 88163156 2024-10-01
No rows.
Processing: 88163156 2024-11-01
No rows.
Processing: 88163156 2024-12-01
No rows.
Processing: 88163156 2025-01-01
No rows.
Processing: 88163156 2025-02-01
No rows.
Processing: 88163156 2025-03-01
No rows.
Processing: 88163156 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88163156_all_months_standard_clean.csv Rows: 5

===== Player 90/1000: 25916203 =====
Processing: 25916203 2024-05-01
No rows.
Processing: 25916203 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 25916203 2024-07-01
No rows.
Processing: 25916203 2024-08-01
No rows.
Processing: 25916203 2024-09-01
No rows.
Processing: 25916203 2024-10-01
No rows.
Processing: 25916203 2024-11-01
No rows.
Processing: 25916203 2024-12-01
No rows.
Processing: 25916203 2025-01-01
No rows.
Processing: 25916203 2025-02-01
No rows.
Processing: 25916203 2025-03-01
No rows.
Processing: 25916203 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25916203_all_months_standard_clean.csv Rows: 6

===== Player 91/1000: 48773859 =====
Processing: 48773859 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 48773859 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 48773859 2024-07-01
No rows.
Processing: 48773859 2024-08-01
No rows.
Processing: 48773859 2024-09-01
No rows.
Processing: 48773859 2024-10-01
No rows.
Processing: 48773859 2024-11-01
No rows.
Processing: 48773859 2024-12-01
No rows.
Processing: 48773859 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 48773859 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 48773859 2025-03-01
No rows.
Processing: 48773859 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48773859_all_months_standard_clean.csv Rows: 22

===== Player 92/1000: 547040637 =====
Processing: 547040637 2024-05-01
No rows.
Processing: 547040637 2024-06-01
No rows.
Processing: 547040637 2024-07-01
No rows.
Processing: 547040637 2024-08-01
No rows.
Processing: 547040637 2024-09-01
No rows.
Processing: 547040637 2024-10-01
No rows.
Processing: 547040637 2024-11-01
No rows.
Processing: 547040637 2024-12-01
No rows.
Processing: 547040637 2025-01-01
No rows.
Processing: 547040637 2025-02-01
No rows.
Processing: 547040637 2025-03-01
No rows.
Processing: 547040637 2025-04-01
No rows.

===== Player 93/1000: 537062336 =====
Processing: 537062336 2024-05-01
No rows.
Processing: 537062336 2024-06-01
No rows.
Processing: 537062336 2024-07-01
No rows.
Processing: 537062336 2024-08-01
No rows.
Processing: 537062336 2024-09-01
No rows.
Processing: 537062336 2024-10-01
No rows.
Processing: 537062336 2024-11-01
No rows.
Processing: 537062336 2024-12-01
No rows.
Processing: 537062336 2025-01-01
No rows.
Processing: 537062336 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 537062336 2025-03-01
No rows.
Processing: 537062336 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537062336_all_months_standard_clean.csv Rows: 6

===== Player 94/1000: 564005437 =====
Processing: 564005437 2024-05-01
No rows.
Processing: 564005437 2024-06-01
No rows.
Processing: 564005437 2024-07-01
No rows.
Processing: 564005437 2024-08-01
No rows.
Processing: 564005437 2024-09-01
No rows.
Processing: 564005437 2024-10-01
No rows.
Processing: 564005437 2024-11-01
No rows.
Processing: 564005437 2024-12-01
No rows.
Processing: 564005437 2025-01-01
No rows.
Processing: 564005437 2025-02-01
No rows.
Processing: 564005437 2025-03-01
No rows.
Processing: 564005437 2025-04-01
No rows.

===== Player 95/1000: 537041754 =====
Processing: 537041754 2024-05-01
No rows.
Processing: 537041754 2024-06-01
No rows.
Processing: 537041754 2024-07-01
No rows.
Processing: 537041754 2024-08-01
No rows.
Processing: 537041754 2024-09-01
No rows.
Processing: 537041754 2024-10-01
No rows.
Processing: 537041754 2024-11-01
No rows.
Processing: 537041754 2024-12-01
No rows.
Processing: 537041754 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 537041754 2025-02-01
No rows.
Processing: 537041754 2025-03-01
No rows.
Processing: 537041754 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537041754_all_months_standard_clean.csv Rows: 6

===== Player 96/1000: 531001424 =====
Processing: 531001424 2024-05-01
No rows.
Processing: 531001424 2024-06-01
No rows.
Processing: 531001424 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 531001424 2024-08-01
No rows.
Processing: 531001424 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 531001424 2024-10-01
No rows.
Processing: 531001424 2024-11-01
No rows.
Processing: 531001424 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 531001424 2025-01-01
No rows.
Processing: 531001424 2025-02-01
No rows.
Processing: 531001424 2025-03-01
No rows.
Processing: 531001424 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531001424_all_months_standard_clean.csv Rows: 17

===== Player 97/1000: 33421250 =====
Processing: 33421250 2024-05-01
No rows.
Processing: 33421250 2024-06-01
No rows.
Processing: 33421250 2024-07-01
No rows.
Processing: 33421250 2024-08-01
No rows.
Processing: 33421250 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 33421250 2024-10-01
No rows.
Processing: 33421250 2024-11-01
No rows.
Processing: 33421250 2024-12-01
No rows.
Processing: 33421250 2025-01-01
No rows.
Processing: 33421250 2025-02-01
No rows.
Processing: 33421250 2025-03-01
No rows.
Processing: 33421250 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33421250_all_months_standard_clean.csv Rows: 3

===== Player 98/1000: 33392854 =====
Processing: 33392854 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 33392854 2024-06-01
No rows.
Processing: 33392854 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 10
Processing: 33392854 2024-08-01
No rows.
Processing: 33392854 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33392854 2024-10-01
No rows.
Processing: 33392854 2024-11-01
No rows.
Processing: 33392854 2024-12-01
No rows.
Processing: 33392854 2025-01-01
No rows.
Processing: 33392854 2025-02-01
No rows.
Processing: 33392854 2025-03-01
No rows.
Processing: 33392854 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33392854_all_months_standard_clean.csv Rows: 18

===== Player 99/1000: 429023599 =====
Processing: 429023599 2024-05-01
No rows.
Processing: 429023599 2024-06-01
No rows.
Processing: 429023599 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 429023599 2024-08-01
No rows.
Processing: 429023599 2024-09-01
No rows.
Processing: 429023599 2024-10-01
No rows.
Processing: 429023599 2024-11-01
No rows.
Processing: 429023599 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 429023599 2025-01-01
No rows.
Processing: 429023599 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 429023599 2025-03-01
No rows.
Processing: 429023599 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429023599_all_months_standard_clean.csv Rows: 11

===== Player 100/1000: 33491089 =====
Processing: 33491089 2024-05-01
No rows.
Processing: 33491089 2024-06-01
No rows.
Processing: 33491089 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 33491089 2024-08-01
No rows.
Processing: 33491089 2024-09-01
No rows.
Processing: 33491089 2024-10-01
No rows.
Processing: 33491089 2024-11-01
No rows.
Processing: 33491089 2024-12-01
No rows.
Processing: 33491089 2025-01-01
No rows.
Processing: 33491089 2025-02-01
No rows.
Processing: 33491089 2025-03-01
No rows.
Processing: 33491089 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33491089_all_months_standard_clean.csv Rows: 3

===== Player 101/1000: 558012222 =====
Processing: 558012222 2024-05-01
No rows.
Processing: 558012222 2024-06-01
No rows.
Processing: 558012222 2024-07-01
No rows.
Processing: 558012222 2024-08-01
No rows.
Processing: 558012222 2024-09-01
No rows.
Processing: 558012222 2024-10-01
No rows.
Processing: 558012222 2024-11-01
No rows.
Processing: 558012222 2024-12-01
No rows.
Processing: 558012222 2025-01-01
No rows.
Processing: 558012222 2025-02-01
No rows.
Processing: 558012222 2025-03-01
No rows.
Processing: 558012222 2025-04-01
No rows.

===== Player 102/1000: 547077808 =====
Processing: 547077808 2024-05-01
No rows.
Processing: 547077808 2024-06-01
No rows.
Processing: 547077808 2024-07-01
No rows.
Processing: 547077808 2024-08-01
No rows.
Processing: 547077808 2024-09-01
No rows.
Processing: 547077808 2024-10-01
No rows.
Processing: 547077808 2024-11-01
No rows.
Processing: 547077808 2024-12-01
No rows.
Processing: 547077808 2025-01-01
No rows.
Processing: 547077808 2025-02-01
No rows.
Processing: 547077808 2025-03-01
No rows.
Processing: 547077808 2025-04-01
No rows.

===== Player 103/1000: 25600117 =====
Processing: 25600117 2024-05-01
No rows.
Processing: 25600117 2024-06-01
No rows.
Processing: 25600117 2024-07-01
No rows.
Processing: 25600117 2024-08-01
No rows.
Processing: 25600117 2024-09-01
No rows.
Processing: 25600117 2024-10-01
No rows.
Processing: 25600117 2024-11-01
No rows.
Processing: 25600117 2024-12-01
No rows.
Processing: 25600117 2025-01-01
No rows.
Processing: 25600117 2025-02-01
No rows.
Processing: 25600117 2025-03-01
No rows.
Processing: 25600117 2025-04-01
No rows.

===== Player 104/1000: 537033093 =====
Processing: 537033093 2024-05-01
No rows.
Processing: 537033093 2024-06-01
No rows.
Processing: 537033093 2024-07-01
No rows.
Processing: 537033093 2024-08-01
No rows.
Processing: 537033093 2024-09-01
No rows.
Processing: 537033093 2024-10-01
No rows.
Processing: 537033093 2024-11-01
No rows.
Processing: 537033093 2024-12-01
No rows.
Processing: 537033093 2025-01-01
No rows.
Processing: 537033093 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 537033093 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 537033093 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537033093_all_months_standard_clean.csv Rows: 7

===== Player 105/1000: 33441340 =====
Processing: 33441340 2024-05-01
No rows.
Processing: 33441340 2024-06-01
No rows.
Processing: 33441340 2024-07-01
No rows.
Processing: 33441340 2024-08-01
No rows.
Processing: 33441340 2024-09-01
No rows.
Processing: 33441340 2024-10-01
No rows.
Processing: 33441340 2024-11-01
No rows.
Processing: 33441340 2024-12-01
No rows.
Processing: 33441340 2025-01-01
No rows.
Processing: 33441340 2025-02-01
No rows.
Processing: 33441340 2025-03-01
No rows.
Processing: 33441340 2025-04-01
No rows.

===== Player 106/1000: 558024387 =====
Processing: 558024387 2024-05-01
No rows.
Processing: 558024387 2024-06-01
No rows.
Processing: 558024387 2024-07-01
No rows.
Processing: 558024387 2024-08-01
No rows.
Processing: 558024387 2024-09-01
No rows.
Processing: 558024387 2024-10-01
No rows.
Processing: 558024387 2024-11-01
No rows.
Processing: 558024387 2024-12-01
No rows.
Processing: 558024387 2025-01-01
No rows.
Processing: 558024387 2025-02-01
No rows.
Processing: 558024387 2025-03-01
No rows.
Processing: 558024387 2025-04-01
No rows.

===== Player 107/1000: 25153331 =====
Processing: 25153331 2024-05-01
No rows.
Processing: 25153331 2024-06-01
No rows.
Processing: 25153331 2024-07-01
No rows.
Processing: 25153331 2024-08-01
No rows.
Processing: 25153331 2024-09-01
No rows.
Processing: 25153331 2024-10-01
No rows.
Processing: 25153331 2024-11-01
No rows.
Processing: 25153331 2024-12-01
No rows.
Processing: 25153331 2025-01-01
No rows.
Processing: 25153331 2025-02-01
No rows.
Processing: 25153331 2025-03-01
No rows.
Processing: 25153331 2025-04-01
No rows.

===== Player 108/1000: 366127043 =====
Processing: 366127043 2024-05-01
No rows.
Processing: 366127043 2024-06-01
No rows.
Processing: 366127043 2024-07-01
No rows.
Processing: 366127043 2024-08-01
No rows.
Processing: 366127043 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 366127043 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 366127043 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 366127043 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 366127043 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 366127043 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 366127043 2025-03-01
No rows.
Processing: 366127043 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/366127043_all_months_standard_clean.csv Rows: 46

===== Player 109/1000: 537040120 =====
Processing: 537040120 2024-05-01
No rows.
Processing: 537040120 2024-06-01
No rows.
Processing: 537040120 2024-07-01
No rows.
Processing: 537040120 2024-08-01
No rows.
Processing: 537040120 2024-09-01
No rows.
Processing: 537040120 2024-10-01
No rows.
Processing: 537040120 2024-11-01
No rows.
Processing: 537040120 2024-12-01
No rows.
Processing: 537040120 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 537040120 2025-02-01
No rows.
Processing: 537040120 2025-03-01
No rows.
Processing: 537040120 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537040120_all_months_standard_clean.csv Rows: 1

===== Player 110/1000: 343444890 =====
Processing: 343444890 2024-05-01
No rows.
Processing: 343444890 2024-06-01
No rows.
Processing: 343444890 2024-07-01
No rows.
Processing: 343444890 2024-08-01
No rows.
Processing: 343444890 2024-09-01
No rows.
Processing: 343444890 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 343444890 2024-11-01
No rows.
Processing: 343444890 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 19
Processing: 343444890 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 343444890 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 24
Processing: 343444890 2025-03-01
No rows.
Processing: 343444890 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 15
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/343444890_all_months_standard_clean.csv Rows: 74

===== Player 111/1000: 88163717 =====
Processing: 88163717 2024-05-01
No rows.
Processing: 88163717 2024-06-01
No rows.
Processing: 88163717 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 88163717 2024-08-01
No rows.
Processing: 88163717 2024-09-01
No rows.
Processing: 88163717 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 88163717 2024-11-01
No rows.
Processing: 88163717 2024-12-01
No rows.
Processing: 88163717 2025-01-01
No rows.
Processing: 88163717 2025-02-01
No rows.
Processing: 88163717 2025-03-01
No rows.
Processing: 88163717 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88163717_all_months_standard_clean.csv Rows: 4

===== Player 112/1000: 25998870 =====
Processing: 25998870 2024-05-01
No rows.
Processing: 25998870 2024-06-01
No rows.
Processing: 25998870 2024-07-01
No rows.
Processing: 25998870 2024-08-01
No rows.
Processing: 25998870 2024-09-01
No rows.
Processing: 25998870 2024-10-01
No rows.
Processing: 25998870 2024-11-01
No rows.
Processing: 25998870 2024-12-01
No rows.
Processing: 25998870 2025-01-01
No rows.
Processing: 25998870 2025-02-01
No rows.
Processing: 25998870 2025-03-01
No rows.
Processing: 25998870 2025-04-01
No rows.

===== Player 113/1000: 25793136 =====
Processing: 25793136 2024-05-01
No rows.
Processing: 25793136 2024-06-01
Rows: 9
Processing: 25793136 2024-07-01
No rows.
Processing: 25793136 2024-08-01
No rows.
Processing: 25793136 2024-09-01
No rows.
Processing: 25793136 2024-10-01
Rows: 11
Processing: 25793136 2024-11-01
No rows.
Processing: 25793136 2024-12-01
Rows: 11
Processing: 25793136 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 25793136 2025-02-01
No rows.
Processing: 25793136 2025-03-01
No rows.
Processing: 25793136 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25793136_all_months_standard_clean.csv Rows: 40

===== Player 114/1000: 25693808 =====
Processing: 25693808 2024-05-01
No rows.
Processing: 25693808 2024-06-01
No rows.
Processing: 25693808 2024-07-01
No rows.
Processing: 25693808 2024-08-01
No rows.
Processing: 25693808 2024-09-01
No rows.
Processing: 25693808 2024-10-01
No rows.
Processing: 25693808 2024-11-01
No rows.
Processing: 25693808 2024-12-01
No rows.
Processing: 25693808 2025-01-01
No rows.
Processing: 25693808 2025-02-01
No rows.
Processing: 25693808 2025-03-01
No rows.
Processing: 25693808 2025-04-01
No rows.

===== Player 115/1000: 48739162 =====
Processing: 48739162 2024-05-01
No rows.
Processing: 48739162 2024-06-01
No rows.
Processing: 48739162 2024-07-01
No rows.
Processing: 48739162 2024-08-01
No rows.
Processing: 48739162 2024-09-01
No rows.
Processing: 48739162 2024-10-01
No rows.
Processing: 48739162 2024-11-01
No rows.
Processing: 48739162 2024-12-01
No rows.
Processing: 48739162 2025-01-01
No rows.
Processing: 48739162 2025-02-01
No rows.
Processing: 48739162 2025-03-01
No rows.
Processing: 48739162 2025-04-01
No rows.

===== Player 116/1000: 429002508 =====
Processing: 429002508 2024-05-01
No rows.
Processing: 429002508 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 429002508 2024-07-01
No rows.
Processing: 429002508 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 429002508 2024-09-01
No rows.
Processing: 429002508 2024-10-01
No rows.
Processing: 429002508 2024-11-01
No rows.
Processing: 429002508 2024-12-01
No rows.
Processing: 429002508 2025-01-01
No rows.
Processing: 429002508 2025-02-01
No rows.
Processing: 429002508 2025-03-01
No rows.
Processing: 429002508 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429002508_all_months_standard_clean.csv Rows: 7

===== Player 117/1000: 429077087 =====
Processing: 429077087 2024-05-01
No rows.
Processing: 429077087 2024-06-01
No rows.
Processing: 429077087 2024-07-01
No rows.
Processing: 429077087 2024-08-01
No rows.
Processing: 429077087 2024-09-01
No rows.
Processing: 429077087 2024-10-01
No rows.
Processing: 429077087 2024-11-01
No rows.
Processing: 429077087 2024-12-01
No rows.
Processing: 429077087 2025-01-01
No rows.
Processing: 429077087 2025-02-01
No rows.
Processing: 429077087 2025-03-01
No rows.
Processing: 429077087 2025-04-01
No rows.

===== Player 118/1000: 33398968 =====
Processing: 33398968 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33398968 2024-06-01
No rows.
Processing: 33398968 2024-07-01
Rows: 7
Processing: 33398968 2024-08-01
No rows.
Processing: 33398968 2024-09-01
No rows.
Processing: 33398968 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33398968 2024-11-01
Rows: 11
Processing: 33398968 2024-12-01
No rows.
Processing: 33398968 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 19
Processing: 33398968 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 33398968 2025-03-01
No rows.
Processing: 33398968 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33398968_all_months_standard_clean.csv Rows: 62

===== Player 119/1000: 564010937 =====
Processing: 564010937 2024-05-01
No rows.
Processing: 564010937 2024-06-01
No rows.
Processing: 564010937 2024-07-01
No rows.
Processing: 564010937 2024-08-01
No rows.
Processing: 564010937 2024-09-01
No rows.
Processing: 564010937 2024-10-01
No rows.
Processing: 564010937 2024-11-01
No rows.
Processing: 564010937 2024-12-01
No rows.
Processing: 564010937 2025-01-01
No rows.
Processing: 564010937 2025-02-01
No rows.
Processing: 564010937 2025-03-01
No rows.
Processing: 564010937 2025-04-01
No rows.

===== Player 120/1000: 429020476 =====
Processing: 429020476 2024-05-01
No rows.
Processing: 429020476 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 429020476 2024-07-01
No rows.
Processing: 429020476 2024-08-01
No rows.
Processing: 429020476 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 429020476 2024-10-01
No rows.
Processing: 429020476 2024-11-01
No rows.
Processing: 429020476 2024-12-01
No rows.
Processing: 429020476 2025-01-01
No rows.
Processing: 429020476 2025-02-01
No rows.
Processing: 429020476 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 429020476 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429020476_all_months_standard_clean.csv Rows: 8

===== Player 121/1000: 537042904 =====
Processing: 537042904 2024-05-01
No rows.
Processing: 537042904 2024-06-01
No rows.
Processing: 537042904 2024-07-01
No rows.
Processing: 537042904 2024-08-01
No rows.
Processing: 537042904 2024-09-01
No rows.
Processing: 537042904 2024-10-01
No rows.
Processing: 537042904 2024-11-01
No rows.
Processing: 537042904 2024-12-01
No rows.
Processing: 537042904 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 537042904 2025-02-01
No rows.
Processing: 537042904 2025-03-01
No rows.
Processing: 537042904 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537042904_all_months_standard_clean.csv Rows: 2

===== Player 122/1000: 547006242 =====
Processing: 547006242 2024-05-01
No rows.
Processing: 547006242 2024-06-01
No rows.
Processing: 547006242 2024-07-01
No rows.
Processing: 547006242 2024-08-01
No rows.
Processing: 547006242 2024-09-01
No rows.
Processing: 547006242 2024-10-01
No rows.
Processing: 547006242 2024-11-01
No rows.
Processing: 547006242 2024-12-01
No rows.
Processing: 547006242 2025-01-01
No rows.
Processing: 547006242 2025-02-01
No rows.
Processing: 547006242 2025-03-01
No rows.
Processing: 547006242 2025-04-01
No rows.

===== Player 123/1000: 429025702 =====
Processing: 429025702 2024-05-01
No rows.
Processing: 429025702 2024-06-01
No rows.
Processing: 429025702 2024-07-01
No rows.
Processing: 429025702 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 429025702 2024-09-01
No rows.
Processing: 429025702 2024-10-01
No rows.
Processing: 429025702 2024-11-01
No rows.
Processing: 429025702 2024-12-01
No rows.
Processing: 429025702 2025-01-01
No rows.
Processing: 429025702 2025-02-01
No rows.
Processing: 429025702 2025-03-01
No rows.
Processing: 429025702 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429025702_all_months_standard_clean.csv Rows: 6

===== Player 124/1000: 33357684 =====
Processing: 33357684 2024-05-01
No rows.
Processing: 33357684 2024-06-01
No rows.
Processing: 33357684 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 33357684 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 33357684 2024-09-01
No rows.
Processing: 33357684 2024-10-01
No rows.
Processing: 33357684 2024-11-01
No rows.
Processing: 33357684 2024-12-01
No rows.
Processing: 33357684 2025-01-01
No rows.
Processing: 33357684 2025-02-01
No rows.
Processing: 33357684 2025-03-01
No rows.
Processing: 33357684 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33357684_all_months_standard_clean.csv Rows: 2

===== Player 125/1000: 531070191 =====
Processing: 531070191 2024-05-01
No rows.
Processing: 531070191 2024-06-01
No rows.
Processing: 531070191 2024-07-01
No rows.
Processing: 531070191 2024-08-01
No rows.
Processing: 531070191 2024-09-01
No rows.
Processing: 531070191 2024-10-01
No rows.
Processing: 531070191 2024-11-01
No rows.
Processing: 531070191 2024-12-01
No rows.
Processing: 531070191 2025-01-01
No rows.
Processing: 531070191 2025-02-01
No rows.
Processing: 531070191 2025-03-01
No rows.
Processing: 531070191 2025-04-01
No rows.

===== Player 126/1000: 33491780 =====
Processing: 33491780 2024-05-01
No rows.
Processing: 33491780 2024-06-01
No rows.
Processing: 33491780 2024-07-01
No rows.
Processing: 33491780 2024-08-01
No rows.
Processing: 33491780 2024-09-01
No rows.
Processing: 33491780 2024-10-01
No rows.
Processing: 33491780 2024-11-01
No rows.
Processing: 33491780 2024-12-01
No rows.
Processing: 33491780 2025-01-01
No rows.
Processing: 33491780 2025-02-01
No rows.
Processing: 33491780 2025-03-01
No rows.
Processing: 33491780 2025-04-01
No rows.

===== Player 127/1000: 558037330 =====
Processing: 558037330 2024-05-01
No rows.
Processing: 558037330 2024-06-01
No rows.
Processing: 558037330 2024-07-01
No rows.
Processing: 558037330 2024-08-01
No rows.
Processing: 558037330 2024-09-01
No rows.
Processing: 558037330 2024-10-01
No rows.
Processing: 558037330 2024-11-01
No rows.
Processing: 558037330 2024-12-01
No rows.
Processing: 558037330 2025-01-01
No rows.
Processing: 558037330 2025-02-01
No rows.
Processing: 558037330 2025-03-01
No rows.
Processing: 558037330 2025-04-01
No rows.

===== Player 128/1000: 88113760 =====
Processing: 88113760 2024-05-01
No rows.
Processing: 88113760 2024-06-01
No rows.
Processing: 88113760 2024-07-01
No rows.
Processing: 88113760 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 88113760 2024-09-01
No rows.
Processing: 88113760 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 88113760 2024-11-01
No rows.
Processing: 88113760 2024-12-01
No rows.
Processing: 88113760 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 88113760 2025-02-01
No rows.
Processing: 88113760 2025-03-01
No rows.
Processing: 88113760 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88113760_all_months_standard_clean.csv Rows: 4

===== Player 129/1000: 25739557 =====
Processing: 25739557 2024-05-01
No rows.
Processing: 25739557 2024-06-01
No rows.
Processing: 25739557 2024-07-01
No rows.
Processing: 25739557 2024-08-01
No rows.
Processing: 25739557 2024-09-01
No rows.
Processing: 25739557 2024-10-01
No rows.
Processing: 25739557 2024-11-01
No rows.
Processing: 25739557 2024-12-01
No rows.
Processing: 25739557 2025-01-01
No rows.
Processing: 25739557 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 26
Processing: 25739557 2025-03-01
No rows.
Processing: 25739557 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25739557_all_months_standard_clean.csv Rows: 26

===== Player 130/1000: 88123090 =====
Processing: 88123090 2024-05-01
No rows.
Processing: 88123090 2024-06-01
No rows.
Processing: 88123090 2024-07-01
No rows.
Processing: 88123090 2024-08-01
No rows.
Processing: 88123090 2024-09-01
No rows.
Processing: 88123090 2024-10-01
No rows.
Processing: 88123090 2024-11-01
No rows.
Processing: 88123090 2024-12-01
No rows.
Processing: 88123090 2025-01-01
No rows.
Processing: 88123090 2025-02-01
No rows.
Processing: 88123090 2025-03-01
No rows.
Processing: 88123090 2025-04-01
No rows.

===== Player 131/1000: 25162578 =====
Processing: 25162578 2024-05-01
No rows.
Processing: 25162578 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 25162578 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 25162578 2024-08-01
No rows.
Processing: 25162578 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 25162578 2024-10-01
No rows.
Processing: 25162578 2024-11-01
No rows.
Processing: 25162578 2024-12-01
No rows.
Processing: 25162578 2025-01-01
No rows.
Processing: 25162578 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 25162578 2025-03-01
No rows.
Processing: 25162578 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25162578_all_months_standard_clean.csv Rows: 20

===== Player 132/1000: 531019730 =====
Processing: 531019730 2024-05-01
No rows.
Processing: 531019730 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 531019730 2024-07-01
No rows.
Processing: 531019730 2024-08-01
No rows.
Processing: 531019730 2024-09-01
No rows.
Processing: 531019730 2024-10-01
No rows.
Processing: 531019730 2024-11-01
No rows.
Processing: 531019730 2024-12-01
No rows.
Processing: 531019730 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 531019730 2025-02-01
No rows.
Processing: 531019730 2025-03-01
No rows.
Processing: 531019730 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531019730_all_months_standard_clean.csv Rows: 8

===== Player 133/1000: 429019508 =====
Processing: 429019508 2024-05-01
No rows.
Processing: 429019508 2024-06-01
No rows.
Processing: 429019508 2024-07-01
No rows.
Processing: 429019508 2024-08-01
No rows.
Processing: 429019508 2024-09-01
No rows.
Processing: 429019508 2024-10-01
No rows.
Processing: 429019508 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 429019508 2024-12-01
No rows.
Processing: 429019508 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 429019508 2025-02-01
No rows.
Processing: 429019508 2025-03-01
No rows.
Processing: 429019508 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429019508_all_months_standard_clean.csv Rows: 12

===== Player 134/1000: 25182242 =====
Processing: 25182242 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 18
Processing: 25182242 2024-06-01
No rows.
Processing: 25182242 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 25182242 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 27
Processing: 25182242 2024-09-01
Rows: 11
Processing: 25182242 2024-10-01
Rows: 11
Processing: 25182242 2024-11-01
No rows.
Processing: 25182242 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 25182242 2025-01-01
Rows: 20
Processing: 25182242 2025-02-01
Rows: 10
Processing: 25182242 2025-03-01
No rows.
Processing: 25182242 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25182242_all_months_standard_clean.csv Rows: 124

===== Player 135/1000: 25751336 =====
Processing: 25751336 2024-05-01
No rows.
Processing: 25751336 2024-06-01
No rows.
Processing: 25751336 2024-07-01
No rows.
Processing: 25751336 2024-08-01
No rows.
Processing: 25751336 2024-09-01
No rows.
Processing: 25751336 2024-10-01
No rows.
Processing: 25751336 2024-11-01
No rows.
Processing: 25751336 2024-12-01
No rows.
Processing: 25751336 2025-01-01
No rows.
Processing: 25751336 2025-02-01
No rows.
Processing: 25751336 2025-03-01
No rows.
Processing: 25751336 2025-04-01
No rows.

===== Player 136/1000: 88136299 =====
Processing: 88136299 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 88136299 2024-06-01
No rows.
Processing: 88136299 2024-07-01
No rows.
Processing: 88136299 2024-08-01
No rows.
Processing: 88136299 2024-09-01
No rows.
Processing: 88136299 2024-10-01
No rows.
Processing: 88136299 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 88136299 2024-12-01
No rows.
Processing: 88136299 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 29
Processing: 88136299 2025-02-01
No rows.
Processing: 88136299 2025-03-01
No rows.
Processing: 88136299 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88136299_all_months_standard_clean.csv Rows: 38

===== Player 137/1000: 88167569 =====
Processing: 88167569 2024-05-01
No rows.
Processing: 88167569 2024-06-01
No rows.
Processing: 88167569 2024-07-01
No rows.
Processing: 88167569 2024-08-01
No rows.
Processing: 88167569 2024-09-01
No rows.
Processing: 88167569 2024-10-01
No rows.
Processing: 88167569 2024-11-01
No rows.
Processing: 88167569 2024-12-01
No rows.
Processing: 88167569 2025-01-01
No rows.
Processing: 88167569 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 88167569 2025-03-01
No rows.
Processing: 88167569 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88167569_all_months_standard_clean.csv Rows: 7

===== Player 138/1000: 547059206 =====
Processing: 547059206 2024-05-01
No rows.
Processing: 547059206 2024-06-01
No rows.
Processing: 547059206 2024-07-01
No rows.
Processing: 547059206 2024-08-01
No rows.
Processing: 547059206 2024-09-01
No rows.
Processing: 547059206 2024-10-01
No rows.
Processing: 547059206 2024-11-01
No rows.
Processing: 547059206 2024-12-01
No rows.
Processing: 547059206 2025-01-01
No rows.
Processing: 547059206 2025-02-01
No rows.
Processing: 547059206 2025-03-01
No rows.
Processing: 547059206 2025-04-01
No rows.

===== Player 139/1000: 537058673 =====
Processing: 537058673 2024-05-01
No rows.
Processing: 537058673 2024-06-01
No rows.
Processing: 537058673 2024-07-01
No rows.
Processing: 537058673 2024-08-01
No rows.
Processing: 537058673 2024-09-01
No rows.
Processing: 537058673 2024-10-01
No rows.
Processing: 537058673 2024-11-01
No rows.
Processing: 537058673 2024-12-01
No rows.
Processing: 537058673 2025-01-01
No rows.
Processing: 537058673 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 537058673 2025-03-01
No rows.
Processing: 537058673 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537058673_all_months_standard_clean.csv Rows: 5

===== Player 140/1000: 48771457 =====
Processing: 48771457 2024-05-01
No rows.
Processing: 48771457 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 48771457 2024-07-01
No rows.
Processing: 48771457 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 48771457 2024-09-01
No rows.
Processing: 48771457 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 48771457 2024-11-01
No rows.
Processing: 48771457 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 48771457 2025-01-01
No rows.
Processing: 48771457 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 48771457 2025-03-01
No rows.
Processing: 48771457 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48771457_all_months_standard_clean.csv Rows: 32

===== Player 141/1000: 531077714 =====
Processing: 531077714 2024-05-01
No rows.
Processing: 531077714 2024-06-01
No rows.
Processing: 531077714 2024-07-01
No rows.
Processing: 531077714 2024-08-01
No rows.
Processing: 531077714 2024-09-01
No rows.
Processing: 531077714 2024-10-01
No rows.
Processing: 531077714 2024-11-01
No rows.
Processing: 531077714 2024-12-01
No rows.
Processing: 531077714 2025-01-01
No rows.
Processing: 531077714 2025-02-01
No rows.
Processing: 531077714 2025-03-01
No rows.
Processing: 531077714 2025-04-01
No rows.

===== Player 142/1000: 33321990 =====
Processing: 33321990 2024-05-01
No rows.
Processing: 33321990 2024-06-01
No rows.
Processing: 33321990 2024-07-01
No rows.
Processing: 33321990 2024-08-01
No rows.
Processing: 33321990 2024-09-01
No rows.
Processing: 33321990 2024-10-01
No rows.
Processing: 33321990 2024-11-01
No rows.
Processing: 33321990 2024-12-01
No rows.
Processing: 33321990 2025-01-01
No rows.
Processing: 33321990 2025-02-01
No rows.
Processing: 33321990 2025-03-01
No rows.
Processing: 33321990 2025-04-01
No rows.

===== Player 143/1000: 547005033 =====
Processing: 547005033 2024-05-01
No rows.
Processing: 547005033 2024-06-01
No rows.
Processing: 547005033 2024-07-01
No rows.
Processing: 547005033 2024-08-01
No rows.
Processing: 547005033 2024-09-01
No rows.
Processing: 547005033 2024-10-01
No rows.
Processing: 547005033 2024-11-01
No rows.
Processing: 547005033 2024-12-01
No rows.
Processing: 547005033 2025-01-01
No rows.
Processing: 547005033 2025-02-01
No rows.
Processing: 547005033 2025-03-01
No rows.
Processing: 547005033 2025-04-01
No rows.

===== Player 144/1000: 25798960 =====
Processing: 25798960 2024-05-01
No rows.
Processing: 25798960 2024-06-01
No rows.
Processing: 25798960 2024-07-01
No rows.
Processing: 25798960 2024-08-01
No rows.
Processing: 25798960 2024-09-01
No rows.
Processing: 25798960 2024-10-01
No rows.
Processing: 25798960 2024-11-01
No rows.
Processing: 25798960 2024-12-01
No rows.
Processing: 25798960 2025-01-01
No rows.
Processing: 25798960 2025-02-01
No rows.
Processing: 25798960 2025-03-01
No rows.
Processing: 25798960 2025-04-01
No rows.

===== Player 145/1000: 564029476 =====
Processing: 564029476 2024-05-01
No rows.
Processing: 564029476 2024-06-01
No rows.
Processing: 564029476 2024-07-01
No rows.
Processing: 564029476 2024-08-01
No rows.
Processing: 564029476 2024-09-01
No rows.
Processing: 564029476 2024-10-01
No rows.
Processing: 564029476 2024-11-01
No rows.
Processing: 564029476 2024-12-01
No rows.
Processing: 564029476 2025-01-01
No rows.
Processing: 564029476 2025-02-01
No rows.
Processing: 564029476 2025-03-01
No rows.
Processing: 564029476 2025-04-01
No rows.

===== Player 146/1000: 33361258 =====
Processing: 33361258 2024-05-01
No rows.
Processing: 33361258 2024-06-01
No rows.
Processing: 33361258 2024-07-01
No rows.
Processing: 33361258 2024-08-01
No rows.
Processing: 33361258 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 15
Processing: 33361258 2024-10-01
No rows.
Processing: 33361258 2024-11-01
No rows.
Processing: 33361258 2024-12-01
No rows.
Processing: 33361258 2025-01-01
No rows.
Processing: 33361258 2025-02-01
No rows.
Processing: 33361258 2025-03-01
No rows.
Processing: 33361258 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33361258_all_months_standard_clean.csv Rows: 15

===== Player 147/1000: 429073111 =====
Processing: 429073111 2024-05-01
No rows.
Processing: 429073111 2024-06-01
No rows.
Processing: 429073111 2024-07-01
No rows.
Processing: 429073111 2024-08-01
No rows.
Processing: 429073111 2024-09-01
No rows.
Processing: 429073111 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 429073111 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 429073111 2024-12-01
No rows.
Processing: 429073111 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 429073111 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 429073111 2025-03-01
No rows.
Processing: 429073111 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429073111_all_months_standard_clean.csv Rows: 21

===== Player 148/1000: 537067508 =====
Processing: 537067508 2024-05-01
No rows.
Processing: 537067508 2024-06-01
No rows.
Processing: 537067508 2024-07-01
No rows.
Processing: 537067508 2024-08-01
No rows.
Processing: 537067508 2024-09-01
No rows.
Processing: 537067508 2024-10-01
No rows.
Processing: 537067508 2024-11-01
No rows.
Processing: 537067508 2024-12-01
No rows.
Processing: 537067508 2025-01-01
No rows.
Processing: 537067508 2025-02-01
No rows.
Processing: 537067508 2025-03-01
No rows.
Processing: 537067508 2025-04-01
No rows.

===== Player 149/1000: 537053493 =====
Processing: 537053493 2024-05-01
No rows.
Processing: 537053493 2024-06-01
No rows.
Processing: 537053493 2024-07-01
No rows.
Processing: 537053493 2024-08-01
No rows.
Processing: 537053493 2024-09-01
No rows.
Processing: 537053493 2024-10-01
No rows.
Processing: 537053493 2024-11-01
No rows.
Processing: 537053493 2024-12-01
No rows.
Processing: 537053493 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 537053493 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 537053493 2025-03-01
No rows.
Processing: 537053493 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537053493_all_months_standard_clean.csv Rows: 7

===== Player 150/1000: 547005130 =====
Processing: 547005130 2024-05-01
No rows.
Processing: 547005130 2024-06-01
No rows.
Processing: 547005130 2024-07-01
No rows.
Processing: 547005130 2024-08-01
No rows.
Processing: 547005130 2024-09-01
No rows.
Processing: 547005130 2024-10-01
No rows.
Processing: 547005130 2024-11-01
No rows.
Processing: 547005130 2024-12-01
No rows.
Processing: 547005130 2025-01-01
No rows.
Processing: 547005130 2025-02-01
No rows.
Processing: 547005130 2025-03-01
No rows.
Processing: 547005130 2025-04-01
No rows.

===== Player 151/1000: 537045059 =====
Processing: 537045059 2024-05-01
No rows.
Processing: 537045059 2024-06-01
No rows.
Processing: 537045059 2024-07-01
No rows.
Processing: 537045059 2024-08-01
No rows.
Processing: 537045059 2024-09-01
No rows.
Processing: 537045059 2024-10-01
No rows.
Processing: 537045059 2024-11-01
No rows.
Processing: 537045059 2024-12-01
No rows.
Processing: 537045059 2025-01-01
No rows.
Processing: 537045059 2025-02-01
No rows.
Processing: 537045059 2025-03-01
No rows.
Processing: 537045059 2025-04-01
No rows.

===== Player 152/1000: 88132226 =====
Processing: 88132226 2024-05-01
No rows.
Processing: 88132226 2024-06-01
No rows.
Processing: 88132226 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 88132226 2024-08-01
No rows.
Processing: 88132226 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 88132226 2024-10-01
No rows.
Processing: 88132226 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 88132226 2024-12-01
No rows.
Processing: 88132226 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 20
Processing: 88132226 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 88132226 2025-03-01
No rows.
Processing: 88132226 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88132226_all_months_standard_clean.csv Rows: 36

===== Player 153/1000: 429037786 =====
Processing: 429037786 2024-05-01
No rows.
Processing: 429037786 2024-06-01
No rows.
Processing: 429037786 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 429037786 2024-08-01
No rows.
Processing: 429037786 2024-09-01
No rows.
Processing: 429037786 2024-10-01
No rows.
Processing: 429037786 2024-11-01
No rows.
Processing: 429037786 2024-12-01
No rows.
Processing: 429037786 2025-01-01
No rows.
Processing: 429037786 2025-02-01
No rows.
Processing: 429037786 2025-03-01
No rows.
Processing: 429037786 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429037786_all_months_standard_clean.csv Rows: 1

===== Player 154/1000: 88138593 =====
Processing: 88138593 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 88138593 2024-06-01
No rows.
Processing: 88138593 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 12
Processing: 88138593 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 88138593 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 88138593 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 88138593 2024-11-01
No rows.
Processing: 88138593 2024-12-01
No rows.
Processing: 88138593 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 88138593 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 88138593 2025-03-01
No rows.
Processing: 88138593 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88138593_all_months_standard_clean.csv Rows: 41

===== Player 155/1000: 25667483 =====
Processing: 25667483 2024-05-01
No rows.
Processing: 25667483 2024-06-01
No rows.
Processing: 25667483 2024-07-01
No rows.
Processing: 25667483 2024-08-01
No rows.
Processing: 25667483 2024-09-01
No rows.
Processing: 25667483 2024-10-01
No rows.
Processing: 25667483 2024-11-01
No rows.
Processing: 25667483 2024-12-01
No rows.
Processing: 25667483 2025-01-01
No rows.
Processing: 25667483 2025-02-01
No rows.
Processing: 25667483 2025-03-01
No rows.
Processing: 25667483 2025-04-01
No rows.

===== Player 156/1000: 537051164 =====
Processing: 537051164 2024-05-01
No rows.
Processing: 537051164 2024-06-01
No rows.
Processing: 537051164 2024-07-01
No rows.
Processing: 537051164 2024-08-01
No rows.
Processing: 537051164 2024-09-01
No rows.
Processing: 537051164 2024-10-01
No rows.
Processing: 537051164 2024-11-01
No rows.
Processing: 537051164 2024-12-01
No rows.
Processing: 537051164 2025-01-01
No rows.
Processing: 537051164 2025-02-01
No rows.
Processing: 537051164 2025-03-01
No rows.
Processing: 537051164 2025-04-01
No rows.

===== Player 157/1000: 48796034 =====
Processing: 48796034 2024-05-01
No rows.
Processing: 48796034 2024-06-01
No rows.
Processing: 48796034 2024-07-01
No rows.
Processing: 48796034 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 48796034 2024-09-01
No rows.
Processing: 48796034 2024-10-01
No rows.
Processing: 48796034 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 48796034 2024-12-01
No rows.
Processing: 48796034 2025-01-01
No rows.
Processing: 48796034 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 11
Processing: 48796034 2025-03-01
No rows.
Processing: 48796034 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48796034_all_months_standard_clean.csv Rows: 15

===== Player 158/1000: 25950991 =====
Processing: 25950991 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 25950991 2024-06-01
No rows.
Processing: 25950991 2024-07-01
No rows.
Processing: 25950991 2024-08-01
No rows.
Processing: 25950991 2024-09-01
No rows.
Processing: 25950991 2024-10-01
No rows.
Processing: 25950991 2024-11-01
No rows.
Processing: 25950991 2024-12-01
No rows.
Processing: 25950991 2025-01-01
No rows.
Processing: 25950991 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 25950991 2025-03-01
No rows.
Processing: 25950991 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25950991_all_months_standard_clean.csv Rows: 4

===== Player 159/1000: 531019900 =====
Processing: 531019900 2024-05-01
No rows.
Processing: 531019900 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 531019900 2024-07-01
No rows.
Processing: 531019900 2024-08-01
No rows.
Processing: 531019900 2024-09-01
No rows.
Processing: 531019900 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 531019900 2024-11-01
No rows.
Processing: 531019900 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 531019900 2025-01-01
No rows.
Processing: 531019900 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 531019900 2025-03-01
No rows.
Processing: 531019900 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531019900_all_months_standard_clean.csv Rows: 12

===== Player 160/1000: 88143864 =====
Processing: 88143864 2024-05-01
No rows.
Processing: 88143864 2024-06-01
No rows.
Processing: 88143864 2024-07-01
No rows.
Processing: 88143864 2024-08-01
No rows.
Processing: 88143864 2024-09-01
No rows.
Processing: 88143864 2024-10-01
No rows.
Processing: 88143864 2024-11-01
No rows.
Processing: 88143864 2024-12-01
No rows.
Processing: 88143864 2025-01-01
No rows.
Processing: 88143864 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 88143864 2025-03-01
No rows.
Processing: 88143864 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88143864_all_months_standard_clean.csv Rows: 6

===== Player 161/1000: 88168611 =====
Processing: 88168611 2024-05-01
No rows.
Processing: 88168611 2024-06-01
No rows.
Processing: 88168611 2024-07-01
No rows.
Processing: 88168611 2024-08-01
No rows.
Processing: 88168611 2024-09-01
No rows.
Processing: 88168611 2024-10-01
No rows.
Processing: 88168611 2024-11-01
No rows.
Processing: 88168611 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 88168611 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 88168611 2025-02-01
No rows.
Processing: 88168611 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 88168611 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88168611_all_months_standard_clean.csv Rows: 16

===== Player 162/1000: 25120883 =====
Processing: 25120883 2024-05-01
No rows.
Processing: 25120883 2024-06-01
No rows.
Processing: 25120883 2024-07-01
No rows.
Processing: 25120883 2024-08-01
No rows.
Processing: 25120883 2024-09-01
No rows.
Processing: 25120883 2024-10-01
No rows.
Processing: 25120883 2024-11-01
No rows.
Processing: 25120883 2024-12-01
No rows.
Processing: 25120883 2025-01-01
No rows.
Processing: 25120883 2025-02-01
No rows.
Processing: 25120883 2025-03-01
No rows.
Processing: 25120883 2025-04-01
No rows.

===== Player 163/1000: 88155404 =====
Processing: 88155404 2024-05-01
No rows.
Processing: 88155404 2024-06-01
No rows.
Processing: 88155404 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 88155404 2024-08-01
No rows.
Processing: 88155404 2024-09-01
No rows.
Processing: 88155404 2024-10-01
No rows.
Processing: 88155404 2024-11-01
No rows.
Processing: 88155404 2024-12-01
No rows.
Processing: 88155404 2025-01-01
No rows.
Processing: 88155404 2025-02-01
No rows.
Processing: 88155404 2025-03-01
No rows.
Processing: 88155404 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88155404_all_months_standard_clean.csv Rows: 4

===== Player 164/1000: 25166735 =====
Processing: 25166735 2024-05-01
No rows.
Processing: 25166735 2024-06-01
No rows.
Processing: 25166735 2024-07-01
No rows.
Processing: 25166735 2024-08-01
No rows.
Processing: 25166735 2024-09-01
No rows.
Processing: 25166735 2024-10-01
No rows.
Processing: 25166735 2024-11-01
No rows.
Processing: 25166735 2024-12-01
No rows.
Processing: 25166735 2025-01-01
No rows.
Processing: 25166735 2025-02-01
No rows.
Processing: 25166735 2025-03-01
No rows.
Processing: 25166735 2025-04-01
No rows.

===== Player 165/1000: 558033270 =====
Processing: 558033270 2024-05-01
No rows.
Processing: 558033270 2024-06-01
No rows.
Processing: 558033270 2024-07-01
No rows.
Processing: 558033270 2024-08-01
No rows.
Processing: 558033270 2024-09-01
No rows.
Processing: 558033270 2024-10-01
No rows.
Processing: 558033270 2024-11-01
No rows.
Processing: 558033270 2024-12-01
No rows.
Processing: 558033270 2025-01-01
No rows.
Processing: 558033270 2025-02-01
No rows.
Processing: 558033270 2025-03-01
No rows.
Processing: 558033270 2025-04-01
No rows.

===== Player 166/1000: 33384657 =====
Processing: 33384657 2024-05-01
No rows.
Processing: 33384657 2024-06-01
No rows.
Processing: 33384657 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33384657 2024-08-01
No rows.
Processing: 33384657 2024-09-01
No rows.
Processing: 33384657 2024-10-01
No rows.
Processing: 33384657 2024-11-01
No rows.
Processing: 33384657 2024-12-01
No rows.
Processing: 33384657 2025-01-01
No rows.
Processing: 33384657 2025-02-01
No rows.
Processing: 33384657 2025-03-01
No rows.
Processing: 33384657 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33384657_all_months_standard_clean.csv Rows: 5

===== Player 167/1000: 547093293 =====
Processing: 547093293 2024-05-01
No rows.
Processing: 547093293 2024-06-01
No rows.
Processing: 547093293 2024-07-01
No rows.
Processing: 547093293 2024-08-01
No rows.
Processing: 547093293 2024-09-01
No rows.
Processing: 547093293 2024-10-01
No rows.
Processing: 547093293 2024-11-01
No rows.
Processing: 547093293 2024-12-01
No rows.
Processing: 547093293 2025-01-01
No rows.
Processing: 547093293 2025-02-01
No rows.
Processing: 547093293 2025-03-01
No rows.
Processing: 547093293 2025-04-01
No rows.

===== Player 168/1000: 537085549 =====
Processing: 537085549 2024-05-01
No rows.
Processing: 537085549 2024-06-01
No rows.
Processing: 537085549 2024-07-01
No rows.
Processing: 537085549 2024-08-01
No rows.
Processing: 537085549 2024-09-01
No rows.
Processing: 537085549 2024-10-01
No rows.
Processing: 537085549 2024-11-01
No rows.
Processing: 537085549 2024-12-01
No rows.
Processing: 537085549 2025-01-01
No rows.
Processing: 537085549 2025-02-01
No rows.
Processing: 537085549 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 537085549 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537085549_all_months_standard_clean.csv Rows: 6

===== Player 169/1000: 537073966 =====
Processing: 537073966 2024-05-01
No rows.
Processing: 537073966 2024-06-01
No rows.
Processing: 537073966 2024-07-01
No rows.
Processing: 537073966 2024-08-01
No rows.
Processing: 537073966 2024-09-01
No rows.
Processing: 537073966 2024-10-01
No rows.
Processing: 537073966 2024-11-01
No rows.
Processing: 537073966 2024-12-01
No rows.
Processing: 537073966 2025-01-01
No rows.
Processing: 537073966 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 537073966 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 537073966 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537073966_all_months_standard_clean.csv Rows: 8

===== Player 170/1000: 48737330 =====
Processing: 48737330 2024-05-01
No rows.
Processing: 48737330 2024-06-01
No rows.
Processing: 48737330 2024-07-01
No rows.
Processing: 48737330 2024-08-01
Rows: 4
Processing: 48737330 2024-09-01
No rows.
Processing: 48737330 2024-10-01
No rows.
Processing: 48737330 2024-11-01
No rows.
Processing: 48737330 2024-12-01
No rows.
Processing: 48737330 2025-01-01
No rows.
Processing: 48737330 2025-02-01
No rows.
Processing: 48737330 2025-03-01
No rows.
Processing: 48737330 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48737330_all_months_standard_clean.csv Rows: 4

===== Player 171/1000: 48777056 =====
Processing: 48777056 2024-05-01
No rows.
Processing: 48777056 2024-06-01
No rows.
Processing: 48777056 2024-07-01
No rows.
Processing: 48777056 2024-08-01
No rows.
Processing: 48777056 2024-09-01
No rows.
Processing: 48777056 2024-10-01
No rows.
Processing: 48777056 2024-11-01
No rows.
Processing: 48777056 2024-12-01
No rows.
Processing: 48777056 2025-01-01
No rows.
Processing: 48777056 2025-02-01
No rows.
Processing: 48777056 2025-03-01
No rows.
Processing: 48777056 2025-04-01
No rows.

===== Player 172/1000: 88131726 =====
Processing: 88131726 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 88131726 2024-06-01
No rows.
Processing: 88131726 2024-07-01
No rows.
Processing: 88131726 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 88131726 2024-09-01
No rows.
Processing: 88131726 2024-10-01
No rows.
Processing: 88131726 2024-11-01
No rows.
Processing: 88131726 2024-12-01
No rows.
Processing: 88131726 2025-01-01
No rows.
Processing: 88131726 2025-02-01
No rows.
Processing: 88131726 2025-03-01
No rows.
Processing: 88131726 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88131726_all_months_standard_clean.csv Rows: 7

===== Player 173/1000: 88199495 =====
Processing: 88199495 2024-05-01
No rows.
Processing: 88199495 2024-06-01
No rows.
Processing: 88199495 2024-07-01
No rows.
Processing: 88199495 2024-08-01
No rows.
Processing: 88199495 2024-09-01
No rows.
Processing: 88199495 2024-10-01
No rows.
Processing: 88199495 2024-11-01
No rows.
Processing: 88199495 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 88199495 2025-01-01
No rows.
Processing: 88199495 2025-02-01
No rows.
Processing: 88199495 2025-03-01
No rows.
Processing: 88199495 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88199495_all_months_standard_clean.csv Rows: 2

===== Player 174/1000: 88120511 =====
Processing: 88120511 2024-05-01
Rows: 8
Processing: 88120511 2024-06-01
No rows.
Processing: 88120511 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 16
Processing: 88120511 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 88120511 2024-09-01
Rows: 11
Processing: 88120511 2024-10-01
No rows.
Processing: 88120511 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 88120511 2024-12-01
No rows.
Processing: 88120511 2025-01-01
No rows.
Processing: 88120511 2025-02-01
No rows.
Processing: 88120511 2025-03-01
No rows.
Processing: 88120511 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88120511_all_months_standard_clean.csv Rows: 53

===== Player 175/1000: 564055981 =====
Processing: 564055981 2024-05-01
No rows.
Processing: 564055981 2024-06-01
No rows.
Processing: 564055981 2024-07-01
No rows.
Processing: 564055981 2024-08-01
No rows.
Processing: 564055981 2024-09-01
No rows.
Processing: 564055981 2024-10-01
No rows.
Processing: 564055981 2024-11-01
No rows.
Processing: 564055981 2024-12-01
No rows.
Processing: 564055981 2025-01-01
No rows.
Processing: 564055981 2025-02-01
No rows.
Processing: 564055981 2025-03-01
No rows.
Processing: 564055981 2025-04-01
No rows.

===== Player 176/1000: 547069007 =====
Processing: 547069007 2024-05-01
No rows.
Processing: 547069007 2024-06-01
No rows.
Processing: 547069007 2024-07-01
No rows.
Processing: 547069007 2024-08-01
No rows.
Processing: 547069007 2024-09-01
No rows.
Processing: 547069007 2024-10-01
No rows.
Processing: 547069007 2024-11-01
No rows.
Processing: 547069007 2024-12-01
No rows.
Processing: 547069007 2025-01-01
No rows.
Processing: 547069007 2025-02-01
No rows.
Processing: 547069007 2025-03-01
No rows.
Processing: 547069007 2025-04-01
No rows.

===== Player 177/1000: 531074529 =====
Processing: 531074529 2024-05-01
No rows.
Processing: 531074529 2024-06-01
No rows.
Processing: 531074529 2024-07-01
No rows.
Processing: 531074529 2024-08-01
No rows.
Processing: 531074529 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 531074529 2024-10-01
No rows.
Processing: 531074529 2024-11-01
No rows.
Processing: 531074529 2024-12-01
No rows.
Processing: 531074529 2025-01-01
No rows.
Processing: 531074529 2025-02-01
No rows.
Processing: 531074529 2025-03-01
No rows.
Processing: 531074529 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531074529_all_months_standard_clean.csv Rows: 1

===== Player 178/1000: 537041797 =====
Processing: 537041797 2024-05-01
No rows.
Processing: 537041797 2024-06-01
No rows.
Processing: 537041797 2024-07-01
No rows.
Processing: 537041797 2024-08-01
No rows.
Processing: 537041797 2024-09-01
No rows.
Processing: 537041797 2024-10-01
No rows.
Processing: 537041797 2024-11-01
No rows.
Processing: 537041797 2024-12-01
No rows.
Processing: 537041797 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 537041797 2025-02-01
No rows.
Processing: 537041797 2025-03-01
No rows.
Processing: 537041797 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537041797_all_months_standard_clean.csv Rows: 1

===== Player 179/1000: 33393362 =====
Processing: 33393362 2024-05-01
No rows.
Processing: 33393362 2024-06-01
No rows.
Processing: 33393362 2024-07-01
No rows.
Processing: 33393362 2024-08-01
No rows.
Processing: 33393362 2024-09-01
No rows.
Processing: 33393362 2024-10-01
No rows.
Processing: 33393362 2024-11-01
No rows.
Processing: 33393362 2024-12-01
No rows.
Processing: 33393362 2025-01-01
No rows.
Processing: 33393362 2025-02-01
No rows.
Processing: 33393362 2025-03-01
No rows.
Processing: 33393362 2025-04-01
No rows.

===== Player 180/1000: 33421714 =====
Processing: 33421714 2024-05-01
No rows.
Processing: 33421714 2024-06-01
No rows.
Processing: 33421714 2024-07-01
No rows.
Processing: 33421714 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 33421714 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 33421714 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 33421714 2024-11-01
No rows.
Processing: 33421714 2024-12-01
No rows.
Processing: 33421714 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 33421714 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 10
Processing: 33421714 2025-03-01
No rows.
Processing: 33421714 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33421714_all_months_standard_clean.csv Rows: 37

===== Player 181/1000: 88164683 =====
Processing: 88164683 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 88164683 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 88164683 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 88164683 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 88164683 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 88164683 2024-10-01
No rows.
Processing: 88164683 2024-11-01
No rows.
Processing: 88164683 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 88164683 2025-01-01
No rows.
Processing: 88164683 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 88164683 2025-03-01
No rows.
Processing: 88164683 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88164683_all_months_standard_clean.csv Rows: 37

===== Player 182/1000: 33396612 =====
Processing: 33396612 2024-05-01
No rows.
Processing: 33396612 2024-06-01
No rows.
Processing: 33396612 2024-07-01
No rows.
Processing: 33396612 2024-08-01
No rows.
Processing: 33396612 2024-09-01
No rows.
Processing: 33396612 2024-10-01
No rows.
Processing: 33396612 2024-11-01
No rows.
Processing: 33396612 2024-12-01
No rows.
Processing: 33396612 2025-01-01
No rows.
Processing: 33396612 2025-02-01
No rows.
Processing: 33396612 2025-03-01
No rows.
Processing: 33396612 2025-04-01
No rows.

===== Player 183/1000: 429003237 =====
Processing: 429003237 2024-05-01
No rows.
Processing: 429003237 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 429003237 2024-07-01
No rows.
Processing: 429003237 2024-08-01
No rows.
Processing: 429003237 2024-09-01
No rows.
Processing: 429003237 2024-10-01
No rows.
Processing: 429003237 2024-11-01
No rows.
Processing: 429003237 2024-12-01
No rows.
Processing: 429003237 2025-01-01
No rows.
Processing: 429003237 2025-02-01
No rows.
Processing: 429003237 2025-03-01
No rows.
Processing: 429003237 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429003237_all_months_standard_clean.csv Rows: 4

===== Player 184/1000: 537010182 =====
Processing: 537010182 2024-05-01
No rows.
Processing: 537010182 2024-06-01
No rows.
Processing: 537010182 2024-07-01
No rows.
Processing: 537010182 2024-08-01
No rows.
Processing: 537010182 2024-09-01
No rows.
Processing: 537010182 2024-10-01
No rows.
Processing: 537010182 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 537010182 2024-12-01
No rows.
Processing: 537010182 2025-01-01
No rows.
Processing: 537010182 2025-02-01
No rows.
Processing: 537010182 2025-03-01
No rows.
Processing: 537010182 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537010182_all_months_standard_clean.csv Rows: 2

===== Player 185/1000: 531010440 =====
Processing: 531010440 2024-05-01
No rows.
Processing: 531010440 2024-06-01
No rows.
Processing: 531010440 2024-07-01
No rows.
Processing: 531010440 2024-08-01
No rows.
Processing: 531010440 2024-09-01
No rows.
Processing: 531010440 2024-10-01
No rows.
Processing: 531010440 2024-11-01
No rows.
Processing: 531010440 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 531010440 2025-01-01
No rows.
Processing: 531010440 2025-02-01
No rows.
Processing: 531010440 2025-03-01
No rows.
Processing: 531010440 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531010440_all_months_standard_clean.csv Rows: 2

===== Player 186/1000: 45099251 =====
Processing: 45099251 2024-05-01
No rows.
Processing: 45099251 2024-06-01
No rows.
Processing: 45099251 2024-07-01
No rows.
Processing: 45099251 2024-08-01
No rows.
Processing: 45099251 2024-09-01
No rows.
Processing: 45099251 2024-10-01
No rows.
Processing: 45099251 2024-11-01
No rows.
Processing: 45099251 2024-12-01
No rows.
Processing: 45099251 2025-01-01
No rows.
Processing: 45099251 2025-02-01
No rows.
Processing: 45099251 2025-03-01
No rows.
Processing: 45099251 2025-04-01
No rows.

===== Player 187/1000: 558094270 =====
Processing: 558094270 2024-05-01
No rows.
Processing: 558094270 2024-06-01
No rows.
Processing: 558094270 2024-07-01
No rows.
Processing: 558094270 2024-08-01
No rows.
Processing: 558094270 2024-09-01
No rows.
Processing: 558094270 2024-10-01
No rows.
Processing: 558094270 2024-11-01
No rows.
Processing: 558094270 2024-12-01
No rows.
Processing: 558094270 2025-01-01
No rows.
Processing: 558094270 2025-02-01
No rows.
Processing: 558094270 2025-03-01
No rows.
Processing: 558094270 2025-04-01
No rows.

===== Player 188/1000: 48748820 =====
Processing: 48748820 2024-05-01
No rows.
Processing: 48748820 2024-06-01
No rows.
Processing: 48748820 2024-07-01
No rows.
Processing: 48748820 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 48748820 2024-09-01
No rows.
Processing: 48748820 2024-10-01
No rows.
Processing: 48748820 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 48748820 2024-12-01
No rows.
Processing: 48748820 2025-01-01
No rows.
Processing: 48748820 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 12
Processing: 48748820 2025-03-01
No rows.
Processing: 48748820 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48748820_all_months_standard_clean.csv Rows: 21

===== Player 189/1000: 25628070 =====
Processing: 25628070 2024-05-01
No rows.
Processing: 25628070 2024-06-01
No rows.
Processing: 25628070 2024-07-01
No rows.
Processing: 25628070 2024-08-01
No rows.
Processing: 25628070 2024-09-01
No rows.
Processing: 25628070 2024-10-01
No rows.
Processing: 25628070 2024-11-01
No rows.
Processing: 25628070 2024-12-01
No rows.
Processing: 25628070 2025-01-01
No rows.
Processing: 25628070 2025-02-01
No rows.
Processing: 25628070 2025-03-01
No rows.
Processing: 25628070 2025-04-01
No rows.

===== Player 190/1000: 33315051 =====
Processing: 33315051 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 33315051 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 33315051 2024-07-01
No rows.
Processing: 33315051 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 11
Processing: 33315051 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 33315051 2024-10-01
No rows.
Processing: 33315051 2024-11-01
No rows.
Processing: 33315051 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 13
Processing: 33315051 2025-01-01
No rows.
Processing: 33315051 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 33315051 2025-03-01
No rows.
Processing: 33315051 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33315051_all_months_standard_clean.csv Rows: 47

===== Player 191/1000: 48763225 =====
Processing: 48763225 2024-05-01
No rows.
Processing: 48763225 2024-06-01
No rows.
Processing: 48763225 2024-07-01
No rows.
Processing: 48763225 2024-08-01
No rows.
Processing: 48763225 2024-09-01
No rows.
Processing: 48763225 2024-10-01
No rows.
Processing: 48763225 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 48763225 2024-12-01
No rows.
Processing: 48763225 2025-01-01
No rows.
Processing: 48763225 2025-02-01
No rows.
Processing: 48763225 2025-03-01
No rows.
Processing: 48763225 2025-04-01
Rows: 5
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48763225_all_months_standard_clean.csv Rows: 10

===== Player 192/1000: 429052610 =====
Processing: 429052610 2024-05-01
No rows.
Processing: 429052610 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 429052610 2024-07-01
No rows.
Processing: 429052610 2024-08-01
No rows.
Processing: 429052610 2024-09-01
No rows.
Processing: 429052610 2024-10-01
No rows.
Processing: 429052610 2024-11-01
No rows.
Processing: 429052610 2024-12-01
No rows.
Processing: 429052610 2025-01-01
No rows.
Processing: 429052610 2025-02-01
No rows.
Processing: 429052610 2025-03-01
No rows.
Processing: 429052610 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429052610_all_months_standard_clean.csv Rows: 5

===== Player 193/1000: 25906305 =====
Processing: 25906305 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 25906305 2024-06-01
No rows.
Processing: 25906305 2024-07-01
No rows.
Processing: 25906305 2024-08-01
No rows.
Processing: 25906305 2024-09-01
No rows.
Processing: 25906305 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 25906305 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 25906305 2024-12-01
No rows.
Processing: 25906305 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 15
Processing: 25906305 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 25906305 2025-03-01
No rows.
Processing: 25906305 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25906305_all_months_standard_clean.csv Rows: 36

===== Player 194/1000: 558057609 =====
Processing: 558057609 2024-05-01
No rows.
Processing: 558057609 2024-06-01
No rows.
Processing: 558057609 2024-07-01
No rows.
Processing: 558057609 2024-08-01
No rows.
Processing: 558057609 2024-09-01
No rows.
Processing: 558057609 2024-10-01
No rows.
Processing: 558057609 2024-11-01
No rows.
Processing: 558057609 2024-12-01
No rows.
Processing: 558057609 2025-01-01
No rows.
Processing: 558057609 2025-02-01
No rows.
Processing: 558057609 2025-03-01
No rows.
Processing: 558057609 2025-04-01
No rows.

===== Player 195/1000: 537059025 =====
Processing: 537059025 2024-05-01
No rows.
Processing: 537059025 2024-06-01
No rows.
Processing: 537059025 2024-07-01
No rows.
Processing: 537059025 2024-08-01
No rows.
Processing: 537059025 2024-09-01
No rows.
Processing: 537059025 2024-10-01
No rows.
Processing: 537059025 2024-11-01
No rows.
Processing: 537059025 2024-12-01
No rows.
Processing: 537059025 2025-01-01
No rows.
Processing: 537059025 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 537059025 2025-03-01
No rows.
Processing: 537059025 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537059025_all_months_standard_clean.csv Rows: 4

===== Player 196/1000: 531018017 =====
Processing: 531018017 2024-05-01
No rows.
Processing: 531018017 2024-06-01
No rows.
Processing: 531018017 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 531018017 2024-08-01
No rows.
Processing: 531018017 2024-09-01
No rows.
Processing: 531018017 2024-10-01
No rows.
Processing: 531018017 2024-11-01
No rows.
Processing: 531018017 2024-12-01
No rows.
Processing: 531018017 2025-01-01
No rows.
Processing: 531018017 2025-02-01
No rows.
Processing: 531018017 2025-03-01
No rows.
Processing: 531018017 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531018017_all_months_standard_clean.csv Rows: 8

===== Player 197/1000: 48739839 =====
Processing: 48739839 2024-05-01
No rows.
Processing: 48739839 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 48739839 2024-07-01
No rows.
Processing: 48739839 2024-08-01
No rows.
Processing: 48739839 2024-09-01
No rows.
Processing: 48739839 2024-10-01
No rows.
Processing: 48739839 2024-11-01
No rows.
Processing: 48739839 2024-12-01
No rows.
Processing: 48739839 2025-01-01
No rows.
Processing: 48739839 2025-02-01
No rows.
Processing: 48739839 2025-03-01
No rows.
Processing: 48739839 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48739839_all_months_standard_clean.csv Rows: 3

===== Player 198/1000: 25755382 =====
Processing: 25755382 2024-05-01
No rows.
Processing: 25755382 2024-06-01
No rows.
Processing: 25755382 2024-07-01
No rows.
Processing: 25755382 2024-08-01
No rows.
Processing: 25755382 2024-09-01
No rows.
Processing: 25755382 2024-10-01
No rows.
Processing: 25755382 2024-11-01
No rows.
Processing: 25755382 2024-12-01
No rows.
Processing: 25755382 2025-01-01
No rows.
Processing: 25755382 2025-02-01
No rows.
Processing: 25755382 2025-03-01
No rows.
Processing: 25755382 2025-04-01
No rows.

===== Player 199/1000: 25677217 =====
Processing: 25677217 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 25677217 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 17
Processing: 25677217 2024-07-01
No rows.
Processing: 25677217 2024-08-01
Rows: 11
Processing: 25677217 2024-09-01
Rows: 11
Processing: 25677217 2024-10-01
No rows.
Processing: 25677217 2024-11-01
No rows.
Processing: 25677217 2024-12-01
No rows.
Processing: 25677217 2025-01-01
Rows: 10
Processing: 25677217 2025-02-01
Rows: 18
Processing: 25677217 2025-03-01
No rows.
Processing: 25677217 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25677217_all_months_standard_clean.csv Rows: 76

===== Player 200/1000: 547063874 =====
Processing: 547063874 2024-05-01
No rows.
Processing: 547063874 2024-06-01
No rows.
Processing: 547063874 2024-07-01
No rows.
Processing: 547063874 2024-08-01
No rows.
Processing: 547063874 2024-09-01
No rows.
Processing: 547063874 2024-10-01
No rows.
Processing: 547063874 2024-11-01
No rows.
Processing: 547063874 2024-12-01
No rows.
Processing: 547063874 2025-01-01
No rows.
Processing: 547063874 2025-02-01
No rows.
Processing: 547063874 2025-03-01
No rows.
Processing: 547063874 2025-04-01
No rows.

===== Player 201/1000: 547090960 =====
Processing: 547090960 2024-05-01
No rows.
Processing: 547090960 2024-06-01
No rows.
Processing: 547090960 2024-07-01
No rows.
Processing: 547090960 2024-08-01
No rows.
Processing: 547090960 2024-09-01
No rows.
Processing: 547090960 2024-10-01
No rows.
Processing: 547090960 2024-11-01
No rows.
Processing: 547090960 2024-12-01
No rows.
Processing: 547090960 2025-01-01
No rows.
Processing: 547090960 2025-02-01
No rows.
Processing: 547090960 2025-03-01
No rows.
Processing: 547090960 2025-04-01
No rows.

===== Player 202/1000: 48795518 =====
Processing: 48795518 2024-05-01
No rows.
Processing: 48795518 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 48795518 2024-07-01
No rows.
Processing: 48795518 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 48795518 2024-09-01
No rows.
Processing: 48795518 2024-10-01
No rows.
Processing: 48795518 2024-11-01
No rows.
Processing: 48795518 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 48795518 2025-01-01
No rows.
Processing: 48795518 2025-02-01
No rows.
Processing: 48795518 2025-03-01
No rows.
Processing: 48795518 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48795518_all_months_standard_clean.csv Rows: 17

===== Player 203/1000: 48782645 =====
Processing: 48782645 2024-05-01
No rows.
Processing: 48782645 2024-06-01
No rows.
Processing: 48782645 2024-07-01
No rows.
Processing: 48782645 2024-08-01
No rows.
Processing: 48782645 2024-09-01
No rows.
Processing: 48782645 2024-10-01
No rows.
Processing: 48782645 2024-11-01
No rows.
Processing: 48782645 2024-12-01
No rows.
Processing: 48782645 2025-01-01
No rows.
Processing: 48782645 2025-02-01
No rows.
Processing: 48782645 2025-03-01
No rows.
Processing: 48782645 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48782645_all_months_standard_clean.csv Rows: 6

===== Player 204/1000: 33402388 =====
Processing: 33402388 2024-05-01
No rows.
Processing: 33402388 2024-06-01
No rows.
Processing: 33402388 2024-07-01
No rows.
Processing: 33402388 2024-08-01
No rows.
Processing: 33402388 2024-09-01
No rows.
Processing: 33402388 2024-10-01
No rows.
Processing: 33402388 2024-11-01
No rows.
Processing: 33402388 2024-12-01
No rows.
Processing: 33402388 2025-01-01
No rows.
Processing: 33402388 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 33402388 2025-03-01
No rows.
Processing: 33402388 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33402388_all_months_standard_clean.csv Rows: 3

===== Player 205/1000: 33479828 =====
Processing: 33479828 2024-05-01
No rows.
Processing: 33479828 2024-06-01
No rows.
Processing: 33479828 2024-07-01
No rows.
Processing: 33479828 2024-08-01
No rows.
Processing: 33479828 2024-09-01
No rows.
Processing: 33479828 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 33479828 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 33479828 2024-12-01
No rows.
Processing: 33479828 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 33479828 2025-02-01
No rows.
Processing: 33479828 2025-03-01
No rows.
Processing: 33479828 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33479828_all_months_standard_clean.csv Rows: 11

===== Player 206/1000: 537092340 =====
Processing: 537092340 2024-05-01
No rows.
Processing: 537092340 2024-06-01
No rows.
Processing: 537092340 2024-07-01
No rows.
Processing: 537092340 2024-08-01
No rows.
Processing: 537092340 2024-09-01
No rows.
Processing: 537092340 2024-10-01
No rows.
Processing: 537092340 2024-11-01
No rows.
Processing: 537092340 2024-12-01
No rows.
Processing: 537092340 2025-01-01
No rows.
Processing: 537092340 2025-02-01
No rows.
Processing: 537092340 2025-03-01
No rows.
Processing: 537092340 2025-04-01
No rows.

===== Player 207/1000: 429022592 =====
Processing: 429022592 2024-05-01
No rows.
Processing: 429022592 2024-06-01
No rows.
Processing: 429022592 2024-07-01
No rows.
Processing: 429022592 2024-08-01
No rows.
Processing: 429022592 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 11
Processing: 429022592 2024-10-01
No rows.
Processing: 429022592 2024-11-01
Rows: 5
Processing: 429022592 2024-12-01
No rows.
Processing: 429022592 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 429022592 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 18
Processing: 429022592 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 429022592 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429022592_all_months_standard_clean.csv Rows: 39

===== Player 208/1000: 25955527 =====
Processing: 25955527 2024-05-01
No rows.
Processing: 25955527 2024-06-01
No rows.
Processing: 25955527 2024-07-01
No rows.
Processing: 25955527 2024-08-01
No rows.
Processing: 25955527 2024-09-01
No rows.
Processing: 25955527 2024-10-01
No rows.
Processing: 25955527 2024-11-01
No rows.
Processing: 25955527 2024-12-01
No rows.
Processing: 25955527 2025-01-01
No rows.
Processing: 25955527 2025-02-01
No rows.
Processing: 25955527 2025-03-01
No rows.
Processing: 25955527 2025-04-01
No rows.

===== Player 209/1000: 25926047 =====
Processing: 25926047 2024-05-01
No rows.
Processing: 25926047 2024-06-01
No rows.
Processing: 25926047 2024-07-01
No rows.
Processing: 25926047 2024-08-01
No rows.
Processing: 25926047 2024-09-01
No rows.
Processing: 25926047 2024-10-01
No rows.
Processing: 25926047 2024-11-01
No rows.
Processing: 25926047 2024-12-01
No rows.
Processing: 25926047 2025-01-01
No rows.
Processing: 25926047 2025-02-01
No rows.
Processing: 25926047 2025-03-01
No rows.
Processing: 25926047 2025-04-01
No rows.

===== Player 210/1000: 564037975 =====
Processing: 564037975 2024-05-01
No rows.
Processing: 564037975 2024-06-01
No rows.
Processing: 564037975 2024-07-01
No rows.
Processing: 564037975 2024-08-01
No rows.
Processing: 564037975 2024-09-01
No rows.
Processing: 564037975 2024-10-01
No rows.
Processing: 564037975 2024-11-01
No rows.
Processing: 564037975 2024-12-01
No rows.
Processing: 564037975 2025-01-01
No rows.
Processing: 564037975 2025-02-01
No rows.
Processing: 564037975 2025-03-01
No rows.
Processing: 564037975 2025-04-01
No rows.

===== Player 211/1000: 33305420 =====
Processing: 33305420 2024-05-01
No rows.
Processing: 33305420 2024-06-01
No rows.
Processing: 33305420 2024-07-01
No rows.
Processing: 33305420 2024-08-01
No rows.
Processing: 33305420 2024-09-01
No rows.
Processing: 33305420 2024-10-01
No rows.
Processing: 33305420 2024-11-01
No rows.
Processing: 33305420 2024-12-01
No rows.
Processing: 33305420 2025-01-01
No rows.
Processing: 33305420 2025-02-01
No rows.
Processing: 33305420 2025-03-01
No rows.
Processing: 33305420 2025-04-01
No rows.

===== Player 212/1000: 25732226 =====
Processing: 25732226 2024-05-01
No rows.
Processing: 25732226 2024-06-01
No rows.
Processing: 25732226 2024-07-01
No rows.
Processing: 25732226 2024-08-01
No rows.
Processing: 25732226 2024-09-01
No rows.
Processing: 25732226 2024-10-01
No rows.
Processing: 25732226 2024-11-01
No rows.
Processing: 25732226 2024-12-01
No rows.
Processing: 25732226 2025-01-01
No rows.
Processing: 25732226 2025-02-01
No rows.
Processing: 25732226 2025-03-01
No rows.
Processing: 25732226 2025-04-01
No rows.

===== Player 213/1000: 564033210 =====
Processing: 564033210 2024-05-01
No rows.
Processing: 564033210 2024-06-01
No rows.
Processing: 564033210 2024-07-01
No rows.
Processing: 564033210 2024-08-01
No rows.
Processing: 564033210 2024-09-01
No rows.
Processing: 564033210 2024-10-01
No rows.
Processing: 564033210 2024-11-01
No rows.
Processing: 564033210 2024-12-01
No rows.
Processing: 564033210 2025-01-01
No rows.
Processing: 564033210 2025-02-01
No rows.
Processing: 564033210 2025-03-01
No rows.
Processing: 564033210 2025-04-01
No rows.

===== Player 214/1000: 429072930 =====
Processing: 429072930 2024-05-01
No rows.
Processing: 429072930 2024-06-01
No rows.
Processing: 429072930 2024-07-01
No rows.
Processing: 429072930 2024-08-01
No rows.
Processing: 429072930 2024-09-01
No rows.
Processing: 429072930 2024-10-01
No rows.
Processing: 429072930 2024-11-01
No rows.
Processing: 429072930 2024-12-01
No rows.
Processing: 429072930 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 429072930 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 429072930 2025-03-01
No rows.
Processing: 429072930 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429072930_all_months_standard_clean.csv Rows: 8

===== Player 215/1000: 25771663 =====
Processing: 25771663 2024-05-01
No rows.
Processing: 25771663 2024-06-01
No rows.
Processing: 25771663 2024-07-01
No rows.
Processing: 25771663 2024-08-01
No rows.
Processing: 25771663 2024-09-01
No rows.
Processing: 25771663 2024-10-01
No rows.
Processing: 25771663 2024-11-01
No rows.
Processing: 25771663 2024-12-01
No rows.
Processing: 25771663 2025-01-01
No rows.
Processing: 25771663 2025-02-01
No rows.
Processing: 25771663 2025-03-01
No rows.
Processing: 25771663 2025-04-01
No rows.

===== Player 216/1000: 88189988 =====
Processing: 88189988 2024-05-01
No rows.
Processing: 88189988 2024-06-01
No rows.
Processing: 88189988 2024-07-01
No rows.
Processing: 88189988 2024-08-01
No rows.
Processing: 88189988 2024-09-01
No rows.
Processing: 88189988 2024-10-01
No rows.
Processing: 88189988 2024-11-01
No rows.
Processing: 88189988 2024-12-01
No rows.
Processing: 88189988 2025-01-01
No rows.
Processing: 88189988 2025-02-01
No rows.
Processing: 88189988 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 88189988 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88189988_all_months_standard_clean.csv Rows: 7

===== Player 217/1000: 88197530 =====
Processing: 88197530 2024-05-01
No rows.
Processing: 88197530 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 88197530 2024-07-01
No rows.
Processing: 88197530 2024-08-01
No rows.
Processing: 88197530 2024-09-01
No rows.
Processing: 88197530 2024-10-01
No rows.
Processing: 88197530 2024-11-01
No rows.
Processing: 88197530 2024-12-01
No rows.
Processing: 88197530 2025-01-01
No rows.
Processing: 88197530 2025-02-01
No rows.
Processing: 88197530 2025-03-01
No rows.
Processing: 88197530 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88197530_all_months_standard_clean.csv Rows: 5

===== Player 218/1000: 531013643 =====
Processing: 531013643 2024-05-01
No rows.
Processing: 531013643 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 531013643 2024-07-01
No rows.
Processing: 531013643 2024-08-01
No rows.
Processing: 531013643 2024-09-01
No rows.
Processing: 531013643 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 531013643 2024-11-01
No rows.
Processing: 531013643 2024-12-01
No rows.
Processing: 531013643 2025-01-01
No rows.
Processing: 531013643 2025-02-01
No rows.
Processing: 531013643 2025-03-01
No rows.
Processing: 531013643 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531013643_all_months_standard_clean.csv Rows: 8

===== Player 219/1000: 33423415 =====
Processing: 33423415 2024-05-01
No rows.
Processing: 33423415 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33423415 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 33423415 2024-08-01
No rows.
Processing: 33423415 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 33423415 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33423415 2024-11-01
No rows.
Processing: 33423415 2024-12-01
No rows.
Processing: 33423415 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33423415 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 19
Processing: 33423415 2025-03-01
No rows.
Processing: 33423415 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33423415_all_months_standard_clean.csv Rows: 55

===== Player 220/1000: 33499128 =====
Processing: 33499128 2024-05-01
No rows.
Processing: 33499128 2024-06-01
No rows.
Processing: 33499128 2024-07-01
No rows.
Processing: 33499128 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33499128 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 33499128 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33499128 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 33499128 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33499128 2025-01-01
No rows.
Processing: 33499128 2025-02-01
No rows.
Processing: 33499128 2025-03-01
No rows.
Processing: 33499128 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33499128_all_months_standard_clean.csv Rows: 34

===== Player 221/1000: 33478325 =====
Processing: 33478325 2024-05-01
No rows.
Processing: 33478325 2024-06-01
No rows.
Processing: 33478325 2024-07-01
No rows.
Processing: 33478325 2024-08-01
No rows.
Processing: 33478325 2024-09-01
No rows.
Processing: 33478325 2024-10-01
No rows.
Processing: 33478325 2024-11-01
No rows.
Processing: 33478325 2024-12-01
No rows.
Processing: 33478325 2025-01-01
No rows.
Processing: 33478325 2025-02-01
No rows.
Processing: 33478325 2025-03-01
No rows.
Processing: 33478325 2025-04-01
No rows.

===== Player 222/1000: 48758205 =====
Processing: 48758205 2024-05-01
No rows.
Processing: 48758205 2024-06-01
No rows.
Processing: 48758205 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 48758205 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 48758205 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 48758205 2024-10-01
No rows.
Processing: 48758205 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 48758205 2024-12-01
No rows.
Processing: 48758205 2025-01-01
No rows.
Processing: 48758205 2025-02-01
No rows.
Processing: 48758205 2025-03-01
No rows.
Processing: 48758205 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48758205_all_months_standard_clean.csv Rows: 11

===== Player 223/1000: 33420408 =====
Processing: 33420408 2024-05-01
No rows.
Processing: 33420408 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33420408 2024-07-01
Rows: 8
Processing: 33420408 2024-08-01
No rows.
Processing: 33420408 2024-09-01
No rows.
Processing: 33420408 2024-10-01
No rows.
Processing: 33420408 2024-11-01
No rows.
Processing: 33420408 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 18
Processing: 33420408 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 11
Processing: 33420408 2025-02-01
No rows.
Processing: 33420408 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 33420408 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33420408_all_months_standard_clean.csv Rows: 52

===== Player 224/1000: 537068857 =====
Processing: 537068857 2024-05-01
No rows.
Processing: 537068857 2024-06-01
No rows.
Processing: 537068857 2024-07-01
No rows.
Processing: 537068857 2024-08-01
No rows.
Processing: 537068857 2024-09-01
No rows.
Processing: 537068857 2024-10-01
No rows.
Processing: 537068857 2024-11-01
No rows.
Processing: 537068857 2024-12-01
No rows.
Processing: 537068857 2025-01-01
No rows.
Processing: 537068857 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 537068857 2025-03-01
No rows.
Processing: 537068857 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537068857_all_months_standard_clean.csv Rows: 5

===== Player 225/1000: 429010160 =====
Processing: 429010160 2024-05-01
No rows.
Processing: 429010160 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 429010160 2024-07-01
No rows.
Processing: 429010160 2024-08-01
No rows.
Processing: 429010160 2024-09-01
No rows.
Processing: 429010160 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 429010160 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 429010160 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 429010160 2025-01-01
No rows.
Processing: 429010160 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 429010160 2025-03-01
No rows.
Processing: 429010160 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429010160_all_months_standard_clean.csv Rows: 22

===== Player 226/1000: 429082692 =====
Processing: 429082692 2024-05-01
No rows.
Processing: 429082692 2024-06-01
No rows.
Processing: 429082692 2024-07-01
No rows.
Processing: 429082692 2024-08-01
No rows.
Processing: 429082692 2024-09-01
No rows.
Processing: 429082692 2024-10-01
No rows.
Processing: 429082692 2024-11-01
No rows.
Processing: 429082692 2024-12-01
No rows.
Processing: 429082692 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 429082692 2025-02-01
No rows.
Processing: 429082692 2025-03-01
No rows.
Processing: 429082692 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429082692_all_months_standard_clean.csv Rows: 2

===== Player 227/1000: 558006249 =====
Processing: 558006249 2024-05-01
No rows.
Processing: 558006249 2024-06-01
No rows.
Processing: 558006249 2024-07-01
No rows.
Processing: 558006249 2024-08-01
No rows.
Processing: 558006249 2024-09-01
No rows.
Processing: 558006249 2024-10-01
No rows.
Processing: 558006249 2024-11-01
No rows.
Processing: 558006249 2024-12-01
No rows.
Processing: 558006249 2025-01-01
No rows.
Processing: 558006249 2025-02-01
No rows.
Processing: 558006249 2025-03-01
No rows.
Processing: 558006249 2025-04-01
No rows.

===== Player 228/1000: 33404593 =====
Processing: 33404593 2024-05-01
No rows.
Processing: 33404593 2024-06-01
No rows.
Processing: 33404593 2024-07-01
No rows.
Processing: 33404593 2024-08-01
No rows.
Processing: 33404593 2024-09-01
No rows.
Processing: 33404593 2024-10-01
No rows.
Processing: 33404593 2024-11-01
No rows.
Processing: 33404593 2024-12-01
No rows.
Processing: 33404593 2025-01-01
No rows.
Processing: 33404593 2025-02-01
No rows.
Processing: 33404593 2025-03-01
No rows.
Processing: 33404593 2025-04-01
No rows.

===== Player 229/1000: 48723290 =====
Processing: 48723290 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 48723290 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 48723290 2024-07-01
No rows.
Processing: 48723290 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 48723290 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 48723290 2024-10-01
No rows.
Processing: 48723290 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 48723290 2024-12-01
No rows.
Processing: 48723290 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 48723290 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 13
Processing: 48723290 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 48723290 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48723290_all_months_standard_clean.csv Rows: 46

===== Player 230/1000: 33395756 =====
Processing: 33395756 2024-05-01
No rows.
Processing: 33395756 2024-06-01
No rows.
Processing: 33395756 2024-07-01
No rows.
Processing: 33395756 2024-08-01
No rows.
Processing: 33395756 2024-09-01
No rows.
Processing: 33395756 2024-10-01
No rows.
Processing: 33395756 2024-11-01
No rows.
Processing: 33395756 2024-12-01
No rows.
Processing: 33395756 2025-01-01
No rows.
Processing: 33395756 2025-02-01
No rows.
Processing: 33395756 2025-03-01
No rows.
Processing: 33395756 2025-04-01
No rows.

===== Player 231/1000: 558074201 =====
Processing: 558074201 2024-05-01
No rows.
Processing: 558074201 2024-06-01
No rows.
Processing: 558074201 2024-07-01
No rows.
Processing: 558074201 2024-08-01
No rows.
Processing: 558074201 2024-09-01
No rows.
Processing: 558074201 2024-10-01
No rows.
Processing: 558074201 2024-11-01
No rows.
Processing: 558074201 2024-12-01
No rows.
Processing: 558074201 2025-01-01
No rows.
Processing: 558074201 2025-02-01
No rows.
Processing: 558074201 2025-03-01
No rows.
Processing: 558074201 2025-04-01
No rows.

===== Player 232/1000: 366195016 =====
Processing: 366195016 2024-05-01
Rows: 18
Processing: 366195016 2024-06-01
No rows.
Processing: 366195016 2024-07-01
No rows.
Processing: 366195016 2024-08-01
Rows: 18
Processing: 366195016 2024-09-01
Rows: 16
Processing: 366195016 2024-10-01
Rows: 9
Processing: 366195016 2024-11-01
No rows.
Processing: 366195016 2024-12-01
No rows.
Processing: 366195016 2025-01-01
Rows: 8
Processing: 366195016 2025-02-01
Rows: 8
Processing: 366195016 2025-03-01
No rows.
Processing: 366195016 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/366195016_all_months_standard_clean.csv Rows: 77

===== Player 233/1000: 88104281 =====
Processing: 88104281 2024-05-01
No rows.
Processing: 88104281 2024-06-01
No rows.
Processing: 88104281 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 88104281 2024-08-01
No rows.
Processing: 88104281 2024-09-01
No rows.
Processing: 88104281 2024-10-01
No rows.
Processing: 88104281 2024-11-01
No rows.
Processing: 88104281 2024-12-01
No rows.
Processing: 88104281 2025-01-01
No rows.
Processing: 88104281 2025-02-01
No rows.
Processing: 88104281 2025-03-01
No rows.
Processing: 88104281 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88104281_all_months_standard_clean.csv Rows: 7

===== Player 234/1000: 531088449 =====
Processing: 531088449 2024-05-01
No rows.
Processing: 531088449 2024-06-01
No rows.
Processing: 531088449 2024-07-01
No rows.
Processing: 531088449 2024-08-01
No rows.
Processing: 531088449 2024-09-01
No rows.
Processing: 531088449 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 531088449 2024-11-01
No rows.
Processing: 531088449 2024-12-01
No rows.
Processing: 531088449 2025-01-01
No rows.
Processing: 531088449 2025-02-01
No rows.
Processing: 531088449 2025-03-01
No rows.
Processing: 531088449 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531088449_all_months_standard_clean.csv Rows: 5

===== Player 235/1000: 429077753 =====
Processing: 429077753 2024-05-01
No rows.
Processing: 429077753 2024-06-01
No rows.
Processing: 429077753 2024-07-01
No rows.
Processing: 429077753 2024-08-01
No rows.
Processing: 429077753 2024-09-01
No rows.
Processing: 429077753 2024-10-01
No rows.
Processing: 429077753 2024-11-01
No rows.
Processing: 429077753 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 429077753 2025-01-01
No rows.
Processing: 429077753 2025-02-01
No rows.
Processing: 429077753 2025-03-01
No rows.
Processing: 429077753 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429077753_all_months_standard_clean.csv Rows: 6

===== Player 236/1000: 33396116 =====
Processing: 33396116 2024-05-01
No rows.
Processing: 33396116 2024-06-01
No rows.
Processing: 33396116 2024-07-01
No rows.
Processing: 33396116 2024-08-01
No rows.
Processing: 33396116 2024-09-01
No rows.
Processing: 33396116 2024-10-01
No rows.
Processing: 33396116 2024-11-01
No rows.
Processing: 33396116 2024-12-01
No rows.
Processing: 33396116 2025-01-01
No rows.
Processing: 33396116 2025-02-01
No rows.
Processing: 33396116 2025-03-01
No rows.
Processing: 33396116 2025-04-01
No rows.

===== Player 237/1000: 429066832 =====
Processing: 429066832 2024-05-01
No rows.
Processing: 429066832 2024-06-01
No rows.
Processing: 429066832 2024-07-01
No rows.
Processing: 429066832 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 429066832 2024-09-01
No rows.
Processing: 429066832 2024-10-01
No rows.
Processing: 429066832 2024-11-01
No rows.
Processing: 429066832 2024-12-01
No rows.
Processing: 429066832 2025-01-01
No rows.
Processing: 429066832 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 429066832 2025-03-01
No rows.
Processing: 429066832 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429066832_all_months_standard_clean.csv Rows: 6

===== Player 238/1000: 429010969 =====
Processing: 429010969 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 429010969 2024-06-01
No rows.
Processing: 429010969 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 429010969 2024-08-01
No rows.
Processing: 429010969 2024-09-01
No rows.
Processing: 429010969 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 429010969 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 429010969 2024-12-01
No rows.
Processing: 429010969 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 429010969 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 429010969 2025-03-01
No rows.
Processing: 429010969 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429010969_all_months_standard_clean.csv Rows: 29

===== Player 239/1000: 531014623 =====
Processing: 531014623 2024-05-01
No rows.
Processing: 531014623 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 531014623 2024-07-01
No rows.
Processing: 531014623 2024-08-01
No rows.
Processing: 531014623 2024-09-01
No rows.
Processing: 531014623 2024-10-01
No rows.
Processing: 531014623 2024-11-01
No rows.
Processing: 531014623 2024-12-01
No rows.
Processing: 531014623 2025-01-01
No rows.
Processing: 531014623 2025-02-01
No rows.
Processing: 531014623 2025-03-01
No rows.
Processing: 531014623 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531014623_all_months_standard_clean.csv Rows: 1

===== Player 240/1000: 537012347 =====
Processing: 537012347 2024-05-01
No rows.
Processing: 537012347 2024-06-01
No rows.
Processing: 537012347 2024-07-01
No rows.
Processing: 537012347 2024-08-01
No rows.
Processing: 537012347 2024-09-01
No rows.
Processing: 537012347 2024-10-01
No rows.
Processing: 537012347 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 537012347 2024-12-01
No rows.
Processing: 537012347 2025-01-01
No rows.
Processing: 537012347 2025-02-01
No rows.
Processing: 537012347 2025-03-01
No rows.
Processing: 537012347 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537012347_all_months_standard_clean.csv Rows: 3

===== Player 241/1000: 547090944 =====
Processing: 547090944 2024-05-01
No rows.
Processing: 547090944 2024-06-01
No rows.
Processing: 547090944 2024-07-01
No rows.
Processing: 547090944 2024-08-01
No rows.
Processing: 547090944 2024-09-01
No rows.
Processing: 547090944 2024-10-01
No rows.
Processing: 547090944 2024-11-01
No rows.
Processing: 547090944 2024-12-01
No rows.
Processing: 547090944 2025-01-01
No rows.
Processing: 547090944 2025-02-01
No rows.
Processing: 547090944 2025-03-01
No rows.
Processing: 547090944 2025-04-01
No rows.

===== Player 242/1000: 25629743 =====
Processing: 25629743 2024-05-01
No rows.
Processing: 25629743 2024-06-01
No rows.
Processing: 25629743 2024-07-01
No rows.
Processing: 25629743 2024-08-01
No rows.
Processing: 25629743 2024-09-01
No rows.
Processing: 25629743 2024-10-01
No rows.
Processing: 25629743 2024-11-01
No rows.
Processing: 25629743 2024-12-01
No rows.
Processing: 25629743 2025-01-01
No rows.
Processing: 25629743 2025-02-01
No rows.
Processing: 25629743 2025-03-01
No rows.
Processing: 25629743 2025-04-01
No rows.

===== Player 243/1000: 25983059 =====
Processing: 25983059 2024-05-01
No rows.
Processing: 25983059 2024-06-01
No rows.
Processing: 25983059 2024-07-01
No rows.
Processing: 25983059 2024-08-01
No rows.
Processing: 25983059 2024-09-01
No rows.
Processing: 25983059 2024-10-01
No rows.
Processing: 25983059 2024-11-01
No rows.
Processing: 25983059 2024-12-01
No rows.
Processing: 25983059 2025-01-01
No rows.
Processing: 25983059 2025-02-01
No rows.
Processing: 25983059 2025-03-01
No rows.
Processing: 25983059 2025-04-01
No rows.

===== Player 244/1000: 547078960 =====
Processing: 547078960 2024-05-01
No rows.
Processing: 547078960 2024-06-01
No rows.
Processing: 547078960 2024-07-01
No rows.
Processing: 547078960 2024-08-01
No rows.
Processing: 547078960 2024-09-01
No rows.
Processing: 547078960 2024-10-01
No rows.
Processing: 547078960 2024-11-01
No rows.
Processing: 547078960 2024-12-01
No rows.
Processing: 547078960 2025-01-01
No rows.
Processing: 547078960 2025-02-01
No rows.
Processing: 547078960 2025-03-01
No rows.
Processing: 547078960 2025-04-01
No rows.

===== Player 245/1000: 33461775 =====
Processing: 33461775 2024-05-01
No rows.
Processing: 33461775 2024-06-01
No rows.
Processing: 33461775 2024-07-01
No rows.
Processing: 33461775 2024-08-01
No rows.
Processing: 33461775 2024-09-01
No rows.
Processing: 33461775 2024-10-01
No rows.
Processing: 33461775 2024-11-01
No rows.
Processing: 33461775 2024-12-01
No rows.
Processing: 33461775 2025-01-01
No rows.
Processing: 33461775 2025-02-01
No rows.
Processing: 33461775 2025-03-01
No rows.
Processing: 33461775 2025-04-01
No rows.

===== Player 246/1000: 48781681 =====
Processing: 48781681 2024-05-01
No rows.
Processing: 48781681 2024-06-01
No rows.
Processing: 48781681 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 48781681 2024-08-01
No rows.
Processing: 48781681 2024-09-01
No rows.
Processing: 48781681 2024-10-01
No rows.
Processing: 48781681 2024-11-01
No rows.
Processing: 48781681 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 48781681 2025-01-01
No rows.
Processing: 48781681 2025-02-01
No rows.
Processing: 48781681 2025-03-01
No rows.
Processing: 48781681 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48781681_all_months_standard_clean.csv Rows: 11

===== Player 247/1000: 33378614 =====
Processing: 33378614 2024-05-01
No rows.
Processing: 33378614 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 33378614 2024-07-01
No rows.
Processing: 33378614 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33378614 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 33378614 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 33378614 2024-11-01
No rows.
Processing: 33378614 2024-12-01
No rows.
Processing: 33378614 2025-01-01
No rows.
Processing: 33378614 2025-02-01
No rows.
Processing: 33378614 2025-03-01
No rows.
Processing: 33378614 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33378614_all_months_standard_clean.csv Rows: 21

===== Player 248/1000: 48755842 =====
Processing: 48755842 2024-05-01
No rows.
Processing: 48755842 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 48755842 2024-07-01
No rows.
Processing: 48755842 2024-08-01
No rows.
Processing: 48755842 2024-09-01
No rows.
Processing: 48755842 2024-10-01
No rows.
Processing: 48755842 2024-11-01
No rows.
Processing: 48755842 2024-12-01
No rows.
Processing: 48755842 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 48755842 2025-02-01
No rows.
Processing: 48755842 2025-03-01
No rows.
Processing: 48755842 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48755842_all_months_standard_clean.csv Rows: 4

===== Player 249/1000: 429068177 =====
Processing: 429068177 2024-05-01
No rows.
Processing: 429068177 2024-06-01
No rows.
Processing: 429068177 2024-07-01
No rows.
Processing: 429068177 2024-08-01
No rows.
Processing: 429068177 2024-09-01
No rows.
Processing: 429068177 2024-10-01
No rows.
Processing: 429068177 2024-11-01
No rows.
Processing: 429068177 2024-12-01
No rows.
Processing: 429068177 2025-01-01
No rows.
Processing: 429068177 2025-02-01
No rows.
Processing: 429068177 2025-03-01
No rows.
Processing: 429068177 2025-04-01
No rows.

===== Player 250/1000: 25697285 =====
Processing: 25697285 2024-05-01
No rows.
Processing: 25697285 2024-06-01
No rows.
Processing: 25697285 2024-07-01
No rows.
Processing: 25697285 2024-08-01
No rows.
Processing: 25697285 2024-09-01
No rows.
Processing: 25697285 2024-10-01
No rows.
Processing: 25697285 2024-11-01
No rows.
Processing: 25697285 2024-12-01
No rows.
Processing: 25697285 2025-01-01
No rows.
Processing: 25697285 2025-02-01
No rows.
Processing: 25697285 2025-03-01
No rows.
Processing: 25697285 2025-04-01
No rows.

===== Player 251/1000: 33492123 =====
Processing: 33492123 2024-05-01
No rows.
Processing: 33492123 2024-06-01
No rows.
Processing: 33492123 2024-07-01
No rows.
Processing: 33492123 2024-08-01
No rows.
Processing: 33492123 2024-09-01
Rows: 2
Processing: 33492123 2024-10-01
No rows.
Processing: 33492123 2024-11-01
No rows.
Processing: 33492123 2024-12-01
No rows.
Processing: 33492123 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 33492123 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 11
Processing: 33492123 2025-03-01
No rows.
Processing: 33492123 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33492123_all_months_standard_clean.csv Rows: 24

===== Player 252/1000: 531043291 =====
Processing: 531043291 2024-05-01
No rows.
Processing: 531043291 2024-06-01
No rows.
Processing: 531043291 2024-07-01
No rows.
Processing: 531043291 2024-08-01
No rows.
Processing: 531043291 2024-09-01
No rows.
Processing: 531043291 2024-10-01
No rows.
Processing: 531043291 2024-11-01
No rows.
Processing: 531043291 2024-12-01
No rows.
Processing: 531043291 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 531043291 2025-02-01
No rows.
Processing: 531043291 2025-03-01
No rows.
Processing: 531043291 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531043291_all_months_standard_clean.csv Rows: 7

===== Player 253/1000: 48709034 =====
Processing: 48709034 2024-05-01
No rows.
Processing: 48709034 2024-06-01
No rows.
Processing: 48709034 2024-07-01
No rows.
Processing: 48709034 2024-08-01
No rows.
Processing: 48709034 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 48709034 2024-10-01
No rows.
Processing: 48709034 2024-11-01
No rows.
Processing: 48709034 2024-12-01
No rows.
Processing: 48709034 2025-01-01
No rows.
Processing: 48709034 2025-02-01
No rows.
Processing: 48709034 2025-03-01
No rows.
Processing: 48709034 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48709034_all_months_standard_clean.csv Rows: 1

===== Player 254/1000: 577022408 =====
Processing: 577022408 2024-05-01
No rows.
Processing: 577022408 2024-06-01
No rows.
Processing: 577022408 2024-07-01
No rows.
Processing: 577022408 2024-08-01
No rows.
Processing: 577022408 2024-09-01
No rows.
Processing: 577022408 2024-10-01
No rows.
Processing: 577022408 2024-11-01
No rows.
Processing: 577022408 2024-12-01
No rows.
Processing: 577022408 2025-01-01
No rows.
Processing: 577022408 2025-02-01
No rows.
Processing: 577022408 2025-03-01
No rows.
Processing: 577022408 2025-04-01
No rows.

===== Player 255/1000: 25112880 =====
Processing: 25112880 2024-05-01
No rows.
Processing: 25112880 2024-06-01
No rows.
Processing: 25112880 2024-07-01
No rows.
Processing: 25112880 2024-08-01
No rows.
Processing: 25112880 2024-09-01
No rows.
Processing: 25112880 2024-10-01
No rows.
Processing: 25112880 2024-11-01
No rows.
Processing: 25112880 2024-12-01
No rows.
Processing: 25112880 2025-01-01
No rows.
Processing: 25112880 2025-02-01
No rows.
Processing: 25112880 2025-03-01
No rows.
Processing: 25112880 2025-04-01
No rows.

===== Player 256/1000: 531021387 =====
Processing: 531021387 2024-05-01
No rows.
Processing: 531021387 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 531021387 2024-07-01
No rows.
Processing: 531021387 2024-08-01
No rows.
Processing: 531021387 2024-09-01
No rows.
Processing: 531021387 2024-10-01
No rows.
Processing: 531021387 2024-11-01
No rows.
Processing: 531021387 2024-12-01
No rows.
Processing: 531021387 2025-01-01
No rows.
Processing: 531021387 2025-02-01
No rows.
Processing: 531021387 2025-03-01
No rows.
Processing: 531021387 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531021387_all_months_standard_clean.csv Rows: 1

===== Player 257/1000: 547077514 =====
Processing: 547077514 2024-05-01
No rows.
Processing: 547077514 2024-06-01
No rows.
Processing: 547077514 2024-07-01
No rows.
Processing: 547077514 2024-08-01
No rows.
Processing: 547077514 2024-09-01
No rows.
Processing: 547077514 2024-10-01
No rows.
Processing: 547077514 2024-11-01
No rows.
Processing: 547077514 2024-12-01
No rows.
Processing: 547077514 2025-01-01
No rows.
Processing: 547077514 2025-02-01
No rows.
Processing: 547077514 2025-03-01
No rows.
Processing: 547077514 2025-04-01
No rows.

===== Player 258/1000: 429009650 =====
Processing: 429009650 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 429009650 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 429009650 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 429009650 2024-08-01
No rows.
Processing: 429009650 2024-09-01
No rows.
Processing: 429009650 2024-10-01
No rows.
Processing: 429009650 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 429009650 2024-12-01
No rows.
Processing: 429009650 2025-01-01
No rows.
Processing: 429009650 2025-02-01
No rows.
Processing: 429009650 2025-03-01
No rows.
Processing: 429009650 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429009650_all_months_standard_clean.csv Rows: 28

===== Player 259/1000: 48714356 =====
Processing: 48714356 2024-05-01
No rows.
Processing: 48714356 2024-06-01
No rows.
Processing: 48714356 2024-07-01
No rows.
Processing: 48714356 2024-08-01
No rows.
Processing: 48714356 2024-09-01
No rows.
Processing: 48714356 2024-10-01
No rows.
Processing: 48714356 2024-11-01
No rows.
Processing: 48714356 2024-12-01
No rows.
Processing: 48714356 2025-01-01
No rows.
Processing: 48714356 2025-02-01
No rows.
Processing: 48714356 2025-03-01
No rows.
Processing: 48714356 2025-04-01
No rows.

===== Player 260/1000: 33496471 =====
Processing: 33496471 2024-05-01
No rows.
Processing: 33496471 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 14
Processing: 33496471 2024-07-01
No rows.
Processing: 33496471 2024-08-01
No rows.
Processing: 33496471 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 11
Processing: 33496471 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 33496471 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33496471 2024-12-01
No rows.
Processing: 33496471 2025-01-01
No rows.
Processing: 33496471 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33496471 2025-03-01
No rows.
Processing: 33496471 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33496471_all_months_standard_clean.csv Rows: 39

===== Player 261/1000: 48728306 =====
Processing: 48728306 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 48728306 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 48728306 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 48728306 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 48728306 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 48728306 2024-10-01
No rows.
Processing: 48728306 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 48728306 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 48728306 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 48728306 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 48728306 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 48728306 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48728306_all_months_standard_clean.csv Rows: 34

===== Player 262/1000: 531073867 =====
Processing: 531073867 2024-05-01
No rows.
Processing: 531073867 2024-06-01
No rows.
Processing: 531073867 2024-07-01
No rows.
Processing: 531073867 2024-08-01
No rows.
Processing: 531073867 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 531073867 2024-10-01
No rows.
Processing: 531073867 2024-11-01
No rows.
Processing: 531073867 2024-12-01
No rows.
Processing: 531073867 2025-01-01
No rows.
Processing: 531073867 2025-02-01
No rows.
Processing: 531073867 2025-03-01
No rows.
Processing: 531073867 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531073867_all_months_standard_clean.csv Rows: 1

===== Player 263/1000: 48744794 =====
Processing: 48744794 2024-05-01
No rows.
Processing: 48744794 2024-06-01
No rows.
Processing: 48744794 2024-07-01
No rows.
Processing: 48744794 2024-08-01
No rows.
Processing: 48744794 2024-09-01
No rows.
Processing: 48744794 2024-10-01
No rows.
Processing: 48744794 2024-11-01
No rows.
Processing: 48744794 2024-12-01
No rows.
Processing: 48744794 2025-01-01
No rows.
Processing: 48744794 2025-02-01
No rows.
Processing: 48744794 2025-03-01
No rows.
Processing: 48744794 2025-04-01
No rows.

===== Player 264/1000: 429037107 =====
Processing: 429037107 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 429037107 2024-06-01
No rows.
Processing: 429037107 2024-07-01
No rows.
Processing: 429037107 2024-08-01
No rows.
Processing: 429037107 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 429037107 2024-10-01
No rows.
Processing: 429037107 2024-11-01
No rows.
Processing: 429037107 2024-12-01
No rows.
Processing: 429037107 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 10
Processing: 429037107 2025-02-01
No rows.
Processing: 429037107 2025-03-01
No rows.
Processing: 429037107 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429037107_all_months_standard_clean.csv Rows: 13

===== Player 265/1000: 547001640 =====
Processing: 547001640 2024-05-01
No rows.
Processing: 547001640 2024-06-01
No rows.
Processing: 547001640 2024-07-01
No rows.
Processing: 547001640 2024-08-01
No rows.
Processing: 547001640 2024-09-01
No rows.
Processing: 547001640 2024-10-01
No rows.
Processing: 547001640 2024-11-01
No rows.
Processing: 547001640 2024-12-01
No rows.
Processing: 547001640 2025-01-01
No rows.
Processing: 547001640 2025-02-01
No rows.
Processing: 547001640 2025-03-01
No rows.
Processing: 547001640 2025-04-01
No rows.

===== Player 266/1000: 25924230 =====
Processing: 25924230 2024-05-01
Rows: 10
Processing: 25924230 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 18
Processing: 25924230 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 25924230 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 25924230 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 14
Processing: 25924230 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 25924230 2024-11-01
No rows.
Processing: 25924230 2024-12-01
Rows: 19
Processing: 25924230 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 30
Processing: 25924230 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 19
Processing: 25924230 2025-03-01
No rows.
Processing: 25924230 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25924230_all_months_standard_clean.csv Rows: 139

===== Player 267/1000: 33387478 =====
Processing: 33387478 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 33387478 2024-06-01
No rows.
Processing: 33387478 2024-07-01
No rows.
Processing: 33387478 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 17
Processing: 33387478 2024-09-01
No rows.
Processing: 33387478 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 14
Processing: 33387478 2024-11-01
No rows.
Processing: 33387478 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 10
Processing: 33387478 2025-01-01
No rows.
Processing: 33387478 2025-02-01
No rows.
Processing: 33387478 2025-03-01
No rows.
Processing: 33387478 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33387478_all_months_standard_clean.csv Rows: 45

===== Player 268/1000: 25156969 =====
Processing: 25156969 2024-05-01
No rows.
Processing: 25156969 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 25156969 2024-07-01
No rows.
Processing: 25156969 2024-08-01
No rows.
Processing: 25156969 2024-09-01
No rows.
Processing: 25156969 2024-10-01
No rows.
Processing: 25156969 2024-11-01
No rows.
Processing: 25156969 2024-12-01
No rows.
Processing: 25156969 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 25156969 2025-02-01
No rows.
Processing: 25156969 2025-03-01
No rows.
Processing: 25156969 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25156969_all_months_standard_clean.csv Rows: 10

===== Player 269/1000: 33383472 =====
Processing: 33383472 2024-05-01
No rows.
Processing: 33383472 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 15
Processing: 33383472 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33383472 2024-08-01
No rows.
Processing: 33383472 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 18
Processing: 33383472 2024-10-01
No rows.
Processing: 33383472 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 33383472 2024-12-01
No rows.
Processing: 33383472 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 20
Processing: 33383472 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 10
Processing: 33383472 2025-03-01
No rows.
Processing: 33383472 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33383472_all_months_standard_clean.csv Rows: 78

===== Player 270/1000: 547045043 =====
Processing: 547045043 2024-05-01
No rows.
Processing: 547045043 2024-06-01
No rows.
Processing: 547045043 2024-07-01
No rows.
Processing: 547045043 2024-08-01
No rows.
Processing: 547045043 2024-09-01
No rows.
Processing: 547045043 2024-10-01
No rows.
Processing: 547045043 2024-11-01
No rows.
Processing: 547045043 2024-12-01
No rows.
Processing: 547045043 2025-01-01
No rows.
Processing: 547045043 2025-02-01
No rows.
Processing: 547045043 2025-03-01
No rows.
Processing: 547045043 2025-04-01
No rows.

===== Player 271/1000: 531072461 =====
Processing: 531072461 2024-05-01
No rows.
Processing: 531072461 2024-06-01
No rows.
Processing: 531072461 2024-07-01
No rows.
Processing: 531072461 2024-08-01
No rows.
Processing: 531072461 2024-09-01
No rows.
Processing: 531072461 2024-10-01
No rows.
Processing: 531072461 2024-11-01
No rows.
Processing: 531072461 2024-12-01
No rows.
Processing: 531072461 2025-01-01
No rows.
Processing: 531072461 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 531072461 2025-03-01
No rows.
Processing: 531072461 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531072461_all_months_standard_clean.csv Rows: 8

===== Player 272/1000: 537084046 =====
Processing: 537084046 2024-05-01
No rows.
Processing: 537084046 2024-06-01
No rows.
Processing: 537084046 2024-07-01
No rows.
Processing: 537084046 2024-08-01
No rows.
Processing: 537084046 2024-09-01
No rows.
Processing: 537084046 2024-10-01
No rows.
Processing: 537084046 2024-11-01
No rows.
Processing: 537084046 2024-12-01
No rows.
Processing: 537084046 2025-01-01
No rows.
Processing: 537084046 2025-02-01
No rows.
Processing: 537084046 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 537084046 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537084046_all_months_standard_clean.csv Rows: 8

===== Player 273/1000: 88158594 =====
Processing: 88158594 2024-05-01
No rows.
Processing: 88158594 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 88158594 2024-07-01
No rows.
Processing: 88158594 2024-08-01
No rows.
Processing: 88158594 2024-09-01
No rows.
Processing: 88158594 2024-10-01
No rows.
Processing: 88158594 2024-11-01
No rows.
Processing: 88158594 2024-12-01
No rows.
Processing: 88158594 2025-01-01
No rows.
Processing: 88158594 2025-02-01
No rows.
Processing: 88158594 2025-03-01
No rows.
Processing: 88158594 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88158594_all_months_standard_clean.csv Rows: 1

===== Player 274/1000: 33496854 =====
Processing: 33496854 2024-05-01
No rows.
Processing: 33496854 2024-06-01
No rows.
Processing: 33496854 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 33496854 2024-08-01
No rows.
Processing: 33496854 2024-09-01
No rows.
Processing: 33496854 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 33496854 2024-11-01
No rows.
Processing: 33496854 2024-12-01
No rows.
Processing: 33496854 2025-01-01
No rows.
Processing: 33496854 2025-02-01
No rows.
Processing: 33496854 2025-03-01
No rows.
Processing: 33496854 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33496854_all_months_standard_clean.csv Rows: 8

===== Player 275/1000: 25911759 =====
Processing: 25911759 2024-05-01
No rows.
Processing: 25911759 2024-06-01
Rows: 3
Processing: 25911759 2024-07-01
No rows.
Processing: 25911759 2024-08-01
No rows.
Processing: 25911759 2024-09-01
No rows.
Processing: 25911759 2024-10-01
No rows.
Processing: 25911759 2024-11-01
No rows.
Processing: 25911759 2024-12-01
No rows.
Processing: 25911759 2025-01-01
No rows.
Processing: 25911759 2025-02-01
No rows.
Processing: 25911759 2025-03-01
No rows.
Processing: 25911759 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25911759_all_months_standard_clean.csv Rows: 3

===== Player 276/1000: 33372853 =====
Processing: 33372853 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33372853 2024-06-01
No rows.
Processing: 33372853 2024-07-01
No rows.
Processing: 33372853 2024-08-01
No rows.
Processing: 33372853 2024-09-01
No rows.
Processing: 33372853 2024-10-01
No rows.
Processing: 33372853 2024-11-01
No rows.
Processing: 33372853 2024-12-01
No rows.
Processing: 33372853 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 33372853 2025-02-01
No rows.
Processing: 33372853 2025-03-01
No rows.
Processing: 33372853 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33372853_all_months_standard_clean.csv Rows: 11

===== Player 277/1000: 547026006 =====
Processing: 547026006 2024-05-01
No rows.
Processing: 547026006 2024-06-01
No rows.
Processing: 547026006 2024-07-01
No rows.
Processing: 547026006 2024-08-01
No rows.
Processing: 547026006 2024-09-01
No rows.
Processing: 547026006 2024-10-01
No rows.
Processing: 547026006 2024-11-01
No rows.
Processing: 547026006 2024-12-01
No rows.
Processing: 547026006 2025-01-01
No rows.
Processing: 547026006 2025-02-01
No rows.
Processing: 547026006 2025-03-01
No rows.
Processing: 547026006 2025-04-01
No rows.

===== Player 278/1000: 88183122 =====
Processing: 88183122 2024-05-01
No rows.
Processing: 88183122 2024-06-01
No rows.
Processing: 88183122 2024-07-01
No rows.
Processing: 88183122 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 13
Processing: 88183122 2024-09-01
No rows.
Processing: 88183122 2024-10-01
No rows.
Processing: 88183122 2024-11-01
No rows.
Processing: 88183122 2024-12-01
No rows.
Processing: 88183122 2025-01-01
No rows.
Processing: 88183122 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 88183122 2025-03-01
No rows.
Processing: 88183122 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88183122_all_months_standard_clean.csv Rows: 22

===== Player 279/1000: 45050465 =====
Processing: 45050465 2024-05-01
No rows.
Processing: 45050465 2024-06-01
No rows.
Processing: 45050465 2024-07-01
No rows.
Processing: 45050465 2024-08-01
No rows.
Processing: 45050465 2024-09-01
No rows.
Processing: 45050465 2024-10-01
No rows.
Processing: 45050465 2024-11-01
No rows.
Processing: 45050465 2024-12-01
No rows.
Processing: 45050465 2025-01-01
No rows.
Processing: 45050465 2025-02-01
No rows.
Processing: 45050465 2025-03-01
No rows.
Processing: 45050465 2025-04-01
No rows.

===== Player 280/1000: 33436720 =====
Processing: 33436720 2024-05-01
No rows.
Processing: 33436720 2024-06-01
No rows.
Processing: 33436720 2024-07-01
No rows.
Processing: 33436720 2024-08-01
No rows.
Processing: 33436720 2024-09-01
No rows.
Processing: 33436720 2024-10-01
No rows.
Processing: 33436720 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 33436720 2024-12-01
No rows.
Processing: 33436720 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33436720 2025-02-01
No rows.
Processing: 33436720 2025-03-01
No rows.
Processing: 33436720 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33436720_all_months_standard_clean.csv Rows: 10

===== Player 281/1000: 48776157 =====
Processing: 48776157 2024-05-01
No rows.
Processing: 48776157 2024-06-01
No rows.
Processing: 48776157 2024-07-01
No rows.
Processing: 48776157 2024-08-01
No rows.
Processing: 48776157 2024-09-01
No rows.
Processing: 48776157 2024-10-01
No rows.
Processing: 48776157 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 48776157 2024-12-01
No rows.
Processing: 48776157 2025-01-01
No rows.
Processing: 48776157 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 48776157 2025-03-01
No rows.
Processing: 48776157 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48776157_all_months_standard_clean.csv Rows: 12

===== Player 282/1000: 577031016 =====
Processing: 577031016 2024-05-01
No rows.
Processing: 577031016 2024-06-01
No rows.
Processing: 577031016 2024-07-01
No rows.
Processing: 577031016 2024-08-01
No rows.
Processing: 577031016 2024-09-01
No rows.
Processing: 577031016 2024-10-01
No rows.
Processing: 577031016 2024-11-01
No rows.
Processing: 577031016 2024-12-01
No rows.
Processing: 577031016 2025-01-01
No rows.
Processing: 577031016 2025-02-01
No rows.
Processing: 577031016 2025-03-01
No rows.
Processing: 577031016 2025-04-01
No rows.

===== Player 283/1000: 547082976 =====
Processing: 547082976 2024-05-01
No rows.
Processing: 547082976 2024-06-01
No rows.
Processing: 547082976 2024-07-01
No rows.
Processing: 547082976 2024-08-01
No rows.
Processing: 547082976 2024-09-01
No rows.
Processing: 547082976 2024-10-01
No rows.
Processing: 547082976 2024-11-01
No rows.
Processing: 547082976 2024-12-01
No rows.
Processing: 547082976 2025-01-01
No rows.
Processing: 547082976 2025-02-01
No rows.
Processing: 547082976 2025-03-01
No rows.
Processing: 547082976 2025-04-01
No rows.

===== Player 284/1000: 25683977 =====
Processing: 25683977 2024-05-01
No rows.
Processing: 25683977 2024-06-01
No rows.
Processing: 25683977 2024-07-01
No rows.
Processing: 25683977 2024-08-01
No rows.
Processing: 25683977 2024-09-01
No rows.
Processing: 25683977 2024-10-01
No rows.
Processing: 25683977 2024-11-01
No rows.
Processing: 25683977 2024-12-01
No rows.
Processing: 25683977 2025-01-01
No rows.
Processing: 25683977 2025-02-01
No rows.
Processing: 25683977 2025-03-01
No rows.
Processing: 25683977 2025-04-01
No rows.

===== Player 285/1000: 33418179 =====
Processing: 33418179 2024-05-01
No rows.
Processing: 33418179 2024-06-01
No rows.
Processing: 33418179 2024-07-01
No rows.
Processing: 33418179 2024-08-01
No rows.
Processing: 33418179 2024-09-01
No rows.
Processing: 33418179 2024-10-01
No rows.
Processing: 33418179 2024-11-01
No rows.
Processing: 33418179 2024-12-01
No rows.
Processing: 33418179 2025-01-01
No rows.
Processing: 33418179 2025-02-01
No rows.
Processing: 33418179 2025-03-01
No rows.
Processing: 33418179 2025-04-01
No rows.

===== Player 286/1000: 88165310 =====
Processing: 88165310 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 88165310 2024-06-01
No rows.
Processing: 88165310 2024-07-01
No rows.
Processing: 88165310 2024-08-01
No rows.
Processing: 88165310 2024-09-01
No rows.
Processing: 88165310 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 88165310 2024-11-01
No rows.
Processing: 88165310 2024-12-01
No rows.
Processing: 88165310 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 88165310 2025-02-01
No rows.
Processing: 88165310 2025-03-01
No rows.
Processing: 88165310 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88165310_all_months_standard_clean.csv Rows: 17

===== Player 287/1000: 48785458 =====
Processing: 48785458 2024-05-01
No rows.
Processing: 48785458 2024-06-01
No rows.
Processing: 48785458 2024-07-01
No rows.
Processing: 48785458 2024-08-01
No rows.
Processing: 48785458 2024-09-01
No rows.
Processing: 48785458 2024-10-01
No rows.
Processing: 48785458 2024-11-01
No rows.
Processing: 48785458 2024-12-01
No rows.
Processing: 48785458 2025-01-01
No rows.
Processing: 48785458 2025-02-01
No rows.
Processing: 48785458 2025-03-01
No rows.
Processing: 48785458 2025-04-01
No rows.

===== Player 288/1000: 531025820 =====
Processing: 531025820 2024-05-01
No rows.
Processing: 531025820 2024-06-01
No rows.
Processing: 531025820 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 531025820 2024-08-01
No rows.
Processing: 531025820 2024-09-01
No rows.
Processing: 531025820 2024-10-01
No rows.
Processing: 531025820 2024-11-01
No rows.
Processing: 531025820 2024-12-01
No rows.
Processing: 531025820 2025-01-01
No rows.
Processing: 531025820 2025-02-01
No rows.
Processing: 531025820 2025-03-01
No rows.
Processing: 531025820 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531025820_all_months_standard_clean.csv Rows: 3

===== Player 289/1000: 25154907 =====
Processing: 25154907 2024-05-01
No rows.
Processing: 25154907 2024-06-01
No rows.
Processing: 25154907 2024-07-01
No rows.
Processing: 25154907 2024-08-01
No rows.
Processing: 25154907 2024-09-01
No rows.
Processing: 25154907 2024-10-01
No rows.
Processing: 25154907 2024-11-01
No rows.
Processing: 25154907 2024-12-01
No rows.
Processing: 25154907 2025-01-01
No rows.
Processing: 25154907 2025-02-01
No rows.
Processing: 25154907 2025-03-01
No rows.
Processing: 25154907 2025-04-01
No rows.

===== Player 290/1000: 25792962 =====
Processing: 25792962 2024-05-01
No rows.
Processing: 25792962 2024-06-01
No rows.
Processing: 25792962 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 25792962 2024-08-01
No rows.
Processing: 25792962 2024-09-01
No rows.
Processing: 25792962 2024-10-01
No rows.
Processing: 25792962 2024-11-01
No rows.
Processing: 25792962 2024-12-01
No rows.
Processing: 25792962 2025-01-01
No rows.
Processing: 25792962 2025-02-01
No rows.
Processing: 25792962 2025-03-01
No rows.
Processing: 25792962 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25792962_all_months_standard_clean.csv Rows: 2

===== Player 291/1000: 429099765 =====
Processing: 429099765 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 429099765 2024-06-01
No rows.
Processing: 429099765 2024-07-01
No rows.
Processing: 429099765 2024-08-01
No rows.
Processing: 429099765 2024-09-01
No rows.
Processing: 429099765 2024-10-01
No rows.
Processing: 429099765 2024-11-01
No rows.
Processing: 429099765 2024-12-01
No rows.
Processing: 429099765 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 429099765 2025-02-01
No rows.
Processing: 429099765 2025-03-01
No rows.
Processing: 429099765 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429099765_all_months_standard_clean.csv Rows: 14

===== Player 292/1000: 547095571 =====
Processing: 547095571 2024-05-01
No rows.
Processing: 547095571 2024-06-01
No rows.
Processing: 547095571 2024-07-01
No rows.
Processing: 547095571 2024-08-01
No rows.
Processing: 547095571 2024-09-01
No rows.
Processing: 547095571 2024-10-01
No rows.
Processing: 547095571 2024-11-01
No rows.
Processing: 547095571 2024-12-01
No rows.
Processing: 547095571 2025-01-01
No rows.
Processing: 547095571 2025-02-01
No rows.
Processing: 547095571 2025-03-01
No rows.
Processing: 547095571 2025-04-01
No rows.

===== Player 293/1000: 33425086 =====
Processing: 33425086 2024-05-01
No rows.
Processing: 33425086 2024-06-01
No rows.
Processing: 33425086 2024-07-01
No rows.
Processing: 33425086 2024-08-01
No rows.
Processing: 33425086 2024-09-01
No rows.
Processing: 33425086 2024-10-01
No rows.
Processing: 33425086 2024-11-01
No rows.
Processing: 33425086 2024-12-01
No rows.
Processing: 33425086 2025-01-01
No rows.
Processing: 33425086 2025-02-01
No rows.
Processing: 33425086 2025-03-01
No rows.
Processing: 33425086 2025-04-01
No rows.

===== Player 294/1000: 531017711 =====
Processing: 531017711 2024-05-01
No rows.
Processing: 531017711 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 531017711 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 531017711 2024-08-01
No rows.
Processing: 531017711 2024-09-01
No rows.
Processing: 531017711 2024-10-01
No rows.
Processing: 531017711 2024-11-01
No rows.
Processing: 531017711 2024-12-01
No rows.
Processing: 531017711 2025-01-01
No rows.
Processing: 531017711 2025-02-01
No rows.
Processing: 531017711 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 531017711 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531017711_all_months_standard_clean.csv Rows: 14

===== Player 295/1000: 429090652 =====
Processing: 429090652 2024-05-01
No rows.
Processing: 429090652 2024-06-01
No rows.
Processing: 429090652 2024-07-01
No rows.
Processing: 429090652 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 429090652 2024-09-01
No rows.
Processing: 429090652 2024-10-01
No rows.
Processing: 429090652 2024-11-01
No rows.
Processing: 429090652 2024-12-01
No rows.
Processing: 429090652 2025-01-01
No rows.
Processing: 429090652 2025-02-01
No rows.
Processing: 429090652 2025-03-01
No rows.
Processing: 429090652 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429090652_all_months_standard_clean.csv Rows: 2

===== Player 296/1000: 88164276 =====
Processing: 88164276 2024-05-01
No rows.
Processing: 88164276 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 88164276 2024-07-01
No rows.
Processing: 88164276 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 88164276 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 88164276 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 88164276 2024-11-01
No rows.
Processing: 88164276 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 88164276 2025-01-01
No rows.
Processing: 88164276 2025-02-01
No rows.
Processing: 88164276 2025-03-01
No rows.
Processing: 88164276 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88164276_all_months_standard_clean.csv Rows: 14

===== Player 297/1000: 88142655 =====
Processing: 88142655 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 88142655 2024-06-01
No rows.
Processing: 88142655 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 88142655 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 88142655 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 88142655 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 88142655 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 10
Processing: 88142655 2024-12-01
No rows.
Processing: 88142655 2025-01-01
No rows.
Processing: 88142655 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 18
Processing: 88142655 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 88142655 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88142655_all_months_standard_clean.csv Rows: 66

===== Player 298/1000: 25187139 =====
Processing: 25187139 2024-05-01
No rows.
Processing: 25187139 2024-06-01
No rows.
Processing: 25187139 2024-07-01
No rows.
Processing: 25187139 2024-08-01
No rows.
Processing: 25187139 2024-09-01
No rows.
Processing: 25187139 2024-10-01
No rows.
Processing: 25187139 2024-11-01
No rows.
Processing: 25187139 2024-12-01
No rows.
Processing: 25187139 2025-01-01
No rows.
Processing: 25187139 2025-02-01
No rows.
Processing: 25187139 2025-03-01
No rows.
Processing: 25187139 2025-04-01
No rows.

===== Player 299/1000: 25994557 =====
Processing: 25994557 2024-05-01
No rows.
Processing: 25994557 2024-06-01
No rows.
Processing: 25994557 2024-07-01
No rows.
Processing: 25994557 2024-08-01
No rows.
Processing: 25994557 2024-09-01
No rows.
Processing: 25994557 2024-10-01
No rows.
Processing: 25994557 2024-11-01
No rows.
Processing: 25994557 2024-12-01
No rows.
Processing: 25994557 2025-01-01
No rows.
Processing: 25994557 2025-02-01
No rows.
Processing: 25994557 2025-03-01
No rows.
Processing: 25994557 2025-04-01
No rows.

===== Player 300/1000: 33487952 =====
Processing: 33487952 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 10
Processing: 33487952 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 16
Processing: 33487952 2024-07-01
No rows.
Processing: 33487952 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 33487952 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33487952 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 33487952 2024-11-01
No rows.
Processing: 33487952 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 10
Processing: 33487952 2025-01-01
No rows.
Processing: 33487952 2025-02-01
No rows.
Processing: 33487952 2025-03-01
No rows.
Processing: 33487952 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33487952_all_months_standard_clean.csv Rows: 48

===== Player 301/1000: 531088058 =====
Processing: 531088058 2024-05-01
No rows.
Processing: 531088058 2024-06-01
No rows.
Processing: 531088058 2024-07-01
No rows.
Processing: 531088058 2024-08-01
No rows.
Processing: 531088058 2024-09-01
No rows.
Processing: 531088058 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 531088058 2024-11-01
No rows.
Processing: 531088058 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 531088058 2025-01-01
No rows.
Processing: 531088058 2025-02-01
No rows.
Processing: 531088058 2025-03-01
No rows.
Processing: 531088058 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531088058_all_months_standard_clean.csv Rows: 9

===== Player 302/1000: 48767549 =====
Processing: 48767549 2024-05-01
No rows.
Processing: 48767549 2024-06-01
No rows.
Processing: 48767549 2024-07-01
No rows.
Processing: 48767549 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 48767549 2024-09-01
No rows.
Processing: 48767549 2024-10-01
No rows.
Processing: 48767549 2024-11-01
No rows.
Processing: 48767549 2024-12-01
No rows.
Processing: 48767549 2025-01-01
No rows.
Processing: 48767549 2025-02-01
No rows.
Processing: 48767549 2025-03-01
No rows.
Processing: 48767549 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48767549_all_months_standard_clean.csv Rows: 4

===== Player 303/1000: 33466190 =====
Processing: 33466190 2024-05-01
No rows.
Processing: 33466190 2024-06-01
No rows.
Processing: 33466190 2024-07-01
No rows.
Processing: 33466190 2024-08-01
No rows.
Processing: 33466190 2024-09-01
No rows.
Processing: 33466190 2024-10-01
No rows.
Processing: 33466190 2024-11-01
No rows.
Processing: 33466190 2024-12-01
No rows.
Processing: 33466190 2025-01-01
No rows.
Processing: 33466190 2025-02-01
No rows.
Processing: 33466190 2025-03-01
No rows.
Processing: 33466190 2025-04-01
No rows.

===== Player 304/1000: 429053498 =====
Processing: 429053498 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 429053498 2024-06-01
No rows.
Processing: 429053498 2024-07-01
No rows.
Processing: 429053498 2024-08-01
No rows.
Processing: 429053498 2024-09-01
No rows.
Processing: 429053498 2024-10-01
No rows.
Processing: 429053498 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 429053498 2024-12-01
No rows.
Processing: 429053498 2025-01-01
No rows.
Processing: 429053498 2025-02-01
No rows.
Processing: 429053498 2025-03-01
No rows.
Processing: 429053498 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429053498_all_months_standard_clean.csv Rows: 4

===== Player 305/1000: 429078997 =====
Processing: 429078997 2024-05-01
No rows.
Processing: 429078997 2024-06-01
No rows.
Processing: 429078997 2024-07-01
No rows.
Processing: 429078997 2024-08-01
No rows.
Processing: 429078997 2024-09-01
No rows.
Processing: 429078997 2024-10-01
No rows.
Processing: 429078997 2024-11-01
No rows.
Processing: 429078997 2024-12-01
No rows.
Processing: 429078997 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 429078997 2025-02-01
No rows.
Processing: 429078997 2025-03-01
No rows.
Processing: 429078997 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429078997_all_months_standard_clean.csv Rows: 5

===== Player 306/1000: 25770799 =====
Processing: 25770799 2024-05-01
No rows.
Processing: 25770799 2024-06-01
No rows.
Processing: 25770799 2024-07-01
No rows.
Processing: 25770799 2024-08-01
No rows.
Processing: 25770799 2024-09-01
No rows.
Processing: 25770799 2024-10-01
No rows.
Processing: 25770799 2024-11-01
No rows.
Processing: 25770799 2024-12-01
No rows.
Processing: 25770799 2025-01-01
No rows.
Processing: 25770799 2025-02-01
No rows.
Processing: 25770799 2025-03-01
No rows.
Processing: 25770799 2025-04-01
No rows.

===== Player 307/1000: 48793353 =====
Processing: 48793353 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 48793353 2024-06-01
No rows.
Processing: 48793353 2024-07-01
No rows.
Processing: 48793353 2024-08-01
No rows.
Processing: 48793353 2024-09-01
No rows.
Processing: 48793353 2024-10-01
No rows.
Processing: 48793353 2024-11-01
No rows.
Processing: 48793353 2024-12-01
No rows.
Processing: 48793353 2025-01-01
No rows.
Processing: 48793353 2025-02-01
No rows.
Processing: 48793353 2025-03-01
No rows.
Processing: 48793353 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48793353_all_months_standard_clean.csv Rows: 5

===== Player 308/1000: 25191373 =====
Processing: 25191373 2024-05-01
No rows.
Processing: 25191373 2024-06-01
No rows.
Processing: 25191373 2024-07-01
No rows.
Processing: 25191373 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 25191373 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 25191373 2024-10-01
No rows.
Processing: 25191373 2024-11-01
No rows.
Processing: 25191373 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 25191373 2025-01-01
No rows.
Processing: 25191373 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 25191373 2025-03-01
No rows.
Processing: 25191373 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25191373_all_months_standard_clean.csv Rows: 15

===== Player 309/1000: 33426937 =====
Processing: 33426937 2024-05-01
No rows.
Processing: 33426937 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 33426937 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33426937 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 14
Processing: 33426937 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33426937 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 33426937 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 14
Processing: 33426937 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33426937 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 19
Processing: 33426937 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33426937 2025-03-01
No rows.
Processing: 33426937 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33426937_all_months_standard_clean.csv Rows: 89

===== Player 310/1000: 25104560 =====
Processing: 25104560 2024-05-01
No rows.
Processing: 25104560 2024-06-01
No rows.
Processing: 25104560 2024-07-01
No rows.
Processing: 25104560 2024-08-01
No rows.
Processing: 25104560 2024-09-01
No rows.
Processing: 25104560 2024-10-01
No rows.
Processing: 25104560 2024-11-01
No rows.
Processing: 25104560 2024-12-01
No rows.
Processing: 25104560 2025-01-01
No rows.
Processing: 25104560 2025-02-01
No rows.
Processing: 25104560 2025-03-01
No rows.
Processing: 25104560 2025-04-01
No rows.

===== Player 311/1000: 88149897 =====
Processing: 88149897 2024-05-01
No rows.
Processing: 88149897 2024-06-01
No rows.
Processing: 88149897 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 88149897 2024-08-01
No rows.
Processing: 88149897 2024-09-01
No rows.
Processing: 88149897 2024-10-01
No rows.
Processing: 88149897 2024-11-01
No rows.
Processing: 88149897 2024-12-01
No rows.
Processing: 88149897 2025-01-01
No rows.
Processing: 88149897 2025-02-01
No rows.
Processing: 88149897 2025-03-01
No rows.
Processing: 88149897 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88149897_all_months_standard_clean.csv Rows: 3

===== Player 312/1000: 429087767 =====
Processing: 429087767 2024-05-01
No rows.
Processing: 429087767 2024-06-01
No rows.
Processing: 429087767 2024-07-01
No rows.
Processing: 429087767 2024-08-01
No rows.
Processing: 429087767 2024-09-01
No rows.
Processing: 429087767 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 429087767 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 429087767 2024-12-01
No rows.
Processing: 429087767 2025-01-01
No rows.
Processing: 429087767 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 429087767 2025-03-01
No rows.
Processing: 429087767 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429087767_all_months_standard_clean.csv Rows: 6

===== Player 313/1000: 48781487 =====
Processing: 48781487 2024-05-01
No rows.
Processing: 48781487 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 48781487 2024-07-01
No rows.
Processing: 48781487 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 48781487 2024-09-01
No rows.
Processing: 48781487 2024-10-01
No rows.
Processing: 48781487 2024-11-01
No rows.
Processing: 48781487 2024-12-01
No rows.
Processing: 48781487 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 48781487 2025-02-01
No rows.
Processing: 48781487 2025-03-01
No rows.
Processing: 48781487 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48781487_all_months_standard_clean.csv Rows: 17

===== Player 314/1000: 25964640 =====
Processing: 25964640 2024-05-01
No rows.
Processing: 25964640 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 25964640 2024-07-01
No rows.
Processing: 25964640 2024-08-01
No rows.
Processing: 25964640 2024-09-01
No rows.
Processing: 25964640 2024-10-01
No rows.
Processing: 25964640 2024-11-01
No rows.
Processing: 25964640 2024-12-01
No rows.
Processing: 25964640 2025-01-01
No rows.
Processing: 25964640 2025-02-01
No rows.
Processing: 25964640 2025-03-01
No rows.
Processing: 25964640 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25964640_all_months_standard_clean.csv Rows: 4

===== Player 315/1000: 537021095 =====
Processing: 537021095 2024-05-01
No rows.
Processing: 537021095 2024-06-01
No rows.
Processing: 537021095 2024-07-01
No rows.
Processing: 537021095 2024-08-01
No rows.
Processing: 537021095 2024-09-01
No rows.
Processing: 537021095 2024-10-01
No rows.
Processing: 537021095 2024-11-01
No rows.
Processing: 537021095 2024-12-01
No rows.
Processing: 537021095 2025-01-01
No rows.
Processing: 537021095 2025-02-01
No rows.
Processing: 537021095 2025-03-01
No rows.
Processing: 537021095 2025-04-01
No rows.

===== Player 316/1000: 531039359 =====
Processing: 531039359 2024-05-01
No rows.
Processing: 531039359 2024-06-01
No rows.
Processing: 531039359 2024-07-01
No rows.
Processing: 531039359 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 531039359 2024-09-01
No rows.
Processing: 531039359 2024-10-01
No rows.
Processing: 531039359 2024-11-01
No rows.
Processing: 531039359 2024-12-01
Rows: 4
Processing: 531039359 2025-01-01
No rows.
Processing: 531039359 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 531039359 2025-03-01
No rows.
Processing: 531039359 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531039359_all_months_standard_clean.csv Rows: 13

===== Player 317/1000: 48792497 =====
Processing: 48792497 2024-05-01
No rows.
Processing: 48792497 2024-06-01
No rows.
Processing: 48792497 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 48792497 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 48792497 2024-09-01
No rows.
Processing: 48792497 2024-10-01
No rows.
Processing: 48792497 2024-11-01
No rows.
Processing: 48792497 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 48792497 2025-01-01
No rows.
Processing: 48792497 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 48792497 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 48792497 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48792497_all_months_standard_clean.csv Rows: 24

===== Player 318/1000: 537017020 =====
Processing: 537017020 2024-05-01
No rows.
Processing: 537017020 2024-06-01
No rows.
Processing: 537017020 2024-07-01
No rows.
Processing: 537017020 2024-08-01
No rows.
Processing: 537017020 2024-09-01
No rows.
Processing: 537017020 2024-10-01
No rows.
Processing: 537017020 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 537017020 2024-12-01
No rows.
Processing: 537017020 2025-01-01
No rows.
Processing: 537017020 2025-02-01
No rows.
Processing: 537017020 2025-03-01
No rows.
Processing: 537017020 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537017020_all_months_standard_clean.csv Rows: 3

===== Player 319/1000: 564061060 =====
Processing: 564061060 2024-05-01
No rows.
Processing: 564061060 2024-06-01
No rows.
Processing: 564061060 2024-07-01
No rows.
Processing: 564061060 2024-08-01
No rows.
Processing: 564061060 2024-09-01
No rows.
Processing: 564061060 2024-10-01
No rows.
Processing: 564061060 2024-11-01
No rows.
Processing: 564061060 2024-12-01
No rows.
Processing: 564061060 2025-01-01
No rows.
Processing: 564061060 2025-02-01
No rows.
Processing: 564061060 2025-03-01
No rows.
Processing: 564061060 2025-04-01
No rows.

===== Player 320/1000: 88167747 =====
Processing: 88167747 2024-05-01
No rows.
Processing: 88167747 2024-06-01
No rows.
Processing: 88167747 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 13
Processing: 88167747 2024-08-01
No rows.
Processing: 88167747 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 88167747 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 88167747 2024-11-01
No rows.
Processing: 88167747 2024-12-01
No rows.
Processing: 88167747 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 15
Processing: 88167747 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 14
Processing: 88167747 2025-03-01
No rows.
Processing: 88167747 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88167747_all_months_standard_clean.csv Rows: 55

===== Player 321/1000: 429004365 =====
Processing: 429004365 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 429004365 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 429004365 2024-07-01
No rows.
Processing: 429004365 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 429004365 2024-09-01
No rows.
Processing: 429004365 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 429004365 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 429004365 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 429004365 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 429004365 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 429004365 2025-03-01
No rows.
Processing: 429004365 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429004365_all_months_standard_clean.csv Rows: 31

===== Player 322/1000: 25774069 =====
Processing: 25774069 2024-05-01
No rows.
Processing: 25774069 2024-06-01
No rows.
Processing: 25774069 2024-07-01
No rows.
Processing: 25774069 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 25774069 2024-09-01
No rows.
Processing: 25774069 2024-10-01
No rows.
Processing: 25774069 2024-11-01
No rows.
Processing: 25774069 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 25774069 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 25774069 2025-02-01
No rows.
Processing: 25774069 2025-03-01
No rows.
Processing: 25774069 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25774069_all_months_standard_clean.csv Rows: 14

===== Player 323/1000: 429003300 =====
Processing: 429003300 2024-05-01
No rows.
Processing: 429003300 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 429003300 2024-07-01
No rows.
Processing: 429003300 2024-08-01
No rows.
Processing: 429003300 2024-09-01
No rows.
Processing: 429003300 2024-10-01
No rows.
Processing: 429003300 2024-11-01
No rows.
Processing: 429003300 2024-12-01
No rows.
Processing: 429003300 2025-01-01
No rows.
Processing: 429003300 2025-02-01
No rows.
Processing: 429003300 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 429003300 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429003300_all_months_standard_clean.csv Rows: 12

===== Player 324/1000: 88158616 =====
Processing: 88158616 2024-05-01
No rows.
Processing: 88158616 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 88158616 2024-07-01
No rows.
Processing: 88158616 2024-08-01
No rows.
Processing: 88158616 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 88158616 2024-10-01
No rows.
Processing: 88158616 2024-11-01
No rows.
Processing: 88158616 2024-12-01
No rows.
Processing: 88158616 2025-01-01
No rows.
Processing: 88158616 2025-02-01
No rows.
Processing: 88158616 2025-03-01
No rows.
Processing: 88158616 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88158616_all_months_standard_clean.csv Rows: 5

===== Player 325/1000: 88135950 =====
Processing: 88135950 2024-05-01
No rows.
Processing: 88135950 2024-06-01
No rows.
Processing: 88135950 2024-07-01
No rows.
Processing: 88135950 2024-08-01
No rows.
Processing: 88135950 2024-09-01
No rows.
Processing: 88135950 2024-10-01
No rows.
Processing: 88135950 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 88135950 2024-12-01
No rows.
Processing: 88135950 2025-01-01
No rows.
Processing: 88135950 2025-02-01
No rows.
Processing: 88135950 2025-03-01
No rows.
Processing: 88135950 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88135950_all_months_standard_clean.csv Rows: 4

===== Player 326/1000: 48781606 =====
Processing: 48781606 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 48781606 2024-06-01
No rows.
Processing: 48781606 2024-07-01
No rows.
Processing: 48781606 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 48781606 2024-09-01
No rows.
Processing: 48781606 2024-10-01
No rows.
Processing: 48781606 2024-11-01
No rows.
Processing: 48781606 2024-12-01
No rows.
Processing: 48781606 2025-01-01
No rows.
Processing: 48781606 2025-02-01
No rows.
Processing: 48781606 2025-03-01
No rows.
Processing: 48781606 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48781606_all_months_standard_clean.csv Rows: 6

===== Player 327/1000: 33479771 =====
Processing: 33479771 2024-05-01
No rows.
Processing: 33479771 2024-06-01
No rows.
Processing: 33479771 2024-07-01
No rows.
Processing: 33479771 2024-08-01
No rows.
Processing: 33479771 2024-09-01
No rows.
Processing: 33479771 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 33479771 2024-11-01
No rows.
Processing: 33479771 2024-12-01
No rows.
Processing: 33479771 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 33479771 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 33479771 2025-03-01
No rows.
Processing: 33479771 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33479771_all_months_standard_clean.csv Rows: 17

===== Player 328/1000: 33450080 =====
Processing: 33450080 2024-05-01
No rows.
Processing: 33450080 2024-06-01
No rows.
Processing: 33450080 2024-07-01
No rows.
Processing: 33450080 2024-08-01
No rows.
Processing: 33450080 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 33450080 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 33450080 2024-11-01
No rows.
Processing: 33450080 2024-12-01
No rows.
Processing: 33450080 2025-01-01
No rows.
Processing: 33450080 2025-02-01
No rows.
Processing: 33450080 2025-03-01
No rows.
Processing: 33450080 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33450080_all_months_standard_clean.csv Rows: 12

===== Player 329/1000: 48785342 =====
Processing: 48785342 2024-05-01
No rows.
Processing: 48785342 2024-06-01
No rows.
Processing: 48785342 2024-07-01
No rows.
Processing: 48785342 2024-08-01
No rows.
Processing: 48785342 2024-09-01
No rows.
Processing: 48785342 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 48785342 2024-11-01
No rows.
Processing: 48785342 2024-12-01
No rows.
Processing: 48785342 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 48785342 2025-02-01
No rows.
Processing: 48785342 2025-03-01
No rows.
Processing: 48785342 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48785342_all_months_standard_clean.csv Rows: 7

===== Player 330/1000: 25612867 =====
Processing: 25612867 2024-05-01
No rows.
Processing: 25612867 2024-06-01
No rows.
Processing: 25612867 2024-07-01
No rows.
Processing: 25612867 2024-08-01
No rows.
Processing: 25612867 2024-09-01
No rows.
Processing: 25612867 2024-10-01
No rows.
Processing: 25612867 2024-11-01
No rows.
Processing: 25612867 2024-12-01
No rows.
Processing: 25612867 2025-01-01
No rows.
Processing: 25612867 2025-02-01
No rows.
Processing: 25612867 2025-03-01
No rows.
Processing: 25612867 2025-04-01
No rows.

===== Player 331/1000: 88136973 =====
Processing: 88136973 2024-05-01
No rows.
Processing: 88136973 2024-06-01
No rows.
Processing: 88136973 2024-07-01
No rows.
Processing: 88136973 2024-08-01
No rows.
Processing: 88136973 2024-09-01
No rows.
Processing: 88136973 2024-10-01
No rows.
Processing: 88136973 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 88136973 2024-12-01
No rows.
Processing: 88136973 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 88136973 2025-02-01
No rows.
Processing: 88136973 2025-03-01
No rows.
Processing: 88136973 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88136973_all_months_standard_clean.csv Rows: 14

===== Player 332/1000: 429078628 =====
Processing: 429078628 2024-05-01
No rows.
Processing: 429078628 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 429078628 2024-07-01
No rows.
Processing: 429078628 2024-08-01
No rows.
Processing: 429078628 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 429078628 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 429078628 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 429078628 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 429078628 2025-01-01
No rows.
Processing: 429078628 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 429078628 2025-03-01
No rows.
Processing: 429078628 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429078628_all_months_standard_clean.csv Rows: 33

===== Player 333/1000: 429044715 =====
Processing: 429044715 2024-05-01
No rows.
Processing: 429044715 2024-06-01
No rows.
Processing: 429044715 2024-07-01
No rows.
Processing: 429044715 2024-08-01
No rows.
Processing: 429044715 2024-09-01
Rows: 4
Processing: 429044715 2024-10-01
No rows.
Processing: 429044715 2024-11-01
No rows.
Processing: 429044715 2024-12-01
No rows.
Processing: 429044715 2025-01-01
No rows.
Processing: 429044715 2025-02-01
No rows.
Processing: 429044715 2025-03-01
No rows.
Processing: 429044715 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429044715_all_months_standard_clean.csv Rows: 4

===== Player 334/1000: 429037689 =====
Processing: 429037689 2024-05-01
No rows.
Processing: 429037689 2024-06-01
No rows.
Processing: 429037689 2024-07-01
No rows.
Processing: 429037689 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 429037689 2024-09-01
No rows.
Processing: 429037689 2024-10-01
No rows.
Processing: 429037689 2024-11-01
No rows.
Processing: 429037689 2024-12-01
No rows.
Processing: 429037689 2025-01-01
No rows.
Processing: 429037689 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 429037689 2025-03-01
No rows.
Processing: 429037689 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429037689_all_months_standard_clean.csv Rows: 6

===== Player 335/1000: 25100122 =====
Processing: 25100122 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 25100122 2024-06-01
No rows.
Processing: 25100122 2024-07-01
No rows.
Processing: 25100122 2024-08-01
No rows.
Processing: 25100122 2024-09-01
No rows.
Processing: 25100122 2024-10-01
No rows.
Processing: 25100122 2024-11-01
No rows.
Processing: 25100122 2024-12-01
No rows.
Processing: 25100122 2025-01-01
No rows.
Processing: 25100122 2025-02-01
No rows.
Processing: 25100122 2025-03-01
No rows.
Processing: 25100122 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25100122_all_months_standard_clean.csv Rows: 4

===== Player 336/1000: 33465061 =====
Processing: 33465061 2024-05-01
No rows.
Processing: 33465061 2024-06-01
No rows.
Processing: 33465061 2024-07-01
No rows.
Processing: 33465061 2024-08-01
No rows.
Processing: 33465061 2024-09-01
No rows.
Processing: 33465061 2024-10-01
No rows.
Processing: 33465061 2024-11-01
No rows.
Processing: 33465061 2024-12-01
No rows.
Processing: 33465061 2025-01-01
No rows.
Processing: 33465061 2025-02-01
No rows.
Processing: 33465061 2025-03-01
No rows.
Processing: 33465061 2025-04-01
No rows.

===== Player 337/1000: 48707201 =====
Processing: 48707201 2024-05-01
No rows.
Processing: 48707201 2024-06-01
No rows.
Processing: 48707201 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 48707201 2024-08-01
No rows.
Processing: 48707201 2024-09-01
No rows.
Processing: 48707201 2024-10-01
No rows.
Processing: 48707201 2024-11-01
No rows.
Processing: 48707201 2024-12-01
No rows.
Processing: 48707201 2025-01-01
No rows.
Processing: 48707201 2025-02-01
No rows.
Processing: 48707201 2025-03-01
No rows.
Processing: 48707201 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48707201_all_months_standard_clean.csv Rows: 4

===== Player 338/1000: 88119050 =====
Processing: 88119050 2024-05-01
No rows.
Processing: 88119050 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 88119050 2024-07-01
Failed: 88119050 2024-07-01 TimeoutError('Page.goto: Timeout 60000ms exceeded.\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=88119050&period=2024-07-01&rating=0", waiting until "networkidle"\n')
Processing: 88119050 2024-08-01
Failed: 88119050 2024-08-01 TimeoutError('Page.goto: Timeout 60000ms exceeded.\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=88119050&period=2024-08-01&rating=0", waiting until "networkidle"\n')
Processing: 88119050 2024-09-01
Failed: 88119050 2024-09-01 TimeoutError('Page.goto: Timeout 60000ms exceeded.\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=88119050&period=2024-09-01&rating=0", waiting until "networkidle"\n')
Processing: 88119050 2024-10-01
Failed: 88119050 2024-10-01 TimeoutError('Page.goto: Timeout 60000ms exceeded.\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=88119050&period=2024-10-01&rating=0", waiting until "networkidle"\n')
Processing: 88119050 2024-11-01
Failed: 88119050 2024-11-01 TimeoutError('Page.goto: Timeout 60000ms exceeded.\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=88119050&period=2024-11-01&rating=0", waiting until "networkidle"\n')
Processing: 88119050 2024-12-01
Failed: 88119050 2024-12-01 TimeoutError('Page.goto: Timeout 60000ms exceeded.\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=88119050&period=2024-12-01&rating=0", waiting until "networkidle"\n')
Processing: 88119050 2025-01-01
Failed: 88119050 2025-01-01 TimeoutError('Page.goto: Timeout 60000ms exceeded.\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=88119050&period=2025-01-01&rating=0", waiting until "networkidle"\n')
Processing: 88119050 2025-02-01
Failed: 88119050 2025-02-01 TimeoutError('Page.goto: Timeout 60000ms exceeded.\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=88119050&period=2025-02-01&rating=0", waiting until "networkidle"\n')
Processing: 88119050 2025-03-01
Failed: 88119050 2025-03-01 TimeoutError('Page.goto: Timeout 60000ms exceeded.\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=88119050&period=2025-03-01&rating=0", waiting until "networkidle"\n')
Processing: 88119050 2025-04-01
Failed: 88119050 2025-04-01 TimeoutError('Page.goto: Timeout 60000ms exceeded.\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=88119050&period=2025-04-01&rating=0", waiting until "networkidle"\n')
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88119050_all_months_standard_clean.csv Rows: 4

===== Player 339/1000: 25738020 =====
Processing: 25738020 2024-05-01
Failed: 25738020 2024-05-01 TimeoutError('Page.goto: Timeout 60000ms exceeded.\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=25738020&period=2024-05-01&rating=0", waiting until "networkidle"\n')
Processing: 25738020 2024-06-01
Failed: 25738020 2024-06-01 TimeoutError('Page.goto: Timeout 60000ms exceeded.\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=25738020&period=2024-06-01&rating=0", waiting until "networkidle"\n')
Processing: 25738020 2024-07-01
Failed: 25738020 2024-07-01 TimeoutError('Page.goto: Timeout 60000ms exceeded.\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=25738020&period=2024-07-01&rating=0", waiting until "networkidle"\n')
Processing: 25738020 2024-08-01
Failed: 25738020 2024-08-01 TimeoutError('Page.goto: Timeout 60000ms exceeded.\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=25738020&period=2024-08-01&rating=0", waiting until "networkidle"\n')
Processing: 25738020 2024-09-01
No rows.
Processing: 25738020 2024-10-01
No rows.
Processing: 25738020 2024-11-01
No rows.
Processing: 25738020 2024-12-01
No rows.
Processing: 25738020 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 25738020 2025-02-01
Rows: 4
Processing: 25738020 2025-03-01
No rows.
Processing: 25738020 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25738020_all_months_standard_clean.csv Rows: 8

===== Player 340/1000: 547031280 =====
Processing: 547031280 2024-05-01
No rows.
Processing: 547031280 2024-06-01
No rows.
Processing: 547031280 2024-07-01
No rows.
Processing: 547031280 2024-08-01
No rows.
Processing: 547031280 2024-09-01
No rows.
Processing: 547031280 2024-10-01
No rows.
Processing: 547031280 2024-11-01
No rows.
Processing: 547031280 2024-12-01
No rows.
Processing: 547031280 2025-01-01
No rows.
Processing: 547031280 2025-02-01
No rows.
Processing: 547031280 2025-03-01
No rows.
Processing: 547031280 2025-04-01
No rows.

===== Player 341/1000: 88108325 =====
Processing: 88108325 2024-05-01
No rows.
Processing: 88108325 2024-06-01
No rows.
Processing: 88108325 2024-07-01
No rows.
Processing: 88108325 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 88108325 2024-09-01
No rows.
Processing: 88108325 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 88108325 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 88108325 2024-12-01
No rows.
Processing: 88108325 2025-01-01
No rows.
Processing: 88108325 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 88108325 2025-03-01
No rows.
Processing: 88108325 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88108325_all_months_standard_clean.csv Rows: 14

===== Player 342/1000: 33379980 =====
Processing: 33379980 2024-05-01
No rows.
Processing: 33379980 2024-06-01
No rows.
Processing: 33379980 2024-07-01
No rows.
Processing: 33379980 2024-08-01
No rows.
Processing: 33379980 2024-09-01
No rows.
Processing: 33379980 2024-10-01
No rows.
Processing: 33379980 2024-11-01
No rows.
Processing: 33379980 2024-12-01
No rows.
Processing: 33379980 2025-01-01
No rows.
Processing: 33379980 2025-02-01
No rows.
Processing: 33379980 2025-03-01
No rows.
Processing: 33379980 2025-04-01
No rows.

===== Player 343/1000: 531081703 =====
Processing: 531081703 2024-05-01
No rows.
Processing: 531081703 2024-06-01
No rows.
Processing: 531081703 2024-07-01
No rows.
Processing: 531081703 2024-08-01
No rows.
Processing: 531081703 2024-09-01
No rows.
Processing: 531081703 2024-10-01
No rows.
Processing: 531081703 2024-11-01
No rows.
Processing: 531081703 2024-12-01
No rows.
Processing: 531081703 2025-01-01
No rows.
Processing: 531081703 2025-02-01
No rows.
Processing: 531081703 2025-03-01
No rows.
Processing: 531081703 2025-04-01
No rows.

===== Player 344/1000: 33420467 =====
Processing: 33420467 2024-05-01
No rows.
Processing: 33420467 2024-06-01
No rows.
Processing: 33420467 2024-07-01
No rows.
Processing: 33420467 2024-08-01
No rows.
Processing: 33420467 2024-09-01
No rows.
Processing: 33420467 2024-10-01
No rows.
Processing: 33420467 2024-11-01
No rows.
Processing: 33420467 2024-12-01
No rows.
Processing: 33420467 2025-01-01
No rows.
Processing: 33420467 2025-02-01
No rows.
Processing: 33420467 2025-03-01
No rows.
Processing: 33420467 2025-04-01
No rows.

===== Player 345/1000: 537028537 =====
Processing: 537028537 2024-05-01
No rows.
Processing: 537028537 2024-06-01
No rows.
Processing: 537028537 2024-07-01
No rows.
Processing: 537028537 2024-08-01
No rows.
Processing: 537028537 2024-09-01
No rows.
Processing: 537028537 2024-10-01
No rows.
Processing: 537028537 2024-11-01
No rows.
Processing: 537028537 2024-12-01
No rows.
Processing: 537028537 2025-01-01
No rows.
Processing: 537028537 2025-02-01
No rows.
Processing: 537028537 2025-03-01
No rows.
Processing: 537028537 2025-04-01
No rows.

===== Player 346/1000: 33349770 =====
Processing: 33349770 2024-05-01
No rows.
Processing: 33349770 2024-06-01
No rows.
Processing: 33349770 2024-07-01
No rows.
Processing: 33349770 2024-08-01
No rows.
Processing: 33349770 2024-09-01
No rows.
Processing: 33349770 2024-10-01
No rows.
Processing: 33349770 2024-11-01
No rows.
Processing: 33349770 2024-12-01
No rows.
Processing: 33349770 2025-01-01
No rows.
Processing: 33349770 2025-02-01
No rows.
Processing: 33349770 2025-03-01
No rows.
Processing: 33349770 2025-04-01
No rows.

===== Player 347/1000: 537054171 =====
Processing: 537054171 2024-05-01
No rows.
Processing: 537054171 2024-06-01
No rows.
Processing: 537054171 2024-07-01
No rows.
Processing: 537054171 2024-08-01
No rows.
Processing: 537054171 2024-09-01
No rows.
Processing: 537054171 2024-10-01
No rows.
Processing: 537054171 2024-11-01
No rows.
Processing: 537054171 2024-12-01
No rows.
Processing: 537054171 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 537054171 2025-02-01
No rows.
Processing: 537054171 2025-03-01
No rows.
Processing: 537054171 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537054171_all_months_standard_clean.csv Rows: 2

===== Player 348/1000: 531049370 =====
Processing: 531049370 2024-05-01
No rows.
Processing: 531049370 2024-06-01
No rows.
Processing: 531049370 2024-07-01
No rows.
Processing: 531049370 2024-08-01
No rows.
Processing: 531049370 2024-09-01
No rows.
Processing: 531049370 2024-10-01
No rows.
Processing: 531049370 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 531049370 2024-12-01
No rows.
Processing: 531049370 2025-01-01
No rows.
Processing: 531049370 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 531049370 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 531049370 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531049370_all_months_standard_clean.csv Rows: 16

===== Player 349/1000: 547016540 =====
Processing: 547016540 2024-05-01
No rows.
Processing: 547016540 2024-06-01
No rows.
Processing: 547016540 2024-07-01
No rows.
Processing: 547016540 2024-08-01
No rows.
Processing: 547016540 2024-09-01
No rows.
Processing: 547016540 2024-10-01
No rows.
Processing: 547016540 2024-11-01
No rows.
Processing: 547016540 2024-12-01
No rows.
Processing: 547016540 2025-01-01
No rows.
Processing: 547016540 2025-02-01
No rows.
Processing: 547016540 2025-03-01
No rows.
Processing: 547016540 2025-04-01
No rows.

===== Player 350/1000: 558073035 =====
Processing: 558073035 2024-05-01
No rows.
Processing: 558073035 2024-06-01
No rows.
Processing: 558073035 2024-07-01
No rows.
Processing: 558073035 2024-08-01
No rows.
Processing: 558073035 2024-09-01
No rows.
Processing: 558073035 2024-10-01
No rows.
Processing: 558073035 2024-11-01
No rows.
Processing: 558073035 2024-12-01
No rows.
Processing: 558073035 2025-01-01
No rows.
Processing: 558073035 2025-02-01
No rows.
Processing: 558073035 2025-03-01
No rows.
Processing: 558073035 2025-04-01
No rows.

===== Player 351/1000: 531099840 =====
Processing: 531099840 2024-05-01
No rows.
Processing: 531099840 2024-06-01
No rows.
Processing: 531099840 2024-07-01
No rows.
Processing: 531099840 2024-08-01
No rows.
Processing: 531099840 2024-09-01
No rows.
Processing: 531099840 2024-10-01
No rows.
Processing: 531099840 2024-11-01
No rows.
Processing: 531099840 2024-12-01
No rows.
Processing: 531099840 2025-01-01
No rows.
Processing: 531099840 2025-02-01
No rows.
Processing: 531099840 2025-03-01
No rows.
Processing: 531099840 2025-04-01
No rows.

===== Player 352/1000: 88170462 =====
Processing: 88170462 2024-05-01
No rows.
Processing: 88170462 2024-06-01
No rows.
Processing: 88170462 2024-07-01
No rows.
Processing: 88170462 2024-08-01
No rows.
Processing: 88170462 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 88170462 2024-10-01
No rows.
Processing: 88170462 2024-11-01
No rows.
Processing: 88170462 2024-12-01
No rows.
Processing: 88170462 2025-01-01
No rows.
Processing: 88170462 2025-02-01
No rows.
Processing: 88170462 2025-03-01
No rows.
Processing: 88170462 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88170462_all_months_standard_clean.csv Rows: 3

===== Player 353/1000: 45047502 =====
Processing: 45047502 2024-05-01
No rows.
Processing: 45047502 2024-06-01
No rows.
Processing: 45047502 2024-07-01
No rows.
Processing: 45047502 2024-08-01
No rows.
Processing: 45047502 2024-09-01
No rows.
Processing: 45047502 2024-10-01
No rows.
Processing: 45047502 2024-11-01
No rows.
Processing: 45047502 2024-12-01
No rows.
Processing: 45047502 2025-01-01
No rows.
Processing: 45047502 2025-02-01
No rows.
Processing: 45047502 2025-03-01
No rows.
Processing: 45047502 2025-04-01
No rows.

===== Player 354/1000: 25954253 =====
Processing: 25954253 2024-05-01
No rows.
Processing: 25954253 2024-06-01
No rows.
Processing: 25954253 2024-07-01
No rows.
Processing: 25954253 2024-08-01
No rows.
Processing: 25954253 2024-09-01
No rows.
Processing: 25954253 2024-10-01
No rows.
Processing: 25954253 2024-11-01
No rows.
Processing: 25954253 2024-12-01
No rows.
Processing: 25954253 2025-01-01
No rows.
Processing: 25954253 2025-02-01
No rows.
Processing: 25954253 2025-03-01
No rows.
Processing: 25954253 2025-04-01
No rows.

===== Player 355/1000: 33428018 =====
Processing: 33428018 2024-05-01
No rows.
Processing: 33428018 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 33428018 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 33428018 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 12
Processing: 33428018 2024-09-01
No rows.
Processing: 33428018 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33428018 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 13
Processing: 33428018 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 33428018 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 10
Processing: 33428018 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 33428018 2025-03-01
No rows.
Processing: 33428018 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33428018_all_months_standard_clean.csv Rows: 67

===== Player 356/1000: 547003375 =====
Processing: 547003375 2024-05-01
No rows.
Processing: 547003375 2024-06-01
No rows.
Processing: 547003375 2024-07-01
No rows.
Processing: 547003375 2024-08-01
No rows.
Processing: 547003375 2024-09-01
No rows.
Processing: 547003375 2024-10-01
No rows.
Processing: 547003375 2024-11-01
No rows.
Processing: 547003375 2024-12-01
No rows.
Processing: 547003375 2025-01-01
No rows.
Processing: 547003375 2025-02-01
No rows.
Processing: 547003375 2025-03-01
No rows.
Processing: 547003375 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 11
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/547003375_all_months_standard_clean.csv Rows: 11

===== Player 357/1000: 33491666 =====
Processing: 33491666 2024-05-01
No rows.
Processing: 33491666 2024-06-01
No rows.
Processing: 33491666 2024-07-01
No rows.
Processing: 33491666 2024-08-01
No rows.
Processing: 33491666 2024-09-01
No rows.
Processing: 33491666 2024-10-01
No rows.
Processing: 33491666 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 33491666 2024-12-01
No rows.
Processing: 33491666 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 33491666 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33491666 2025-03-01
No rows.
Processing: 33491666 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33491666_all_months_standard_clean.csv Rows: 19

===== Player 358/1000: 429026610 =====
Processing: 429026610 2024-05-01
No rows.
Processing: 429026610 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 429026610 2024-07-01
No rows.
Processing: 429026610 2024-08-01
No rows.
Processing: 429026610 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 429026610 2024-10-01
No rows.
Processing: 429026610 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 429026610 2024-12-01
No rows.
Processing: 429026610 2025-01-01
No rows.
Processing: 429026610 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 429026610 2025-03-01
No rows.
Processing: 429026610 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429026610_all_months_standard_clean.csv Rows: 16

===== Player 359/1000: 48766437 =====
Processing: 48766437 2024-05-01
No rows.
Processing: 48766437 2024-06-01
No rows.
Processing: 48766437 2024-07-01
No rows.
Processing: 48766437 2024-08-01
No rows.
Processing: 48766437 2024-09-01
No rows.
Processing: 48766437 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 48766437 2024-11-01
No rows.
Processing: 48766437 2024-12-01
No rows.
Processing: 48766437 2025-01-01
No rows.
Processing: 48766437 2025-02-01
No rows.
Processing: 48766437 2025-03-01
No rows.
Processing: 48766437 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48766437_all_months_standard_clean.csv Rows: 7

===== Player 360/1000: 88156419 =====
Processing: 88156419 2024-05-01
No rows.
Processing: 88156419 2024-06-01
No rows.
Processing: 88156419 2024-07-01
No rows.
Processing: 88156419 2024-08-01
No rows.
Processing: 88156419 2024-09-01
No rows.
Processing: 88156419 2024-10-01
No rows.
Processing: 88156419 2024-11-01
No rows.
Processing: 88156419 2024-12-01
No rows.
Processing: 88156419 2025-01-01
No rows.
Processing: 88156419 2025-02-01
No rows.
Processing: 88156419 2025-03-01
No rows.
Processing: 88156419 2025-04-01
No rows.

===== Player 361/1000: 48768235 =====
Processing: 48768235 2024-05-01
No rows.
Processing: 48768235 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 48768235 2024-07-01
No rows.
Processing: 48768235 2024-08-01
No rows.
Processing: 48768235 2024-09-01
No rows.
Processing: 48768235 2024-10-01
No rows.
Processing: 48768235 2024-11-01
No rows.
Processing: 48768235 2024-12-01
No rows.
Processing: 48768235 2025-01-01
No rows.
Processing: 48768235 2025-02-01
No rows.
Processing: 48768235 2025-03-01
No rows.
Processing: 48768235 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48768235_all_months_standard_clean.csv Rows: 6

===== Player 362/1000: 531039421 =====
Processing: 531039421 2024-05-01
No rows.
Processing: 531039421 2024-06-01
No rows.
Processing: 531039421 2024-07-01
No rows.
Processing: 531039421 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 531039421 2024-09-01
No rows.
Processing: 531039421 2024-10-01
No rows.
Processing: 531039421 2024-11-01
No rows.
Processing: 531039421 2024-12-01
No rows.
Processing: 531039421 2025-01-01
No rows.
Processing: 531039421 2025-02-01
No rows.
Processing: 531039421 2025-03-01
No rows.
Processing: 531039421 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531039421_all_months_standard_clean.csv Rows: 5

===== Player 363/1000: 429012937 =====
Processing: 429012937 2024-05-01
No rows.
Processing: 429012937 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 429012937 2024-07-01
No rows.
Processing: 429012937 2024-08-01
No rows.
Processing: 429012937 2024-09-01
No rows.
Processing: 429012937 2024-10-01
No rows.
Processing: 429012937 2024-11-01
No rows.
Processing: 429012937 2024-12-01
No rows.
Processing: 429012937 2025-01-01
No rows.
Processing: 429012937 2025-02-01
No rows.
Processing: 429012937 2025-03-01
No rows.
Processing: 429012937 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429012937_all_months_standard_clean.csv Rows: 4

===== Player 364/1000: 48712671 =====
Processing: 48712671 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 48712671 2024-06-01
No rows.
Processing: 48712671 2024-07-01
No rows.
Processing: 48712671 2024-08-01
No rows.
Processing: 48712671 2024-09-01
No rows.
Processing: 48712671 2024-10-01
No rows.
Processing: 48712671 2024-11-01
No rows.
Processing: 48712671 2024-12-01
No rows.
Processing: 48712671 2025-01-01
No rows.
Processing: 48712671 2025-02-01
No rows.
Processing: 48712671 2025-03-01
No rows.
Processing: 48712671 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48712671_all_months_standard_clean.csv Rows: 2

===== Player 365/1000: 531078168 =====
Processing: 531078168 2024-05-01
No rows.
Processing: 531078168 2024-06-01
No rows.
Processing: 531078168 2024-07-01
No rows.
Processing: 531078168 2024-08-01
No rows.
Processing: 531078168 2024-09-01
No rows.
Processing: 531078168 2024-10-01
No rows.
Processing: 531078168 2024-11-01
No rows.
Processing: 531078168 2024-12-01
No rows.
Processing: 531078168 2025-01-01
No rows.
Processing: 531078168 2025-02-01
No rows.
Processing: 531078168 2025-03-01
No rows.
Processing: 531078168 2025-04-01
No rows.

===== Player 366/1000: 547012137 =====
Processing: 547012137 2024-05-01
No rows.
Processing: 547012137 2024-06-01
No rows.
Processing: 547012137 2024-07-01
No rows.
Processing: 547012137 2024-08-01
No rows.
Processing: 547012137 2024-09-01
No rows.
Processing: 547012137 2024-10-01
No rows.
Processing: 547012137 2024-11-01
No rows.
Processing: 547012137 2024-12-01
No rows.
Processing: 547012137 2025-01-01
No rows.
Processing: 547012137 2025-02-01
No rows.
Processing: 547012137 2025-03-01
No rows.
Processing: 547012137 2025-04-01
No rows.

===== Player 367/1000: 33422117 =====
Processing: 33422117 2024-05-01
No rows.
Processing: 33422117 2024-06-01
No rows.
Processing: 33422117 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33422117 2024-08-01
No rows.
Processing: 33422117 2024-09-01
No rows.
Processing: 33422117 2024-10-01
No rows.
Processing: 33422117 2024-11-01
No rows.
Processing: 33422117 2024-12-01
No rows.
Processing: 33422117 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33422117 2025-02-01
No rows.
Processing: 33422117 2025-03-01
No rows.
Processing: 33422117 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33422117_all_months_standard_clean.csv Rows: 13

===== Player 368/1000: 547097175 =====
Processing: 547097175 2024-05-01
No rows.
Processing: 547097175 2024-06-01
No rows.
Processing: 547097175 2024-07-01
No rows.
Processing: 547097175 2024-08-01
No rows.
Processing: 547097175 2024-09-01
No rows.
Processing: 547097175 2024-10-01
No rows.
Processing: 547097175 2024-11-01
No rows.
Processing: 547097175 2024-12-01
No rows.
Processing: 547097175 2025-01-01
No rows.
Processing: 547097175 2025-02-01
No rows.
Processing: 547097175 2025-03-01
No rows.
Processing: 547097175 2025-04-01
No rows.

===== Player 369/1000: 14350670 =====
Processing: 14350670 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 14350670 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 11
Processing: 14350670 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 14350670 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 14350670 2024-09-01
No rows.
Processing: 14350670 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 14350670 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 14350670 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 14350670 2025-01-01
No rows.
Processing: 14350670 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 12
Processing: 14350670 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 14350670 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/14350670_all_months_standard_clean.csv Rows: 62

===== Player 370/1000: 547045248 =====
Processing: 547045248 2024-05-01
No rows.
Processing: 547045248 2024-06-01
No rows.
Processing: 547045248 2024-07-01
No rows.
Processing: 547045248 2024-08-01
No rows.
Processing: 547045248 2024-09-01
No rows.
Processing: 547045248 2024-10-01
No rows.
Processing: 547045248 2024-11-01
No rows.
Processing: 547045248 2024-12-01
No rows.
Processing: 547045248 2025-01-01
No rows.
Processing: 547045248 2025-02-01
No rows.
Processing: 547045248 2025-03-01
No rows.
Processing: 547045248 2025-04-01
No rows.

===== Player 371/1000: 547026626 =====
Processing: 547026626 2024-05-01
No rows.
Processing: 547026626 2024-06-01
No rows.
Processing: 547026626 2024-07-01
No rows.
Processing: 547026626 2024-08-01
No rows.
Processing: 547026626 2024-09-01
No rows.
Processing: 547026626 2024-10-01
No rows.
Processing: 547026626 2024-11-01
No rows.
Processing: 547026626 2024-12-01
No rows.
Processing: 547026626 2025-01-01
No rows.
Processing: 547026626 2025-02-01
No rows.
Processing: 547026626 2025-03-01
No rows.
Processing: 547026626 2025-04-01
No rows.

===== Player 372/1000: 48730823 =====
Processing: 48730823 2024-05-01
No rows.
Processing: 48730823 2024-06-01
No rows.
Processing: 48730823 2024-07-01
No rows.
Processing: 48730823 2024-08-01
No rows.
Processing: 48730823 2024-09-01
No rows.
Processing: 48730823 2024-10-01
No rows.
Processing: 48730823 2024-11-01
No rows.
Processing: 48730823 2024-12-01
No rows.
Processing: 48730823 2025-01-01
No rows.
Processing: 48730823 2025-02-01
No rows.
Processing: 48730823 2025-03-01
No rows.
Processing: 48730823 2025-04-01
No rows.

===== Player 373/1000: 33395403 =====
Processing: 33395403 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33395403 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 12
Processing: 33395403 2024-07-01
No rows.
Processing: 33395403 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 10
Processing: 33395403 2024-09-01
No rows.
Processing: 33395403 2024-10-01
No rows.
Processing: 33395403 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33395403 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 19
Processing: 33395403 2025-01-01
No rows.
Processing: 33395403 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 33395403 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 33395403 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33395403_all_months_standard_clean.csv Rows: 57

===== Player 374/1000: 429057990 =====
Processing: 429057990 2024-05-01
No rows.
Processing: 429057990 2024-06-01
No rows.
Processing: 429057990 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 429057990 2024-08-01
No rows.
Processing: 429057990 2024-09-01
No rows.
Processing: 429057990 2024-10-01
No rows.
Processing: 429057990 2024-11-01
Failed: 429057990 2024-11-01 TimeoutError('Page.goto: Timeout 60000ms exceeded.\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=429057990&period=2024-11-01&rating=0", waiting until "networkidle"\n')
Processing: 429057990 2024-12-01
Failed: 429057990 2024-12-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=429057990&period=2024-12-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=429057990&period=2024-12-01&rating=0", waiting until "networkidle"\n')
Processing: 429057990 2025-01-01
Failed: 429057990 2025-01-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=429057990&period=2025-01-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=429057990&period=2025-01-01&rating=0", waiting until "networkidle"\n')
Processing: 429057990 2025-02-01
Failed: 429057990 2025-02-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=429057990&period=2025-02-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=429057990&period=2025-02-01&rating=0", waiting until "networkidle"\n')
Processing: 429057990 2025-03-01
Failed: 429057990 2025-03-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=429057990&period=2025-03-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=429057990&period=2025-03-01&rating=0", waiting until "networkidle"\n')
Processing: 429057990 2025-04-01
Failed: 429057990 2025-04-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=429057990&period=2025-04-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=429057990&period=2025-04-01&rating=0", waiting until "networkidle"\n')
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429057990_all_months_standard_clean.csv Rows: 4

===== Player 375/1000: 531027261 =====
Processing: 531027261 2024-05-01
Failed: 531027261 2024-05-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=531027261&period=2024-05-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=531027261&period=2024-05-01&rating=0", waiting until "networkidle"\n')
Processing: 531027261 2024-06-01
Failed: 531027261 2024-06-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=531027261&period=2024-06-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=531027261&period=2024-06-01&rating=0", waiting until "networkidle"\n')
Processing: 531027261 2024-07-01
Failed: 531027261 2024-07-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=531027261&period=2024-07-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=531027261&period=2024-07-01&rating=0", waiting until "networkidle"\n')
Processing: 531027261 2024-08-01
Failed: 531027261 2024-08-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=531027261&period=2024-08-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=531027261&period=2024-08-01&rating=0", waiting until "networkidle"\n')
Processing: 531027261 2024-09-01
Failed: 531027261 2024-09-01 Error('Page.goto: net::ERR_NAME_NOT_RESOLVED at https://ratings.fide.com/calculations.phtml?id_number=531027261&period=2024-09-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=531027261&period=2024-09-01&rating=0", waiting until "networkidle"\n')
Processing: 531027261 2024-10-01
Failed: 531027261 2024-10-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=531027261&period=2024-10-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=531027261&period=2024-10-01&rating=0", waiting until "networkidle"\n')
Processing: 531027261 2024-11-01
Failed: 531027261 2024-11-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=531027261&period=2024-11-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=531027261&period=2024-11-01&rating=0", waiting until "networkidle"\n')
Processing: 531027261 2024-12-01
Failed: 531027261 2024-12-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=531027261&period=2024-12-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=531027261&period=2024-12-01&rating=0", waiting until "networkidle"\n')
Processing: 531027261 2025-01-01
Failed: 531027261 2025-01-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=531027261&period=2025-01-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=531027261&period=2025-01-01&rating=0", waiting until "networkidle"\n')
Processing: 531027261 2025-02-01
Failed: 531027261 2025-02-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=531027261&period=2025-02-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=531027261&period=2025-02-01&rating=0", waiting until "networkidle"\n')
Processing: 531027261 2025-03-01
Failed: 531027261 2025-03-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=531027261&period=2025-03-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=531027261&period=2025-03-01&rating=0", waiting until "networkidle"\n')
Processing: 531027261 2025-04-01
Failed: 531027261 2025-04-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=531027261&period=2025-04-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=531027261&period=2025-04-01&rating=0", waiting until "networkidle"\n')

===== Player 376/1000: 547094532 =====
Processing: 547094532 2024-05-01
Failed: 547094532 2024-05-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=547094532&period=2024-05-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=547094532&period=2024-05-01&rating=0", waiting until "networkidle"\n')
Processing: 547094532 2024-06-01
Failed: 547094532 2024-06-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=547094532&period=2024-06-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=547094532&period=2024-06-01&rating=0", waiting until "networkidle"\n')
Processing: 547094532 2024-07-01
Failed: 547094532 2024-07-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=547094532&period=2024-07-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=547094532&period=2024-07-01&rating=0", waiting until "networkidle"\n')
Processing: 547094532 2024-08-01
Failed: 547094532 2024-08-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=547094532&period=2024-08-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=547094532&period=2024-08-01&rating=0", waiting until "networkidle"\n')
Processing: 547094532 2024-09-01
Failed: 547094532 2024-09-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=547094532&period=2024-09-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=547094532&period=2024-09-01&rating=0", waiting until "networkidle"\n')
Processing: 547094532 2024-10-01
Failed: 547094532 2024-10-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=547094532&period=2024-10-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=547094532&period=2024-10-01&rating=0", waiting until "networkidle"\n')
Processing: 547094532 2024-11-01
Failed: 547094532 2024-11-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=547094532&period=2024-11-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=547094532&period=2024-11-01&rating=0", waiting until "networkidle"\n')
Processing: 547094532 2024-12-01
Failed: 547094532 2024-12-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=547094532&period=2024-12-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=547094532&period=2024-12-01&rating=0", waiting until "networkidle"\n')
Processing: 547094532 2025-01-01
Failed: 547094532 2025-01-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=547094532&period=2025-01-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=547094532&period=2025-01-01&rating=0", waiting until "networkidle"\n')
Processing: 547094532 2025-02-01
Failed: 547094532 2025-02-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=547094532&period=2025-02-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=547094532&period=2025-02-01&rating=0", waiting until "networkidle"\n')
Processing: 547094532 2025-03-01
Failed: 547094532 2025-03-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=547094532&period=2025-03-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=547094532&period=2025-03-01&rating=0", waiting until "networkidle"\n')
Processing: 547094532 2025-04-01
Failed: 547094532 2025-04-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=547094532&period=2025-04-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=547094532&period=2025-04-01&rating=0", waiting until "networkidle"\n')

===== Player 377/1000: 33463727 =====
Processing: 33463727 2024-05-01
Failed: 33463727 2024-05-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=33463727&period=2024-05-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=33463727&period=2024-05-01&rating=0", waiting until "networkidle"\n')
Processing: 33463727 2024-06-01
Failed: 33463727 2024-06-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=33463727&period=2024-06-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=33463727&period=2024-06-01&rating=0", waiting until "networkidle"\n')
Processing: 33463727 2024-07-01
Failed: 33463727 2024-07-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=33463727&period=2024-07-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=33463727&period=2024-07-01&rating=0", waiting until "networkidle"\n')
Processing: 33463727 2024-08-01
Failed: 33463727 2024-08-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=33463727&period=2024-08-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=33463727&period=2024-08-01&rating=0", waiting until "networkidle"\n')
Processing: 33463727 2024-09-01
Failed: 33463727 2024-09-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=33463727&period=2024-09-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=33463727&period=2024-09-01&rating=0", waiting until "networkidle"\n')
Processing: 33463727 2024-10-01
Failed: 33463727 2024-10-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=33463727&period=2024-10-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=33463727&period=2024-10-01&rating=0", waiting until "networkidle"\n')
Processing: 33463727 2024-11-01
Failed: 33463727 2024-11-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=33463727&period=2024-11-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=33463727&period=2024-11-01&rating=0", waiting until "networkidle"\n')
Processing: 33463727 2024-12-01
Failed: 33463727 2024-12-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=33463727&period=2024-12-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=33463727&period=2024-12-01&rating=0", waiting until "networkidle"\n')
Processing: 33463727 2025-01-01
Failed: 33463727 2025-01-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=33463727&period=2025-01-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=33463727&period=2025-01-01&rating=0", waiting until "networkidle"\n')
Processing: 33463727 2025-02-01
Failed: 33463727 2025-02-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=33463727&period=2025-02-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=33463727&period=2025-02-01&rating=0", waiting until "networkidle"\n')
Processing: 33463727 2025-03-01
Failed: 33463727 2025-03-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=33463727&period=2025-03-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=33463727&period=2025-03-01&rating=0", waiting until "networkidle"\n')
Processing: 33463727 2025-04-01
Failed: 33463727 2025-04-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=33463727&period=2025-04-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=33463727&period=2025-04-01&rating=0", waiting until "networkidle"\n')

===== Player 378/1000: 88176983 =====
Processing: 88176983 2024-05-01
Failed: 88176983 2024-05-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=88176983&period=2024-05-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=88176983&period=2024-05-01&rating=0", waiting until "networkidle"\n')
Processing: 88176983 2024-06-01
Failed: 88176983 2024-06-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=88176983&period=2024-06-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=88176983&period=2024-06-01&rating=0", waiting until "networkidle"\n')
Processing: 88176983 2024-07-01
Failed: 88176983 2024-07-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=88176983&period=2024-07-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=88176983&period=2024-07-01&rating=0", waiting until "networkidle"\n')
Processing: 88176983 2024-08-01
Failed: 88176983 2024-08-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=88176983&period=2024-08-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=88176983&period=2024-08-01&rating=0", waiting until "networkidle"\n')
Processing: 88176983 2024-09-01
Failed: 88176983 2024-09-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=88176983&period=2024-09-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=88176983&period=2024-09-01&rating=0", waiting until "networkidle"\n')
Processing: 88176983 2024-10-01
Failed: 88176983 2024-10-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=88176983&period=2024-10-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=88176983&period=2024-10-01&rating=0", waiting until "networkidle"\n')
Processing: 88176983 2024-11-01
Failed: 88176983 2024-11-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=88176983&period=2024-11-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=88176983&period=2024-11-01&rating=0", waiting until "networkidle"\n')
Processing: 88176983 2024-12-01
Failed: 88176983 2024-12-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=88176983&period=2024-12-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=88176983&period=2024-12-01&rating=0", waiting until "networkidle"\n')
Processing: 88176983 2025-01-01
Failed: 88176983 2025-01-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=88176983&period=2025-01-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=88176983&period=2025-01-01&rating=0", waiting until "networkidle"\n')
Processing: 88176983 2025-02-01
Failed: 88176983 2025-02-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=88176983&period=2025-02-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=88176983&period=2025-02-01&rating=0", waiting until "networkidle"\n')
Processing: 88176983 2025-03-01
Failed: 88176983 2025-03-01 Error('Page.goto: net::ERR_INTERNET_DISCONNECTED at https://ratings.fide.com/calculations.phtml?id_number=88176983&period=2025-03-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=88176983&period=2025-03-01&rating=0", waiting until "networkidle"\n')
Processing: 88176983 2025-04-01
Failed: 88176983 2025-04-01 Error('Page.goto: net::ERR_NAME_NOT_RESOLVED at https://ratings.fide.com/calculations.phtml?id_number=88176983&period=2025-04-01&rating=0\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=88176983&period=2025-04-01&rating=0", waiting until "networkidle"\n')

===== Player 379/1000: 25638661 =====
Processing: 25638661 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 11
Processing: 88121860 2024-06-01
No rows.
Processing: 88121860 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 15
Processing: 88121860 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 88121860 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 88121860 2024-10-01
No rows.
Processing: 88121860 2024-11-01
No rows.
Processing: 88121860 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 88121860 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 88121860 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 88121860 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 88121860 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88121860_all_months_standard_clean.csv Rows: 69

===== Player 382/1000: 537044184 =====
Processing: 537044184 2024-05-01
No rows.
Processing: 537044184 2024-06-01
No rows.
Processing: 537044184 2024-07-01
No rows.
Processing: 537044184 2024-08-01
No rows.
Processing: 537044184 2024-09-01
No rows.
Processing: 537044184 2024-10-01
No rows.
Processing: 537044184 2024-11-01
No rows.
Processing: 537044184 2024-12-01
No rows.
Processing: 537044184 2025-01-01
No rows.
Processing: 537044184 2025-02-01
No rows.
Processing: 537044184 2025-03-01
No rows.
Processing: 537044184 2025-04-01
No rows.

===== Player 383/1000: 547026642 =====
Processing: 547026642 2024-05-01
No rows.
Processing: 547026642 2024-06-01
No rows.
Processing: 547026642 2024-07-01
No rows.
Processing: 547026642 2024-08-01
No rows.
Processing: 547026642 2024-09-01
No rows.
Processing: 547026642 2024-10-01
No rows.
Processing: 547026642 2024-11-01
No rows.
Processing: 547026642 2024-12-01
No rows.
Processing: 547026642 2025-01-01
No rows.
Processing: 547026642 2025-02-01
No rows.
Processing: 547026642 2025-03-01
No rows.
Processing: 547026642 2025-04-01
No rows.

===== Player 384/1000: 429048575 =====
Processing: 429048575 2024-05-01
No rows.
Processing: 429048575 2024-06-01
No rows.
Processing: 429048575 2024-07-01
No rows.
Processing: 429048575 2024-08-01
No rows.
Processing: 429048575 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 429048575 2024-10-01
No rows.
Processing: 429048575 2024-11-01
No rows.
Processing: 429048575 2024-12-01
No rows.
Processing: 429048575 2025-01-01
No rows.
Processing: 429048575 2025-02-01
No rows.
Processing: 429048575 2025-03-01
No rows.
Processing: 429048575 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429048575_all_months_standard_clean.csv Rows: 3

===== Player 385/1000: 88107515 =====
Processing: 88107515 2024-05-01
No rows.
Processing: 88107515 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 88107515 2024-07-01
Failed: 88107515 2024-07-01 TimeoutError('Page.goto: Timeout 60000ms exceeded.\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=88107515&period=2024-07-01&rating=0", waiting until "networkidle"\n')
Processing: 88107515 2024-08-01
No rows.
Processing: 88107515 2024-09-01
No rows.
Processing: 88107515 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 88107515 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 88107515 2024-12-01
No rows.
Processing: 88107515 2025-01-01
No rows.
Processing: 88107515 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 88107515 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 88107515 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88107515_all_months_standard_clean.csv Rows: 18

===== Player 386/1000: 88182754 =====
Processing: 88182754 2024-05-01
No rows.
Processing: 88182754 2024-06-01
No rows.
Processing: 88182754 2024-07-01
No rows.
Processing: 88182754 2024-08-01
No rows.
Processing: 88182754 2024-09-01
No rows.
Processing: 88182754 2024-10-01
No rows.
Processing: 88182754 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 88182754 2024-12-01
No rows.
Processing: 88182754 2025-01-01
No rows.
Processing: 88182754 2025-02-01
No rows.
Processing: 88182754 2025-03-01
No rows.
Processing: 88182754 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88182754_all_months_standard_clean.csv Rows: 6

===== Player 387/1000: 25912968 =====
Processing: 25912968 2024-05-01
No rows.
Processing: 25912968 2024-06-01
No rows.
Processing: 25912968 2024-07-01
No rows.
Processing: 25912968 2024-08-01
No rows.
Processing: 25912968 2024-09-01
No rows.
Processing: 25912968 2024-10-01
No rows.
Processing: 25912968 2024-11-01
No rows.
Processing: 25912968 2024-12-01
No rows.
Processing: 25912968 2025-01-01
No rows.
Processing: 25912968 2025-02-01
No rows.
Processing: 25912968 2025-03-01
No rows.
Processing: 25912968 2025-04-01
No rows.

===== Player 388/1000: 531012264 =====
Processing: 531012264 2024-05-01
No rows.
Processing: 531012264 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 531012264 2024-07-01
No rows.
Processing: 531012264 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 531012264 2024-09-01
No rows.
Processing: 531012264 2024-10-01
No rows.
Processing: 531012264 2024-11-01
No rows.
Processing: 531012264 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 531012264 2025-01-01
No rows.
Processing: 531012264 2025-02-01
No rows.
Processing: 531012264 2025-03-01
No rows.
Processing: 531012264 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531012264_all_months_standard_clean.csv Rows: 12

===== Player 389/1000: 25195425 =====
Processing: 25195425 2024-05-01
Rows: 9
Processing: 25195425 2024-06-01
No rows.
Processing: 25195425 2024-07-01
Rows: 11
Processing: 25195425 2024-08-01
Rows: 9
Processing: 25195425 2024-09-01
Rows: 10
Processing: 25195425 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 29
Processing: 25195425 2024-11-01
Rows: 8
Processing: 25195425 2024-12-01
No rows.
Processing: 25195425 2025-01-01
Rows: 10
Processing: 25195425 2025-02-01
Rows: 20
Processing: 25195425 2025-03-01
No rows.
Processing: 25195425 2025-04-01
Rows: 9
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25195425_all_months_standard_clean.csv Rows: 115

===== Player 390/1000: 48735396 =====
Processing: 48735396 2024-05-01
No rows.
Processing: 48735396 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 10
Processing: 48735396 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 48735396 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 48735396 2024-09-01
Rows: 5
Processing: 48735396 2024-10-01
No rows.
Processing: 48735396 2024-11-01
No rows.
Processing: 48735396 2024-12-01
No rows.
Processing: 48735396 2025-01-01
No rows.
Processing: 48735396 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 48735396 2025-03-01
No rows.
Processing: 48735396 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48735396_all_months_standard_clean.csv Rows: 29

===== Player 391/1000: 547077670 =====
Processing: 547077670 2024-05-01
No rows.
Processing: 547077670 2024-06-01
No rows.
Processing: 547077670 2024-07-01
No rows.
Processing: 547077670 2024-08-01
No rows.
Processing: 547077670 2024-09-01
No rows.
Processing: 547077670 2024-10-01
No rows.
Processing: 547077670 2024-11-01
No rows.
Processing: 547077670 2024-12-01
No rows.
Processing: 547077670 2025-01-01
No rows.
Processing: 547077670 2025-02-01
No rows.
Processing: 547077670 2025-03-01
No rows.
Processing: 547077670 2025-04-01
No rows.

===== Player 392/1000: 88126951 =====
Processing: 88126951 2024-05-01
No rows.
Processing: 88126951 2024-06-01
No rows.
Processing: 88126951 2024-07-01
No rows.
Processing: 88126951 2024-08-01
No rows.
Processing: 88126951 2024-09-01
No rows.
Processing: 88126951 2024-10-01
No rows.
Processing: 88126951 2024-11-01
No rows.
Processing: 88126951 2024-12-01
No rows.
Processing: 88126951 2025-01-01
No rows.
Processing: 88126951 2025-02-01
No rows.
Processing: 88126951 2025-03-01
No rows.
Processing: 88126951 2025-04-01
No rows.

===== Player 393/1000: 33429537 =====
Processing: 33429537 2024-05-01
No rows.
Processing: 33429537 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 33429537 2024-07-01
No rows.
Processing: 33429537 2024-08-01
No rows.
Processing: 33429537 2024-09-01
No rows.
Processing: 33429537 2024-10-01
No rows.
Processing: 33429537 2024-11-01
No rows.
Processing: 33429537 2024-12-01
No rows.
Processing: 33429537 2025-01-01
No rows.
Processing: 33429537 2025-02-01
No rows.
Processing: 33429537 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 33429537 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33429537_all_months_standard_clean.csv Rows: 9

===== Player 394/1000: 25712608 =====
Processing: 25712608 2024-05-01
No rows.
Processing: 25712608 2024-06-01
No rows.
Processing: 25712608 2024-07-01
No rows.
Processing: 25712608 2024-08-01
No rows.
Processing: 25712608 2024-09-01
No rows.
Processing: 25712608 2024-10-01
No rows.
Processing: 25712608 2024-11-01
No rows.
Processing: 25712608 2024-12-01
No rows.
Processing: 25712608 2025-01-01
No rows.
Processing: 25712608 2025-02-01
No rows.
Processing: 25712608 2025-03-01
No rows.
Processing: 25712608 2025-04-01
No rows.

===== Player 395/1000: 531005594 =====
Processing: 531005594 2024-05-01
No rows.
Processing: 531005594 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 531005594 2024-07-01
No rows.
Processing: 531005594 2024-08-01
No rows.
Processing: 531005594 2024-09-01
No rows.
Processing: 531005594 2024-10-01
No rows.
Processing: 531005594 2024-11-01
No rows.
Processing: 531005594 2024-12-01
No rows.
Processing: 531005594 2025-01-01
No rows.
Processing: 531005594 2025-02-01
No rows.
Processing: 531005594 2025-03-01
No rows.
Processing: 531005594 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531005594_all_months_standard_clean.csv Rows: 2

===== Player 396/1000: 25189549 =====
Processing: 25189549 2024-05-01
No rows.
Processing: 25189549 2024-06-01
No rows.
Processing: 25189549 2024-07-01
No rows.
Processing: 25189549 2024-08-01
No rows.
Processing: 25189549 2024-09-01
No rows.
Processing: 25189549 2024-10-01
No rows.
Processing: 25189549 2024-11-01
No rows.
Processing: 25189549 2024-12-01
No rows.
Processing: 25189549 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 25189549 2025-02-01
No rows.
Processing: 25189549 2025-03-01
No rows.
Processing: 25189549 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25189549_all_months_standard_clean.csv Rows: 4

===== Player 397/1000: 558047255 =====
Processing: 558047255 2024-05-01
No rows.
Processing: 558047255 2024-06-01
No rows.
Processing: 558047255 2024-07-01
No rows.
Processing: 558047255 2024-08-01
No rows.
Processing: 558047255 2024-09-01
No rows.
Processing: 558047255 2024-10-01
No rows.
Processing: 558047255 2024-11-01
No rows.
Processing: 558047255 2024-12-01
No rows.
Processing: 558047255 2025-01-01
No rows.
Processing: 558047255 2025-02-01
No rows.
Processing: 558047255 2025-03-01
No rows.
Processing: 558047255 2025-04-01
No rows.

===== Player 398/1000: 564078388 =====
Processing: 564078388 2024-05-01
No rows.
Processing: 564078388 2024-06-01
No rows.
Processing: 564078388 2024-07-01
No rows.
Processing: 564078388 2024-08-01
No rows.
Processing: 564078388 2024-09-01
No rows.
Processing: 564078388 2024-10-01
No rows.
Processing: 564078388 2024-11-01
No rows.
Processing: 564078388 2024-12-01
No rows.
Processing: 564078388 2025-01-01
No rows.
Processing: 564078388 2025-02-01
No rows.
Processing: 564078388 2025-03-01
No rows.
Processing: 564078388 2025-04-01
No rows.

===== Player 399/1000: 531044840 =====
Processing: 531044840 2024-05-01
No rows.
Processing: 531044840 2024-06-01
No rows.
Processing: 531044840 2024-07-01
No rows.
Processing: 531044840 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 531044840 2024-09-01
No rows.
Processing: 531044840 2024-10-01
No rows.
Processing: 531044840 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 531044840 2024-12-01
No rows.
Processing: 531044840 2025-01-01
No rows.
Processing: 531044840 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 531044840 2025-03-01
No rows.
Processing: 531044840 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531044840_all_months_standard_clean.csv Rows: 11

===== Player 400/1000: 33417318 =====
Processing: 33417318 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33417318 2024-06-01
No rows.
Processing: 33417318 2024-07-01
No rows.
Processing: 33417318 2024-08-01
No rows.
Processing: 33417318 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 33417318 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 33417318 2024-11-01
No rows.
Processing: 33417318 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 33417318 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33417318 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 33417318 2025-03-01
No rows.
Processing: 33417318 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33417318_all_months_standard_clean.csv Rows: 30

===== Player 401/1000: 537026216 =====
Processing: 537026216 2024-05-01
No rows.
Processing: 537026216 2024-06-01
No rows.
Processing: 537026216 2024-07-01
No rows.
Processing: 537026216 2024-08-01
No rows.
Processing: 537026216 2024-09-01
No rows.
Processing: 537026216 2024-10-01
No rows.
Processing: 537026216 2024-11-01
No rows.
Processing: 537026216 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 537026216 2025-01-01
No rows.
Processing: 537026216 2025-02-01
No rows.
Processing: 537026216 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 537026216 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537026216_all_months_standard_clean.csv Rows: 5

===== Player 402/1000: 25136160 =====
Processing: 25136160 2024-05-01
No rows.
Processing: 25136160 2024-06-01
No rows.
Processing: 25136160 2024-07-01
No rows.
Processing: 25136160 2024-08-01
No rows.
Processing: 25136160 2024-09-01
No rows.
Processing: 25136160 2024-10-01
No rows.
Processing: 25136160 2024-11-01
No rows.
Processing: 25136160 2024-12-01
No rows.
Processing: 25136160 2025-01-01
No rows.
Processing: 25136160 2025-02-01
No rows.
Processing: 25136160 2025-03-01
No rows.
Processing: 25136160 2025-04-01
No rows.

===== Player 403/1000: 33467501 =====
Processing: 33467501 2024-05-01
No rows.
Processing: 33467501 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33467501 2024-07-01
No rows.
Processing: 33467501 2024-08-01
No rows.
Processing: 33467501 2024-09-01
No rows.
Processing: 33467501 2024-10-01
No rows.
Processing: 33467501 2024-11-01
No rows.
Processing: 33467501 2024-12-01
No rows.
Processing: 33467501 2025-01-01
No rows.
Processing: 33467501 2025-02-01
No rows.
Processing: 33467501 2025-03-01
No rows.
Processing: 33467501 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33467501_all_months_standard_clean.csv Rows: 5

===== Player 404/1000: 531026710 =====
Processing: 531026710 2024-05-01
No rows.
Processing: 531026710 2024-06-01
No rows.
Processing: 531026710 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 531026710 2024-08-01
No rows.
Processing: 531026710 2024-09-01
No rows.
Processing: 531026710 2024-10-01
No rows.
Processing: 531026710 2024-11-01
No rows.
Processing: 531026710 2024-12-01
No rows.
Processing: 531026710 2025-01-01
No rows.
Processing: 531026710 2025-02-01
No rows.
Processing: 531026710 2025-03-01
No rows.
Processing: 531026710 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531026710_all_months_standard_clean.csv Rows: 7

===== Player 405/1000: 48785610 =====
Processing: 48785610 2024-05-01
No rows.
Processing: 48785610 2024-06-01
No rows.
Processing: 48785610 2024-07-01
No rows.
Processing: 48785610 2024-08-01
No rows.
Processing: 48785610 2024-09-01
No rows.
Processing: 48785610 2024-10-01
No rows.
Processing: 48785610 2024-11-01
No rows.
Processing: 48785610 2024-12-01
No rows.
Processing: 48785610 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 48785610 2025-02-01
Rows: 5
Processing: 48785610 2025-03-01
No rows.
Processing: 48785610 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48785610_all_months_standard_clean.csv Rows: 8

===== Player 406/1000: 531027474 =====
Processing: 531027474 2024-05-01
No rows.
Processing: 531027474 2024-06-01
No rows.
Processing: 531027474 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 531027474 2024-08-01
No rows.
Processing: 531027474 2024-09-01
No rows.
Processing: 531027474 2024-10-01
No rows.
Processing: 531027474 2024-11-01
No rows.
Processing: 531027474 2024-12-01
No rows.
Processing: 531027474 2025-01-01
No rows.
Processing: 531027474 2025-02-01
No rows.
Processing: 531027474 2025-03-01
No rows.
Processing: 531027474 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531027474_all_months_standard_clean.csv Rows: 8

===== Player 407/1000: 48753890 =====
Processing: 48753890 2024-05-01
No rows.
Processing: 48753890 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 48753890 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 48753890 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 48753890 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 48753890 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 48753890 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 48753890 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 48753890 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 48753890 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 17
Processing: 48753890 2025-03-01
No rows.
Processing: 48753890 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48753890_all_months_standard_clean.csv Rows: 60

===== Player 408/1000: 537092014 =====
Processing: 537092014 2024-05-01
No rows.
Processing: 537092014 2024-06-01
No rows.
Processing: 537092014 2024-07-01
No rows.
Processing: 537092014 2024-08-01
No rows.
Processing: 537092014 2024-09-01
No rows.
Processing: 537092014 2024-10-01
No rows.
Processing: 537092014 2024-11-01
No rows.
Processing: 537092014 2024-12-01
No rows.
Processing: 537092014 2025-01-01
No rows.
Processing: 537092014 2025-02-01
No rows.
Processing: 537092014 2025-03-01
No rows.
Processing: 537092014 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537092014_all_months_standard_clean.csv Rows: 6

===== Player 409/1000: 25120921 =====
Processing: 25120921 2024-05-01
No rows.
Processing: 25120921 2024-06-01
No rows.
Processing: 25120921 2024-07-01
No rows.
Processing: 25120921 2024-08-01
No rows.
Processing: 25120921 2024-09-01
No rows.
Processing: 25120921 2024-10-01
No rows.
Processing: 25120921 2024-11-01
No rows.
Processing: 25120921 2024-12-01
No rows.
Processing: 25120921 2025-01-01
No rows.
Processing: 25120921 2025-02-01
No rows.
Processing: 25120921 2025-03-01
No rows.
Processing: 25120921 2025-04-01
No rows.

===== Player 410/1000: 25128981 =====
Processing: 25128981 2024-05-01
No rows.
Processing: 25128981 2024-06-01
No rows.
Processing: 25128981 2024-07-01
No rows.
Processing: 25128981 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 11
Processing: 25128981 2024-09-01
No rows.
Processing: 25128981 2024-10-01
No rows.
Processing: 25128981 2024-11-01
No rows.
Processing: 25128981 2024-12-01
No rows.
Processing: 25128981 2025-01-01
No rows.
Processing: 25128981 2025-02-01
No rows.
Processing: 25128981 2025-03-01
No rows.
Processing: 25128981 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25128981_all_months_standard_clean.csv Rows: 11

===== Player 411/1000: 33460710 =====
Processing: 33460710 2024-05-01
No rows.
Processing: 33460710 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 33460710 2024-07-01
No rows.
Processing: 33460710 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 33460710 2024-09-01
No rows.
Processing: 33460710 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33460710 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 19
Processing: 33460710 2024-12-01
No rows.
Processing: 33460710 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 17
Processing: 33460710 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 14
Processing: 33460710 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 33460710 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33460710_all_months_standard_clean.csv Rows: 75

===== Player 412/1000: 33321094 =====
Processing: 33321094 2024-05-01
No rows.
Processing: 33321094 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 16
Processing: 33321094 2024-07-01
No rows.
Processing: 33321094 2024-08-01
No rows.
Processing: 33321094 2024-09-01
No rows.
Processing: 33321094 2024-10-01
No rows.
Processing: 33321094 2024-11-01
No rows.
Processing: 33321094 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 11
Processing: 33321094 2025-01-01
No rows.
Processing: 33321094 2025-02-01
No rows.
Processing: 33321094 2025-03-01
No rows.
Processing: 33321094 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33321094_all_months_standard_clean.csv Rows: 27

===== Player 413/1000: 547061847 =====
Processing: 547061847 2024-05-01
No rows.
Processing: 547061847 2024-06-01
No rows.
Processing: 547061847 2024-07-01
No rows.
Processing: 547061847 2024-08-01
No rows.
Processing: 547061847 2024-09-01
No rows.
Processing: 547061847 2024-10-01
No rows.
Processing: 547061847 2024-11-01
No rows.
Processing: 547061847 2024-12-01
No rows.
Processing: 547061847 2025-01-01
No rows.
Processing: 547061847 2025-02-01
No rows.
Processing: 547061847 2025-03-01
No rows.
Processing: 547061847 2025-04-01
No rows.

===== Player 414/1000: 33481091 =====
Processing: 33481091 2024-05-01
No rows.
Processing: 33481091 2024-06-01
No rows.
Processing: 33481091 2024-07-01
No rows.
Processing: 33481091 2024-08-01
No rows.
Processing: 33481091 2024-09-01
No rows.
Processing: 33481091 2024-10-01
No rows.
Processing: 33481091 2024-11-01
No rows.
Processing: 33481091 2024-12-01
No rows.
Processing: 33481091 2025-01-01
No rows.
Processing: 33481091 2025-02-01
No rows.
Processing: 33481091 2025-03-01
No rows.
Processing: 33481091 2025-04-01
No rows.

===== Player 415/1000: 547043067 =====
Processing: 547043067 2024-05-01
No rows.
Processing: 547043067 2024-06-01
No rows.
Processing: 547043067 2024-07-01
No rows.
Processing: 547043067 2024-08-01
No rows.
Processing: 547043067 2024-09-01
No rows.
Processing: 547043067 2024-10-01
No rows.
Processing: 547043067 2024-11-01
No rows.
Processing: 547043067 2024-12-01
No rows.
Processing: 547043067 2025-01-01
No rows.
Processing: 547043067 2025-02-01
No rows.
Processing: 547043067 2025-03-01
No rows.
Processing: 547043067 2025-04-01
No rows.

===== Player 416/1000: 25755242 =====
Processing: 25755242 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 25755242 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 16
Processing: 25755242 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 25755242 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 25755242 2024-09-01
No rows.
Processing: 25755242 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 25755242 2024-11-01
No rows.
Processing: 25755242 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 10
Processing: 25755242 2025-01-01
No rows.
Processing: 25755242 2025-02-01
No rows.
Processing: 25755242 2025-03-01
No rows.
Processing: 25755242 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25755242_all_months_standard_clean.csv Rows: 44

===== Player 417/1000: 88119190 =====
Processing: 88119190 2024-05-01
No rows.
Processing: 88119190 2024-06-01
No rows.
Processing: 88119190 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 88119190 2024-08-01
No rows.
Processing: 88119190 2024-09-01
No rows.
Processing: 88119190 2024-10-01
No rows.
Processing: 88119190 2024-11-01
No rows.
Processing: 88119190 2024-12-01
No rows.
Processing: 88119190 2025-01-01
No rows.
Processing: 88119190 2025-02-01
No rows.
Processing: 88119190 2025-03-01
No rows.
Processing: 88119190 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88119190_all_months_standard_clean.csv Rows: 4

===== Player 418/1000: 48768669 =====
Processing: 48768669 2024-05-01
No rows.
Processing: 48768669 2024-06-01
No rows.
Processing: 48768669 2024-07-01
No rows.
Processing: 48768669 2024-08-01
No rows.
Processing: 48768669 2024-09-01
No rows.
Processing: 48768669 2024-10-01
No rows.
Processing: 48768669 2024-11-01
No rows.
Processing: 48768669 2024-12-01
No rows.
Processing: 48768669 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 48768669 2025-02-01
No rows.
Processing: 48768669 2025-03-01
No rows.
Processing: 48768669 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48768669_all_months_standard_clean.csv Rows: 6

===== Player 419/1000: 547042044 =====
Processing: 547042044 2024-05-01
No rows.
Processing: 547042044 2024-06-01
No rows.
Processing: 547042044 2024-07-01
No rows.
Processing: 547042044 2024-08-01
No rows.
Processing: 547042044 2024-09-01
No rows.
Processing: 547042044 2024-10-01
No rows.
Processing: 547042044 2024-11-01
No rows.
Processing: 547042044 2024-12-01
No rows.
Processing: 547042044 2025-01-01
No rows.
Processing: 547042044 2025-02-01
No rows.
Processing: 547042044 2025-03-01
No rows.
Processing: 547042044 2025-04-01
No rows.

===== Player 420/1000: 48784753 =====
Processing: 48784753 2024-05-01
No rows.
Processing: 48784753 2024-06-01
No rows.
Processing: 48784753 2024-07-01
No rows.
Processing: 48784753 2024-08-01
No rows.
Processing: 48784753 2024-09-01
No rows.
Processing: 48784753 2024-10-01
No rows.
Processing: 48784753 2024-11-01
No rows.
Processing: 48784753 2024-12-01
No rows.
Processing: 48784753 2025-01-01
No rows.
Processing: 48784753 2025-02-01
No rows.
Processing: 48784753 2025-03-01
No rows.
Processing: 48784753 2025-04-01
No rows.

===== Player 421/1000: 547049588 =====
Processing: 547049588 2024-05-01
No rows.
Processing: 547049588 2024-06-01
No rows.
Processing: 547049588 2024-07-01
No rows.
Processing: 547049588 2024-08-01
No rows.
Processing: 547049588 2024-09-01
No rows.
Processing: 547049588 2024-10-01
No rows.
Processing: 547049588 2024-11-01
No rows.
Processing: 547049588 2024-12-01
No rows.
Processing: 547049588 2025-01-01
No rows.
Processing: 547049588 2025-02-01
No rows.
Processing: 547049588 2025-03-01
No rows.
Processing: 547049588 2025-04-01
No rows.

===== Player 422/1000: 48761630 =====
Processing: 48761630 2024-05-01
No rows.
Processing: 48761630 2024-06-01
No rows.
Processing: 48761630 2024-07-01
No rows.
Processing: 48761630 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 48761630 2024-09-01
No rows.
Processing: 48761630 2024-10-01
No rows.
Processing: 48761630 2024-11-01
No rows.
Processing: 48761630 2024-12-01
No rows.
Processing: 48761630 2025-01-01
No rows.
Processing: 48761630 2025-02-01
No rows.
Processing: 48761630 2025-03-01
No rows.
Processing: 48761630 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48761630_all_months_standard_clean.csv Rows: 4

===== Player 423/1000: 531026486 =====
Processing: 531026486 2024-05-01
No rows.
Processing: 531026486 2024-06-01
No rows.
Processing: 531026486 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 13
Processing: 531026486 2024-08-01
No rows.
Processing: 531026486 2024-09-01
No rows.
Processing: 531026486 2024-10-01
No rows.
Processing: 531026486 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 531026486 2024-12-01
No rows.
Processing: 531026486 2025-01-01
No rows.
Processing: 531026486 2025-02-01
No rows.
Processing: 531026486 2025-03-01
No rows.
Processing: 531026486 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531026486_all_months_standard_clean.csv Rows: 19

===== Player 424/1000: 429002109 =====
Processing: 429002109 2024-05-01
No rows.
Processing: 429002109 2024-06-01
No rows.
Processing: 429002109 2024-07-01
No rows.
Processing: 429002109 2024-08-01
No rows.
Processing: 429002109 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 429002109 2024-10-01
No rows.
Processing: 429002109 2024-11-01
No rows.
Processing: 429002109 2024-12-01
No rows.
Processing: 429002109 2025-01-01
No rows.
Processing: 429002109 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 429002109 2025-03-01
No rows.
Processing: 429002109 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429002109_all_months_standard_clean.csv Rows: 11

===== Player 425/1000: 25683489 =====
Processing: 25683489 2024-05-01
No rows.
Processing: 25683489 2024-06-01
No rows.
Processing: 25683489 2024-07-01
No rows.
Processing: 25683489 2024-08-01
No rows.
Processing: 25683489 2024-09-01
No rows.
Processing: 25683489 2024-10-01
No rows.
Processing: 25683489 2024-11-01
No rows.
Processing: 25683489 2024-12-01
No rows.
Processing: 25683489 2025-01-01
No rows.
Processing: 25683489 2025-02-01
No rows.
Processing: 25683489 2025-03-01
No rows.
Processing: 25683489 2025-04-01
No rows.

===== Player 426/1000: 25980866 =====
Processing: 25980866 2024-05-01
No rows.
Processing: 25980866 2024-06-01
No rows.
Processing: 25980866 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 25980866 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 14
Processing: 25980866 2024-09-01
No rows.
Processing: 25980866 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 25980866 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 25980866 2024-12-01
No rows.
Processing: 25980866 2025-01-01
No rows.
Processing: 25980866 2025-02-01
No rows.
Processing: 25980866 2025-03-01
No rows.
Processing: 25980866 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25980866_all_months_standard_clean.csv Rows: 34

===== Player 427/1000: 48710318 =====
Processing: 48710318 2024-05-01
No rows.
Processing: 48710318 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 48710318 2024-07-01
Rows: 5
Processing: 48710318 2024-08-01
No rows.
Processing: 48710318 2024-09-01
No rows.
Processing: 48710318 2024-10-01
No rows.
Processing: 48710318 2024-11-01
No rows.
Processing: 48710318 2024-12-01
No rows.
Processing: 48710318 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 48710318 2025-02-01
No rows.
Processing: 48710318 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 48710318 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48710318_all_months_standard_clean.csv Rows: 16

===== Player 428/1000: 537011685 =====
Processing: 537011685 2024-05-01
No rows.
Processing: 537011685 2024-06-01
No rows.
Processing: 537011685 2024-07-01
No rows.
Processing: 537011685 2024-08-01
No rows.
Processing: 537011685 2024-09-01
No rows.
Processing: 537011685 2024-10-01
No rows.
Processing: 537011685 2024-11-01
No rows.
Processing: 537011685 2024-12-01
No rows.
Processing: 537011685 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 537011685 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 537011685 2025-03-01
No rows.
Processing: 537011685 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537011685_all_months_standard_clean.csv Rows: 13

===== Player 429/1000: 531090281 =====
Processing: 531090281 2024-05-01
No rows.
Processing: 531090281 2024-06-01
No rows.
Processing: 531090281 2024-07-01
No rows.
Processing: 531090281 2024-08-01
No rows.
Processing: 531090281 2024-09-01
No rows.
Processing: 531090281 2024-10-01
No rows.
Processing: 531090281 2024-11-01
No rows.
Processing: 531090281 2024-12-01
No rows.
Processing: 531090281 2025-01-01
No rows.
Processing: 531090281 2025-02-01
No rows.
Processing: 531090281 2025-03-01
No rows.
Processing: 531090281 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531090281_all_months_standard_clean.csv Rows: 2

===== Player 430/1000: 25972928 =====
Processing: 25972928 2024-05-01
No rows.
Processing: 25972928 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 25972928 2024-07-01
No rows.
Processing: 25972928 2024-08-01
No rows.
Processing: 25972928 2024-09-01
No rows.
Processing: 25972928 2024-10-01
No rows.
Processing: 25972928 2024-11-01
No rows.
Processing: 25972928 2024-12-01
No rows.
Processing: 25972928 2025-01-01
No rows.
Processing: 25972928 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 25972928 2025-03-01
No rows.
Processing: 25972928 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25972928_all_months_standard_clean.csv Rows: 14

===== Player 431/1000: 531084060 =====
Processing: 531084060 2024-05-01
No rows.
Processing: 531084060 2024-06-01
No rows.
Processing: 531084060 2024-07-01
No rows.
Processing: 531084060 2024-08-01
No rows.
Processing: 531084060 2024-09-01
No rows.
Processing: 531084060 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 531084060 2024-11-01
No rows.
Processing: 531084060 2024-12-01
No rows.
Processing: 531084060 2025-01-01
No rows.
Processing: 531084060 2025-02-01
No rows.
Processing: 531084060 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 531084060 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531084060_all_months_standard_clean.csv Rows: 8

===== Player 432/1000: 537023144 =====
Processing: 537023144 2024-05-01
No rows.
Processing: 537023144 2024-06-01
No rows.
Processing: 537023144 2024-07-01
No rows.
Processing: 537023144 2024-08-01
No rows.
Processing: 537023144 2024-09-01
No rows.
Processing: 537023144 2024-10-01
No rows.
Processing: 537023144 2024-11-01
No rows.
Processing: 537023144 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 537023144 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 537023144 2025-02-01
No rows.
Processing: 537023144 2025-03-01
No rows.
Processing: 537023144 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537023144_all_months_standard_clean.csv Rows: 10

===== Player 433/1000: 25995375 =====
Processing: 25995375 2024-05-01
No rows.
Processing: 25995375 2024-06-01
No rows.
Processing: 25995375 2024-07-01
No rows.
Processing: 25995375 2024-08-01
No rows.
Processing: 25995375 2024-09-01
No rows.
Processing: 25995375 2024-10-01
No rows.
Processing: 25995375 2024-11-01
No rows.
Processing: 25995375 2024-12-01
No rows.
Processing: 25995375 2025-01-01
No rows.
Processing: 25995375 2025-02-01
No rows.
Processing: 25995375 2025-03-01
No rows.
Processing: 25995375 2025-04-01
No rows.

===== Player 434/1000: 537061879 =====
Processing: 537061879 2024-05-01
No rows.
Processing: 537061879 2024-06-01
No rows.
Processing: 537061879 2024-07-01
No rows.
Processing: 537061879 2024-08-01
No rows.
Processing: 537061879 2024-09-01
No rows.
Processing: 537061879 2024-10-01
No rows.
Processing: 537061879 2024-11-01
No rows.
Processing: 537061879 2024-12-01
No rows.
Processing: 537061879 2025-01-01
No rows.
Processing: 537061879 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 537061879 2025-03-01
No rows.
Processing: 537061879 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537061879_all_months_standard_clean.csv Rows: 8

===== Player 435/1000: 33410801 =====
Processing: 33410801 2024-05-01
No rows.
Processing: 33410801 2024-06-01
No rows.
Processing: 33410801 2024-07-01
No rows.
Processing: 33410801 2024-08-01
No rows.
Processing: 33410801 2024-09-01
No rows.
Processing: 33410801 2024-10-01
No rows.
Processing: 33410801 2024-11-01
No rows.
Processing: 33410801 2024-12-01
No rows.
Processing: 33410801 2025-01-01
No rows.
Processing: 33410801 2025-02-01
No rows.
Processing: 33410801 2025-03-01
No rows.
Processing: 33410801 2025-04-01
No rows.

===== Player 436/1000: 25956256 =====
Processing: 25956256 2024-05-01
No rows.
Processing: 25956256 2024-06-01
No rows.
Processing: 25956256 2024-07-01
No rows.
Processing: 25956256 2024-08-01
No rows.
Processing: 25956256 2024-09-01
No rows.
Processing: 25956256 2024-10-01
No rows.
Processing: 25956256 2024-11-01
No rows.
Processing: 25956256 2024-12-01
No rows.
Processing: 25956256 2025-01-01
No rows.
Processing: 25956256 2025-02-01
No rows.
Processing: 25956256 2025-03-01
No rows.
Processing: 25956256 2025-04-01
No rows.

===== Player 437/1000: 558023828 =====
Processing: 558023828 2024-05-01
No rows.
Processing: 558023828 2024-06-01
No rows.
Processing: 558023828 2024-07-01
No rows.
Processing: 558023828 2024-08-01
No rows.
Processing: 558023828 2024-09-01
No rows.
Processing: 558023828 2024-10-01
No rows.
Processing: 558023828 2024-11-01
No rows.
Processing: 558023828 2024-12-01
No rows.
Processing: 558023828 2025-01-01
No rows.
Processing: 558023828 2025-02-01
No rows.
Processing: 558023828 2025-03-01
No rows.
Processing: 558023828 2025-04-01
No rows.

===== Player 438/1000: 33461910 =====
Processing: 33461910 2024-05-01
No rows.
Processing: 33461910 2024-06-01
No rows.
Processing: 33461910 2024-07-01
No rows.
Processing: 33461910 2024-08-01
No rows.
Processing: 33461910 2024-09-01
No rows.
Processing: 33461910 2024-10-01
No rows.
Processing: 33461910 2024-11-01
No rows.
Processing: 33461910 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 33461910 2025-01-01
No rows.
Processing: 33461910 2025-02-01
No rows.
Processing: 33461910 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 33461910 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33461910_all_months_standard_clean.csv Rows: 5

===== Player 439/1000: 25926497 =====
Processing: 25926497 2024-05-01
No rows.
Processing: 25926497 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 10
Processing: 25926497 2024-07-01
No rows.
Processing: 25926497 2024-08-01
No rows.
Processing: 25926497 2024-09-01
No rows.
Processing: 25926497 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 25926497 2024-11-01
No rows.
Processing: 25926497 2024-12-01
No rows.
Processing: 25926497 2025-01-01
No rows.
Processing: 25926497 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 25926497 2025-03-01
No rows.
Processing: 25926497 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25926497_all_months_standard_clean.csv Rows: 21

===== Player 440/1000: 537045385 =====
Processing: 537045385 2024-05-01
No rows.
Processing: 537045385 2024-06-01
No rows.
Processing: 537045385 2024-07-01
No rows.
Processing: 537045385 2024-08-01
No rows.
Processing: 537045385 2024-09-01
No rows.
Processing: 537045385 2024-10-01
No rows.
Processing: 537045385 2024-11-01
No rows.
Processing: 537045385 2024-12-01
No rows.
Processing: 537045385 2025-01-01
No rows.
Processing: 537045385 2025-02-01
No rows.
Processing: 537045385 2025-03-01
No rows.
Processing: 537045385 2025-04-01
No rows.

===== Player 441/1000: 537084119 =====
Processing: 537084119 2024-05-01
No rows.
Processing: 537084119 2024-06-01
No rows.
Processing: 537084119 2024-07-01
No rows.
Processing: 537084119 2024-08-01
No rows.
Processing: 537084119 2024-09-01
No rows.
Processing: 537084119 2024-10-01
No rows.
Processing: 537084119 2024-11-01
No rows.
Processing: 537084119 2024-12-01
No rows.
Processing: 537084119 2025-01-01
No rows.
Processing: 537084119 2025-02-01
No rows.
Processing: 537084119 2025-03-01
No rows.
Processing: 537084119 2025-04-01
No rows.

===== Player 442/1000: 531024246 =====
Processing: 531024246 2024-05-01
No rows.
Processing: 531024246 2024-06-01
No rows.
Processing: 531024246 2024-07-01
No rows.
Processing: 531024246 2024-08-01
No rows.
Processing: 531024246 2024-09-01
No rows.
Processing: 531024246 2024-10-01
No rows.
Processing: 531024246 2024-11-01
No rows.
Processing: 531024246 2024-12-01
No rows.
Processing: 531024246 2025-01-01
No rows.
Processing: 531024246 2025-02-01
No rows.
Processing: 531024246 2025-03-01
No rows.
Processing: 531024246 2025-04-01
No rows.

===== Player 443/1000: 25902113 =====
Processing: 25902113 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 18
Processing: 25902113 2024-06-01
No rows.
Processing: 25902113 2024-07-01
Rows: 11
Processing: 25902113 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 29
Processing: 25902113 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 20
Processing: 25902113 2024-10-01
Rows: 11
Processing: 25902113 2024-11-01
No rows.
Processing: 25902113 2024-12-01
Rows: 11
Processing: 25902113 2025-01-01
No rows.
Processing: 25902113 2025-02-01
Rows: 20
Processing: 25902113 2025-03-01
No rows.
Processing: 25902113 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25902113_all_months_standard_clean.csv Rows: 120

===== Player 444/1000: 547097752 =====
Processing: 547097752 2024-05-01
No rows.
Processing: 547097752 2024-06-01
No rows.
Processing: 547097752 2024-07-01
No rows.
Processing: 547097752 2024-08-01
No rows.
Processing: 547097752 2024-09-01
No rows.
Processing: 547097752 2024-10-01
No rows.
Processing: 547097752 2024-11-01
No rows.
Processing: 547097752 2024-12-01
No rows.
Processing: 547097752 2025-01-01
No rows.
Processing: 547097752 2025-02-01
No rows.
Processing: 547097752 2025-03-01
No rows.
Processing: 547097752 2025-04-01
No rows.

===== Player 445/1000: 45092826 =====
Processing: 45092826 2024-05-01
No rows.
Processing: 45092826 2024-06-01
No rows.
Processing: 45092826 2024-07-01
No rows.
Processing: 45092826 2024-08-01
No rows.
Processing: 45092826 2024-09-01
No rows.
Processing: 45092826 2024-10-01
No rows.
Processing: 45092826 2024-11-01
No rows.
Processing: 45092826 2024-12-01
No rows.
Processing: 45092826 2025-01-01
No rows.
Processing: 45092826 2025-02-01
No rows.
Processing: 45092826 2025-03-01
No rows.
Processing: 45092826 2025-04-01
No rows.

===== Player 446/1000: 33438013 =====
Processing: 33438013 2024-05-01
No rows.
Processing: 33438013 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 33438013 2024-07-01
No rows.
Processing: 33438013 2024-08-01
No rows.
Processing: 33438013 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 33438013 2024-10-01
No rows.
Processing: 33438013 2024-11-01
No rows.
Processing: 33438013 2024-12-01
No rows.
Processing: 33438013 2025-01-01
No rows.
Processing: 33438013 2025-02-01
No rows.
Processing: 33438013 2025-03-01
No rows.
Processing: 33438013 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33438013_all_months_standard_clean.csv Rows: 6

===== Player 447/1000: 88163350 =====
Processing: 88163350 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 88163350 2024-06-01
No rows.
Processing: 88163350 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 88163350 2024-08-01
No rows.
Processing: 88163350 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 88163350 2024-10-01
No rows.
Processing: 88163350 2024-11-01
No rows.
Processing: 88163350 2024-12-01
No rows.
Processing: 88163350 2025-01-01
No rows.
Processing: 88163350 2025-02-01
No rows.
Processing: 88163350 2025-03-01
No rows.
Processing: 88163350 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88163350_all_months_standard_clean.csv Rows: 14

===== Player 448/1000: 429094186 =====
Processing: 429094186 2024-05-01
No rows.
Processing: 429094186 2024-06-01
No rows.
Processing: 429094186 2024-07-01
No rows.
Processing: 429094186 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 429094186 2024-09-01
No rows.
Processing: 429094186 2024-10-01
No rows.
Processing: 429094186 2024-11-01
No rows.
Processing: 429094186 2024-12-01
No rows.
Processing: 429094186 2025-01-01
No rows.
Processing: 429094186 2025-02-01
No rows.
Processing: 429094186 2025-03-01
No rows.
Processing: 429094186 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429094186_all_months_standard_clean.csv Rows: 2

===== Player 449/1000: 48794813 =====
Processing: 48794813 2024-05-01
No rows.
Processing: 48794813 2024-06-01
No rows.
Processing: 48794813 2024-07-01
No rows.
Processing: 48794813 2024-08-01
No rows.
Processing: 48794813 2024-09-01
No rows.
Processing: 48794813 2024-10-01
No rows.
Processing: 48794813 2024-11-01
No rows.
Processing: 48794813 2024-12-01
No rows.
Processing: 48794813 2025-01-01
No rows.
Processing: 48794813 2025-02-01
No rows.
Processing: 48794813 2025-03-01
No rows.
Processing: 48794813 2025-04-01
No rows.

===== Player 450/1000: 33493340 =====
Processing: 33493340 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 33493340 2024-06-01
No rows.
Processing: 33493340 2024-07-01
No rows.
Processing: 33493340 2024-08-01
No rows.
Processing: 33493340 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33493340 2024-10-01
No rows.
Processing: 33493340 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 33493340 2024-12-01
No rows.
Processing: 33493340 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 34
Processing: 33493340 2025-02-01
No rows.
Processing: 33493340 2025-03-01
No rows.
Processing: 33493340 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33493340_all_months_standard_clean.csv Rows: 42

===== Player 451/1000: 537054929 =====
Processing: 537054929 2024-05-01
No rows.
Processing: 537054929 2024-06-01
No rows.
Processing: 537054929 2024-07-01
No rows.
Processing: 537054929 2024-08-01
No rows.
Processing: 537054929 2024-09-01
No rows.
Processing: 537054929 2024-10-01
No rows.
Processing: 537054929 2024-11-01
No rows.
Processing: 537054929 2024-12-01
No rows.
Processing: 537054929 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 537054929 2025-02-01
No rows.
Processing: 537054929 2025-03-01
No rows.
Processing: 537054929 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537054929_all_months_standard_clean.csv Rows: 8

===== Player 452/1000: 25786865 =====
Processing: 25786865 2024-05-01
No rows.
Processing: 25786865 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 34
Processing: 25786865 2024-07-01
No rows.
Processing: 25786865 2024-08-01
No rows.
Processing: 25786865 2024-09-01
No rows.
Processing: 25786865 2024-10-01
Rows: 8
Processing: 25786865 2024-11-01
No rows.
Processing: 25786865 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 25786865 2025-01-01
No rows.
Processing: 25786865 2025-02-01
No rows.
Processing: 25786865 2025-03-01
No rows.
Processing: 25786865 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25786865_all_months_standard_clean.csv Rows: 50

===== Player 453/1000: 531059031 =====
Processing: 531059031 2024-05-01
No rows.
Processing: 531059031 2024-06-01
No rows.
Processing: 531059031 2024-07-01
No rows.
Processing: 531059031 2024-08-01
No rows.
Processing: 531059031 2024-09-01
No rows.
Processing: 531059031 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 531059031 2024-11-01
No rows.
Processing: 531059031 2024-12-01
No rows.
Processing: 531059031 2025-01-01
No rows.
Processing: 531059031 2025-02-01
No rows.
Processing: 531059031 2025-03-01
No rows.
Processing: 531059031 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531059031_all_months_standard_clean.csv Rows: 3

===== Player 454/1000: 88155846 =====
Processing: 88155846 2024-05-01
No rows.
Processing: 88155846 2024-06-01
No rows.
Processing: 88155846 2024-07-01
No rows.
Processing: 88155846 2024-08-01
No rows.
Processing: 88155846 2024-09-01
No rows.
Processing: 88155846 2024-10-01
No rows.
Processing: 88155846 2024-11-01
No rows.
Processing: 88155846 2024-12-01
No rows.
Processing: 88155846 2025-01-01
No rows.
Processing: 88155846 2025-02-01
No rows.
Processing: 88155846 2025-03-01
No rows.
Processing: 88155846 2025-04-01
No rows.

===== Player 455/1000: 429030323 =====
Processing: 429030323 2024-05-01
No rows.
Processing: 429030323 2024-06-01
No rows.
Processing: 429030323 2024-07-01
No rows.
Processing: 429030323 2024-08-01
No rows.
Processing: 429030323 2024-09-01
No rows.
Processing: 429030323 2024-10-01
No rows.
Processing: 429030323 2024-11-01
No rows.
Processing: 429030323 2024-12-01
No rows.
Processing: 429030323 2025-01-01
No rows.
Processing: 429030323 2025-02-01
No rows.
Processing: 429030323 2025-03-01
No rows.
Processing: 429030323 2025-04-01
No rows.

===== Player 456/1000: 531033261 =====
Processing: 531033261 2024-05-01
No rows.
Processing: 531033261 2024-06-01
No rows.
Processing: 531033261 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 531033261 2024-08-01
No rows.
Processing: 531033261 2024-09-01
No rows.
Processing: 531033261 2024-10-01
No rows.
Processing: 531033261 2024-11-01
No rows.
Processing: 531033261 2024-12-01
No rows.
Processing: 531033261 2025-01-01
No rows.
Processing: 531033261 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 531033261 2025-03-01
No rows.
Processing: 531033261 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531033261_all_months_standard_clean.csv Rows: 14

===== Player 457/1000: 33490694 =====
Processing: 33490694 2024-05-01
No rows.
Processing: 33490694 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 33490694 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 33490694 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 15
Processing: 33490694 2024-09-01
No rows.
Processing: 33490694 2024-10-01
No rows.
Processing: 33490694 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 33490694 2024-12-01
No rows.
Processing: 33490694 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 14
Processing: 33490694 2025-02-01
No rows.
Processing: 33490694 2025-03-01
No rows.
Processing: 33490694 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33490694_all_months_standard_clean.csv Rows: 48

===== Player 458/1000: 48781444 =====
Processing: 48781444 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 48781444 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 48781444 2024-07-01
No rows.
Processing: 48781444 2024-08-01
No rows.
Processing: 48781444 2024-09-01
No rows.
Processing: 48781444 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 48781444 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 48781444 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 48781444 2025-01-01
No rows.
Processing: 48781444 2025-02-01
No rows.
Processing: 48781444 2025-03-01
No rows.
Processing: 48781444 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48781444_all_months_standard_clean.csv Rows: 12

===== Player 459/1000: 558014560 =====
Processing: 558014560 2024-05-01
No rows.
Processing: 558014560 2024-06-01
No rows.
Processing: 558014560 2024-07-01
No rows.
Processing: 558014560 2024-08-01
No rows.
Processing: 558014560 2024-09-01
No rows.
Processing: 558014560 2024-10-01
No rows.
Processing: 558014560 2024-11-01
No rows.
Processing: 558014560 2024-12-01
No rows.
Processing: 558014560 2025-01-01
No rows.
Processing: 558014560 2025-02-01
No rows.
Processing: 558014560 2025-03-01
No rows.
Processing: 558014560 2025-04-01
No rows.

===== Player 460/1000: 48705136 =====
Processing: 48705136 2024-05-01
No rows.
Processing: 48705136 2024-06-01
No rows.
Processing: 48705136 2024-07-01
No rows.
Processing: 48705136 2024-08-01
No rows.
Processing: 48705136 2024-09-01
No rows.
Processing: 48705136 2024-10-01
No rows.
Processing: 48705136 2024-11-01
No rows.
Processing: 48705136 2024-12-01
No rows.
Processing: 48705136 2025-01-01
No rows.
Processing: 48705136 2025-02-01
No rows.
Processing: 48705136 2025-03-01
No rows.
Processing: 48705136 2025-04-01
No rows.

===== Player 461/1000: 33396094 =====
Processing: 33396094 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 33396094 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 33396094 2024-07-01
No rows.
Processing: 33396094 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 33396094 2024-09-01
No rows.
Processing: 33396094 2024-10-01
No rows.
Processing: 33396094 2024-11-01
No rows.
Processing: 33396094 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 33396094 2025-01-01
No rows.
Processing: 33396094 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 33396094 2025-03-01
No rows.
Processing: 33396094 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33396094_all_months_standard_clean.csv Rows: 16

===== Player 462/1000: 33392978 =====
Processing: 33392978 2024-05-01
No rows.
Processing: 33392978 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 17
Processing: 33392978 2024-07-01
No rows.
Processing: 33392978 2024-08-01
No rows.
Processing: 33392978 2024-09-01
No rows.
Processing: 33392978 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33392978 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 15
Processing: 33392978 2024-12-01
No rows.
Processing: 33392978 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 10
Processing: 33392978 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 33392978 2025-03-01
No rows.
Processing: 33392978 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33392978_all_months_standard_clean.csv Rows: 53

===== Player 463/1000: 25742337 =====
Processing: 25742337 2024-05-01
No rows.
Processing: 25742337 2024-06-01
No rows.
Processing: 25742337 2024-07-01
No rows.
Processing: 25742337 2024-08-01
No rows.
Processing: 25742337 2024-09-01
No rows.
Processing: 25742337 2024-10-01
No rows.
Processing: 25742337 2024-11-01
No rows.
Processing: 25742337 2024-12-01
No rows.
Processing: 25742337 2025-01-01
No rows.
Processing: 25742337 2025-02-01
No rows.
Processing: 25742337 2025-03-01
No rows.
Processing: 25742337 2025-04-01
No rows.

===== Player 464/1000: 48741086 =====
Processing: 48741086 2024-05-01
No rows.
Processing: 48741086 2024-06-01
No rows.
Processing: 48741086 2024-07-01
No rows.
Processing: 48741086 2024-08-01
No rows.
Processing: 48741086 2024-09-01
No rows.
Processing: 48741086 2024-10-01
No rows.
Processing: 48741086 2024-11-01
No rows.
Processing: 48741086 2024-12-01
No rows.
Processing: 48741086 2025-01-01
No rows.
Processing: 48741086 2025-02-01
No rows.
Processing: 48741086 2025-03-01
No rows.
Processing: 48741086 2025-04-01
No rows.

===== Player 465/1000: 33456976 =====
Processing: 33456976 2024-05-01
No rows.
Processing: 33456976 2024-06-01
No rows.
Processing: 33456976 2024-07-01
No rows.
Processing: 33456976 2024-08-01
No rows.
Processing: 33456976 2024-09-01
No rows.
Processing: 33456976 2024-10-01
No rows.
Processing: 33456976 2024-11-01
No rows.
Processing: 33456976 2024-12-01
No rows.
Processing: 33456976 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33456976 2025-02-01
No rows.
Processing: 33456976 2025-03-01
No rows.
Processing: 33456976 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33456976_all_months_standard_clean.csv Rows: 5

===== Player 466/1000: 537023489 =====
Processing: 537023489 2024-05-01
No rows.
Processing: 537023489 2024-06-01
No rows.
Processing: 537023489 2024-07-01
No rows.
Processing: 537023489 2024-08-01
No rows.
Processing: 537023489 2024-09-01
No rows.
Processing: 537023489 2024-10-01
No rows.
Processing: 537023489 2024-11-01
No rows.
Processing: 537023489 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 537023489 2025-01-01
No rows.
Processing: 537023489 2025-02-01
No rows.
Processing: 537023489 2025-03-01
No rows.
Processing: 537023489 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537023489_all_months_standard_clean.csv Rows: 6

===== Player 467/1000: 88154408 =====
Processing: 88154408 2024-05-01
No rows.
Processing: 88154408 2024-06-01
No rows.
Processing: 88154408 2024-07-01
No rows.
Processing: 88154408 2024-08-01
No rows.
Processing: 88154408 2024-09-01
No rows.
Processing: 88154408 2024-10-01
No rows.
Processing: 88154408 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 88154408 2024-12-01
No rows.
Processing: 88154408 2025-01-01
No rows.
Processing: 88154408 2025-02-01
No rows.
Processing: 88154408 2025-03-01
No rows.
Processing: 88154408 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88154408_all_months_standard_clean.csv Rows: 4

===== Player 468/1000: 33389667 =====
Processing: 33389667 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33389667 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 14
Processing: 33389667 2024-07-01
No rows.
Processing: 33389667 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 33389667 2024-09-01
No rows.
Processing: 33389667 2024-10-01
No rows.
Processing: 33389667 2024-11-01
No rows.
Processing: 33389667 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 10
Processing: 33389667 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33389667 2025-02-01
No rows.
Processing: 33389667 2025-03-01
No rows.
Processing: 33389667 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33389667_all_months_standard_clean.csv Rows: 41

===== Player 469/1000: 531014429 =====
Processing: 531014429 2024-05-01
No rows.
Processing: 531014429 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 531014429 2024-07-01
No rows.
Processing: 531014429 2024-08-01
No rows.
Processing: 531014429 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 531014429 2024-10-01
No rows.
Processing: 531014429 2024-11-01
No rows.
Processing: 531014429 2024-12-01
No rows.
Processing: 531014429 2025-01-01
No rows.
Processing: 531014429 2025-02-01
No rows.
Processing: 531014429 2025-03-01
No rows.
Processing: 531014429 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531014429_all_months_standard_clean.csv Rows: 12

===== Player 470/1000: 33493642 =====
Processing: 33493642 2024-05-01
No rows.
Processing: 33493642 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 10
Processing: 33493642 2024-07-01
No rows.
Processing: 33493642 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 33493642 2024-09-01
No rows.
Processing: 33493642 2024-10-01
No rows.
Processing: 33493642 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 33493642 2024-12-01
No rows.
Processing: 33493642 2025-01-01
No rows.
Processing: 33493642 2025-02-01
No rows.
Processing: 33493642 2025-03-01
No rows.
Processing: 33493642 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33493642_all_months_standard_clean.csv Rows: 20

===== Player 471/1000: 537018060 =====
Processing: 537018060 2024-05-01
No rows.
Processing: 537018060 2024-06-01
No rows.
Processing: 537018060 2024-07-01
No rows.
Processing: 537018060 2024-08-01
No rows.
Processing: 537018060 2024-09-01
No rows.
Processing: 537018060 2024-10-01
No rows.
Processing: 537018060 2024-11-01
No rows.
Processing: 537018060 2024-12-01
No rows.
Processing: 537018060 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 537018060 2025-02-01
No rows.
Processing: 537018060 2025-03-01
No rows.
Processing: 537018060 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537018060_all_months_standard_clean.csv Rows: 2

===== Player 472/1000: 537085050 =====
Processing: 537085050 2024-05-01
No rows.
Processing: 537085050 2024-06-01
No rows.
Processing: 537085050 2024-07-01
No rows.
Processing: 537085050 2024-08-01
No rows.
Processing: 537085050 2024-09-01
No rows.
Processing: 537085050 2024-10-01
No rows.
Processing: 537085050 2024-11-01
No rows.
Processing: 537085050 2024-12-01
No rows.
Processing: 537085050 2025-01-01
No rows.
Processing: 537085050 2025-02-01
No rows.
Processing: 537085050 2025-03-01
No rows.
Processing: 537085050 2025-04-01
No rows.

===== Player 473/1000: 48718866 =====
Processing: 48718866 2024-05-01
No rows.
Processing: 48718866 2024-06-01
No rows.
Processing: 48718866 2024-07-01
No rows.
Processing: 48718866 2024-08-01
No rows.
Processing: 48718866 2024-09-01
No rows.
Processing: 48718866 2024-10-01
No rows.
Processing: 48718866 2024-11-01
No rows.
Processing: 48718866 2024-12-01
No rows.
Processing: 48718866 2025-01-01
No rows.
Processing: 48718866 2025-02-01
No rows.
Processing: 48718866 2025-03-01
No rows.
Processing: 48718866 2025-04-01
No rows.

===== Player 474/1000: 558094385 =====
Processing: 558094385 2024-05-01
No rows.
Processing: 558094385 2024-06-01
No rows.
Processing: 558094385 2024-07-01
No rows.
Processing: 558094385 2024-08-01
No rows.
Processing: 558094385 2024-09-01
No rows.
Processing: 558094385 2024-10-01
No rows.
Processing: 558094385 2024-11-01
No rows.
Processing: 558094385 2024-12-01
No rows.
Processing: 558094385 2025-01-01
No rows.
Processing: 558094385 2025-02-01
No rows.
Processing: 558094385 2025-03-01
No rows.
Processing: 558094385 2025-04-01
No rows.

===== Player 475/1000: 48746258 =====
Processing: 48746258 2024-05-01
No rows.
Processing: 48746258 2024-06-01
No rows.
Processing: 48746258 2024-07-01
No rows.
Processing: 48746258 2024-08-01
No rows.
Processing: 48746258 2024-09-01
No rows.
Processing: 48746258 2024-10-01
No rows.
Processing: 48746258 2024-11-01
No rows.
Processing: 48746258 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 11
Processing: 48746258 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 48746258 2025-02-01
No rows.
Processing: 48746258 2025-03-01
No rows.
Processing: 48746258 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48746258_all_months_standard_clean.csv Rows: 18

===== Player 476/1000: 25925946 =====
Processing: 25925946 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 25925946 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 25925946 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 25925946 2024-08-01
No rows.
Processing: 25925946 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 17
Processing: 25925946 2024-10-01
No rows.
Processing: 25925946 2024-11-01
No rows.
Processing: 25925946 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 25925946 2025-01-01
Rows: 19
Processing: 25925946 2025-02-01
No rows.
Processing: 25925946 2025-03-01
No rows.
Processing: 25925946 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25925946_all_months_standard_clean.csv Rows: 70

===== Player 477/1000: 25973959 =====
Processing: 25973959 2024-05-01
No rows.
Processing: 25973959 2024-06-01
No rows.
Processing: 25973959 2024-07-01
No rows.
Processing: 25973959 2024-08-01
No rows.
Processing: 25973959 2024-09-01
No rows.
Processing: 25973959 2024-10-01
No rows.
Processing: 25973959 2024-11-01
No rows.
Processing: 25973959 2024-12-01
No rows.
Processing: 25973959 2025-01-01
No rows.
Processing: 25973959 2025-02-01
No rows.
Processing: 25973959 2025-03-01
No rows.
Processing: 25973959 2025-04-01
No rows.

===== Player 478/1000: 547040831 =====
Processing: 547040831 2024-05-01
No rows.
Processing: 547040831 2024-06-01
No rows.
Processing: 547040831 2024-07-01
No rows.
Processing: 547040831 2024-08-01
No rows.
Processing: 547040831 2024-09-01
No rows.
Processing: 547040831 2024-10-01
No rows.
Processing: 547040831 2024-11-01
No rows.
Processing: 547040831 2024-12-01
No rows.
Processing: 547040831 2025-01-01
No rows.
Processing: 547040831 2025-02-01
No rows.
Processing: 547040831 2025-03-01
No rows.
Processing: 547040831 2025-04-01
No rows.

===== Player 479/1000: 537025503 =====
Processing: 537025503 2024-05-01
No rows.
Processing: 537025503 2024-06-01
No rows.
Processing: 537025503 2024-07-01
No rows.
Processing: 537025503 2024-08-01
No rows.
Processing: 537025503 2024-09-01
No rows.
Processing: 537025503 2024-10-01
No rows.
Processing: 537025503 2024-11-01
No rows.
Processing: 537025503 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 537025503 2025-01-01
No rows.
Processing: 537025503 2025-02-01
No rows.
Processing: 537025503 2025-03-01
No rows.
Processing: 537025503 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537025503_all_months_standard_clean.csv Rows: 6

===== Player 480/1000: 25988859 =====
Processing: 25988859 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 25988859 2024-06-01
No rows.
Processing: 25988859 2024-07-01
No rows.
Processing: 25988859 2024-08-01
No rows.
Processing: 25988859 2024-09-01
No rows.
Processing: 25988859 2024-10-01
No rows.
Processing: 25988859 2024-11-01
No rows.
Processing: 25988859 2024-12-01
No rows.
Processing: 25988859 2025-01-01
No rows.
Processing: 25988859 2025-02-01
No rows.
Processing: 25988859 2025-03-01
No rows.
Processing: 25988859 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25988859_all_months_standard_clean.csv Rows: 6

===== Player 481/1000: 33499152 =====
Processing: 33499152 2024-05-01
No rows.
Processing: 33499152 2024-06-01
No rows.
Processing: 33499152 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 33499152 2024-08-01
No rows.
Processing: 33499152 2024-09-01
No rows.
Processing: 33499152 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 33499152 2024-11-01
No rows.
Processing: 33499152 2024-12-01
No rows.
Processing: 33499152 2025-01-01
No rows.
Processing: 33499152 2025-02-01
No rows.
Processing: 33499152 2025-03-01
No rows.
Processing: 33499152 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33499152_all_months_standard_clean.csv Rows: 10

===== Player 482/1000: 88172406 =====
Processing: 88172406 2024-05-01
No rows.
Processing: 88172406 2024-06-01
No rows.
Processing: 88172406 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 88172406 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 88172406 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 88172406 2024-10-01
No rows.
Processing: 88172406 2024-11-01
No rows.
Processing: 88172406 2024-12-01
No rows.
Processing: 88172406 2025-01-01
No rows.
Processing: 88172406 2025-02-01
No rows.
Processing: 88172406 2025-03-01
No rows.
Processing: 88172406 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88172406_all_months_standard_clean.csv Rows: 14

===== Player 483/1000: 25972901 =====
Processing: 25972901 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 25972901 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 25972901 2024-07-01
No rows.
Processing: 25972901 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 25972901 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 25972901 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 25972901 2024-11-01
No rows.
Processing: 25972901 2024-12-01
No rows.
Processing: 25972901 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 25972901 2025-02-01
No rows.
Processing: 25972901 2025-03-01
No rows.
Processing: 25972901 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25972901_all_months_standard_clean.csv Rows: 19

===== Player 484/1000: 429030463 =====
Processing: 429030463 2024-05-01
No rows.
Processing: 429030463 2024-06-01
No rows.
Processing: 429030463 2024-07-01
No rows.
Processing: 429030463 2024-08-01
No rows.
Processing: 429030463 2024-09-01
No rows.
Processing: 429030463 2024-10-01
No rows.
Processing: 429030463 2024-11-01
No rows.
Processing: 429030463 2024-12-01
No rows.
Processing: 429030463 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 429030463 2025-02-01
No rows.
Processing: 429030463 2025-03-01
No rows.
Processing: 429030463 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429030463_all_months_standard_clean.csv Rows: 5

===== Player 485/1000: 48733555 =====
Processing: 48733555 2024-05-01
No rows.
Processing: 48733555 2024-06-01
No rows.
Processing: 48733555 2024-07-01
No rows.
Processing: 48733555 2024-08-01
No rows.
Processing: 48733555 2024-09-01
No rows.
Processing: 48733555 2024-10-01
No rows.
Processing: 48733555 2024-11-01
No rows.
Processing: 48733555 2024-12-01
No rows.
Processing: 48733555 2025-01-01
No rows.
Processing: 48733555 2025-02-01
No rows.
Processing: 48733555 2025-03-01
No rows.
Processing: 48733555 2025-04-01
No rows.

===== Player 486/1000: 33410631 =====
Processing: 33410631 2024-05-01
No rows.
Processing: 33410631 2024-06-01
No rows.
Processing: 33410631 2024-07-01
No rows.
Processing: 33410631 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 33410631 2024-09-01
No rows.
Processing: 33410631 2024-10-01
No rows.
Processing: 33410631 2024-11-01
No rows.
Processing: 33410631 2024-12-01
No rows.
Processing: 33410631 2025-01-01
No rows.
Processing: 33410631 2025-02-01
No rows.
Processing: 33410631 2025-03-01
No rows.
Processing: 33410631 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33410631_all_months_standard_clean.csv Rows: 1

===== Player 487/1000: 6011136 =====
Processing: 6011136 2024-05-01
No rows.
Processing: 6011136 2024-06-01
No rows.
Processing: 6011136 2024-07-01
No rows.
Processing: 6011136 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 6011136 2024-09-01
No rows.
Processing: 6011136 2024-10-01
No rows.
Processing: 6011136 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 6011136 2024-12-01
No rows.
Processing: 6011136 2025-01-01
No rows.
Processing: 6011136 2025-02-01
No rows.
Processing: 6011136 2025-03-01
No rows.
Processing: 6011136 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/6011136_all_months_standard_clean.csv Rows: 6

===== Player 488/1000: 558064877 =====
Processing: 558064877 2024-05-01
No rows.
Processing: 558064877 2024-06-01
No rows.
Processing: 558064877 2024-07-01
No rows.
Processing: 558064877 2024-08-01
No rows.
Processing: 558064877 2024-09-01
No rows.
Processing: 558064877 2024-10-01
No rows.
Processing: 558064877 2024-11-01
No rows.
Processing: 558064877 2024-12-01
No rows.
Processing: 558064877 2025-01-01
No rows.
Processing: 558064877 2025-02-01
No rows.
Processing: 558064877 2025-03-01
No rows.
Processing: 558064877 2025-04-01
No rows.

===== Player 489/1000: 33459061 =====
Processing: 33459061 2024-05-01
No rows.
Processing: 33459061 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 33459061 2024-07-01
No rows.
Processing: 33459061 2024-08-01
No rows.
Processing: 33459061 2024-09-01
No rows.
Processing: 33459061 2024-10-01
No rows.
Processing: 33459061 2024-11-01
No rows.
Processing: 33459061 2024-12-01
No rows.
Processing: 33459061 2025-01-01
No rows.
Processing: 33459061 2025-02-01
No rows.
Processing: 33459061 2025-03-01
No rows.
Processing: 33459061 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33459061_all_months_standard_clean.csv Rows: 4

===== Player 490/1000: 564003892 =====
Processing: 564003892 2024-05-01
No rows.
Processing: 564003892 2024-06-01
No rows.
Processing: 564003892 2024-07-01
No rows.
Processing: 564003892 2024-08-01
No rows.
Processing: 564003892 2024-09-01
No rows.
Processing: 564003892 2024-10-01
No rows.
Processing: 564003892 2024-11-01
No rows.
Processing: 564003892 2024-12-01
No rows.
Processing: 564003892 2025-01-01
No rows.
Processing: 564003892 2025-02-01
No rows.
Processing: 564003892 2025-03-01
No rows.
Processing: 564003892 2025-04-01
No rows.

===== Player 491/1000: 531013732 =====
Processing: 531013732 2024-05-01
No rows.
Processing: 531013732 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 531013732 2024-07-01
No rows.
Processing: 531013732 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 531013732 2024-09-01
No rows.
Processing: 531013732 2024-10-01
No rows.
Processing: 531013732 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 531013732 2024-12-01
No rows.
Processing: 531013732 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 10
Processing: 531013732 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 20
Processing: 531013732 2025-03-01
No rows.
Processing: 531013732 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531013732_all_months_standard_clean.csv Rows: 49

===== Player 492/1000: 547042087 =====
Processing: 547042087 2024-05-01
No rows.
Processing: 547042087 2024-06-01
No rows.
Processing: 547042087 2024-07-01
No rows.
Processing: 547042087 2024-08-01
No rows.
Processing: 547042087 2024-09-01
No rows.
Processing: 547042087 2024-10-01
No rows.
Processing: 547042087 2024-11-01
No rows.
Processing: 547042087 2024-12-01
No rows.
Processing: 547042087 2025-01-01
No rows.
Processing: 547042087 2025-02-01
No rows.
Processing: 547042087 2025-03-01
No rows.
Processing: 547042087 2025-04-01
No rows.

===== Player 493/1000: 88100421 =====
Processing: 88100421 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 88100421 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 88100421 2024-07-01
No rows.
Processing: 88100421 2024-08-01
No rows.
Processing: 88100421 2024-09-01
No rows.
Processing: 88100421 2024-10-01
No rows.
Processing: 88100421 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 88100421 2024-12-01
No rows.
Processing: 88100421 2025-01-01
No rows.
Processing: 88100421 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 88100421 2025-03-01
No rows.
Processing: 88100421 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88100421_all_months_standard_clean.csv Rows: 13

===== Player 494/1000: 33366519 =====
Processing: 33366519 2024-05-01
No rows.
Processing: 33366519 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 33366519 2024-07-01
No rows.
Processing: 33366519 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 33366519 2024-09-01
No rows.
Processing: 33366519 2024-10-01
No rows.
Processing: 33366519 2024-11-01
No rows.
Processing: 33366519 2024-12-01
No rows.
Processing: 33366519 2025-01-01
No rows.
Processing: 33366519 2025-02-01
No rows.
Processing: 33366519 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 33366519 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33366519_all_months_standard_clean.csv Rows: 8

===== Player 495/1000: 33401292 =====
Processing: 33401292 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33401292 2024-06-01
No rows.
Processing: 33401292 2024-07-01
No rows.
Processing: 33401292 2024-08-01
No rows.
Processing: 33401292 2024-09-01
No rows.
Processing: 33401292 2024-10-01
No rows.
Processing: 33401292 2024-11-01
No rows.
Processing: 33401292 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 33401292 2025-01-01
No rows.
Processing: 33401292 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 33401292 2025-03-01
No rows.
Processing: 33401292 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33401292_all_months_standard_clean.csv Rows: 14

===== Player 496/1000: 33459177 =====
Processing: 33459177 2024-05-01
No rows.
Processing: 33459177 2024-06-01
No rows.
Processing: 33459177 2024-07-01
No rows.
Processing: 33459177 2024-08-01
No rows.
Processing: 33459177 2024-09-01
No rows.
Processing: 33459177 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 33459177 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 33459177 2024-12-01
No rows.
Processing: 33459177 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 33459177 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33459177 2025-03-01
No rows.
Processing: 33459177 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33459177_all_months_standard_clean.csv Rows: 10

===== Player 497/1000: 429094178 =====
Processing: 429094178 2024-05-01
No rows.
Processing: 429094178 2024-06-01
No rows.
Processing: 429094178 2024-07-01
No rows.
Processing: 429094178 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 429094178 2024-09-01
No rows.
Processing: 429094178 2024-10-01
No rows.
Processing: 429094178 2024-11-01
No rows.
Processing: 429094178 2024-12-01
No rows.
Processing: 429094178 2025-01-01
No rows.
Processing: 429094178 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 429094178 2025-03-01
No rows.
Processing: 429094178 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429094178_all_months_standard_clean.csv Rows: 11

===== Player 498/1000: 537064282 =====
Processing: 537064282 2024-05-01
No rows.
Processing: 537064282 2024-06-01
No rows.
Processing: 537064282 2024-07-01
No rows.
Processing: 537064282 2024-08-01
No rows.
Processing: 537064282 2024-09-01
No rows.
Processing: 537064282 2024-10-01
No rows.
Processing: 537064282 2024-11-01
No rows.
Processing: 537064282 2024-12-01
No rows.
Processing: 537064282 2025-01-01
No rows.
Processing: 537064282 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 537064282 2025-03-01
No rows.
Processing: 537064282 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537064282_all_months_standard_clean.csv Rows: 7

===== Player 499/1000: 547020156 =====
Processing: 547020156 2024-05-01
No rows.
Processing: 547020156 2024-06-01
No rows.
Processing: 547020156 2024-07-01
No rows.
Processing: 547020156 2024-08-01
No rows.
Processing: 547020156 2024-09-01
No rows.
Processing: 547020156 2024-10-01
No rows.
Processing: 547020156 2024-11-01
No rows.
Processing: 547020156 2024-12-01
No rows.
Processing: 547020156 2025-01-01
No rows.
Processing: 547020156 2025-02-01
No rows.
Processing: 547020156 2025-03-01
No rows.
Processing: 547020156 2025-04-01
No rows.

===== Player 500/1000: 25177451 =====
Processing: 25177451 2024-05-01
No rows.
Processing: 25177451 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 16
Processing: 25177451 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 25177451 2024-08-01
No rows.
Processing: 25177451 2024-09-01
No rows.
Processing: 25177451 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 17
Processing: 25177451 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 11
Processing: 25177451 2024-12-01
No rows.
Processing: 25177451 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 25177451 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 17
Processing: 25177451 2025-03-01
No rows.
Processing: 25177451 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25177451_all_months_standard_clean.csv Rows: 79

===== Player 501/1000: 33482772 =====
Processing: 33482772 2024-05-01
No rows.
Processing: 33482772 2024-06-01
No rows.
Processing: 33482772 2024-07-01
No rows.
Processing: 33482772 2024-08-01
No rows.
Processing: 33482772 2024-09-01
No rows.
Processing: 33482772 2024-10-01
No rows.
Processing: 33482772 2024-11-01
No rows.
Processing: 33482772 2024-12-01
No rows.
Processing: 33482772 2025-01-01
No rows.
Processing: 33482772 2025-02-01
No rows.
Processing: 33482772 2025-03-01
No rows.
Processing: 33482772 2025-04-01
No rows.

===== Player 502/1000: 33309965 =====
Processing: 33309965 2024-05-01
No rows.
Processing: 33309965 2024-06-01
No rows.
Processing: 33309965 2024-07-01
No rows.
Processing: 33309965 2024-08-01
No rows.
Processing: 33309965 2024-09-01
No rows.
Processing: 33309965 2024-10-01
No rows.
Processing: 33309965 2024-11-01
No rows.
Processing: 33309965 2024-12-01
No rows.
Processing: 33309965 2025-01-01
No rows.
Processing: 33309965 2025-02-01
No rows.
Processing: 33309965 2025-03-01
No rows.
Processing: 33309965 2025-04-01
No rows.

===== Player 503/1000: 537055429 =====
Processing: 537055429 2024-05-01
No rows.
Processing: 537055429 2024-06-01
No rows.
Processing: 537055429 2024-07-01
No rows.
Processing: 537055429 2024-08-01
No rows.
Processing: 537055429 2024-09-01
No rows.
Processing: 537055429 2024-10-01
No rows.
Processing: 537055429 2024-11-01
No rows.
Processing: 537055429 2024-12-01
No rows.
Processing: 537055429 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 537055429 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 537055429 2025-03-01
No rows.
Processing: 537055429 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537055429_all_months_standard_clean.csv Rows: 7

===== Player 504/1000: 531023878 =====
Processing: 531023878 2024-05-01
No rows.
Processing: 531023878 2024-06-01
No rows.
Processing: 531023878 2024-07-01
No rows.
Processing: 531023878 2024-08-01
No rows.
Processing: 531023878 2024-09-01
No rows.
Processing: 531023878 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 531023878 2024-11-01
No rows.
Processing: 531023878 2024-12-01
No rows.
Processing: 531023878 2025-01-01
No rows.
Processing: 531023878 2025-02-01
No rows.
Processing: 531023878 2025-03-01
No rows.
Processing: 531023878 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531023878_all_months_standard_clean.csv Rows: 4

===== Player 505/1000: 45044384 =====
Processing: 45044384 2024-05-01
No rows.
Processing: 45044384 2024-06-01
No rows.
Processing: 45044384 2024-07-01
No rows.
Processing: 45044384 2024-08-01
No rows.
Processing: 45044384 2024-09-01
No rows.
Processing: 45044384 2024-10-01
No rows.
Processing: 45044384 2024-11-01
No rows.
Processing: 45044384 2024-12-01
No rows.
Processing: 45044384 2025-01-01
No rows.
Processing: 45044384 2025-02-01
No rows.
Processing: 45044384 2025-03-01
No rows.
Processing: 45044384 2025-04-01
No rows.

===== Player 506/1000: 537069292 =====
Processing: 537069292 2024-05-01
No rows.
Processing: 537069292 2024-06-01
No rows.
Processing: 537069292 2024-07-01
No rows.
Processing: 537069292 2024-08-01
No rows.
Processing: 537069292 2024-09-01
No rows.
Processing: 537069292 2024-10-01
No rows.
Processing: 537069292 2024-11-01
No rows.
Processing: 537069292 2024-12-01
No rows.
Processing: 537069292 2025-01-01
No rows.
Processing: 537069292 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 537069292 2025-03-01
No rows.
Processing: 537069292 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537069292_all_months_standard_clean.csv Rows: 9

===== Player 507/1000: 33415110 =====
Processing: 33415110 2024-05-01
No rows.
Processing: 33415110 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 33415110 2024-07-01
No rows.
Processing: 33415110 2024-08-01
No rows.
Processing: 33415110 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 33415110 2024-10-01
No rows.
Processing: 33415110 2024-11-01
No rows.
Processing: 33415110 2024-12-01
No rows.
Processing: 33415110 2025-01-01
No rows.
Processing: 33415110 2025-02-01
No rows.
Processing: 33415110 2025-03-01
No rows.
Processing: 33415110 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33415110_all_months_standard_clean.csv Rows: 6

===== Player 508/1000: 547071966 =====
Processing: 547071966 2024-05-01
No rows.
Processing: 547071966 2024-06-01
No rows.
Processing: 547071966 2024-07-01
No rows.
Processing: 547071966 2024-08-01
No rows.
Processing: 547071966 2024-09-01
No rows.
Processing: 547071966 2024-10-01
No rows.
Processing: 547071966 2024-11-01
No rows.
Processing: 547071966 2024-12-01
No rows.
Processing: 547071966 2025-01-01
No rows.
Processing: 547071966 2025-02-01
No rows.
Processing: 547071966 2025-03-01
No rows.
Processing: 547071966 2025-04-01
No rows.

===== Player 509/1000: 33498105 =====
Processing: 33498105 2024-05-01
Rows: 6
Processing: 33498105 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 15
Processing: 33498105 2024-07-01
No rows.
Processing: 33498105 2024-08-01
No rows.
Processing: 33498105 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33498105 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 15
Processing: 33498105 2024-11-01
No rows.
Processing: 33498105 2024-12-01
No rows.
Processing: 33498105 2025-01-01
No rows.
Processing: 33498105 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 10
Processing: 33498105 2025-03-01
No rows.
Processing: 33498105 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33498105_all_months_standard_clean.csv Rows: 54

===== Player 510/1000: 33427496 =====
Processing: 33427496 2024-05-01
No rows.
Processing: 33427496 2024-06-01
No rows.
Processing: 33427496 2024-07-01
No rows.
Processing: 33427496 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 33427496 2024-09-01
No rows.
Processing: 33427496 2024-10-01
No rows.
Processing: 33427496 2024-11-01
No rows.
Processing: 33427496 2024-12-01
No rows.
Processing: 33427496 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 33427496 2025-02-01
No rows.
Processing: 33427496 2025-03-01
No rows.
Processing: 33427496 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33427496_all_months_standard_clean.csv Rows: 9

===== Player 511/1000: 48736570 =====
Processing: 48736570 2024-05-01
No rows.
Processing: 48736570 2024-06-01
No rows.
Processing: 48736570 2024-07-01
No rows.
Processing: 48736570 2024-08-01
No rows.
Processing: 48736570 2024-09-01
No rows.
Processing: 48736570 2024-10-01
No rows.
Processing: 48736570 2024-11-01
No rows.
Processing: 48736570 2024-12-01
No rows.
Processing: 48736570 2025-01-01
No rows.
Processing: 48736570 2025-02-01
No rows.
Processing: 48736570 2025-03-01
No rows.
Processing: 48736570 2025-04-01
No rows.

===== Player 512/1000: 25749757 =====
Processing: 25749757 2024-05-01
No rows.
Processing: 25749757 2024-06-01
No rows.
Processing: 25749757 2024-07-01
No rows.
Processing: 25749757 2024-08-01
No rows.
Processing: 25749757 2024-09-01
No rows.
Processing: 25749757 2024-10-01
No rows.
Processing: 25749757 2024-11-01
No rows.
Processing: 25749757 2024-12-01
No rows.
Processing: 25749757 2025-01-01
No rows.
Processing: 25749757 2025-02-01
No rows.
Processing: 25749757 2025-03-01
No rows.
Processing: 25749757 2025-04-01
No rows.

===== Player 513/1000: 547072172 =====
Processing: 547072172 2024-05-01
No rows.
Processing: 547072172 2024-06-01
No rows.
Processing: 547072172 2024-07-01
No rows.
Processing: 547072172 2024-08-01
No rows.
Processing: 547072172 2024-09-01
No rows.
Processing: 547072172 2024-10-01
No rows.
Processing: 547072172 2024-11-01
No rows.
Processing: 547072172 2024-12-01
No rows.
Processing: 547072172 2025-01-01
No rows.
Processing: 547072172 2025-02-01
No rows.
Processing: 547072172 2025-03-01
No rows.
Processing: 547072172 2025-04-01
No rows.

===== Player 514/1000: 33408912 =====
Processing: 33408912 2024-05-01
No rows.
Processing: 33408912 2024-06-01
No rows.
Processing: 33408912 2024-07-01
No rows.
Processing: 33408912 2024-08-01
No rows.
Processing: 33408912 2024-09-01
No rows.
Processing: 33408912 2024-10-01
No rows.
Processing: 33408912 2024-11-01
No rows.
Processing: 33408912 2024-12-01
No rows.
Processing: 33408912 2025-01-01
No rows.
Processing: 33408912 2025-02-01
No rows.
Processing: 33408912 2025-03-01
No rows.
Processing: 33408912 2025-04-01
No rows.

===== Player 515/1000: 366100362 =====
Processing: 366100362 2024-05-01
No rows.
Processing: 366100362 2024-06-01
No rows.
Processing: 366100362 2024-07-01
No rows.
Processing: 366100362 2024-08-01
No rows.
Processing: 366100362 2024-09-01
No rows.
Processing: 366100362 2024-10-01
No rows.
Processing: 366100362 2024-11-01
No rows.
Processing: 366100362 2024-12-01
No rows.
Processing: 366100362 2025-01-01
No rows.
Processing: 366100362 2025-02-01
No rows.
Processing: 366100362 2025-03-01
No rows.
Processing: 366100362 2025-04-01
No rows.

===== Player 516/1000: 88159051 =====
Processing: 88159051 2024-05-01
No rows.
Processing: 88159051 2024-06-01
No rows.
Processing: 88159051 2024-07-01
No rows.
Processing: 88159051 2024-08-01
No rows.
Processing: 88159051 2024-09-01
No rows.
Processing: 88159051 2024-10-01
No rows.
Processing: 88159051 2024-11-01
No rows.
Processing: 88159051 2024-12-01
No rows.
Processing: 88159051 2025-01-01
No rows.
Processing: 88159051 2025-02-01
No rows.
Processing: 88159051 2025-03-01
No rows.
Processing: 88159051 2025-04-01
No rows.

===== Player 517/1000: 558065601 =====
Processing: 558065601 2024-05-01
No rows.
Processing: 558065601 2024-06-01
No rows.
Processing: 558065601 2024-07-01
No rows.
Processing: 558065601 2024-08-01
No rows.
Processing: 558065601 2024-09-01
No rows.
Processing: 558065601 2024-10-01
No rows.
Processing: 558065601 2024-11-01
No rows.
Processing: 558065601 2024-12-01
No rows.
Processing: 558065601 2025-01-01
No rows.
Processing: 558065601 2025-02-01
No rows.
Processing: 558065601 2025-03-01
No rows.
Processing: 558065601 2025-04-01
No rows.

===== Player 518/1000: 531039103 =====
Processing: 531039103 2024-05-01
No rows.
Processing: 531039103 2024-06-01
No rows.
Processing: 531039103 2024-07-01
No rows.
Processing: 531039103 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 531039103 2024-09-01
No rows.
Processing: 531039103 2024-10-01
No rows.
Processing: 531039103 2024-11-01
No rows.
Processing: 531039103 2024-12-01
No rows.
Processing: 531039103 2025-01-01
No rows.
Processing: 531039103 2025-02-01
No rows.
Processing: 531039103 2025-03-01
No rows.
Processing: 531039103 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531039103_all_months_standard_clean.csv Rows: 6

===== Player 519/1000: 48721506 =====
Processing: 48721506 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 48721506 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 15
Processing: 48721506 2024-07-01
No rows.
Processing: 48721506 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 48721506 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 15
Processing: 48721506 2024-10-01
No rows.
Processing: 48721506 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 48721506 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 11
Processing: 48721506 2025-01-01
Rows: 9
Processing: 48721506 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 18
Processing: 48721506 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 48721506 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48721506_all_months_standard_clean.csv Rows: 107

===== Player 520/1000: 25976826 =====
Processing: 25976826 2024-05-01
No rows.
Processing: 25976826 2024-06-01
No rows.
Processing: 25976826 2024-07-01
No rows.
Processing: 25976826 2024-08-01
No rows.
Processing: 25976826 2024-09-01
No rows.
Processing: 25976826 2024-10-01
No rows.
Processing: 25976826 2024-11-01
No rows.
Processing: 25976826 2024-12-01
No rows.
Processing: 25976826 2025-01-01
No rows.
Processing: 25976826 2025-02-01
No rows.
Processing: 25976826 2025-03-01
No rows.
Processing: 25976826 2025-04-01
No rows.

===== Player 521/1000: 33409153 =====
Processing: 33409153 2024-05-01
No rows.
Processing: 33409153 2024-06-01
No rows.
Processing: 33409153 2024-07-01
No rows.
Processing: 33409153 2024-08-01
No rows.
Processing: 33409153 2024-09-01
No rows.
Processing: 33409153 2024-10-01
No rows.
Processing: 33409153 2024-11-01
No rows.
Processing: 33409153 2024-12-01
No rows.
Processing: 33409153 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33409153 2025-02-01
No rows.
Processing: 33409153 2025-03-01
No rows.
Processing: 33409153 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33409153_all_months_standard_clean.csv Rows: 5

===== Player 522/1000: 48731960 =====
Processing: 48731960 2024-05-01
No rows.
Processing: 48731960 2024-06-01
No rows.
Processing: 48731960 2024-07-01
No rows.
Processing: 48731960 2024-08-01
No rows.
Processing: 48731960 2024-09-01
No rows.
Processing: 48731960 2024-10-01
No rows.
Processing: 48731960 2024-11-01
No rows.
Processing: 48731960 2024-12-01
No rows.
Processing: 48731960 2025-01-01
No rows.
Processing: 48731960 2025-02-01
No rows.
Processing: 48731960 2025-03-01
No rows.
Processing: 48731960 2025-04-01
No rows.

===== Player 523/1000: 33394199 =====
Processing: 33394199 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 33394199 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 33394199 2024-07-01
No rows.
Processing: 33394199 2024-08-01
No rows.
Processing: 33394199 2024-09-01
No rows.
Processing: 33394199 2024-10-01
No rows.
Processing: 33394199 2024-11-01
No rows.
Processing: 33394199 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33394199 2025-01-01
No rows.
Processing: 33394199 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 33394199 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33394199 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33394199_all_months_standard_clean.csv Rows: 33

===== Player 524/1000: 25931130 =====
Processing: 25931130 2024-05-01
No rows.
Processing: 25931130 2024-06-01
No rows.
Processing: 25931130 2024-07-01
No rows.
Processing: 25931130 2024-08-01
No rows.
Processing: 25931130 2024-09-01
No rows.
Processing: 25931130 2024-10-01
No rows.
Processing: 25931130 2024-11-01
No rows.
Processing: 25931130 2024-12-01
No rows.
Processing: 25931130 2025-01-01
No rows.
Processing: 25931130 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 25931130 2025-03-01
No rows.
Processing: 25931130 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25931130_all_months_standard_clean.csv Rows: 4

===== Player 525/1000: 531067565 =====
Processing: 531067565 2024-05-01
No rows.
Processing: 531067565 2024-06-01
No rows.
Processing: 531067565 2024-07-01
No rows.
Processing: 531067565 2024-08-01
No rows.
Processing: 531067565 2024-09-01
No rows.
Processing: 531067565 2024-10-01
No rows.
Processing: 531067565 2024-11-01
No rows.
Processing: 531067565 2024-12-01
No rows.
Processing: 531067565 2025-01-01
No rows.
Processing: 531067565 2025-02-01
No rows.
Processing: 531067565 2025-03-01
No rows.
Processing: 531067565 2025-04-01
No rows.

===== Player 526/1000: 88130533 =====
Processing: 88130533 2024-05-01
No rows.
Processing: 88130533 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 88130533 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 88130533 2024-08-01
No rows.
Processing: 88130533 2024-09-01
No rows.
Processing: 88130533 2024-10-01
No rows.
Processing: 88130533 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 88130533 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 88130533 2025-01-01
No rows.
Processing: 88130533 2025-02-01
No rows.
Processing: 88130533 2025-03-01
No rows.
Processing: 88130533 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88130533_all_months_standard_clean.csv Rows: 34

===== Player 527/1000: 25986341 =====
Processing: 25986341 2024-05-01
No rows.
Processing: 25986341 2024-06-01
No rows.
Processing: 25986341 2024-07-01
No rows.
Processing: 25986341 2024-08-01
No rows.
Processing: 25986341 2024-09-01
No rows.
Processing: 25986341 2024-10-01
No rows.
Processing: 25986341 2024-11-01
No rows.
Processing: 25986341 2024-12-01
No rows.
Processing: 25986341 2025-01-01
No rows.
Processing: 25986341 2025-02-01
No rows.
Processing: 25986341 2025-03-01
No rows.
Processing: 25986341 2025-04-01
No rows.

===== Player 528/1000: 25682091 =====
Processing: 25682091 2024-05-01
No rows.
Processing: 25682091 2024-06-01
No rows.
Processing: 25682091 2024-07-01
No rows.
Processing: 25682091 2024-08-01
No rows.
Processing: 25682091 2024-09-01
No rows.
Processing: 25682091 2024-10-01
No rows.
Processing: 25682091 2024-11-01
No rows.
Processing: 25682091 2024-12-01
No rows.
Processing: 25682091 2025-01-01
No rows.
Processing: 25682091 2025-02-01
No rows.
Processing: 25682091 2025-03-01
No rows.
Processing: 25682091 2025-04-01
No rows.

===== Player 529/1000: 25110462 =====
Processing: 25110462 2024-05-01
No rows.
Processing: 25110462 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 25110462 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 25110462 2024-08-01
No rows.
Processing: 25110462 2024-09-01
No rows.
Processing: 25110462 2024-10-01
No rows.
Processing: 25110462 2024-11-01
No rows.
Processing: 25110462 2024-12-01
No rows.
Processing: 25110462 2025-01-01
No rows.
Processing: 25110462 2025-02-01
No rows.
Processing: 25110462 2025-03-01
No rows.
Processing: 25110462 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25110462_all_months_standard_clean.csv Rows: 9

===== Player 530/1000: 25116533 =====
Processing: 25116533 2024-05-01
No rows.
Processing: 25116533 2024-06-01
No rows.
Processing: 25116533 2024-07-01
No rows.
Processing: 25116533 2024-08-01
No rows.
Processing: 25116533 2024-09-01
No rows.
Processing: 25116533 2024-10-01
No rows.
Processing: 25116533 2024-11-01
No rows.
Processing: 25116533 2024-12-01
No rows.
Processing: 25116533 2025-01-01
No rows.
Processing: 25116533 2025-02-01
No rows.
Processing: 25116533 2025-03-01
No rows.
Processing: 25116533 2025-04-01
No rows.

===== Player 531/1000: 531065589 =====
Processing: 531065589 2024-05-01
No rows.
Processing: 531065589 2024-06-01
No rows.
Processing: 531065589 2024-07-01
No rows.
Processing: 531065589 2024-08-01
No rows.
Processing: 531065589 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 531065589 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 531065589 2024-11-01
No rows.
Processing: 531065589 2024-12-01
No rows.
Processing: 531065589 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 531065589 2025-02-01
No rows.
Processing: 531065589 2025-03-01
No rows.
Processing: 531065589 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531065589_all_months_standard_clean.csv Rows: 9

===== Player 532/1000: 88179788 =====
Processing: 88179788 2024-05-01
No rows.
Processing: 88179788 2024-06-01
No rows.
Processing: 88179788 2024-07-01
No rows.
Processing: 88179788 2024-08-01
No rows.
Processing: 88179788 2024-09-01
No rows.
Processing: 88179788 2024-10-01
No rows.
Processing: 88179788 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 88179788 2024-12-01
No rows.
Processing: 88179788 2025-01-01
No rows.
Processing: 88179788 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 88179788 2025-03-01
No rows.
Processing: 88179788 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88179788_all_months_standard_clean.csv Rows: 9

===== Player 533/1000: 25158570 =====
Processing: 25158570 2024-05-01
No rows.
Processing: 25158570 2024-06-01
No rows.
Processing: 25158570 2024-07-01
No rows.
Processing: 25158570 2024-08-01
No rows.
Processing: 25158570 2024-09-01
No rows.
Processing: 25158570 2024-10-01
No rows.
Processing: 25158570 2024-11-01
No rows.
Processing: 25158570 2024-12-01
No rows.
Processing: 25158570 2025-01-01
No rows.
Processing: 25158570 2025-02-01
No rows.
Processing: 25158570 2025-03-01
No rows.
Processing: 25158570 2025-04-01
No rows.

===== Player 534/1000: 564062805 =====
Processing: 564062805 2024-05-01
No rows.
Processing: 564062805 2024-06-01
No rows.
Processing: 564062805 2024-07-01
No rows.
Processing: 564062805 2024-08-01
No rows.
Processing: 564062805 2024-09-01
No rows.
Processing: 564062805 2024-10-01
No rows.
Processing: 564062805 2024-11-01
No rows.
Processing: 564062805 2024-12-01
No rows.
Processing: 564062805 2025-01-01
No rows.
Processing: 564062805 2025-02-01
No rows.
Processing: 564062805 2025-03-01
No rows.
Processing: 564062805 2025-04-01
No rows.

===== Player 535/1000: 33491917 =====
Processing: 33491917 2024-05-01
No rows.
Processing: 33491917 2024-06-01
Rows: 16
Processing: 33491917 2024-07-01
No rows.
Processing: 33491917 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 33491917 2024-09-01
No rows.
Processing: 33491917 2024-10-01
No rows.
Processing: 33491917 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 20
Processing: 33491917 2024-12-01
No rows.
Processing: 33491917 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 10
Processing: 33491917 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 19
Processing: 33491917 2025-03-01
No rows.
Processing: 33491917 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33491917_all_months_standard_clean.csv Rows: 74

===== Player 536/1000: 531059708 =====
Processing: 531059708 2024-05-01
No rows.
Processing: 531059708 2024-06-01
No rows.
Processing: 531059708 2024-07-01
No rows.
Processing: 531059708 2024-08-01
No rows.
Processing: 531059708 2024-09-01
No rows.
Processing: 531059708 2024-10-01
No rows.
Processing: 531059708 2024-11-01
No rows.
Processing: 531059708 2024-12-01
No rows.
Processing: 531059708 2025-01-01
No rows.
Processing: 531059708 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 531059708 2025-03-01
No rows.
Processing: 531059708 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531059708_all_months_standard_clean.csv Rows: 5

===== Player 537/1000: 48724963 =====
Processing: 48724963 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 48724963 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 48724963 2024-07-01
No rows.
Processing: 48724963 2024-08-01
No rows.
Processing: 48724963 2024-09-01
No rows.
Processing: 48724963 2024-10-01
No rows.
Processing: 48724963 2024-11-01
No rows.
Processing: 48724963 2024-12-01
No rows.
Processing: 48724963 2025-01-01
No rows.
Processing: 48724963 2025-02-01
No rows.
Processing: 48724963 2025-03-01
No rows.
Processing: 48724963 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48724963_all_months_standard_clean.csv Rows: 11

===== Player 538/1000: 33484724 =====
Processing: 33484724 2024-05-01
No rows.
Processing: 33484724 2024-06-01
No rows.
Processing: 33484724 2024-07-01
No rows.
Processing: 33484724 2024-08-01
No rows.
Processing: 33484724 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33484724 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 12
Processing: 33484724 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 33484724 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 33484724 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 33484724 2025-02-01
No rows.
Processing: 33484724 2025-03-01
No rows.
Processing: 33484724 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33484724_all_months_standard_clean.csv Rows: 42

===== Player 539/1000: 531003737 =====
Processing: 531003737 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 531003737 2024-06-01
No rows.
Processing: 531003737 2024-07-01
No rows.
Processing: 531003737 2024-08-01
No rows.
Processing: 531003737 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 531003737 2024-10-01
No rows.
Processing: 531003737 2024-11-01
No rows.
Processing: 531003737 2024-12-01
No rows.
Processing: 531003737 2025-01-01
No rows.
Processing: 531003737 2025-02-01
No rows.
Processing: 531003737 2025-03-01
No rows.
Processing: 531003737 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531003737_all_months_standard_clean.csv Rows: 6

===== Player 540/1000: 531054137 =====
Processing: 531054137 2024-05-01
No rows.
Processing: 531054137 2024-06-01
No rows.
Processing: 531054137 2024-07-01
No rows.
Processing: 531054137 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 531054137 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 531054137 2024-10-01
No rows.
Processing: 531054137 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 531054137 2024-12-01
No rows.
Processing: 531054137 2025-01-01
No rows.
Processing: 531054137 2025-02-01
No rows.
Processing: 531054137 2025-03-01
No rows.
Processing: 531054137 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531054137_all_months_standard_clean.csv Rows: 7

===== Player 541/1000: 33479410 =====
Processing: 33479410 2024-05-01
No rows.
Processing: 33479410 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 33479410 2024-07-01
No rows.
Processing: 33479410 2024-08-01
No rows.
Processing: 33479410 2024-09-01
No rows.
Processing: 33479410 2024-10-01
No rows.
Processing: 33479410 2024-11-01
No rows.
Processing: 33479410 2024-12-01
No rows.
Processing: 33479410 2025-01-01
No rows.
Processing: 33479410 2025-02-01
No rows.
Processing: 33479410 2025-03-01
No rows.
Processing: 33479410 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33479410_all_months_standard_clean.csv Rows: 3

===== Player 542/1000: 531088287 =====
Processing: 531088287 2024-05-01
No rows.
Processing: 531088287 2024-06-01
No rows.
Processing: 531088287 2024-07-01
No rows.
Processing: 531088287 2024-08-01
No rows.
Processing: 531088287 2024-09-01
No rows.
Processing: 531088287 2024-10-01
No rows.
Processing: 531088287 2024-11-01
No rows.
Processing: 531088287 2024-12-01
No rows.
Processing: 531088287 2025-01-01
No rows.
Processing: 531088287 2025-02-01
No rows.
Processing: 531088287 2025-03-01
No rows.
Processing: 531088287 2025-04-01
No rows.

===== Player 543/1000: 558067418 =====
Processing: 558067418 2024-05-01
No rows.
Processing: 558067418 2024-06-01
No rows.
Processing: 558067418 2024-07-01
No rows.
Processing: 558067418 2024-08-01
No rows.
Processing: 558067418 2024-09-01
No rows.
Processing: 558067418 2024-10-01
No rows.
Processing: 558067418 2024-11-01
No rows.
Processing: 558067418 2024-12-01
No rows.
Processing: 558067418 2025-01-01
No rows.
Processing: 558067418 2025-02-01
No rows.
Processing: 558067418 2025-03-01
No rows.
Processing: 558067418 2025-04-01
No rows.

===== Player 544/1000: 537069020 =====
Processing: 537069020 2024-05-01
No rows.
Processing: 537069020 2024-06-01
No rows.
Processing: 537069020 2024-07-01
No rows.
Processing: 537069020 2024-08-01
No rows.
Processing: 537069020 2024-09-01
No rows.
Processing: 537069020 2024-10-01
No rows.
Processing: 537069020 2024-11-01
No rows.
Processing: 537069020 2024-12-01
No rows.
Processing: 537069020 2025-01-01
No rows.
Processing: 537069020 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 537069020 2025-03-01
No rows.
Processing: 537069020 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537069020_all_months_standard_clean.csv Rows: 4

===== Player 545/1000: 33428891 =====
Processing: 33428891 2024-05-01
No rows.
Processing: 33428891 2024-06-01
No rows.
Processing: 33428891 2024-07-01
No rows.
Processing: 33428891 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33428891 2024-09-01
No rows.
Processing: 33428891 2024-10-01
No rows.
Processing: 33428891 2024-11-01
No rows.
Processing: 33428891 2024-12-01
No rows.
Processing: 33428891 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 33428891 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33428891 2025-03-01
No rows.
Processing: 33428891 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33428891_all_months_standard_clean.csv Rows: 16

===== Player 546/1000: 547078405 =====
Processing: 547078405 2024-05-01
No rows.
Processing: 547078405 2024-06-01
No rows.
Processing: 547078405 2024-07-01
No rows.
Processing: 547078405 2024-08-01
No rows.
Processing: 547078405 2024-09-01
No rows.
Processing: 547078405 2024-10-01
No rows.
Processing: 547078405 2024-11-01
No rows.
Processing: 547078405 2024-12-01
No rows.
Processing: 547078405 2025-01-01
No rows.
Processing: 547078405 2025-02-01
No rows.
Processing: 547078405 2025-03-01
No rows.
Processing: 547078405 2025-04-01
No rows.

===== Player 547/1000: 33412588 =====
Processing: 33412588 2024-05-01
No rows.
Processing: 33412588 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 33412588 2024-07-01
No rows.
Processing: 33412588 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33412588 2024-09-01
No rows.
Processing: 33412588 2024-10-01
No rows.
Processing: 33412588 2024-11-01
No rows.
Processing: 33412588 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 33412588 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 33412588 2025-02-01
No rows.
Processing: 33412588 2025-03-01
No rows.
Processing: 33412588 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33412588_all_months_standard_clean.csv Rows: 19

===== Player 548/1000: 531064442 =====
Processing: 531064442 2024-05-01
No rows.
Processing: 531064442 2024-06-01
No rows.
Processing: 531064442 2024-07-01
No rows.
Processing: 531064442 2024-08-01
No rows.
Processing: 531064442 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 531064442 2024-10-01
No rows.
Processing: 531064442 2024-11-01
No rows.
Processing: 531064442 2024-12-01
No rows.
Processing: 531064442 2025-01-01
No rows.
Processing: 531064442 2025-02-01
No rows.
Processing: 531064442 2025-03-01
No rows.
Processing: 531064442 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531064442_all_months_standard_clean.csv Rows: 4

===== Player 549/1000: 33448990 =====
Processing: 33448990 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 33448990 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 15
Processing: 33448990 2024-07-01
Rows: 9
Processing: 33448990 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33448990 2024-09-01
Rows: 9
Processing: 33448990 2024-10-01
No rows.
Processing: 33448990 2024-11-01
Rows: 8
Processing: 33448990 2024-12-01
No rows.
Processing: 33448990 2025-01-01
No rows.
Processing: 33448990 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 19
Processing: 33448990 2025-03-01
No rows.
Processing: 33448990 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33448990_all_months_standard_clean.csv Rows: 75

===== Player 550/1000: 531078800 =====
Processing: 531078800 2024-05-01
No rows.
Processing: 531078800 2024-06-01
No rows.
Processing: 531078800 2024-07-01
No rows.
Processing: 531078800 2024-08-01
No rows.
Processing: 531078800 2024-09-01
No rows.
Processing: 531078800 2024-10-01
No rows.
Processing: 531078800 2024-11-01
No rows.
Processing: 531078800 2024-12-01
No rows.
Processing: 531078800 2025-01-01
No rows.
Processing: 531078800 2025-02-01
No rows.
Processing: 531078800 2025-03-01
No rows.
Processing: 531078800 2025-04-01
No rows.

===== Player 551/1000: 33363692 =====
Processing: 33363692 2024-05-01
No rows.
Processing: 33363692 2024-06-01
No rows.
Processing: 33363692 2024-07-01
No rows.
Processing: 33363692 2024-08-01
No rows.
Processing: 33363692 2024-09-01
No rows.
Processing: 33363692 2024-10-01
No rows.
Processing: 33363692 2024-11-01
No rows.
Processing: 33363692 2024-12-01
No rows.
Processing: 33363692 2025-01-01
No rows.
Processing: 33363692 2025-02-01
No rows.
Processing: 33363692 2025-03-01
No rows.
Processing: 33363692 2025-04-01
No rows.

===== Player 552/1000: 48763039 =====
Processing: 48763039 2024-05-01
No rows.
Processing: 48763039 2024-06-01
No rows.
Processing: 48763039 2024-07-01
No rows.
Processing: 48763039 2024-08-01
No rows.
Processing: 48763039 2024-09-01
No rows.
Processing: 48763039 2024-10-01
No rows.
Processing: 48763039 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 48763039 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 48763039 2025-01-01
No rows.
Processing: 48763039 2025-02-01
No rows.
Processing: 48763039 2025-03-01
No rows.
Processing: 48763039 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48763039_all_months_standard_clean.csv Rows: 11

===== Player 553/1000: 429001196 =====
Processing: 429001196 2024-05-01
No rows.
Processing: 429001196 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 429001196 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 429001196 2024-08-01
No rows.
Processing: 429001196 2024-09-01
No rows.
Processing: 429001196 2024-10-01
No rows.
Processing: 429001196 2024-11-01
No rows.
Processing: 429001196 2024-12-01
No rows.
Processing: 429001196 2025-01-01
No rows.
Processing: 429001196 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 429001196 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 429001196 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429001196_all_months_standard_clean.csv Rows: 31

===== Player 554/1000: 25112554 =====
Processing: 25112554 2024-05-01
No rows.
Processing: 25112554 2024-06-01
No rows.
Processing: 25112554 2024-07-01
No rows.
Processing: 25112554 2024-08-01
No rows.
Processing: 25112554 2024-09-01
No rows.
Processing: 25112554 2024-10-01
No rows.
Processing: 25112554 2024-11-01
No rows.
Processing: 25112554 2024-12-01
No rows.
Processing: 25112554 2025-01-01
No rows.
Processing: 25112554 2025-02-01
No rows.
Processing: 25112554 2025-03-01
No rows.
Processing: 25112554 2025-04-01
No rows.

===== Player 555/1000: 88174468 =====
Processing: 88174468 2024-05-01
No rows.
Processing: 88174468 2024-06-01
No rows.
Processing: 88174468 2024-07-01
No rows.
Processing: 88174468 2024-08-01
No rows.
Processing: 88174468 2024-09-01
No rows.
Processing: 88174468 2024-10-01
No rows.
Processing: 88174468 2024-11-01
No rows.
Processing: 88174468 2024-12-01
No rows.
Processing: 88174468 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 88174468 2025-02-01
No rows.
Processing: 88174468 2025-03-01
No rows.
Processing: 88174468 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88174468_all_months_standard_clean.csv Rows: 9

===== Player 556/1000: 531025080 =====
Processing: 531025080 2024-05-01
No rows.
Processing: 531025080 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 531025080 2024-07-01
No rows.
Processing: 531025080 2024-08-01
No rows.
Processing: 531025080 2024-09-01
No rows.
Processing: 531025080 2024-10-01
No rows.
Processing: 531025080 2024-11-01
No rows.
Processing: 531025080 2024-12-01
No rows.
Processing: 531025080 2025-01-01
No rows.
Processing: 531025080 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 531025080 2025-03-01
No rows.
Processing: 531025080 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531025080_all_months_standard_clean.csv Rows: 16

===== Player 557/1000: 429017904 =====
Processing: 429017904 2024-05-01
No rows.
Processing: 429017904 2024-06-01
No rows.
Processing: 429017904 2024-07-01
No rows.
Processing: 429017904 2024-08-01
No rows.
Processing: 429017904 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 429017904 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 429017904 2024-11-01
No rows.
Processing: 429017904 2024-12-01
No rows.
Processing: 429017904 2025-01-01
No rows.
Processing: 429017904 2025-02-01
No rows.
Processing: 429017904 2025-03-01
No rows.
Processing: 429017904 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429017904_all_months_standard_clean.csv Rows: 5

===== Player 558/1000: 25647610 =====
Processing: 25647610 2024-05-01
No rows.
Processing: 25647610 2024-06-01
No rows.
Processing: 25647610 2024-07-01
No rows.
Processing: 25647610 2024-08-01
No rows.
Processing: 25647610 2024-09-01
No rows.
Processing: 25647610 2024-10-01
No rows.
Processing: 25647610 2024-11-01
No rows.
Processing: 25647610 2024-12-01
No rows.
Processing: 25647610 2025-01-01
No rows.
Processing: 25647610 2025-02-01
No rows.
Processing: 25647610 2025-03-01
No rows.
Processing: 25647610 2025-04-01
No rows.

===== Player 559/1000: 558070753 =====
Processing: 558070753 2024-05-01
No rows.
Processing: 558070753 2024-06-01
No rows.
Processing: 558070753 2024-07-01
No rows.
Processing: 558070753 2024-08-01
No rows.
Processing: 558070753 2024-09-01
No rows.
Processing: 558070753 2024-10-01
No rows.
Processing: 558070753 2024-11-01
No rows.
Processing: 558070753 2024-12-01
No rows.
Processing: 558070753 2025-01-01
No rows.
Processing: 558070753 2025-02-01
No rows.
Processing: 558070753 2025-03-01
No rows.
Processing: 558070753 2025-04-01
No rows.

===== Player 560/1000: 558043381 =====
Processing: 558043381 2024-05-01
No rows.
Processing: 558043381 2024-06-01
No rows.
Processing: 558043381 2024-07-01
No rows.
Processing: 558043381 2024-08-01
No rows.
Processing: 558043381 2024-09-01
No rows.
Processing: 558043381 2024-10-01
No rows.
Processing: 558043381 2024-11-01
No rows.
Processing: 558043381 2024-12-01
No rows.
Processing: 558043381 2025-01-01
No rows.
Processing: 558043381 2025-02-01
No rows.
Processing: 558043381 2025-03-01
No rows.
Processing: 558043381 2025-04-01
No rows.

===== Player 561/1000: 531003745 =====
Processing: 531003745 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 531003745 2024-06-01
No rows.
Processing: 531003745 2024-07-01
No rows.
Processing: 531003745 2024-08-01
No rows.
Processing: 531003745 2024-09-01
No rows.
Processing: 531003745 2024-10-01
No rows.
Processing: 531003745 2024-11-01
No rows.
Processing: 531003745 2024-12-01
No rows.
Processing: 531003745 2025-01-01
No rows.
Processing: 531003745 2025-02-01
No rows.
Processing: 531003745 2025-03-01
No rows.
Processing: 531003745 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531003745_all_months_standard_clean.csv Rows: 3

===== Player 562/1000: 33329664 =====
Processing: 33329664 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 18
Processing: 33329664 2024-06-01
Rows: 17
Processing: 33329664 2024-07-01
No rows.
Processing: 33329664 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 33329664 2024-09-01
Rows: 8
Processing: 33329664 2024-10-01
No rows.
Processing: 33329664 2024-11-01
No rows.
Processing: 33329664 2024-12-01
No rows.
Processing: 33329664 2025-01-01
Rows: 16
Processing: 33329664 2025-02-01
No rows.
Processing: 33329664 2025-03-01
No rows.
Processing: 33329664 2025-04-01
Rows: 18
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33329664_all_months_standard_clean.csv Rows: 84

===== Player 563/1000: 531044018 =====
Processing: 531044018 2024-05-01
No rows.
Processing: 531044018 2024-06-01
No rows.
Processing: 531044018 2024-07-01
No rows.
Processing: 531044018 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 531044018 2024-09-01
No rows.
Processing: 531044018 2024-10-01
No rows.
Processing: 531044018 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 531044018 2024-12-01
No rows.
Processing: 531044018 2025-01-01
No rows.
Processing: 531044018 2025-02-01
No rows.
Processing: 531044018 2025-03-01
No rows.
Processing: 531044018 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531044018_all_months_standard_clean.csv Rows: 10

===== Player 564/1000: 531085377 =====
Processing: 531085377 2024-05-01
No rows.
Processing: 531085377 2024-06-01
No rows.
Processing: 531085377 2024-07-01
No rows.
Processing: 531085377 2024-08-01
No rows.
Processing: 531085377 2024-09-01
No rows.
Processing: 531085377 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 531085377 2024-11-01
No rows.
Processing: 531085377 2024-12-01
No rows.
Processing: 531085377 2025-01-01
No rows.
Processing: 531085377 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 531085377 2025-03-01
No rows.
Processing: 531085377 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531085377_all_months_standard_clean.csv Rows: 5

===== Player 565/1000: 33482217 =====
Processing: 33482217 2024-05-01
No rows.
Processing: 33482217 2024-06-01
No rows.
Processing: 33482217 2024-07-01
No rows.
Processing: 33482217 2024-08-01
No rows.
Processing: 33482217 2024-09-01
No rows.
Processing: 33482217 2024-10-01
No rows.
Processing: 33482217 2024-11-01
No rows.
Processing: 33482217 2024-12-01
No rows.
Processing: 33482217 2025-01-01
No rows.
Processing: 33482217 2025-02-01
No rows.
Processing: 33482217 2025-03-01
No rows.
Processing: 33482217 2025-04-01
No rows.

===== Player 566/1000: 88150674 =====
Processing: 88150674 2024-05-01
No rows.
Processing: 88150674 2024-06-01
No rows.
Processing: 88150674 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 88150674 2024-08-01
No rows.
Processing: 88150674 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 88150674 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 88150674 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 88150674 2024-12-01
No rows.
Processing: 88150674 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 88150674 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 88150674 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 88150674 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88150674_all_months_standard_clean.csv Rows: 36

===== Player 567/1000: 25771280 =====
Processing: 25771280 2024-05-01
Rows: 18
Processing: 25771280 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 25771280 2024-07-01
Rows: 11
Processing: 25771280 2024-08-01
No rows.
Processing: 25771280 2024-09-01
Rows: 11
Processing: 25771280 2024-10-01
Rows: 20
Processing: 25771280 2024-11-01
No rows.
Processing: 25771280 2024-12-01
Rows: 11
Processing: 25771280 2025-01-01
Rows: 20
Processing: 25771280 2025-02-01
Rows: 9
Processing: 25771280 2025-03-01
No rows.
Processing: 25771280 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25771280_all_months_standard_clean.csv Rows: 108

===== Player 568/1000: 25761390 =====
Processing: 25761390 2024-05-01
No rows.
Processing: 25761390 2024-06-01
No rows.
Processing: 25761390 2024-07-01
No rows.
Processing: 25761390 2024-08-01
No rows.
Processing: 25761390 2024-09-01
No rows.
Processing: 25761390 2024-10-01
No rows.
Processing: 25761390 2024-11-01
No rows.
Processing: 25761390 2024-12-01
No rows.
Processing: 25761390 2025-01-01
No rows.
Processing: 25761390 2025-02-01
No rows.
Processing: 25761390 2025-03-01
No rows.
Processing: 25761390 2025-04-01
No rows.

===== Player 569/1000: 537095838 =====
Processing: 537095838 2024-05-01
No rows.
Processing: 537095838 2024-06-01
No rows.
Processing: 537095838 2024-07-01
No rows.
Processing: 537095838 2024-08-01
No rows.
Processing: 537095838 2024-09-01
No rows.
Processing: 537095838 2024-10-01
No rows.
Processing: 537095838 2024-11-01
No rows.
Processing: 537095838 2024-12-01
No rows.
Processing: 537095838 2025-01-01
No rows.
Processing: 537095838 2025-02-01
No rows.
Processing: 537095838 2025-03-01
No rows.
Processing: 537095838 2025-04-01
No rows.

===== Player 570/1000: 25730568 =====
Processing: 25730568 2024-05-01
No rows.
Processing: 25730568 2024-06-01
No rows.
Processing: 25730568 2024-07-01
No rows.
Processing: 25730568 2024-08-01
No rows.
Processing: 25730568 2024-09-01
No rows.
Processing: 25730568 2024-10-01
No rows.
Processing: 25730568 2024-11-01
No rows.
Processing: 25730568 2024-12-01
No rows.
Processing: 25730568 2025-01-01
No rows.
Processing: 25730568 2025-02-01
No rows.
Processing: 25730568 2025-03-01
No rows.
Processing: 25730568 2025-04-01
No rows.

===== Player 571/1000: 537066196 =====
Processing: 537066196 2024-05-01
No rows.
Processing: 537066196 2024-06-01
No rows.
Processing: 537066196 2024-07-01
No rows.
Processing: 537066196 2024-08-01
No rows.
Processing: 537066196 2024-09-01
No rows.
Processing: 537066196 2024-10-01
No rows.
Processing: 537066196 2024-11-01
No rows.
Processing: 537066196 2024-12-01
No rows.
Processing: 537066196 2025-01-01
No rows.
Processing: 537066196 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 537066196 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 537066196 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537066196_all_months_standard_clean.csv Rows: 12

===== Player 572/1000: 25150669 =====
Processing: 25150669 2024-05-01
No rows.
Processing: 25150669 2024-06-01
No rows.
Processing: 25150669 2024-07-01
No rows.
Processing: 25150669 2024-08-01
No rows.
Processing: 25150669 2024-09-01
No rows.
Processing: 25150669 2024-10-01
No rows.
Processing: 25150669 2024-11-01
No rows.
Processing: 25150669 2024-12-01
No rows.
Processing: 25150669 2025-01-01
No rows.
Processing: 25150669 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 25150669 2025-03-01
No rows.
Processing: 25150669 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25150669_all_months_standard_clean.csv Rows: 6

===== Player 573/1000: 531017452 =====
Processing: 531017452 2024-05-01
No rows.
Processing: 531017452 2024-06-01
No rows.
Processing: 531017452 2024-07-01
No rows.
Processing: 531017452 2024-08-01
No rows.
Processing: 531017452 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 531017452 2024-10-01
No rows.
Processing: 531017452 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 531017452 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 531017452 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 13
Processing: 531017452 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 15
Processing: 531017452 2025-03-01
No rows.
Processing: 531017452 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531017452_all_months_standard_clean.csv Rows: 43

===== Player 574/1000: 33401837 =====
Processing: 33401837 2024-05-01
No rows.
Processing: 33401837 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 33401837 2024-07-01
No rows.
Processing: 33401837 2024-08-01
No rows.
Processing: 33401837 2024-09-01
No rows.
Processing: 33401837 2024-10-01
No rows.
Processing: 33401837 2024-11-01
No rows.
Processing: 33401837 2024-12-01
No rows.
Processing: 33401837 2025-01-01
No rows.
Processing: 33401837 2025-02-01
No rows.
Processing: 33401837 2025-03-01
No rows.
Processing: 33401837 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33401837_all_months_standard_clean.csv Rows: 3

===== Player 575/1000: 25110896 =====
Processing: 25110896 2024-05-01
No rows.
Processing: 25110896 2024-06-01
No rows.
Processing: 25110896 2024-07-01
No rows.
Processing: 25110896 2024-08-01
No rows.
Processing: 25110896 2024-09-01
No rows.
Processing: 25110896 2024-10-01
No rows.
Processing: 25110896 2024-11-01
No rows.
Processing: 25110896 2024-12-01
No rows.
Processing: 25110896 2025-01-01
No rows.
Processing: 25110896 2025-02-01
No rows.
Processing: 25110896 2025-03-01
No rows.
Processing: 25110896 2025-04-01
No rows.

===== Player 576/1000: 88154211 =====
Processing: 88154211 2024-05-01
No rows.
Processing: 88154211 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 88154211 2024-07-01
No rows.
Processing: 88154211 2024-08-01
No rows.
Processing: 88154211 2024-09-01
No rows.
Processing: 88154211 2024-10-01
No rows.
Processing: 88154211 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 88154211 2024-12-01
No rows.
Processing: 88154211 2025-01-01
No rows.
Processing: 88154211 2025-02-01
No rows.
Processing: 88154211 2025-03-01
No rows.
Processing: 88154211 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88154211_all_months_standard_clean.csv Rows: 12

===== Player 577/1000: 33373418 =====
Processing: 33373418 2024-05-01
No rows.
Processing: 33373418 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33373418 2024-07-01
No rows.
Processing: 33373418 2024-08-01
No rows.
Processing: 33373418 2024-09-01
No rows.
Processing: 33373418 2024-10-01
No rows.
Processing: 33373418 2024-11-01
No rows.
Processing: 33373418 2024-12-01
No rows.
Processing: 33373418 2025-01-01
No rows.
Processing: 33373418 2025-02-01
No rows.
Processing: 33373418 2025-03-01
No rows.
Processing: 33373418 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33373418_all_months_standard_clean.csv Rows: 8

===== Player 578/1000: 429033977 =====
Processing: 429033977 2024-05-01
No rows.
Processing: 429033977 2024-06-01
No rows.
Processing: 429033977 2024-07-01
No rows.
Processing: 429033977 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 429033977 2024-09-01
No rows.
Processing: 429033977 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 429033977 2024-11-01
No rows.
Processing: 429033977 2024-12-01
No rows.
Processing: 429033977 2025-01-01
No rows.
Processing: 429033977 2025-02-01
No rows.
Processing: 429033977 2025-03-01
No rows.
Processing: 429033977 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429033977_all_months_standard_clean.csv Rows: 16

===== Player 579/1000: 429045649 =====
Processing: 429045649 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 429045649 2024-06-01
No rows.
Processing: 429045649 2024-07-01
No rows.
Processing: 429045649 2024-08-01
No rows.
Processing: 429045649 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 429045649 2024-10-01
No rows.
Processing: 429045649 2024-11-01
No rows.
Processing: 429045649 2024-12-01
No rows.
Processing: 429045649 2025-01-01
No rows.
Processing: 429045649 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 429045649 2025-03-01
No rows.
Processing: 429045649 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429045649_all_months_standard_clean.csv Rows: 7

===== Player 580/1000: 88117472 =====
Processing: 88117472 2024-05-01
No rows.
Processing: 88117472 2024-06-01
No rows.
Processing: 88117472 2024-07-01
No rows.
Processing: 88117472 2024-08-01
No rows.
Processing: 88117472 2024-09-01
No rows.
Processing: 88117472 2024-10-01
No rows.
Processing: 88117472 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 88117472 2024-12-01
No rows.
Processing: 88117472 2025-01-01
No rows.
Processing: 88117472 2025-02-01
No rows.
Processing: 88117472 2025-03-01
No rows.
Processing: 88117472 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88117472_all_months_standard_clean.csv Rows: 2

===== Player 581/1000: 537042955 =====
Processing: 537042955 2024-05-01
No rows.
Processing: 537042955 2024-06-01
No rows.
Processing: 537042955 2024-07-01
No rows.
Processing: 537042955 2024-08-01
No rows.
Processing: 537042955 2024-09-01
No rows.
Processing: 537042955 2024-10-01
No rows.
Processing: 537042955 2024-11-01
No rows.
Processing: 537042955 2024-12-01
No rows.
Processing: 537042955 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 537042955 2025-02-01
No rows.
Processing: 537042955 2025-03-01
No rows.
Processing: 537042955 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537042955_all_months_standard_clean.csv Rows: 3

===== Player 582/1000: 48731722 =====
Processing: 48731722 2024-05-01
No rows.
Processing: 48731722 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 48731722 2024-07-01
No rows.
Processing: 48731722 2024-08-01
No rows.
Processing: 48731722 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 48731722 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 48731722 2024-11-01
No rows.
Processing: 48731722 2024-12-01
No rows.
Processing: 48731722 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 48731722 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 48731722 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 48731722 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48731722_all_months_standard_clean.csv Rows: 37

===== Player 583/1000: 531036279 =====
Processing: 531036279 2024-05-01
No rows.
Processing: 531036279 2024-06-01
No rows.
Processing: 531036279 2024-07-01
No rows.
Processing: 531036279 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 531036279 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 531036279 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 531036279 2024-11-01
No rows.
Processing: 531036279 2024-12-01
No rows.
Processing: 531036279 2025-01-01
No rows.
Processing: 531036279 2025-02-01
No rows.
Processing: 531036279 2025-03-01
No rows.
Processing: 531036279 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531036279_all_months_standard_clean.csv Rows: 7

===== Player 584/1000: 558068902 =====
Processing: 558068902 2024-05-01
No rows.
Processing: 558068902 2024-06-01
No rows.
Processing: 558068902 2024-07-01
No rows.
Processing: 558068902 2024-08-01
No rows.
Processing: 558068902 2024-09-01
No rows.
Processing: 558068902 2024-10-01
No rows.
Processing: 558068902 2024-11-01
No rows.
Processing: 558068902 2024-12-01
No rows.
Processing: 558068902 2025-01-01
No rows.
Processing: 558068902 2025-02-01
No rows.
Processing: 558068902 2025-03-01
No rows.
Processing: 558068902 2025-04-01
No rows.

===== Player 585/1000: 48762385 =====
Processing: 48762385 2024-05-01
Rows: 6
Processing: 48762385 2024-06-01
No rows.
Processing: 48762385 2024-07-01
No rows.
Processing: 48762385 2024-08-01
No rows.
Processing: 48762385 2024-09-01
No rows.
Processing: 48762385 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 48762385 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 48762385 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 48762385 2025-01-01
No rows.
Processing: 48762385 2025-02-01
No rows.
Processing: 48762385 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 48762385 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48762385_all_months_standard_clean.csv Rows: 26

===== Player 586/1000: 25124234 =====
Processing: 25124234 2024-05-01
No rows.
Processing: 25124234 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 25124234 2024-07-01
No rows.
Processing: 25124234 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 25124234 2024-09-01
No rows.
Processing: 25124234 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 25124234 2024-11-01
No rows.
Processing: 25124234 2024-12-01
No rows.
Processing: 25124234 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 25124234 2025-02-01
No rows.
Processing: 25124234 2025-03-01
No rows.
Processing: 25124234 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25124234_all_months_standard_clean.csv Rows: 20

===== Player 587/1000: 531006116 =====
Processing: 531006116 2024-05-01
No rows.
Processing: 531006116 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 531006116 2024-07-01
No rows.
Processing: 531006116 2024-08-01
No rows.
Processing: 531006116 2024-09-01
No rows.
Processing: 531006116 2024-10-01
No rows.
Processing: 531006116 2024-11-01
No rows.
Processing: 531006116 2024-12-01
No rows.
Processing: 531006116 2025-01-01
No rows.
Processing: 531006116 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 531006116 2025-03-01
No rows.
Processing: 531006116 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531006116_all_months_standard_clean.csv Rows: 11

===== Player 588/1000: 33484490 =====
Processing: 33484490 2024-05-01
No rows.
Processing: 33484490 2024-06-01
No rows.
Processing: 33484490 2024-07-01
No rows.
Processing: 33484490 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 33484490 2024-09-01
No rows.
Processing: 33484490 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 33484490 2024-11-01
No rows.
Processing: 33484490 2024-12-01
No rows.
Processing: 33484490 2025-01-01
No rows.
Processing: 33484490 2025-02-01
No rows.
Processing: 33484490 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 13
Processing: 33484490 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33484490_all_months_standard_clean.csv Rows: 23

===== Player 589/1000: 25997777 =====
Processing: 25997777 2024-05-01
No rows.
Processing: 25997777 2024-06-01
No rows.
Processing: 25997777 2024-07-01
No rows.
Processing: 25997777 2024-08-01
No rows.
Processing: 25997777 2024-09-01
No rows.
Processing: 25997777 2024-10-01
No rows.
Processing: 25997777 2024-11-01
No rows.
Processing: 25997777 2024-12-01
No rows.
Processing: 25997777 2025-01-01
No rows.
Processing: 25997777 2025-02-01
No rows.
Processing: 25997777 2025-03-01
No rows.
Processing: 25997777 2025-04-01
No rows.

===== Player 590/1000: 33401268 =====
Processing: 33401268 2024-05-01
No rows.
Processing: 33401268 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33401268 2024-07-01
No rows.
Processing: 33401268 2024-08-01
No rows.
Processing: 33401268 2024-09-01
No rows.
Processing: 33401268 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 12
Processing: 33401268 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33401268 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33401268 2025-01-01
No rows.
Processing: 33401268 2025-02-01
No rows.
Processing: 33401268 2025-03-01
No rows.
Processing: 33401268 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33401268_all_months_standard_clean.csv Rows: 36

===== Player 591/1000: 48704741 =====
Processing: 48704741 2024-05-01
No rows.
Processing: 48704741 2024-06-01
No rows.
Processing: 48704741 2024-07-01
No rows.
Processing: 48704741 2024-08-01
No rows.
Processing: 48704741 2024-09-01
No rows.
Processing: 48704741 2024-10-01
No rows.
Processing: 48704741 2024-11-01
No rows.
Processing: 48704741 2024-12-01
No rows.
Processing: 48704741 2025-01-01
No rows.
Processing: 48704741 2025-02-01
No rows.
Processing: 48704741 2025-03-01
No rows.
Processing: 48704741 2025-04-01
No rows.

===== Player 592/1000: 25158422 =====
Processing: 25158422 2024-05-01
No rows.
Processing: 25158422 2024-06-01
No rows.
Processing: 25158422 2024-07-01
No rows.
Processing: 25158422 2024-08-01
No rows.
Processing: 25158422 2024-09-01
No rows.
Processing: 25158422 2024-10-01
No rows.
Processing: 25158422 2024-11-01
No rows.
Processing: 25158422 2024-12-01
No rows.
Processing: 25158422 2025-01-01
No rows.
Processing: 25158422 2025-02-01
No rows.
Processing: 25158422 2025-03-01
No rows.
Processing: 25158422 2025-04-01
No rows.

===== Player 593/1000: 531053564 =====
Processing: 531053564 2024-05-01
No rows.
Processing: 531053564 2024-06-01
No rows.
Processing: 531053564 2024-07-01
No rows.
Processing: 531053564 2024-08-01
No rows.
Processing: 531053564 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 531053564 2024-10-01
No rows.
Processing: 531053564 2024-11-01
No rows.
Processing: 531053564 2024-12-01
No rows.
Processing: 531053564 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 531053564 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 531053564 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 531053564 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531053564_all_months_standard_clean.csv Rows: 19

===== Player 594/1000: 88173453 =====
Processing: 88173453 2024-05-01
No rows.
Processing: 88173453 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 88173453 2024-07-01
No rows.
Processing: 88173453 2024-08-01
No rows.
Processing: 88173453 2024-09-01
No rows.
Processing: 88173453 2024-10-01
No rows.
Processing: 88173453 2024-11-01
No rows.
Processing: 88173453 2024-12-01
No rows.
Processing: 88173453 2025-01-01
No rows.
Processing: 88173453 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 88173453 2025-03-01
No rows.
Processing: 88173453 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88173453_all_months_standard_clean.csv Rows: 11

===== Player 595/1000: 429013445 =====
Processing: 429013445 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 429013445 2024-06-01
No rows.
Processing: 429013445 2024-07-01
No rows.
Processing: 429013445 2024-08-01
No rows.
Processing: 429013445 2024-09-01
No rows.
Processing: 429013445 2024-10-01
No rows.
Processing: 429013445 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 429013445 2024-12-01
No rows.
Processing: 429013445 2025-01-01
No rows.
Processing: 429013445 2025-02-01
No rows.
Processing: 429013445 2025-03-01
No rows.
Processing: 429013445 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429013445_all_months_standard_clean.csv Rows: 7

===== Player 596/1000: 25748190 =====
Processing: 25748190 2024-05-01
No rows.
Processing: 25748190 2024-06-01
No rows.
Processing: 25748190 2024-07-01
No rows.
Processing: 25748190 2024-08-01
No rows.
Processing: 25748190 2024-09-01
No rows.
Processing: 25748190 2024-10-01
No rows.
Processing: 25748190 2024-11-01
No rows.
Processing: 25748190 2024-12-01
No rows.
Processing: 25748190 2025-01-01
No rows.
Processing: 25748190 2025-02-01
No rows.
Processing: 25748190 2025-03-01
No rows.
Processing: 25748190 2025-04-01
No rows.

===== Player 597/1000: 33439559 =====
Processing: 33439559 2024-05-01
No rows.
Processing: 33439559 2024-06-01
No rows.
Processing: 33439559 2024-07-01
No rows.
Processing: 33439559 2024-08-01
No rows.
Processing: 33439559 2024-09-01
No rows.
Processing: 33439559 2024-10-01
No rows.
Processing: 33439559 2024-11-01
No rows.
Processing: 33439559 2024-12-01
No rows.
Processing: 33439559 2025-01-01
No rows.
Processing: 33439559 2025-02-01
No rows.
Processing: 33439559 2025-03-01
No rows.
Processing: 33439559 2025-04-01
No rows.

===== Player 598/1000: 25181807 =====
Processing: 25181807 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 25181807 2024-06-01
No rows.
Processing: 25181807 2024-07-01
No rows.
Processing: 25181807 2024-08-01
No rows.
Processing: 25181807 2024-09-01
No rows.
Processing: 25181807 2024-10-01
No rows.
Processing: 25181807 2024-11-01
No rows.
Processing: 25181807 2024-12-01
No rows.
Processing: 25181807 2025-01-01
No rows.
Processing: 25181807 2025-02-01
No rows.
Processing: 25181807 2025-03-01
No rows.
Processing: 25181807 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25181807_all_months_standard_clean.csv Rows: 8

===== Player 599/1000: 33359962 =====
Processing: 33359962 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 33359962 2024-06-01
No rows.
Processing: 33359962 2024-07-01
No rows.
Processing: 33359962 2024-08-01
No rows.
Processing: 33359962 2024-09-01
No rows.
Processing: 33359962 2024-10-01
No rows.
Processing: 33359962 2024-11-01
No rows.
Processing: 33359962 2024-12-01
No rows.
Processing: 33359962 2025-01-01
No rows.
Processing: 33359962 2025-02-01
No rows.
Processing: 33359962 2025-03-01
No rows.
Processing: 33359962 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33359962_all_months_standard_clean.csv Rows: 3

===== Player 600/1000: 429031818 =====
Processing: 429031818 2024-05-01
No rows.
Processing: 429031818 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 429031818 2024-07-01
No rows.
Processing: 429031818 2024-08-01
No rows.
Processing: 429031818 2024-09-01
No rows.
Processing: 429031818 2024-10-01
No rows.
Processing: 429031818 2024-11-01
No rows.
Processing: 429031818 2024-12-01
No rows.
Processing: 429031818 2025-01-01
No rows.
Processing: 429031818 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 429031818 2025-03-01
No rows.
Processing: 429031818 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429031818_all_months_standard_clean.csv Rows: 9

===== Player 601/1000: 88107540 =====
Processing: 88107540 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 88107540 2024-06-01
No rows.
Processing: 88107540 2024-07-01
No rows.
Processing: 88107540 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 88107540 2024-09-01
No rows.
Processing: 88107540 2024-10-01
No rows.
Processing: 88107540 2024-11-01
No rows.
Processing: 88107540 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 88107540 2025-01-01
No rows.
Processing: 88107540 2025-02-01
No rows.
Processing: 88107540 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 88107540 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88107540_all_months_standard_clean.csv Rows: 17

===== Player 602/1000: 25118072 =====
Processing: 25118072 2024-05-01
No rows.
Processing: 25118072 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 25118072 2024-07-01
No rows.
Processing: 25118072 2024-08-01
Failed: 25118072 2024-08-01 TimeoutError('Page.goto: Timeout 60000ms exceeded.\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=25118072&period=2024-08-01&rating=0", waiting until "networkidle"\n')
Processing: 25118072 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 11
Processing: 25118072 2024-10-01
No rows.
Processing: 25118072 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 25118072 2024-12-01
No rows.
Processing: 25118072 2025-01-01
No rows.
Processing: 25118072 2025-02-01
No rows.
Processing: 25118072 2025-03-01
No rows.
Processing: 25118072 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25118072_all_months_standard_clean.csv Rows: 23

===== Player 603/1000: 48731846 =====
Processing: 48731846 2024-05-01
No rows.
Processing: 48731846 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 48731846 2024-07-01
No rows.
Processing: 48731846 2024-08-01
No rows.
Processing: 48731846 2024-09-01
No rows.
Processing: 48731846 2024-10-01
No rows.
Processing: 48731846 2024-11-01
No rows.
Processing: 48731846 2024-12-01
No rows.
Processing: 48731846 2025-01-01
No rows.
Processing: 48731846 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 48731846 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 48731846 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48731846_all_months_standard_clean.csv Rows: 14

===== Player 604/1000: 48713325 =====
Processing: 48713325 2024-05-01
No rows.
Processing: 48713325 2024-06-01
No rows.
Processing: 48713325 2024-07-01
No rows.
Processing: 48713325 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 48713325 2024-09-01
No rows.
Processing: 48713325 2024-10-01
No rows.
Processing: 48713325 2024-11-01
No rows.
Processing: 48713325 2024-12-01
No rows.
Processing: 48713325 2025-01-01
No rows.
Processing: 48713325 2025-02-01
No rows.
Processing: 48713325 2025-03-01
No rows.
Processing: 48713325 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48713325_all_months_standard_clean.csv Rows: 8

===== Player 605/1000: 537005022 =====
Processing: 537005022 2024-05-01
No rows.
Processing: 537005022 2024-06-01
No rows.
Processing: 537005022 2024-07-01
No rows.
Processing: 537005022 2024-08-01
No rows.
Processing: 537005022 2024-09-01
No rows.
Processing: 537005022 2024-10-01
No rows.
Processing: 537005022 2024-11-01
No rows.
Processing: 537005022 2024-12-01
No rows.
Processing: 537005022 2025-01-01
No rows.
Processing: 537005022 2025-02-01
No rows.
Processing: 537005022 2025-03-01
No rows.
Processing: 537005022 2025-04-01
No rows.

===== Player 606/1000: 429013496 =====
Processing: 429013496 2024-05-01
No rows.
Processing: 429013496 2024-06-01
No rows.
Processing: 429013496 2024-07-01
No rows.
Processing: 429013496 2024-08-01
No rows.
Processing: 429013496 2024-09-01
No rows.
Processing: 429013496 2024-10-01
No rows.
Processing: 429013496 2024-11-01
No rows.
Processing: 429013496 2024-12-01
No rows.
Processing: 429013496 2025-01-01
No rows.
Processing: 429013496 2025-02-01
No rows.
Processing: 429013496 2025-03-01
No rows.
Processing: 429013496 2025-04-01
No rows.

===== Player 607/1000: 33359660 =====
Processing: 33359660 2024-05-01
No rows.
Processing: 33359660 2024-06-01
No rows.
Processing: 33359660 2024-07-01
No rows.
Processing: 33359660 2024-08-01
No rows.
Processing: 33359660 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33359660 2024-10-01
No rows.
Processing: 33359660 2024-11-01
No rows.
Processing: 33359660 2024-12-01
No rows.
Processing: 33359660 2025-01-01
No rows.
Processing: 33359660 2025-02-01
No rows.
Processing: 33359660 2025-03-01
No rows.
Processing: 33359660 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33359660_all_months_standard_clean.csv Rows: 8

===== Player 608/1000: 547050578 =====
Processing: 547050578 2024-05-01
No rows.
Processing: 547050578 2024-06-01
No rows.
Processing: 547050578 2024-07-01
No rows.
Processing: 547050578 2024-08-01
No rows.
Processing: 547050578 2024-09-01
No rows.
Processing: 547050578 2024-10-01
No rows.
Processing: 547050578 2024-11-01
No rows.
Processing: 547050578 2024-12-01
No rows.
Processing: 547050578 2025-01-01
No rows.
Processing: 547050578 2025-02-01
No rows.
Processing: 547050578 2025-03-01
No rows.
Processing: 547050578 2025-04-01
No rows.

===== Player 609/1000: 429096804 =====
Processing: 429096804 2024-05-01
No rows.
Processing: 429096804 2024-06-01
No rows.
Processing: 429096804 2024-07-01
No rows.
Processing: 429096804 2024-08-01
No rows.
Processing: 429096804 2024-09-01
No rows.
Processing: 429096804 2024-10-01
No rows.
Processing: 429096804 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 429096804 2024-12-01
No rows.
Processing: 429096804 2025-01-01
No rows.
Processing: 429096804 2025-02-01
No rows.
Processing: 429096804 2025-03-01
No rows.
Processing: 429096804 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429096804_all_months_standard_clean.csv Rows: 2

===== Player 610/1000: 429012562 =====
Processing: 429012562 2024-05-01
No rows.
Processing: 429012562 2024-06-01
No rows.
Processing: 429012562 2024-07-01
No rows.
Processing: 429012562 2024-08-01
No rows.
Processing: 429012562 2024-09-01
No rows.
Processing: 429012562 2024-10-01
No rows.
Processing: 429012562 2024-11-01
No rows.
Processing: 429012562 2024-12-01
No rows.
Processing: 429012562 2025-01-01
No rows.
Processing: 429012562 2025-02-01
No rows.
Processing: 429012562 2025-03-01
No rows.
Processing: 429012562 2025-04-01
No rows.

===== Player 611/1000: 45050406 =====
Processing: 45050406 2024-05-01
No rows.
Processing: 45050406 2024-06-01
No rows.
Processing: 45050406 2024-07-01
No rows.
Processing: 45050406 2024-08-01
No rows.
Processing: 45050406 2024-09-01
No rows.
Processing: 45050406 2024-10-01
No rows.
Processing: 45050406 2024-11-01
No rows.
Processing: 45050406 2024-12-01
No rows.
Processing: 45050406 2025-01-01
No rows.
Processing: 45050406 2025-02-01
No rows.
Processing: 45050406 2025-03-01
No rows.
Processing: 45050406 2025-04-01
No rows.

===== Player 612/1000: 88156940 =====
Processing: 88156940 2024-05-01
No rows.
Processing: 88156940 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 88156940 2024-07-01
No rows.
Processing: 88156940 2024-08-01
No rows.
Processing: 88156940 2024-09-01
No rows.
Processing: 88156940 2024-10-01
No rows.
Processing: 88156940 2024-11-01
No rows.
Processing: 88156940 2024-12-01
No rows.
Processing: 88156940 2025-01-01
No rows.
Processing: 88156940 2025-02-01
No rows.
Processing: 88156940 2025-03-01
No rows.
Processing: 88156940 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88156940_all_months_standard_clean.csv Rows: 7

===== Player 613/1000: 88153240 =====
Processing: 88153240 2024-05-01
No rows.
Processing: 88153240 2024-06-01
No rows.
Processing: 88153240 2024-07-01
No rows.
Processing: 88153240 2024-08-01
No rows.
Processing: 88153240 2024-09-01
No rows.
Processing: 88153240 2024-10-01
No rows.
Processing: 88153240 2024-11-01
No rows.
Processing: 88153240 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 88153240 2025-01-01
No rows.
Processing: 88153240 2025-02-01
No rows.
Processing: 88153240 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 88153240 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88153240_all_months_standard_clean.csv Rows: 7

===== Player 614/1000: 547003545 =====
Processing: 547003545 2024-05-01
No rows.
Processing: 547003545 2024-06-01
No rows.
Processing: 547003545 2024-07-01
No rows.
Processing: 547003545 2024-08-01
No rows.
Processing: 547003545 2024-09-01
No rows.
Processing: 547003545 2024-10-01
No rows.
Processing: 547003545 2024-11-01
No rows.
Processing: 547003545 2024-12-01
No rows.
Processing: 547003545 2025-01-01
No rows.
Processing: 547003545 2025-02-01
No rows.
Processing: 547003545 2025-03-01
No rows.
Processing: 547003545 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/547003545_all_months_standard_clean.csv Rows: 5

===== Player 615/1000: 33407649 =====
Processing: 33407649 2024-05-01
Rows: 5
Processing: 33407649 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 33407649 2024-07-01
No rows.
Processing: 33407649 2024-08-01
No rows.
Processing: 33407649 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 33407649 2024-10-01
No rows.
Processing: 33407649 2024-11-01
No rows.
Processing: 33407649 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 33407649 2025-01-01
No rows.
Processing: 33407649 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33407649 2025-03-01
No rows.
Processing: 33407649 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33407649_all_months_standard_clean.csv Rows: 26

===== Player 616/1000: 25130404 =====
Processing: 25130404 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 25130404 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 15
Processing: 25130404 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 25130404 2024-08-01
No rows.
Processing: 25130404 2024-09-01
No rows.
Processing: 25130404 2024-10-01
No rows.
Processing: 25130404 2024-11-01
No rows.
Processing: 25130404 2024-12-01
No rows.
Processing: 25130404 2025-01-01
No rows.
Processing: 25130404 2025-02-01
No rows.
Processing: 25130404 2025-03-01
No rows.
Processing: 25130404 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25130404_all_months_standard_clean.csv Rows: 27

===== Player 617/1000: 33401624 =====
Processing: 33401624 2024-05-01
No rows.
Processing: 33401624 2024-06-01
No rows.
Processing: 33401624 2024-07-01
No rows.
Processing: 33401624 2024-08-01
No rows.
Processing: 33401624 2024-09-01
No rows.
Processing: 33401624 2024-10-01
No rows.
Processing: 33401624 2024-11-01
No rows.
Processing: 33401624 2024-12-01
No rows.
Processing: 33401624 2025-01-01
No rows.
Processing: 33401624 2025-02-01
No rows.
Processing: 33401624 2025-03-01
No rows.
Processing: 33401624 2025-04-01
No rows.

===== Player 618/1000: 33494592 =====
Processing: 33494592 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 33494592 2024-06-01
No rows.
Processing: 33494592 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 33494592 2024-08-01
No rows.
Processing: 33494592 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33494592 2024-10-01
No rows.
Processing: 33494592 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 33494592 2024-12-01
No rows.
Processing: 33494592 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 10
Processing: 33494592 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 33494592 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 33494592 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33494592_all_months_standard_clean.csv Rows: 40

===== Player 619/1000: 88155749 =====
Processing: 88155749 2024-05-01
No rows.
Processing: 88155749 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 11
Processing: 88155749 2024-07-01
No rows.
Processing: 88155749 2024-08-01
No rows.
Processing: 88155749 2024-09-01
No rows.
Processing: 88155749 2024-10-01
No rows.
Processing: 88155749 2024-11-01
No rows.
Processing: 88155749 2024-12-01
No rows.
Processing: 88155749 2025-01-01
No rows.
Processing: 88155749 2025-02-01
No rows.
Processing: 88155749 2025-03-01
No rows.
Processing: 88155749 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88155749_all_months_standard_clean.csv Rows: 11

===== Player 620/1000: 25785559 =====
Processing: 25785559 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 25785559 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 25785559 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 17
Processing: 25785559 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 10
Processing: 25785559 2024-09-01
Rows: 8
Processing: 25785559 2024-10-01
No rows.
Processing: 25785559 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 25785559 2024-12-01
No rows.
Processing: 25785559 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 25785559 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 25785559 2025-03-01
No rows.
Processing: 25785559 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25785559_all_months_standard_clean.csv Rows: 76

===== Player 621/1000: 547031131 =====
Processing: 547031131 2024-05-01
No rows.
Processing: 547031131 2024-06-01
No rows.
Processing: 547031131 2024-07-01
No rows.
Processing: 547031131 2024-08-01
No rows.
Processing: 547031131 2024-09-01
No rows.
Processing: 547031131 2024-10-01
No rows.
Processing: 547031131 2024-11-01
No rows.
Processing: 547031131 2024-12-01
No rows.
Processing: 547031131 2025-01-01
No rows.
Processing: 547031131 2025-02-01
No rows.
Processing: 547031131 2025-03-01
No rows.
Processing: 547031131 2025-04-01
No rows.

===== Player 622/1000: 531070914 =====
Processing: 531070914 2024-05-01
No rows.
Processing: 531070914 2024-06-01
No rows.
Processing: 531070914 2024-07-01
No rows.
Processing: 531070914 2024-08-01
No rows.
Processing: 531070914 2024-09-01
No rows.
Processing: 531070914 2024-10-01
No rows.
Processing: 531070914 2024-11-01
No rows.
Processing: 531070914 2024-12-01
No rows.
Processing: 531070914 2025-01-01
No rows.
Processing: 531070914 2025-02-01
No rows.
Processing: 531070914 2025-03-01
No rows.
Processing: 531070914 2025-04-01
No rows.

===== Player 623/1000: 33403066 =====
Processing: 33403066 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33403066 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33403066 2024-07-01
No rows.
Processing: 33403066 2024-08-01
No rows.
Processing: 33403066 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 33403066 2024-10-01
No rows.
Processing: 33403066 2024-11-01
No rows.
Processing: 33403066 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 33403066 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 33403066 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 33403066 2025-03-01
No rows.
Processing: 33403066 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33403066_all_months_standard_clean.csv Rows: 32

===== Player 624/1000: 547015624 =====
Processing: 547015624 2024-05-01
No rows.
Processing: 547015624 2024-06-01
No rows.
Processing: 547015624 2024-07-01
No rows.
Processing: 547015624 2024-08-01
No rows.
Processing: 547015624 2024-09-01
No rows.
Processing: 547015624 2024-10-01
No rows.
Processing: 547015624 2024-11-01
No rows.
Processing: 547015624 2024-12-01
No rows.
Processing: 547015624 2025-01-01
No rows.
Processing: 547015624 2025-02-01
No rows.
Processing: 547015624 2025-03-01
No rows.
Processing: 547015624 2025-04-01
No rows.

===== Player 625/1000: 537028570 =====
Processing: 537028570 2024-05-01
No rows.
Processing: 537028570 2024-06-01
No rows.
Processing: 537028570 2024-07-01
No rows.
Processing: 537028570 2024-08-01
No rows.
Processing: 537028570 2024-09-01
No rows.
Processing: 537028570 2024-10-01
No rows.
Processing: 537028570 2024-11-01
No rows.
Processing: 537028570 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 537028570 2025-01-01
No rows.
Processing: 537028570 2025-02-01
No rows.
Processing: 537028570 2025-03-01
No rows.
Processing: 537028570 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537028570_all_months_standard_clean.csv Rows: 3

===== Player 626/1000: 88115054 =====
Processing: 88115054 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 10
Processing: 88115054 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 12
Processing: 88115054 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 88115054 2024-08-01
Rows: 4
Processing: 88115054 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 88115054 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 88115054 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 88115054 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 88115054 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 88115054 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 12
Processing: 88115054 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 88115054 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88115054_all_months_standard_clean.csv Rows: 73

===== Player 627/1000: 429070015 =====
Processing: 429070015 2024-05-01
No rows.
Processing: 429070015 2024-06-01
No rows.
Processing: 429070015 2024-07-01
No rows.
Processing: 429070015 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 429070015 2024-09-01
No rows.
Processing: 429070015 2024-10-01
No rows.
Processing: 429070015 2024-11-01
No rows.
Processing: 429070015 2024-12-01
No rows.
Processing: 429070015 2025-01-01
No rows.
Processing: 429070015 2025-02-01
No rows.
Processing: 429070015 2025-03-01
No rows.
Processing: 429070015 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429070015_all_months_standard_clean.csv Rows: 4

===== Player 628/1000: 33351236 =====
Processing: 33351236 2024-05-01
No rows.
Processing: 33351236 2024-06-01
No rows.
Processing: 33351236 2024-07-01
No rows.
Processing: 33351236 2024-08-01
No rows.
Processing: 33351236 2024-09-01
No rows.
Processing: 33351236 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33351236 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 33351236 2024-12-01
No rows.
Processing: 33351236 2025-01-01
No rows.
Processing: 33351236 2025-02-01
No rows.
Processing: 33351236 2025-03-01
No rows.
Processing: 33351236 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33351236_all_months_standard_clean.csv Rows: 7

===== Player 629/1000: 25174657 =====
Processing: 25174657 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 25174657 2024-06-01
Rows: 9
Processing: 25174657 2024-07-01
Rows: 11
Processing: 25174657 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 11
Processing: 25174657 2024-09-01
No rows.
Processing: 25174657 2024-10-01
Rows: 20
Processing: 25174657 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 11
Processing: 25174657 2024-12-01
Rows: 11
Processing: 25174657 2025-01-01
Rows: 10
Processing: 25174657 2025-02-01
Rows: 9
Processing: 25174657 2025-03-01
No rows.
Processing: 25174657 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25174657_all_months_standard_clean.csv Rows: 101

===== Player 630/1000: 564014657 =====
Processing: 564014657 2024-05-01
No rows.
Processing: 564014657 2024-06-01
No rows.
Processing: 564014657 2024-07-01
No rows.
Processing: 564014657 2024-08-01
No rows.
Processing: 564014657 2024-09-01
No rows.
Processing: 564014657 2024-10-01
No rows.
Processing: 564014657 2024-11-01
No rows.
Processing: 564014657 2024-12-01
No rows.
Processing: 564014657 2025-01-01
No rows.
Processing: 564014657 2025-02-01
No rows.
Processing: 564014657 2025-03-01
No rows.
Processing: 564014657 2025-04-01
No rows.

===== Player 631/1000: 25165828 =====
Processing: 25165828 2024-05-01
No rows.
Processing: 25165828 2024-06-01
No rows.
Processing: 25165828 2024-07-01
No rows.
Processing: 25165828 2024-08-01
No rows.
Processing: 25165828 2024-09-01
No rows.
Processing: 25165828 2024-10-01
No rows.
Processing: 25165828 2024-11-01
No rows.
Processing: 25165828 2024-12-01
No rows.
Processing: 25165828 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 25165828 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 25165828 2025-03-01
No rows.
Processing: 25165828 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25165828_all_months_standard_clean.csv Rows: 8

===== Player 632/1000: 25193120 =====
Processing: 25193120 2024-05-01
No rows.
Processing: 25193120 2024-06-01
No rows.
Processing: 25193120 2024-07-01
No rows.
Processing: 25193120 2024-08-01
No rows.
Processing: 25193120 2024-09-01
No rows.
Processing: 25193120 2024-10-01
No rows.
Processing: 25193120 2024-11-01
No rows.
Processing: 25193120 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 25193120 2025-01-01
No rows.
Processing: 25193120 2025-02-01
No rows.
Processing: 25193120 2025-03-01
No rows.
Processing: 25193120 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25193120_all_months_standard_clean.csv Rows: 7

===== Player 633/1000: 33475857 =====
Processing: 33475857 2024-05-01
No rows.
Processing: 33475857 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 33475857 2024-07-01
No rows.
Processing: 33475857 2024-08-01
No rows.
Processing: 33475857 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 33475857 2024-10-01
No rows.
Processing: 33475857 2024-11-01
No rows.
Processing: 33475857 2024-12-01
No rows.
Processing: 33475857 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 33475857 2025-02-01
No rows.
Processing: 33475857 2025-03-01
No rows.
Processing: 33475857 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33475857_all_months_standard_clean.csv Rows: 19

===== Player 634/1000: 88119882 =====
Processing: 88119882 2024-05-01
No rows.
Processing: 88119882 2024-06-01
No rows.
Processing: 88119882 2024-07-01
No rows.
Processing: 88119882 2024-08-01
No rows.
Processing: 88119882 2024-09-01
No rows.
Processing: 88119882 2024-10-01
No rows.
Processing: 88119882 2024-11-01
No rows.
Processing: 88119882 2024-12-01
No rows.
Processing: 88119882 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 88119882 2025-02-01
No rows.
Processing: 88119882 2025-03-01
No rows.
Processing: 88119882 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88119882_all_months_standard_clean.csv Rows: 1

===== Player 635/1000: 48701521 =====
Processing: 48701521 2024-05-01
No rows.
Processing: 48701521 2024-06-01
No rows.
Processing: 48701521 2024-07-01
No rows.
Processing: 48701521 2024-08-01
No rows.
Processing: 48701521 2024-09-01
No rows.
Processing: 48701521 2024-10-01
No rows.
Processing: 48701521 2024-11-01
No rows.
Processing: 48701521 2024-12-01
No rows.
Processing: 48701521 2025-01-01
No rows.
Processing: 48701521 2025-02-01
No rows.
Processing: 48701521 2025-03-01
No rows.
Processing: 48701521 2025-04-01
No rows.

===== Player 636/1000: 88103200 =====
Processing: 88103200 2024-05-01
No rows.
Processing: 88103200 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 88103200 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 88103200 2024-08-01
No rows.
Processing: 88103200 2024-09-01
No rows.
Processing: 88103200 2024-10-01
No rows.
Processing: 88103200 2024-11-01
No rows.
Processing: 88103200 2024-12-01
No rows.
Processing: 88103200 2025-01-01
No rows.
Processing: 88103200 2025-02-01
No rows.
Processing: 88103200 2025-03-01
No rows.
Processing: 88103200 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88103200_all_months_standard_clean.csv Rows: 13

===== Player 637/1000: 33441189 =====
Processing: 33441189 2024-05-01
No rows.
Processing: 33441189 2024-06-01
No rows.
Processing: 33441189 2024-07-01
No rows.
Processing: 33441189 2024-08-01
No rows.
Processing: 33441189 2024-09-01
No rows.
Processing: 33441189 2024-10-01
No rows.
Processing: 33441189 2024-11-01
No rows.
Processing: 33441189 2024-12-01
No rows.
Processing: 33441189 2025-01-01
No rows.
Processing: 33441189 2025-02-01
No rows.
Processing: 33441189 2025-03-01
No rows.
Processing: 33441189 2025-04-01
No rows.

===== Player 638/1000: 46636510 =====
Processing: 46636510 2024-05-01
No rows.
Processing: 46636510 2024-06-01
No rows.
Processing: 46636510 2024-07-01
No rows.
Processing: 46636510 2024-08-01
No rows.
Processing: 46636510 2024-09-01
No rows.
Processing: 46636510 2024-10-01
No rows.
Processing: 46636510 2024-11-01
No rows.
Processing: 46636510 2024-12-01
No rows.
Processing: 46636510 2025-01-01
No rows.
Processing: 46636510 2025-02-01
No rows.
Processing: 46636510 2025-03-01
No rows.
Processing: 46636510 2025-04-01
No rows.

===== Player 639/1000: 531019943 =====
Processing: 531019943 2024-05-01
No rows.
Processing: 531019943 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 531019943 2024-07-01
No rows.
Processing: 531019943 2024-08-01
No rows.
Processing: 531019943 2024-09-01
No rows.
Processing: 531019943 2024-10-01
No rows.
Processing: 531019943 2024-11-01
No rows.
Processing: 531019943 2024-12-01
No rows.
Processing: 531019943 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 531019943 2025-02-01
No rows.
Processing: 531019943 2025-03-01
No rows.
Processing: 531019943 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531019943_all_months_standard_clean.csv Rows: 5

===== Player 640/1000: 25919091 =====
Processing: 25919091 2024-05-01
No rows.
Processing: 25919091 2024-06-01
No rows.
Processing: 25919091 2024-07-01
No rows.
Processing: 25919091 2024-08-01
No rows.
Processing: 25919091 2024-09-01
No rows.
Processing: 25919091 2024-10-01
No rows.
Processing: 25919091 2024-11-01
No rows.
Processing: 25919091 2024-12-01
No rows.
Processing: 25919091 2025-01-01
No rows.
Processing: 25919091 2025-02-01
No rows.
Processing: 25919091 2025-03-01
No rows.
Processing: 25919091 2025-04-01
No rows.

===== Player 641/1000: 33372764 =====
Processing: 33372764 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33372764 2024-06-01
No rows.
Processing: 33372764 2024-07-01
No rows.
Processing: 33372764 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 15
Processing: 33372764 2024-09-01
No rows.
Processing: 33372764 2024-10-01
No rows.
Processing: 33372764 2024-11-01
Rows: 7
Processing: 33372764 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 33372764 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 11
Processing: 33372764 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33372764 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33372764 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33372764_all_months_standard_clean.csv Rows: 73

===== Player 642/1000: 558040684 =====
Processing: 558040684 2024-05-01
No rows.
Processing: 558040684 2024-06-01
No rows.
Processing: 558040684 2024-07-01
No rows.
Processing: 558040684 2024-08-01
No rows.
Processing: 558040684 2024-09-01
No rows.
Processing: 558040684 2024-10-01
No rows.
Processing: 558040684 2024-11-01
No rows.
Processing: 558040684 2024-12-01
No rows.
Processing: 558040684 2025-01-01
No rows.
Processing: 558040684 2025-02-01
No rows.
Processing: 558040684 2025-03-01
No rows.
Processing: 558040684 2025-04-01
No rows.

===== Player 643/1000: 25149245 =====
Processing: 25149245 2024-05-01
No rows.
Processing: 25149245 2024-06-01
No rows.
Processing: 25149245 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 25149245 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 25149245 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 25149245 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 25149245 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 10
Processing: 25149245 2024-12-01
No rows.
Processing: 25149245 2025-01-01
No rows.
Processing: 25149245 2025-02-01
No rows.
Processing: 25149245 2025-03-01
No rows.
Processing: 25149245 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25149245_all_months_standard_clean.csv Rows: 31

===== Player 644/1000: 531059740 =====
Processing: 531059740 2024-05-01
No rows.
Processing: 531059740 2024-06-01
No rows.
Processing: 531059740 2024-07-01
No rows.
Processing: 531059740 2024-08-01
No rows.
Processing: 531059740 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 531059740 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 531059740 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 13
Processing: 531059740 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 531059740 2025-01-01
No rows.
Processing: 531059740 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 13
Processing: 531059740 2025-03-01
No rows.
Processing: 531059740 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531059740_all_months_standard_clean.csv Rows: 44

===== Player 645/1000: 531095143 =====
Processing: 531095143 2024-05-01
No rows.
Processing: 531095143 2024-06-01
No rows.
Processing: 531095143 2024-07-01
No rows.
Processing: 531095143 2024-08-01
No rows.
Processing: 531095143 2024-09-01
No rows.
Processing: 531095143 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 531095143 2024-11-01
No rows.
Processing: 531095143 2024-12-01
No rows.
Processing: 531095143 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 531095143 2025-02-01
No rows.
Processing: 531095143 2025-03-01
No rows.
Processing: 531095143 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531095143_all_months_standard_clean.csv Rows: 11

===== Player 646/1000: 48792357 =====
Processing: 48792357 2024-05-01
No rows.
Processing: 48792357 2024-06-01
No rows.
Processing: 48792357 2024-07-01
No rows.
Processing: 48792357 2024-08-01
No rows.
Processing: 48792357 2024-09-01
No rows.
Processing: 48792357 2024-10-01
No rows.
Processing: 48792357 2024-11-01
No rows.
Processing: 48792357 2024-12-01
No rows.
Processing: 48792357 2025-01-01
No rows.
Processing: 48792357 2025-02-01
No rows.
Processing: 48792357 2025-03-01
No rows.
Processing: 48792357 2025-04-01
No rows.

===== Player 647/1000: 48765791 =====
Processing: 48765791 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 48765791 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 48765791 2024-07-01
No rows.
Processing: 48765791 2024-08-01
No rows.
Processing: 48765791 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 48765791 2024-10-01
No rows.
Processing: 48765791 2024-11-01
No rows.
Processing: 48765791 2024-12-01
No rows.
Processing: 48765791 2025-01-01
No rows.
Processing: 48765791 2025-02-01
No rows.
Processing: 48765791 2025-03-01
No rows.
Processing: 48765791 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48765791_all_months_standard_clean.csv Rows: 10

===== Player 648/1000: 33402779 =====
Processing: 33402779 2024-05-01
Rows: 7
Processing: 33402779 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 16
Processing: 33402779 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 33402779 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33402779 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 12
Processing: 33402779 2024-10-01
No rows.
Processing: 33402779 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33402779 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 33402779 2025-01-01
No rows.
Processing: 33402779 2025-02-01
No rows.
Processing: 33402779 2025-03-01
No rows.
Processing: 33402779 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33402779_all_months_standard_clean.csv Rows: 59

===== Player 649/1000: 537075454 =====
Processing: 537075454 2024-05-01
No rows.
Processing: 537075454 2024-06-01
No rows.
Processing: 537075454 2024-07-01
No rows.
Processing: 537075454 2024-08-01
No rows.
Processing: 537075454 2024-09-01
No rows.
Processing: 537075454 2024-10-01
No rows.
Processing: 537075454 2024-11-01
No rows.
Processing: 537075454 2024-12-01
No rows.
Processing: 537075454 2025-01-01
No rows.
Processing: 537075454 2025-02-01
No rows.
Processing: 537075454 2025-03-01
No rows.
Processing: 537075454 2025-04-01
No rows.

===== Player 650/1000: 537010077 =====
Processing: 537010077 2024-05-01
No rows.
Processing: 537010077 2024-06-01
No rows.
Processing: 537010077 2024-07-01
No rows.
Processing: 537010077 2024-08-01
No rows.
Processing: 537010077 2024-09-01
No rows.
Processing: 537010077 2024-10-01
No rows.
Processing: 537010077 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 537010077 2024-12-01
No rows.
Processing: 537010077 2025-01-01
No rows.
Processing: 537010077 2025-02-01
No rows.
Processing: 537010077 2025-03-01
No rows.
Processing: 537010077 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537010077_all_months_standard_clean.csv Rows: 4

===== Player 651/1000: 25766465 =====
Processing: 25766465 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 25766465 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 25766465 2024-07-01
No rows.
Processing: 25766465 2024-08-01
No rows.
Processing: 25766465 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 13
Processing: 25766465 2024-10-01
No rows.
Processing: 25766465 2024-11-01
No rows.
Processing: 25766465 2024-12-01
No rows.
Processing: 25766465 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 17
Processing: 25766465 2025-02-01
No rows.
Processing: 25766465 2025-03-01
No rows.
Processing: 25766465 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25766465_all_months_standard_clean.csv Rows: 41

===== Player 652/1000: 45052646 =====
Processing: 45052646 2024-05-01
No rows.
Processing: 45052646 2024-06-01
No rows.
Processing: 45052646 2024-07-01
No rows.
Processing: 45052646 2024-08-01
No rows.
Processing: 45052646 2024-09-01
No rows.
Processing: 45052646 2024-10-01
No rows.
Processing: 45052646 2024-11-01
No rows.
Processing: 45052646 2024-12-01
No rows.
Processing: 45052646 2025-01-01
No rows.
Processing: 45052646 2025-02-01
No rows.
Processing: 45052646 2025-03-01
No rows.
Processing: 45052646 2025-04-01
No rows.

===== Player 653/1000: 88142388 =====
Processing: 88142388 2024-05-01
No rows.
Processing: 88142388 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 88142388 2024-07-01
No rows.
Processing: 88142388 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 88142388 2024-09-01
Failed: 88142388 2024-09-01 TimeoutError('Page.goto: Timeout 60000ms exceeded.\nCall log:\n  - navigating to "https://ratings.fide.com/calculations.phtml?id_number=88142388&period=2024-09-01&rating=0", waiting until "networkidle"\n')
Processing: 88142388 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 88142388 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 88142388 2024-12-01
No rows.
Processing: 88142388 2025-01-01
No rows.
Processing: 88142388 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 88142388 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 88142388 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88142388_all_months_standard_clean.csv Rows: 24

===== Player 654/1000: 48753580 =====
Processing: 48753580 2024-05-01
No rows.
Processing: 48753580 2024-06-01
No rows.
Processing: 48753580 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 48753580 2024-08-01
No rows.
Processing: 48753580 2024-09-01
No rows.
Processing: 48753580 2024-10-01
No rows.
Processing: 48753580 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 48753580 2024-12-01
No rows.
Processing: 48753580 2025-01-01
No rows.
Processing: 48753580 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 48753580 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 48753580 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48753580_all_months_standard_clean.csv Rows: 22

===== Player 655/1000: 25976206 =====
Processing: 25976206 2024-05-01
No rows.
Processing: 25976206 2024-06-01
No rows.
Processing: 25976206 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 25976206 2024-08-01
No rows.
Processing: 25976206 2024-09-01
No rows.
Processing: 25976206 2024-10-01
No rows.
Processing: 25976206 2024-11-01
No rows.
Processing: 25976206 2024-12-01
No rows.
Processing: 25976206 2025-01-01
No rows.
Processing: 25976206 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 25976206 2025-03-01
No rows.
Processing: 25976206 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25976206_all_months_standard_clean.csv Rows: 8

===== Player 656/1000: 25735489 =====
Processing: 25735489 2024-05-01
No rows.
Processing: 25735489 2024-06-01
No rows.
Processing: 25735489 2024-07-01
No rows.
Processing: 25735489 2024-08-01
No rows.
Processing: 25735489 2024-09-01
No rows.
Processing: 25735489 2024-10-01
No rows.
Processing: 25735489 2024-11-01
No rows.
Processing: 25735489 2024-12-01
No rows.
Processing: 25735489 2025-01-01
No rows.
Processing: 25735489 2025-02-01
No rows.
Processing: 25735489 2025-03-01
No rows.
Processing: 25735489 2025-04-01
No rows.

===== Player 657/1000: 33410526 =====
Processing: 33410526 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 12
Processing: 33410526 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 18
Processing: 33410526 2024-07-01
No rows.
Processing: 33410526 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33410526 2024-09-01
No rows.
Processing: 33410526 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 12
Processing: 33410526 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 15
Processing: 33410526 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 33410526 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 33410526 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 10
Processing: 33410526 2025-03-01
No rows.
Processing: 33410526 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33410526_all_months_standard_clean.csv Rows: 87

===== Player 658/1000: 547070927 =====
Processing: 547070927 2024-05-01
No rows.
Processing: 547070927 2024-06-01
No rows.
Processing: 547070927 2024-07-01
No rows.
Processing: 547070927 2024-08-01
No rows.
Processing: 547070927 2024-09-01
No rows.
Processing: 547070927 2024-10-01
No rows.
Processing: 547070927 2024-11-01
No rows.
Processing: 547070927 2024-12-01
No rows.
Processing: 547070927 2025-01-01
No rows.
Processing: 547070927 2025-02-01
No rows.
Processing: 547070927 2025-03-01
No rows.
Processing: 547070927 2025-04-01
No rows.

===== Player 659/1000: 88131807 =====
Processing: 88131807 2024-05-01
No rows.
Processing: 88131807 2024-06-01
No rows.
Processing: 88131807 2024-07-01
No rows.
Processing: 88131807 2024-08-01
No rows.
Processing: 88131807 2024-09-01
No rows.
Processing: 88131807 2024-10-01
No rows.
Processing: 88131807 2024-11-01
No rows.
Processing: 88131807 2024-12-01
No rows.
Processing: 88131807 2025-01-01
No rows.
Processing: 88131807 2025-02-01
No rows.
Processing: 88131807 2025-03-01
No rows.
Processing: 88131807 2025-04-01
No rows.

===== Player 660/1000: 33411360 =====
Processing: 33411360 2024-05-01
No rows.
Processing: 33411360 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 33411360 2024-07-01
No rows.
Processing: 33411360 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33411360 2024-09-01
No rows.
Processing: 33411360 2024-10-01
No rows.
Processing: 33411360 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33411360 2024-12-01
No rows.
Processing: 33411360 2025-01-01
No rows.
Processing: 33411360 2025-02-01
No rows.
Processing: 33411360 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 33411360 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33411360_all_months_standard_clean.csv Rows: 24

===== Player 661/1000: 33386137 =====
Processing: 33386137 2024-05-01
No rows.
Processing: 33386137 2024-06-01
No rows.
Processing: 33386137 2024-07-01
No rows.
Processing: 33386137 2024-08-01
No rows.
Processing: 33386137 2024-09-01
No rows.
Processing: 33386137 2024-10-01
No rows.
Processing: 33386137 2024-11-01
No rows.
Processing: 33386137 2024-12-01
No rows.
Processing: 33386137 2025-01-01
No rows.
Processing: 33386137 2025-02-01
No rows.
Processing: 33386137 2025-03-01
No rows.
Processing: 33386137 2025-04-01
No rows.

===== Player 662/1000: 33401780 =====
Processing: 33401780 2024-05-01
No rows.
Processing: 33401780 2024-06-01
No rows.
Processing: 33401780 2024-07-01
No rows.
Processing: 33401780 2024-08-01
No rows.
Processing: 33401780 2024-09-01
No rows.
Processing: 33401780 2024-10-01
No rows.
Processing: 33401780 2024-11-01
No rows.
Processing: 33401780 2024-12-01
No rows.
Processing: 33401780 2025-01-01
No rows.
Processing: 33401780 2025-02-01
No rows.
Processing: 33401780 2025-03-01
No rows.
Processing: 33401780 2025-04-01
No rows.

===== Player 663/1000: 48730963 =====
Processing: 48730963 2024-05-01
No rows.
Processing: 48730963 2024-06-01
No rows.
Processing: 48730963 2024-07-01
No rows.
Processing: 48730963 2024-08-01
No rows.
Processing: 48730963 2024-09-01
No rows.
Processing: 48730963 2024-10-01
No rows.
Processing: 48730963 2024-11-01
No rows.
Processing: 48730963 2024-12-01
No rows.
Processing: 48730963 2025-01-01
No rows.
Processing: 48730963 2025-02-01
No rows.
Processing: 48730963 2025-03-01
No rows.
Processing: 48730963 2025-04-01
No rows.

===== Player 664/1000: 537047310 =====
Processing: 537047310 2024-05-01
No rows.
Processing: 537047310 2024-06-01
No rows.
Processing: 537047310 2024-07-01
No rows.
Processing: 537047310 2024-08-01
No rows.
Processing: 537047310 2024-09-01
No rows.
Processing: 537047310 2024-10-01
No rows.
Processing: 537047310 2024-11-01
No rows.
Processing: 537047310 2024-12-01
No rows.
Processing: 537047310 2025-01-01
No rows.
Processing: 537047310 2025-02-01
No rows.
Processing: 537047310 2025-03-01
No rows.
Processing: 537047310 2025-04-01
No rows.

===== Player 665/1000: 537087177 =====
Processing: 537087177 2024-05-01
No rows.
Processing: 537087177 2024-06-01
No rows.
Processing: 537087177 2024-07-01
No rows.
Processing: 537087177 2024-08-01
No rows.
Processing: 537087177 2024-09-01
No rows.
Processing: 537087177 2024-10-01
No rows.
Processing: 537087177 2024-11-01
No rows.
Processing: 537087177 2024-12-01
No rows.
Processing: 537087177 2025-01-01
No rows.
Processing: 537087177 2025-02-01
No rows.
Processing: 537087177 2025-03-01
No rows.
Processing: 537087177 2025-04-01
No rows.

===== Player 666/1000: 558072241 =====
Processing: 558072241 2024-05-01
No rows.
Processing: 558072241 2024-06-01
No rows.
Processing: 558072241 2024-07-01
No rows.
Processing: 558072241 2024-08-01
No rows.
Processing: 558072241 2024-09-01
No rows.
Processing: 558072241 2024-10-01
No rows.
Processing: 558072241 2024-11-01
No rows.
Processing: 558072241 2024-12-01
No rows.
Processing: 558072241 2025-01-01
No rows.
Processing: 558072241 2025-02-01
No rows.
Processing: 558072241 2025-03-01
No rows.
Processing: 558072241 2025-04-01
No rows.

===== Player 667/1000: 531044603 =====
Processing: 531044603 2024-05-01
No rows.
Processing: 531044603 2024-06-01
No rows.
Processing: 531044603 2024-07-01
No rows.
Processing: 531044603 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 531044603 2024-09-01
No rows.
Processing: 531044603 2024-10-01
No rows.
Processing: 531044603 2024-11-01
No rows.
Processing: 531044603 2024-12-01
No rows.
Processing: 531044603 2025-01-01
No rows.
Processing: 531044603 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 531044603 2025-03-01
No rows.
Processing: 531044603 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531044603_all_months_standard_clean.csv Rows: 8

===== Player 668/1000: 25158830 =====
Processing: 25158830 2024-05-01
No rows.
Processing: 25158830 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 25158830 2024-07-01
No rows.
Processing: 25158830 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 25158830 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 25158830 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 25158830 2024-11-01
No rows.
Processing: 25158830 2024-12-01
No rows.
Processing: 25158830 2025-01-01
No rows.
Processing: 25158830 2025-02-01
No rows.
Processing: 25158830 2025-03-01
No rows.
Processing: 25158830 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25158830_all_months_standard_clean.csv Rows: 18

===== Player 669/1000: 429045924 =====
Processing: 429045924 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 15
Processing: 429045924 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 14
Processing: 429045924 2024-07-01
No rows.
Processing: 429045924 2024-08-01
No rows.
Processing: 429045924 2024-09-01
No rows.
Processing: 429045924 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 12
Processing: 429045924 2024-11-01
No rows.
Processing: 429045924 2024-12-01
No rows.
Processing: 429045924 2025-01-01
No rows.
Processing: 429045924 2025-02-01
No rows.
Processing: 429045924 2025-03-01
No rows.
Processing: 429045924 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429045924_all_months_standard_clean.csv Rows: 41

===== Player 670/1000: 25140930 =====
Processing: 25140930 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 25140930 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 12
Processing: 25140930 2024-07-01
No rows.
Processing: 25140930 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 13
Processing: 25140930 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 25140930 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 20
Processing: 25140930 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 14
Processing: 25140930 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 25140930 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 15
Processing: 25140930 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 17
Processing: 25140930 2025-03-01
No rows.
Processing: 25140930 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25140930_all_months_standard_clean.csv Rows: 111

===== Player 671/1000: 25915150 =====
Processing: 25915150 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 16
Processing: 25915150 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 11
Processing: 25915150 2024-07-01
No rows.
Processing: 25915150 2024-08-01
No rows.
Processing: 25915150 2024-09-01
No rows.
Processing: 25915150 2024-10-01
No rows.
Processing: 25915150 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 25915150 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 25915150 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 25915150 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 25915150 2025-03-01
No rows.
Processing: 25915150 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25915150_all_months_standard_clean.csv Rows: 48

===== Player 672/1000: 33437114 =====
Processing: 33437114 2024-05-01
No rows.
Processing: 33437114 2024-06-01
No rows.
Processing: 33437114 2024-07-01
No rows.
Processing: 33437114 2024-08-01
No rows.
Processing: 33437114 2024-09-01
No rows.
Processing: 33437114 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 33437114 2024-11-01
No rows.
Processing: 33437114 2024-12-01
No rows.
Processing: 33437114 2025-01-01
No rows.
Processing: 33437114 2025-02-01
No rows.
Processing: 33437114 2025-03-01
No rows.
Processing: 33437114 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33437114_all_months_standard_clean.csv Rows: 2

===== Player 673/1000: 429020522 =====
Processing: 429020522 2024-05-01
No rows.
Processing: 429020522 2024-06-01
No rows.
Processing: 429020522 2024-07-01
No rows.
Processing: 429020522 2024-08-01
No rows.
Processing: 429020522 2024-09-01
No rows.
Processing: 429020522 2024-10-01
No rows.
Processing: 429020522 2024-11-01
No rows.
Processing: 429020522 2024-12-01
No rows.
Processing: 429020522 2025-01-01
No rows.
Processing: 429020522 2025-02-01
No rows.
Processing: 429020522 2025-03-01
No rows.
Processing: 429020522 2025-04-01
No rows.

===== Player 674/1000: 33420165 =====
Processing: 33420165 2024-05-01
No rows.
Processing: 33420165 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 33420165 2024-07-01
No rows.
Processing: 33420165 2024-08-01
No rows.
Processing: 33420165 2024-09-01
No rows.
Processing: 33420165 2024-10-01
No rows.
Processing: 33420165 2024-11-01
No rows.
Processing: 33420165 2024-12-01
No rows.
Processing: 33420165 2025-01-01
No rows.
Processing: 33420165 2025-02-01
No rows.
Processing: 33420165 2025-03-01
No rows.
Processing: 33420165 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33420165_all_months_standard_clean.csv Rows: 6

===== Player 675/1000: 48767662 =====
Processing: 48767662 2024-05-01
No rows.
Processing: 48767662 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 48767662 2024-07-01
No rows.
Processing: 48767662 2024-08-01
No rows.
Processing: 48767662 2024-09-01
No rows.
Processing: 48767662 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 48767662 2024-11-01
No rows.
Processing: 48767662 2024-12-01
No rows.
Processing: 48767662 2025-01-01
No rows.
Processing: 48767662 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 48767662 2025-03-01
No rows.
Processing: 48767662 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48767662_all_months_standard_clean.csv Rows: 21

===== Player 676/1000: 531008046 =====
Processing: 531008046 2024-05-01
No rows.
Processing: 531008046 2024-06-01
No rows.
Processing: 531008046 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 531008046 2024-08-01
No rows.
Processing: 531008046 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 531008046 2024-10-01
No rows.
Processing: 531008046 2024-11-01
No rows.
Processing: 531008046 2024-12-01
No rows.
Processing: 531008046 2025-01-01
No rows.
Processing: 531008046 2025-02-01
No rows.
Processing: 531008046 2025-03-01
No rows.
Processing: 531008046 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531008046_all_months_standard_clean.csv Rows: 17

===== Player 677/1000: 531023924 =====
Processing: 531023924 2024-05-01
No rows.
Processing: 531023924 2024-06-01
No rows.
Processing: 531023924 2024-07-01
No rows.
Processing: 531023924 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 531023924 2024-09-01
No rows.
Processing: 531023924 2024-10-01
No rows.
Processing: 531023924 2024-11-01
No rows.
Processing: 531023924 2024-12-01
No rows.
Processing: 531023924 2025-01-01
No rows.
Processing: 531023924 2025-02-01
No rows.
Processing: 531023924 2025-03-01
No rows.
Processing: 531023924 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531023924_all_months_standard_clean.csv Rows: 5

===== Player 678/1000: 537005219 =====
Processing: 537005219 2024-05-01
No rows.
Processing: 537005219 2024-06-01
No rows.
Processing: 537005219 2024-07-01
No rows.
Processing: 537005219 2024-08-01
No rows.
Processing: 537005219 2024-09-01
No rows.
Processing: 537005219 2024-10-01
No rows.
Processing: 537005219 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 537005219 2024-12-01
No rows.
Processing: 537005219 2025-01-01
No rows.
Processing: 537005219 2025-02-01
No rows.
Processing: 537005219 2025-03-01
No rows.
Processing: 537005219 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537005219_all_months_standard_clean.csv Rows: 1

===== Player 679/1000: 33421307 =====
Processing: 33421307 2024-05-01
No rows.
Processing: 33421307 2024-06-01
No rows.
Processing: 33421307 2024-07-01
No rows.
Processing: 33421307 2024-08-01
No rows.
Processing: 33421307 2024-09-01
No rows.
Processing: 33421307 2024-10-01
No rows.
Processing: 33421307 2024-11-01
No rows.
Processing: 33421307 2024-12-01
No rows.
Processing: 33421307 2025-01-01
No rows.
Processing: 33421307 2025-02-01
No rows.
Processing: 33421307 2025-03-01
No rows.
Processing: 33421307 2025-04-01
No rows.

===== Player 680/1000: 33330735 =====
Processing: 33330735 2024-05-01
No rows.
Processing: 33330735 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 33330735 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33330735 2024-08-01
No rows.
Processing: 33330735 2024-09-01
No rows.
Processing: 33330735 2024-10-01
No rows.
Processing: 33330735 2024-11-01
No rows.
Processing: 33330735 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 33330735 2025-01-01
No rows.
Processing: 33330735 2025-02-01
No rows.
Processing: 33330735 2025-03-01
No rows.
Processing: 33330735 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33330735_all_months_standard_clean.csv Rows: 14

===== Player 681/1000: 558035362 =====
Processing: 558035362 2024-05-01
No rows.
Processing: 558035362 2024-06-01
No rows.
Processing: 558035362 2024-07-01
No rows.
Processing: 558035362 2024-08-01
No rows.
Processing: 558035362 2024-09-01
No rows.
Processing: 558035362 2024-10-01
No rows.
Processing: 558035362 2024-11-01
No rows.
Processing: 558035362 2024-12-01
No rows.
Processing: 558035362 2025-01-01
No rows.
Processing: 558035362 2025-02-01
No rows.
Processing: 558035362 2025-03-01
No rows.
Processing: 558035362 2025-04-01
No rows.

===== Player 682/1000: 48796166 =====
Processing: 48796166 2024-05-01
No rows.
Processing: 48796166 2024-06-01
No rows.
Processing: 48796166 2024-07-01
No rows.
Processing: 48796166 2024-08-01
No rows.
Processing: 48796166 2024-09-01
No rows.
Processing: 48796166 2024-10-01
No rows.
Processing: 48796166 2024-11-01
No rows.
Processing: 48796166 2024-12-01
No rows.
Processing: 48796166 2025-01-01
No rows.
Processing: 48796166 2025-02-01
No rows.
Processing: 48796166 2025-03-01
No rows.
Processing: 48796166 2025-04-01
No rows.

===== Player 683/1000: 547065389 =====
Processing: 547065389 2024-05-01
No rows.
Processing: 547065389 2024-06-01
No rows.
Processing: 547065389 2024-07-01
No rows.
Processing: 547065389 2024-08-01
No rows.
Processing: 547065389 2024-09-01
No rows.
Processing: 547065389 2024-10-01
No rows.
Processing: 547065389 2024-11-01
No rows.
Processing: 547065389 2024-12-01
No rows.
Processing: 547065389 2025-01-01
No rows.
Processing: 547065389 2025-02-01
No rows.
Processing: 547065389 2025-03-01
No rows.
Processing: 547065389 2025-04-01
No rows.

===== Player 684/1000: 25154370 =====
Processing: 25154370 2024-05-01
No rows.
Processing: 25154370 2024-06-01
No rows.
Processing: 25154370 2024-07-01
No rows.
Processing: 25154370 2024-08-01
No rows.
Processing: 25154370 2024-09-01
No rows.
Processing: 25154370 2024-10-01
No rows.
Processing: 25154370 2024-11-01
No rows.
Processing: 25154370 2024-12-01
No rows.
Processing: 25154370 2025-01-01
No rows.
Processing: 25154370 2025-02-01
No rows.
Processing: 25154370 2025-03-01
No rows.
Processing: 25154370 2025-04-01
No rows.

===== Player 685/1000: 33432325 =====
Processing: 33432325 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 33432325 2024-06-01
No rows.
Processing: 33432325 2024-07-01
No rows.
Processing: 33432325 2024-08-01
No rows.
Processing: 33432325 2024-09-01
No rows.
Processing: 33432325 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 33432325 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 33432325 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 33432325 2025-01-01
No rows.
Processing: 33432325 2025-02-01
No rows.
Processing: 33432325 2025-03-01
No rows.
Processing: 33432325 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33432325_all_months_standard_clean.csv Rows: 14

===== Player 686/1000: 48767883 =====
Processing: 48767883 2024-05-01
No rows.
Processing: 48767883 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 48767883 2024-07-01
No rows.
Processing: 48767883 2024-08-01
No rows.
Processing: 48767883 2024-09-01
No rows.
Processing: 48767883 2024-10-01
No rows.
Processing: 48767883 2024-11-01
No rows.
Processing: 48767883 2024-12-01
No rows.
Processing: 48767883 2025-01-01
No rows.
Processing: 48767883 2025-02-01
No rows.
Processing: 48767883 2025-03-01
No rows.
Processing: 48767883 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48767883_all_months_standard_clean.csv Rows: 5

===== Player 687/1000: 429038863 =====
Processing: 429038863 2024-05-01
No rows.
Processing: 429038863 2024-06-01
No rows.
Processing: 429038863 2024-07-01
No rows.
Processing: 429038863 2024-08-01
No rows.
Processing: 429038863 2024-09-01
No rows.
Processing: 429038863 2024-10-01
No rows.
Processing: 429038863 2024-11-01
No rows.
Processing: 429038863 2024-12-01
No rows.
Processing: 429038863 2025-01-01
No rows.
Processing: 429038863 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 429038863 2025-03-01
No rows.
Processing: 429038863 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429038863_all_months_standard_clean.csv Rows: 9

===== Player 688/1000: 88109267 =====
Processing: 88109267 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 88109267 2024-06-01
No rows.
Processing: 88109267 2024-07-01
Rows: 6
Processing: 88109267 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 88109267 2024-09-01
No rows.
Processing: 88109267 2024-10-01
No rows.
Processing: 88109267 2024-11-01
No rows.
Processing: 88109267 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 88109267 2025-01-01
No rows.
Processing: 88109267 2025-02-01
No rows.
Processing: 88109267 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 88109267 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88109267_all_months_standard_clean.csv Rows: 27

===== Player 689/1000: 25173308 =====
Processing: 25173308 2024-05-01
No rows.
Processing: 25173308 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 10
Processing: 25173308 2024-07-01
No rows.
Processing: 25173308 2024-08-01
No rows.
Processing: 25173308 2024-09-01
No rows.
Processing: 25173308 2024-10-01
No rows.
Processing: 25173308 2024-11-01
No rows.
Processing: 25173308 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 25173308 2025-01-01
No rows.
Processing: 25173308 2025-02-01
No rows.
Processing: 25173308 2025-03-01
No rows.
Processing: 25173308 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25173308_all_months_standard_clean.csv Rows: 17

===== Player 690/1000: 429094240 =====
Processing: 429094240 2024-05-01
No rows.
Processing: 429094240 2024-06-01
No rows.
Processing: 429094240 2024-07-01
No rows.
Processing: 429094240 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 429094240 2024-09-01
No rows.
Processing: 429094240 2024-10-01
No rows.
Processing: 429094240 2024-11-01
No rows.
Processing: 429094240 2024-12-01
No rows.
Processing: 429094240 2025-01-01
No rows.
Processing: 429094240 2025-02-01
No rows.
Processing: 429094240 2025-03-01
No rows.
Processing: 429094240 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429094240_all_months_standard_clean.csv Rows: 5

===== Player 691/1000: 531063284 =====
Processing: 531063284 2024-05-01
No rows.
Processing: 531063284 2024-06-01
No rows.
Processing: 531063284 2024-07-01
No rows.
Processing: 531063284 2024-08-01
No rows.
Processing: 531063284 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 531063284 2024-10-01
No rows.
Processing: 531063284 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 531063284 2024-12-01
No rows.
Processing: 531063284 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 531063284 2025-02-01
No rows.
Processing: 531063284 2025-03-01
No rows.
Processing: 531063284 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531063284_all_months_standard_clean.csv Rows: 20

===== Player 692/1000: 88144585 =====
Processing: 88144585 2024-05-01
No rows.
Processing: 88144585 2024-06-01
No rows.
Processing: 88144585 2024-07-01
No rows.
Processing: 88144585 2024-08-01
Rows: 8
Processing: 88144585 2024-09-01
No rows.
Processing: 88144585 2024-10-01
No rows.
Processing: 88144585 2024-11-01
No rows.
Processing: 88144585 2024-12-01
No rows.
Processing: 88144585 2025-01-01
No rows.
Processing: 88144585 2025-02-01
No rows.
Processing: 88144585 2025-03-01
No rows.
Processing: 88144585 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88144585_all_months_standard_clean.csv Rows: 8

===== Player 693/1000: 88120066 =====
Processing: 88120066 2024-05-01
No rows.
Processing: 88120066 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 88120066 2024-07-01
No rows.
Processing: 88120066 2024-08-01
No rows.
Processing: 88120066 2024-09-01
No rows.
Processing: 88120066 2024-10-01
No rows.
Processing: 88120066 2024-11-01
No rows.
Processing: 88120066 2024-12-01
No rows.
Processing: 88120066 2025-01-01
No rows.
Processing: 88120066 2025-02-01
No rows.
Processing: 88120066 2025-03-01
No rows.
Processing: 88120066 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88120066_all_months_standard_clean.csv Rows: 1

===== Player 694/1000: 547046554 =====
Processing: 547046554 2024-05-01
No rows.
Processing: 547046554 2024-06-01
No rows.
Processing: 547046554 2024-07-01
No rows.
Processing: 547046554 2024-08-01
No rows.
Processing: 547046554 2024-09-01
No rows.
Processing: 547046554 2024-10-01
No rows.
Processing: 547046554 2024-11-01
No rows.
Processing: 547046554 2024-12-01
No rows.
Processing: 547046554 2025-01-01
No rows.
Processing: 547046554 2025-02-01
No rows.
Processing: 547046554 2025-03-01
No rows.
Processing: 547046554 2025-04-01
No rows.

===== Player 695/1000: 531019560 =====
Processing: 531019560 2024-05-01
No rows.
Processing: 531019560 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 531019560 2024-07-01
No rows.
Processing: 531019560 2024-08-01
No rows.
Processing: 531019560 2024-09-01
No rows.
Processing: 531019560 2024-10-01
No rows.
Processing: 531019560 2024-11-01
No rows.
Processing: 531019560 2024-12-01
No rows.
Processing: 531019560 2025-01-01
No rows.
Processing: 531019560 2025-02-01
No rows.
Processing: 531019560 2025-03-01
No rows.
Processing: 531019560 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531019560_all_months_standard_clean.csv Rows: 1

===== Player 696/1000: 25966898 =====
Processing: 25966898 2024-05-01
No rows.
Processing: 25966898 2024-06-01
No rows.
Processing: 25966898 2024-07-01
No rows.
Processing: 25966898 2024-08-01
No rows.
Processing: 25966898 2024-09-01
No rows.
Processing: 25966898 2024-10-01
No rows.
Processing: 25966898 2024-11-01
No rows.
Processing: 25966898 2024-12-01
No rows.
Processing: 25966898 2025-01-01
No rows.
Processing: 25966898 2025-02-01
No rows.
Processing: 25966898 2025-03-01
No rows.
Processing: 25966898 2025-04-01
No rows.

===== Player 697/1000: 88188523 =====
Processing: 88188523 2024-05-01
No rows.
Processing: 88188523 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 88188523 2024-07-01
No rows.
Processing: 88188523 2024-08-01
No rows.
Processing: 88188523 2024-09-01
No rows.
Processing: 88188523 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 88188523 2024-11-01
No rows.
Processing: 88188523 2024-12-01
No rows.
Processing: 88188523 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 88188523 2025-02-01
No rows.
Processing: 88188523 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 88188523 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88188523_all_months_standard_clean.csv Rows: 11

===== Player 698/1000: 558008365 =====
Processing: 558008365 2024-05-01
No rows.
Processing: 558008365 2024-06-01
No rows.
Processing: 558008365 2024-07-01
No rows.
Processing: 558008365 2024-08-01
No rows.
Processing: 558008365 2024-09-01
No rows.
Processing: 558008365 2024-10-01
No rows.
Processing: 558008365 2024-11-01
No rows.
Processing: 558008365 2024-12-01
No rows.
Processing: 558008365 2025-01-01
No rows.
Processing: 558008365 2025-02-01
No rows.
Processing: 558008365 2025-03-01
No rows.
Processing: 558008365 2025-04-01
No rows.

===== Player 699/1000: 558045171 =====
Processing: 558045171 2024-05-01
No rows.
Processing: 558045171 2024-06-01
No rows.
Processing: 558045171 2024-07-01
No rows.
Processing: 558045171 2024-08-01
No rows.
Processing: 558045171 2024-09-01
No rows.
Processing: 558045171 2024-10-01
No rows.
Processing: 558045171 2024-11-01
No rows.
Processing: 558045171 2024-12-01
No rows.
Processing: 558045171 2025-01-01
No rows.
Processing: 558045171 2025-02-01
No rows.
Processing: 558045171 2025-03-01
No rows.
Processing: 558045171 2025-04-01
No rows.

===== Player 700/1000: 33319626 =====
Processing: 33319626 2024-05-01
No rows.
Processing: 33319626 2024-06-01
No rows.
Processing: 33319626 2024-07-01
No rows.
Processing: 33319626 2024-08-01
No rows.
Processing: 33319626 2024-09-01
No rows.
Processing: 33319626 2024-10-01
No rows.
Processing: 33319626 2024-11-01
No rows.
Processing: 33319626 2024-12-01
No rows.
Processing: 33319626 2025-01-01
No rows.
Processing: 33319626 2025-02-01
No rows.
Processing: 33319626 2025-03-01
No rows.
Processing: 33319626 2025-04-01
No rows.

===== Player 701/1000: 25973835 =====
Processing: 25973835 2024-05-01
No rows.
Processing: 25973835 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 25973835 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 25973835 2024-08-01
No rows.
Processing: 25973835 2024-09-01
No rows.
Processing: 25973835 2024-10-01
No rows.
Processing: 25973835 2024-11-01
No rows.
Processing: 25973835 2024-12-01
No rows.
Processing: 25973835 2025-01-01
No rows.
Processing: 25973835 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 25973835 2025-03-01
No rows.
Processing: 25973835 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25973835_all_months_standard_clean.csv Rows: 12

===== Player 702/1000: 429039118 =====
Processing: 429039118 2024-05-01
No rows.
Processing: 429039118 2024-06-01
No rows.
Processing: 429039118 2024-07-01
No rows.
Processing: 429039118 2024-08-01
No rows.
Processing: 429039118 2024-09-01
No rows.
Processing: 429039118 2024-10-01
No rows.
Processing: 429039118 2024-11-01
No rows.
Processing: 429039118 2024-12-01
No rows.
Processing: 429039118 2025-01-01
No rows.
Processing: 429039118 2025-02-01
No rows.
Processing: 429039118 2025-03-01
No rows.
Processing: 429039118 2025-04-01
No rows.

===== Player 703/1000: 429005191 =====
Processing: 429005191 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 11
Processing: 429005191 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 10
Processing: 429005191 2024-07-01
No rows.
Processing: 429005191 2024-08-01
No rows.
Processing: 429005191 2024-09-01
No rows.
Processing: 429005191 2024-10-01
No rows.
Processing: 429005191 2024-11-01
No rows.
Processing: 429005191 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 429005191 2025-01-01
No rows.
Processing: 429005191 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 429005191 2025-03-01
No rows.
Processing: 429005191 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429005191_all_months_standard_clean.csv Rows: 33

===== Player 704/1000: 25682652 =====
Processing: 25682652 2024-05-01
No rows.
Processing: 25682652 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 13
Processing: 25682652 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 13
Processing: 25682652 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 25682652 2024-09-01
No rows.
Processing: 25682652 2024-10-01
No rows.
Processing: 25682652 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 25682652 2024-12-01
No rows.
Processing: 25682652 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 25682652 2025-02-01
No rows.
Processing: 25682652 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 14
Processing: 25682652 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25682652_all_months_standard_clean.csv Rows: 68

===== Player 705/1000: 537023896 =====
Processing: 537023896 2024-05-01
No rows.
Processing: 537023896 2024-06-01
No rows.
Processing: 537023896 2024-07-01
No rows.
Processing: 537023896 2024-08-01
No rows.
Processing: 537023896 2024-09-01
No rows.
Processing: 537023896 2024-10-01
No rows.
Processing: 537023896 2024-11-01
No rows.
Processing: 537023896 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 537023896 2025-01-01
No rows.
Processing: 537023896 2025-02-01
No rows.
Processing: 537023896 2025-03-01
No rows.
Processing: 537023896 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537023896_all_months_standard_clean.csv Rows: 7

===== Player 706/1000: 48786047 =====
Processing: 48786047 2024-05-01
No rows.
Processing: 48786047 2024-06-01
No rows.
Processing: 48786047 2024-07-01
No rows.
Processing: 48786047 2024-08-01
No rows.
Processing: 48786047 2024-09-01
No rows.
Processing: 48786047 2024-10-01
No rows.
Processing: 48786047 2024-11-01
No rows.
Processing: 48786047 2024-12-01
No rows.
Processing: 48786047 2025-01-01
No rows.
Processing: 48786047 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 48786047 2025-03-01
No rows.
Processing: 48786047 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48786047_all_months_standard_clean.csv Rows: 6

===== Player 707/1000: 25785974 =====
Processing: 25785974 2024-05-01
No rows.
Processing: 25785974 2024-06-01
No rows.
Processing: 25785974 2024-07-01
No rows.
Processing: 25785974 2024-08-01
No rows.
Processing: 25785974 2024-09-01
No rows.
Processing: 25785974 2024-10-01
No rows.
Processing: 25785974 2024-11-01
No rows.
Processing: 25785974 2024-12-01
No rows.
Processing: 25785974 2025-01-01
No rows.
Processing: 25785974 2025-02-01
No rows.
Processing: 25785974 2025-03-01
No rows.
Processing: 25785974 2025-04-01
No rows.

===== Player 708/1000: 429012635 =====
Processing: 429012635 2024-05-01
No rows.
Processing: 429012635 2024-06-01
No rows.
Processing: 429012635 2024-07-01
No rows.
Processing: 429012635 2024-08-01
No rows.
Processing: 429012635 2024-09-01
No rows.
Processing: 429012635 2024-10-01
No rows.
Processing: 429012635 2024-11-01
No rows.
Processing: 429012635 2024-12-01
No rows.
Processing: 429012635 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 429012635 2025-02-01
No rows.
Processing: 429012635 2025-03-01
No rows.
Processing: 429012635 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429012635_all_months_standard_clean.csv Rows: 2

===== Player 709/1000: 25773526 =====
Processing: 25773526 2024-05-01
No rows.
Processing: 25773526 2024-06-01
No rows.
Processing: 25773526 2024-07-01
No rows.
Processing: 25773526 2024-08-01
No rows.
Processing: 25773526 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 25773526 2024-10-01
No rows.
Processing: 25773526 2024-11-01
No rows.
Processing: 25773526 2024-12-01
No rows.
Processing: 25773526 2025-01-01
No rows.
Processing: 25773526 2025-02-01
No rows.
Processing: 25773526 2025-03-01
No rows.
Processing: 25773526 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25773526_all_months_standard_clean.csv Rows: 4

===== Player 710/1000: 429072832 =====
Processing: 429072832 2024-05-01
No rows.
Processing: 429072832 2024-06-01
No rows.
Processing: 429072832 2024-07-01
No rows.
Processing: 429072832 2024-08-01
No rows.
Processing: 429072832 2024-09-01
No rows.
Processing: 429072832 2024-10-01
No rows.
Processing: 429072832 2024-11-01
No rows.
Processing: 429072832 2024-12-01
No rows.
Processing: 429072832 2025-01-01
No rows.
Processing: 429072832 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 429072832 2025-03-01
No rows.
Processing: 429072832 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429072832_all_months_standard_clean.csv Rows: 4

===== Player 711/1000: 429014182 =====
Processing: 429014182 2024-05-01
No rows.
Processing: 429014182 2024-06-01
No rows.
Processing: 429014182 2024-07-01
No rows.
Processing: 429014182 2024-08-01
No rows.
Processing: 429014182 2024-09-01
No rows.
Processing: 429014182 2024-10-01
No rows.
Processing: 429014182 2024-11-01
No rows.
Processing: 429014182 2024-12-01
No rows.
Processing: 429014182 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 429014182 2025-02-01
No rows.
Processing: 429014182 2025-03-01
No rows.
Processing: 429014182 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429014182_all_months_standard_clean.csv Rows: 8

===== Player 712/1000: 48785121 =====
Processing: 48785121 2024-05-01
No rows.
Processing: 48785121 2024-06-01
No rows.
Processing: 48785121 2024-07-01
No rows.
Processing: 48785121 2024-08-01
No rows.
Processing: 48785121 2024-09-01
No rows.
Processing: 48785121 2024-10-01
No rows.
Processing: 48785121 2024-11-01
No rows.
Processing: 48785121 2024-12-01
No rows.
Processing: 48785121 2025-01-01
No rows.
Processing: 48785121 2025-02-01
No rows.
Processing: 48785121 2025-03-01
No rows.
Processing: 48785121 2025-04-01
No rows.

===== Player 713/1000: 537050591 =====
Processing: 537050591 2024-05-01
No rows.
Processing: 537050591 2024-06-01
No rows.
Processing: 537050591 2024-07-01
No rows.
Processing: 537050591 2024-08-01
No rows.
Processing: 537050591 2024-09-01
No rows.
Processing: 537050591 2024-10-01
No rows.
Processing: 537050591 2024-11-01
No rows.
Processing: 537050591 2024-12-01
No rows.
Processing: 537050591 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 537050591 2025-02-01
No rows.
Processing: 537050591 2025-03-01
No rows.
Processing: 537050591 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537050591_all_months_standard_clean.csv Rows: 1

===== Player 714/1000: 547059850 =====
Processing: 547059850 2024-05-01
No rows.
Processing: 547059850 2024-06-01
No rows.
Processing: 547059850 2024-07-01
No rows.
Processing: 547059850 2024-08-01
No rows.
Processing: 547059850 2024-09-01
No rows.
Processing: 547059850 2024-10-01
No rows.
Processing: 547059850 2024-11-01
No rows.
Processing: 547059850 2024-12-01
No rows.
Processing: 547059850 2025-01-01
No rows.
Processing: 547059850 2025-02-01
No rows.
Processing: 547059850 2025-03-01
No rows.
Processing: 547059850 2025-04-01
No rows.

===== Player 715/1000: 577029151 =====
Processing: 577029151 2024-05-01
No rows.
Processing: 577029151 2024-06-01
No rows.
Processing: 577029151 2024-07-01
No rows.
Processing: 577029151 2024-08-01
No rows.
Processing: 577029151 2024-09-01
No rows.
Processing: 577029151 2024-10-01
No rows.
Processing: 577029151 2024-11-01
No rows.
Processing: 577029151 2024-12-01
No rows.
Processing: 577029151 2025-01-01
No rows.
Processing: 577029151 2025-02-01
No rows.
Processing: 577029151 2025-03-01
No rows.
Processing: 577029151 2025-04-01
No rows.

===== Player 716/1000: 48756156 =====
Processing: 48756156 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 48756156 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 48756156 2024-07-01
No rows.
Processing: 48756156 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 48756156 2024-09-01
No rows.
Processing: 48756156 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 48756156 2024-11-01
No rows.
Processing: 48756156 2024-12-01
No rows.
Processing: 48756156 2025-01-01
No rows.
Processing: 48756156 2025-02-01
No rows.
Processing: 48756156 2025-03-01
No rows.
Processing: 48756156 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48756156_all_months_standard_clean.csv Rows: 15

===== Player 717/1000: 88122832 =====
Processing: 88122832 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 88122832 2024-06-01
No rows.
Processing: 88122832 2024-07-01
No rows.
Processing: 88122832 2024-08-01
No rows.
Processing: 88122832 2024-09-01
No rows.
Processing: 88122832 2024-10-01
No rows.
Processing: 88122832 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 88122832 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 88122832 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 88122832 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 88122832 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 88122832 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88122832_all_months_standard_clean.csv Rows: 30

===== Player 718/1000: 33421668 =====
Processing: 33421668 2024-05-01
No rows.
Processing: 33421668 2024-06-01
No rows.
Processing: 33421668 2024-07-01
No rows.
Processing: 33421668 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 33421668 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33421668 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 33421668 2024-11-01
No rows.
Processing: 33421668 2024-12-01
No rows.
Processing: 33421668 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 10
Processing: 33421668 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 33421668 2025-03-01
No rows.
Processing: 33421668 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33421668_all_months_standard_clean.csv Rows: 35

===== Player 719/1000: 48794872 =====
Processing: 48794872 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 12
Processing: 48794872 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 17
Processing: 48794872 2024-07-01
No rows.
Processing: 48794872 2024-08-01
No rows.
Processing: 48794872 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 15
Processing: 48794872 2024-10-01
No rows.
Processing: 48794872 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 48794872 2024-12-01
No rows.
Processing: 48794872 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 48794872 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 27
Processing: 48794872 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 48794872 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48794872_all_months_standard_clean.csv Rows: 86

===== Player 720/1000: 558065997 =====
Processing: 558065997 2024-05-01
No rows.
Processing: 558065997 2024-06-01
No rows.
Processing: 558065997 2024-07-01
No rows.
Processing: 558065997 2024-08-01
No rows.
Processing: 558065997 2024-09-01
No rows.
Processing: 558065997 2024-10-01
No rows.
Processing: 558065997 2024-11-01
No rows.
Processing: 558065997 2024-12-01
No rows.
Processing: 558065997 2025-01-01
No rows.
Processing: 558065997 2025-02-01
No rows.
Processing: 558065997 2025-03-01
No rows.
Processing: 558065997 2025-04-01
No rows.

===== Player 721/1000: 564052524 =====
Processing: 564052524 2024-05-01
No rows.
Processing: 564052524 2024-06-01
No rows.
Processing: 564052524 2024-07-01
No rows.
Processing: 564052524 2024-08-01
No rows.
Processing: 564052524 2024-09-01
No rows.
Processing: 564052524 2024-10-01
No rows.
Processing: 564052524 2024-11-01
No rows.
Processing: 564052524 2024-12-01
No rows.
Processing: 564052524 2025-01-01
No rows.
Processing: 564052524 2025-02-01
No rows.
Processing: 564052524 2025-03-01
No rows.
Processing: 564052524 2025-04-01
No rows.

===== Player 722/1000: 88197174 =====
Processing: 88197174 2024-05-01
No rows.
Processing: 88197174 2024-06-01
No rows.
Processing: 88197174 2024-07-01
No rows.
Processing: 88197174 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 88197174 2024-09-01
No rows.
Processing: 88197174 2024-10-01
No rows.
Processing: 88197174 2024-11-01
No rows.
Processing: 88197174 2024-12-01
No rows.
Processing: 88197174 2025-01-01
No rows.
Processing: 88197174 2025-02-01
No rows.
Processing: 88197174 2025-03-01
No rows.
Processing: 88197174 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88197174_all_months_standard_clean.csv Rows: 5

===== Player 723/1000: 33388520 =====
Processing: 33388520 2024-05-01
No rows.
Processing: 33388520 2024-06-01
No rows.
Processing: 33388520 2024-07-01
No rows.
Processing: 33388520 2024-08-01
No rows.
Processing: 33388520 2024-09-01
No rows.
Processing: 33388520 2024-10-01
No rows.
Processing: 33388520 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 33388520 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33388520 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 11
Processing: 33388520 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33388520 2025-03-01
No rows.
Processing: 33388520 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33388520_all_months_standard_clean.csv Rows: 30

===== Player 724/1000: 531013619 =====
Processing: 531013619 2024-05-01
No rows.
Processing: 531013619 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 531013619 2024-07-01
No rows.
Processing: 531013619 2024-08-01
No rows.
Processing: 531013619 2024-09-01
No rows.
Processing: 531013619 2024-10-01
No rows.
Processing: 531013619 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 531013619 2024-12-01
No rows.
Processing: 531013619 2025-01-01
No rows.
Processing: 531013619 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 531013619 2025-03-01
No rows.
Processing: 531013619 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531013619_all_months_standard_clean.csv Rows: 14

===== Player 725/1000: 48752622 =====
Processing: 48752622 2024-05-01
No rows.
Processing: 48752622 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 48752622 2024-07-01
No rows.
Processing: 48752622 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 48752622 2024-09-01
No rows.
Processing: 48752622 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 48752622 2024-11-01
No rows.
Processing: 48752622 2024-12-01
No rows.
Processing: 48752622 2025-01-01
No rows.
Processing: 48752622 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 48752622 2025-03-01
No rows.
Processing: 48752622 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48752622_all_months_standard_clean.csv Rows: 19

===== Player 726/1000: 531066445 =====
Processing: 531066445 2024-05-01
No rows.
Processing: 531066445 2024-06-01
No rows.
Processing: 531066445 2024-07-01
No rows.
Processing: 531066445 2024-08-01
No rows.
Processing: 531066445 2024-09-01
No rows.
Processing: 531066445 2024-10-01
No rows.
Processing: 531066445 2024-11-01
No rows.
Processing: 531066445 2024-12-01
No rows.
Processing: 531066445 2025-01-01
No rows.
Processing: 531066445 2025-02-01
No rows.
Processing: 531066445 2025-03-01
No rows.
Processing: 531066445 2025-04-01
No rows.

===== Player 727/1000: 537099612 =====
Processing: 537099612 2024-05-01
No rows.
Processing: 537099612 2024-06-01
No rows.
Processing: 537099612 2024-07-01
No rows.
Processing: 537099612 2024-08-01
No rows.
Processing: 537099612 2024-09-01
No rows.
Processing: 537099612 2024-10-01
No rows.
Processing: 537099612 2024-11-01
No rows.
Processing: 537099612 2024-12-01
No rows.
Processing: 537099612 2025-01-01
No rows.
Processing: 537099612 2025-02-01
No rows.
Processing: 537099612 2025-03-01
No rows.
Processing: 537099612 2025-04-01
Rows: 2
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537099612_all_months_standard_clean.csv Rows: 2

===== Player 728/1000: 558097945 =====
Processing: 558097945 2024-05-01
No rows.
Processing: 558097945 2024-06-01
No rows.
Processing: 558097945 2024-07-01
No rows.
Processing: 558097945 2024-08-01
No rows.
Processing: 558097945 2024-09-01
No rows.
Processing: 558097945 2024-10-01
No rows.
Processing: 558097945 2024-11-01
No rows.
Processing: 558097945 2024-12-01
No rows.
Processing: 558097945 2025-01-01
No rows.
Processing: 558097945 2025-02-01
No rows.
Processing: 558097945 2025-03-01
No rows.
Processing: 558097945 2025-04-01
No rows.

===== Player 729/1000: 33465614 =====
Processing: 33465614 2024-05-01
No rows.
Processing: 33465614 2024-06-01
No rows.
Processing: 33465614 2024-07-01
No rows.
Processing: 33465614 2024-08-01
No rows.
Processing: 33465614 2024-09-01
No rows.
Processing: 33465614 2024-10-01
No rows.
Processing: 33465614 2024-11-01
No rows.
Processing: 33465614 2024-12-01
Rows: 3
Processing: 33465614 2025-01-01
No rows.
Processing: 33465614 2025-02-01
No rows.
Processing: 33465614 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 33465614 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33465614_all_months_standard_clean.csv Rows: 6

===== Player 730/1000: 558023682 =====
Processing: 558023682 2024-05-01
No rows.
Processing: 558023682 2024-06-01
No rows.
Processing: 558023682 2024-07-01
No rows.
Processing: 558023682 2024-08-01
No rows.
Processing: 558023682 2024-09-01
No rows.
Processing: 558023682 2024-10-01
No rows.
Processing: 558023682 2024-11-01
No rows.
Processing: 558023682 2024-12-01
No rows.
Processing: 558023682 2025-01-01
No rows.
Processing: 558023682 2025-02-01
No rows.
Processing: 558023682 2025-03-01
No rows.
Processing: 558023682 2025-04-01
No rows.

===== Player 731/1000: 537087070 =====
Processing: 537087070 2024-05-01
No rows.
Processing: 537087070 2024-06-01
No rows.
Processing: 537087070 2024-07-01
No rows.
Processing: 537087070 2024-08-01
No rows.
Processing: 537087070 2024-09-01
No rows.
Processing: 537087070 2024-10-01
No rows.
Processing: 537087070 2024-11-01
No rows.
Processing: 537087070 2024-12-01
No rows.
Processing: 537087070 2025-01-01
No rows.
Processing: 537087070 2025-02-01
No rows.
Processing: 537087070 2025-03-01
No rows.
Processing: 537087070 2025-04-01
No rows.

===== Player 732/1000: 537037447 =====
Processing: 537037447 2024-05-01
No rows.
Processing: 537037447 2024-06-01
No rows.
Processing: 537037447 2024-07-01
No rows.
Processing: 537037447 2024-08-01
No rows.
Processing: 537037447 2024-09-01
No rows.
Processing: 537037447 2024-10-01
No rows.
Processing: 537037447 2024-11-01
No rows.
Processing: 537037447 2024-12-01
No rows.
Processing: 537037447 2025-01-01
No rows.
Processing: 537037447 2025-02-01
No rows.
Processing: 537037447 2025-03-01
No rows.
Processing: 537037447 2025-04-01
No rows.

===== Player 733/1000: 429099030 =====
Processing: 429099030 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 429099030 2024-06-01
No rows.
Processing: 429099030 2024-07-01
No rows.
Processing: 429099030 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 429099030 2024-09-01
No rows.
Processing: 429099030 2024-10-01
No rows.
Processing: 429099030 2024-11-01
No rows.
Processing: 429099030 2024-12-01
No rows.
Processing: 429099030 2025-01-01
No rows.
Processing: 429099030 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 429099030 2025-03-01
No rows.
Processing: 429099030 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429099030_all_months_standard_clean.csv Rows: 13

===== Player 734/1000: 48767514 =====
Processing: 48767514 2024-05-01
No rows.
Processing: 48767514 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 48767514 2024-07-01
No rows.
Processing: 48767514 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 48767514 2024-09-01
No rows.
Processing: 48767514 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 48767514 2024-11-01
No rows.
Processing: 48767514 2024-12-01
No rows.
Processing: 48767514 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 48767514 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 48767514 2025-03-01
No rows.
Processing: 48767514 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48767514_all_months_standard_clean.csv Rows: 19

===== Player 735/1000: 429016860 =====
Processing: 429016860 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 12
Processing: 429016860 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 429016860 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 429016860 2024-08-01
No rows.
Processing: 429016860 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 20
Processing: 429016860 2024-10-01
No rows.
Processing: 429016860 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 13
Processing: 429016860 2024-12-01
No rows.
Processing: 429016860 2025-01-01
No rows.
Processing: 429016860 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 429016860 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 429016860 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429016860_all_months_standard_clean.csv Rows: 65

===== Player 736/1000: 33489343 =====
Processing: 33489343 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 13
Processing: 33489343 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 11
Processing: 33489343 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 33489343 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 33489343 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 20
Processing: 33489343 2024-10-01
No rows.
Processing: 33489343 2024-11-01
Rows: 8
Processing: 33489343 2024-12-01
No rows.
Processing: 33489343 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 10
Processing: 33489343 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 26
Processing: 33489343 2025-03-01
No rows.
Processing: 33489343 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33489343_all_months_standard_clean.csv Rows: 108

===== Player 737/1000: 25611119 =====
Processing: 25611119 2024-05-01
No rows.
Processing: 25611119 2024-06-01
No rows.
Processing: 25611119 2024-07-01
No rows.
Processing: 25611119 2024-08-01
No rows.
Processing: 25611119 2024-09-01
No rows.
Processing: 25611119 2024-10-01
No rows.
Processing: 25611119 2024-11-01
No rows.
Processing: 25611119 2024-12-01
No rows.
Processing: 25611119 2025-01-01
No rows.
Processing: 25611119 2025-02-01
No rows.
Processing: 25611119 2025-03-01
No rows.
Processing: 25611119 2025-04-01
No rows.

===== Player 738/1000: 33384096 =====
Processing: 33384096 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 33384096 2024-06-01
No rows.
Processing: 33384096 2024-07-01
No rows.
Processing: 33384096 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 33384096 2024-09-01
No rows.
Processing: 33384096 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33384096 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 10
Processing: 33384096 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33384096 2025-01-01
No rows.
Processing: 33384096 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 33384096 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 11
Processing: 33384096 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33384096_all_months_standard_clean.csv Rows: 52

===== Player 739/1000: 531015964 =====
Processing: 531015964 2024-05-01
No rows.
Processing: 531015964 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 531015964 2024-07-01
No rows.
Processing: 531015964 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 531015964 2024-09-01
No rows.
Processing: 531015964 2024-10-01
No rows.
Processing: 531015964 2024-11-01
No rows.
Processing: 531015964 2024-12-01
No rows.
Processing: 531015964 2025-01-01
No rows.
Processing: 531015964 2025-02-01
No rows.
Processing: 531015964 2025-03-01
No rows.
Processing: 531015964 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531015964_all_months_standard_clean.csv Rows: 7

===== Player 740/1000: 429073375 =====
Processing: 429073375 2024-05-01
No rows.
Processing: 429073375 2024-06-01
No rows.
Processing: 429073375 2024-07-01
No rows.
Processing: 429073375 2024-08-01
No rows.
Processing: 429073375 2024-09-01
No rows.
Processing: 429073375 2024-10-01
No rows.
Processing: 429073375 2024-11-01
No rows.
Processing: 429073375 2024-12-01
No rows.
Processing: 429073375 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 429073375 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 10
Processing: 429073375 2025-03-01
No rows.
Processing: 429073375 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429073375_all_months_standard_clean.csv Rows: 12

===== Player 741/1000: 531094511 =====
Processing: 531094511 2024-05-01
No rows.
Processing: 531094511 2024-06-01
No rows.
Processing: 531094511 2024-07-01
No rows.
Processing: 531094511 2024-08-01
No rows.
Processing: 531094511 2024-09-01
No rows.
Processing: 531094511 2024-10-01
No rows.
Processing: 531094511 2024-11-01
No rows.
Processing: 531094511 2024-12-01
No rows.
Processing: 531094511 2025-01-01
No rows.
Processing: 531094511 2025-02-01
No rows.
Processing: 531094511 2025-03-01
No rows.
Processing: 531094511 2025-04-01
No rows.

===== Player 742/1000: 537023861 =====
Processing: 537023861 2024-05-01
No rows.
Processing: 537023861 2024-06-01
No rows.
Processing: 537023861 2024-07-01
No rows.
Processing: 537023861 2024-08-01
No rows.
Processing: 537023861 2024-09-01
No rows.
Processing: 537023861 2024-10-01
No rows.
Processing: 537023861 2024-11-01
No rows.
Processing: 537023861 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 537023861 2025-01-01
No rows.
Processing: 537023861 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 537023861 2025-03-01
No rows.
Processing: 537023861 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537023861_all_months_standard_clean.csv Rows: 13

===== Player 743/1000: 547080302 =====
Processing: 547080302 2024-05-01
No rows.
Processing: 547080302 2024-06-01
No rows.
Processing: 547080302 2024-07-01
No rows.
Processing: 547080302 2024-08-01
No rows.
Processing: 547080302 2024-09-01
No rows.
Processing: 547080302 2024-10-01
No rows.
Processing: 547080302 2024-11-01
No rows.
Processing: 547080302 2024-12-01
No rows.
Processing: 547080302 2025-01-01
No rows.
Processing: 547080302 2025-02-01
No rows.
Processing: 547080302 2025-03-01
No rows.
Processing: 547080302 2025-04-01
No rows.

===== Player 744/1000: 25688693 =====
Processing: 25688693 2024-05-01
No rows.
Processing: 25688693 2024-06-01
No rows.
Processing: 25688693 2024-07-01
No rows.
Processing: 25688693 2024-08-01
No rows.
Processing: 25688693 2024-09-01
No rows.
Processing: 25688693 2024-10-01
No rows.
Processing: 25688693 2024-11-01
No rows.
Processing: 25688693 2024-12-01
No rows.
Processing: 25688693 2025-01-01
No rows.
Processing: 25688693 2025-02-01
No rows.
Processing: 25688693 2025-03-01
No rows.
Processing: 25688693 2025-04-01
No rows.

===== Player 745/1000: 48702935 =====
Processing: 48702935 2024-05-01
No rows.
Processing: 48702935 2024-06-01
No rows.
Processing: 48702935 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 48702935 2024-08-01
No rows.
Processing: 48702935 2024-09-01
No rows.
Processing: 48702935 2024-10-01
No rows.
Processing: 48702935 2024-11-01
No rows.
Processing: 48702935 2024-12-01
No rows.
Processing: 48702935 2025-01-01
No rows.
Processing: 48702935 2025-02-01
No rows.
Processing: 48702935 2025-03-01
No rows.
Processing: 48702935 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48702935_all_months_standard_clean.csv Rows: 7

===== Player 746/1000: 25932721 =====
Processing: 25932721 2024-05-01
No rows.
Processing: 25932721 2024-06-01
No rows.
Processing: 25932721 2024-07-01
No rows.
Processing: 25932721 2024-08-01
No rows.
Processing: 25932721 2024-09-01
No rows.
Processing: 25932721 2024-10-01
No rows.
Processing: 25932721 2024-11-01
No rows.
Processing: 25932721 2024-12-01
No rows.
Processing: 25932721 2025-01-01
No rows.
Processing: 25932721 2025-02-01
No rows.
Processing: 25932721 2025-03-01
No rows.
Processing: 25932721 2025-04-01
No rows.

===== Player 747/1000: 48763993 =====
Processing: 48763993 2024-05-01
No rows.
Processing: 48763993 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 48763993 2024-07-01
No rows.
Processing: 48763993 2024-08-01
No rows.
Processing: 48763993 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 48763993 2024-10-01
No rows.
Processing: 48763993 2024-11-01
No rows.
Processing: 48763993 2024-12-01
No rows.
Processing: 48763993 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 48763993 2025-02-01
No rows.
Processing: 48763993 2025-03-01
No rows.
Processing: 48763993 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48763993_all_months_standard_clean.csv Rows: 13

===== Player 748/1000: 429098505 =====
Processing: 429098505 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 429098505 2024-06-01
No rows.
Processing: 429098505 2024-07-01
No rows.
Processing: 429098505 2024-08-01
No rows.
Processing: 429098505 2024-09-01
No rows.
Processing: 429098505 2024-10-01
No rows.
Processing: 429098505 2024-11-01
No rows.
Processing: 429098505 2024-12-01
No rows.
Processing: 429098505 2025-01-01
No rows.
Processing: 429098505 2025-02-01
No rows.
Processing: 429098505 2025-03-01
No rows.
Processing: 429098505 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429098505_all_months_standard_clean.csv Rows: 5

===== Player 749/1000: 537055186 =====
Processing: 537055186 2024-05-01
No rows.
Processing: 537055186 2024-06-01
No rows.
Processing: 537055186 2024-07-01
No rows.
Processing: 537055186 2024-08-01
No rows.
Processing: 537055186 2024-09-01
No rows.
Processing: 537055186 2024-10-01
No rows.
Processing: 537055186 2024-11-01
No rows.
Processing: 537055186 2024-12-01
No rows.
Processing: 537055186 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 537055186 2025-02-01
No rows.
Processing: 537055186 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 537055186 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/537055186_all_months_standard_clean.csv Rows: 4

===== Player 750/1000: 48715727 =====
Processing: 48715727 2024-05-01
No rows.
Processing: 48715727 2024-06-01
No rows.
Processing: 48715727 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 48715727 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 48715727 2024-09-01
No rows.
Processing: 48715727 2024-10-01
No rows.
Processing: 48715727 2024-11-01
No rows.
Processing: 48715727 2024-12-01
No rows.
Processing: 48715727 2025-01-01
No rows.
Processing: 48715727 2025-02-01
No rows.
Processing: 48715727 2025-03-01
No rows.
Processing: 48715727 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48715727_all_months_standard_clean.csv Rows: 6

===== Player 751/1000: 25911414 =====
Processing: 25911414 2024-05-01
No rows.
Processing: 25911414 2024-06-01
No rows.
Processing: 25911414 2024-07-01
No rows.
Processing: 25911414 2024-08-01
No rows.
Processing: 25911414 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 25911414 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 25911414 2024-11-01
No rows.
Processing: 25911414 2024-12-01
No rows.
Processing: 25911414 2025-01-01
No rows.
Processing: 25911414 2025-02-01
No rows.
Processing: 25911414 2025-03-01
No rows.
Processing: 25911414 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25911414_all_months_standard_clean.csv Rows: 8

===== Player 752/1000: 558059970 =====
Processing: 558059970 2024-05-01
No rows.
Processing: 558059970 2024-06-01
No rows.
Processing: 558059970 2024-07-01
No rows.
Processing: 558059970 2024-08-01
No rows.
Processing: 558059970 2024-09-01
No rows.
Processing: 558059970 2024-10-01
No rows.
Processing: 558059970 2024-11-01
No rows.
Processing: 558059970 2024-12-01
No rows.
Processing: 558059970 2025-01-01
No rows.
Processing: 558059970 2025-02-01
No rows.
Processing: 558059970 2025-03-01
No rows.
Processing: 558059970 2025-04-01
No rows.

===== Player 753/1000: 25142755 =====
Processing: 25142755 2024-05-01
No rows.
Processing: 25142755 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 25142755 2024-07-01
No rows.
Processing: 25142755 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 25142755 2024-09-01
No rows.
Processing: 25142755 2024-10-01
No rows.
Processing: 25142755 2024-11-01
No rows.
Processing: 25142755 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 25142755 2025-01-01
No rows.
Processing: 25142755 2025-02-01
No rows.
Processing: 25142755 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 25142755 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25142755_all_months_standard_clean.csv Rows: 11

===== Player 754/1000: 48763047 =====
Processing: 48763047 2024-05-01
No rows.
Processing: 48763047 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 48763047 2024-07-01
No rows.
Processing: 48763047 2024-08-01
No rows.
Processing: 48763047 2024-09-01
No rows.
Processing: 48763047 2024-10-01
No rows.
Processing: 48763047 2024-11-01
No rows.
Processing: 48763047 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 48763047 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 48763047 2025-02-01
No rows.
Processing: 48763047 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 48763047 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48763047_all_months_standard_clean.csv Rows: 16

===== Player 755/1000: 25162128 =====
Processing: 25162128 2024-05-01
No rows.
Processing: 25162128 2024-06-01
No rows.
Processing: 25162128 2024-07-01
No rows.
Processing: 25162128 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 25162128 2024-09-01
No rows.
Processing: 25162128 2024-10-01
No rows.
Processing: 25162128 2024-11-01
No rows.
Processing: 25162128 2024-12-01
No rows.
Processing: 25162128 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 25162128 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 25162128 2025-03-01
No rows.
Processing: 25162128 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25162128_all_months_standard_clean.csv Rows: 15

===== Player 756/1000: 33442215 =====
Processing: 33442215 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 17
Processing: 33442215 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 33442215 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33442215 2024-08-01
Rows: 8
Processing: 33442215 2024-09-01
No rows.
Processing: 33442215 2024-10-01
No rows.
Processing: 33442215 2024-11-01
No rows.
Processing: 33442215 2024-12-01
Rows: 9
Processing: 33442215 2025-01-01
Rows: 9
Processing: 33442215 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 33442215 2025-03-01
No rows.
Processing: 33442215 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33442215_all_months_standard_clean.csv Rows: 66

===== Player 757/1000: 33465908 =====
Processing: 33465908 2024-05-01
No rows.
Processing: 33465908 2024-06-01
No rows.
Processing: 33465908 2024-07-01
No rows.
Processing: 33465908 2024-08-01
No rows.
Processing: 33465908 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 33465908 2024-10-01
No rows.
Processing: 33465908 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 33465908 2024-12-01
No rows.
Processing: 33465908 2025-01-01
No rows.
Processing: 33465908 2025-02-01
No rows.
Processing: 33465908 2025-03-01
No rows.
Processing: 33465908 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33465908_all_months_standard_clean.csv Rows: 2

===== Player 758/1000: 88138267 =====
Processing: 88138267 2024-05-01
No rows.
Processing: 88138267 2024-06-01
No rows.
Processing: 88138267 2024-07-01
No rows.
Processing: 88138267 2024-08-01
No rows.
Processing: 88138267 2024-09-01
No rows.
Processing: 88138267 2024-10-01
No rows.
Processing: 88138267 2024-11-01
No rows.
Processing: 88138267 2024-12-01
No rows.
Processing: 88138267 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 88138267 2025-02-01
No rows.
Processing: 88138267 2025-03-01
No rows.
Processing: 88138267 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88138267_all_months_standard_clean.csv Rows: 5

===== Player 759/1000: 558049592 =====
Processing: 558049592 2024-05-01
No rows.
Processing: 558049592 2024-06-01
No rows.
Processing: 558049592 2024-07-01
No rows.
Processing: 558049592 2024-08-01
No rows.
Processing: 558049592 2024-09-01
No rows.
Processing: 558049592 2024-10-01
No rows.
Processing: 558049592 2024-11-01
No rows.
Processing: 558049592 2024-12-01
No rows.
Processing: 558049592 2025-01-01
No rows.
Processing: 558049592 2025-02-01
No rows.
Processing: 558049592 2025-03-01
No rows.
Processing: 558049592 2025-04-01
No rows.

===== Player 760/1000: 48744948 =====
Processing: 48744948 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 48744948 2024-06-01
No rows.
Processing: 48744948 2024-07-01
No rows.
Processing: 48744948 2024-08-01
No rows.
Processing: 48744948 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 48744948 2024-10-01
No rows.
Processing: 48744948 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 48744948 2024-12-01
No rows.
Processing: 48744948 2025-01-01
No rows.
Processing: 48744948 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 48744948 2025-03-01
No rows.
Processing: 48744948 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48744948_all_months_standard_clean.csv Rows: 9

===== Player 761/1000: 547052082 =====
Processing: 547052082 2024-05-01
No rows.
Processing: 547052082 2024-06-01
No rows.
Processing: 547052082 2024-07-01
No rows.
Processing: 547052082 2024-08-01
No rows.
Processing: 547052082 2024-09-01
No rows.
Processing: 547052082 2024-10-01
No rows.
Processing: 547052082 2024-11-01
No rows.
Processing: 547052082 2024-12-01
No rows.
Processing: 547052082 2025-01-01
No rows.
Processing: 547052082 2025-02-01
No rows.
Processing: 547052082 2025-03-01
No rows.
Processing: 547052082 2025-04-01
No rows.

===== Player 762/1000: 25124269 =====
Processing: 25124269 2024-05-01
No rows.
Processing: 25124269 2024-06-01
No rows.
Processing: 25124269 2024-07-01
No rows.
Processing: 25124269 2024-08-01
No rows.
Processing: 25124269 2024-09-01
No rows.
Processing: 25124269 2024-10-01
No rows.
Processing: 25124269 2024-11-01
No rows.
Processing: 25124269 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 25124269 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 25124269 2025-02-01
No rows.
Processing: 25124269 2025-03-01
No rows.
Processing: 25124269 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25124269_all_months_standard_clean.csv Rows: 7

===== Player 763/1000: 531072739 =====
Processing: 531072739 2024-05-01
No rows.
Processing: 531072739 2024-06-01
No rows.
Processing: 531072739 2024-07-01
No rows.
Processing: 531072739 2024-08-01
No rows.
Processing: 531072739 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 531072739 2024-10-01
No rows.
Processing: 531072739 2024-11-01
No rows.
Processing: 531072739 2024-12-01
No rows.
Processing: 531072739 2025-01-01
No rows.
Processing: 531072739 2025-02-01
No rows.
Processing: 531072739 2025-03-01
No rows.
Processing: 531072739 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531072739_all_months_standard_clean.csv Rows: 3

===== Player 764/1000: 531079180 =====
Processing: 531079180 2024-05-01
No rows.
Processing: 531079180 2024-06-01
No rows.
Processing: 531079180 2024-07-01
No rows.
Processing: 531079180 2024-08-01
No rows.
Processing: 531079180 2024-09-01
No rows.
Processing: 531079180 2024-10-01
No rows.
Processing: 531079180 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 531079180 2024-12-01
No rows.
Processing: 531079180 2025-01-01
No rows.
Processing: 531079180 2025-02-01
No rows.
Processing: 531079180 2025-03-01
No rows.
Processing: 531079180 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531079180_all_months_standard_clean.csv Rows: 5

===== Player 765/1000: 48793086 =====
Processing: 48793086 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 48793086 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 48793086 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 48793086 2024-08-01
No rows.
Processing: 48793086 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 48793086 2024-10-01
No rows.
Processing: 48793086 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 15
Processing: 48793086 2024-12-01
No rows.
Processing: 48793086 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 20
Processing: 48793086 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 48793086 2025-03-01
No rows.
Processing: 48793086 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48793086_all_months_standard_clean.csv Rows: 69

===== Player 766/1000: 88113213 =====
Processing: 88113213 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 88113213 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 88113213 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 88113213 2024-08-01
No rows.
Processing: 88113213 2024-09-01
No rows.
Processing: 88113213 2024-10-01
No rows.
Processing: 88113213 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 88113213 2024-12-01
No rows.
Processing: 88113213 2025-01-01
No rows.
Processing: 88113213 2025-02-01
No rows.
Processing: 88113213 2025-03-01
No rows.
Processing: 88113213 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88113213_all_months_standard_clean.csv Rows: 28

===== Player 767/1000: 531071520 =====
Processing: 531071520 2024-05-01
No rows.
Processing: 531071520 2024-06-01
No rows.
Processing: 531071520 2024-07-01
No rows.
Processing: 531071520 2024-08-01
No rows.
Processing: 531071520 2024-09-01
No rows.
Processing: 531071520 2024-10-01
No rows.
Processing: 531071520 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 531071520 2024-12-01
No rows.
Processing: 531071520 2025-01-01
No rows.
Processing: 531071520 2025-02-01
No rows.
Processing: 531071520 2025-03-01
No rows.
Processing: 531071520 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531071520_all_months_standard_clean.csv Rows: 7

===== Player 768/1000: 537078631 =====
Processing: 537078631 2024-05-01
No rows.
Processing: 537078631 2024-06-01
No rows.
Processing: 537078631 2024-07-01
No rows.
Processing: 537078631 2024-08-01
No rows.
Processing: 537078631 2024-09-01
No rows.
Processing: 537078631 2024-10-01
No rows.
Processing: 537078631 2024-11-01
No rows.
Processing: 537078631 2024-12-01
No rows.
Processing: 537078631 2025-01-01
No rows.
Processing: 537078631 2025-02-01
No rows.
Processing: 537078631 2025-03-01
No rows.
Processing: 537078631 2025-04-01
No rows.

===== Player 769/1000: 88105563 =====
Processing: 88105563 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 14
Processing: 88105563 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 88105563 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 88105563 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 18
Processing: 88105563 2024-09-01
No rows.
Processing: 88105563 2024-10-01
No rows.
Processing: 88105563 2024-11-01
Rows: 8
Processing: 88105563 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 18
Processing: 88105563 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 88105563 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 88105563 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 13
Processing: 88105563 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 21
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88105563_all_months_standard_clean.csv Rows: 124

===== Player 770/1000: 48723355 =====
Processing: 48723355 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 48723355 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 10
Processing: 48723355 2024-07-01
No rows.
Processing: 48723355 2024-08-01
No rows.
Processing: 48723355 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 48723355 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 48723355 2024-11-01
No rows.
Processing: 48723355 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 48723355 2025-01-01
No rows.
Processing: 48723355 2025-02-01
No rows.
Processing: 48723355 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 48723355 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48723355_all_months_standard_clean.csv Rows: 36

===== Player 771/1000: 88150615 =====
Processing: 88150615 2024-05-01
No rows.
Processing: 88150615 2024-06-01
No rows.
Processing: 88150615 2024-07-01
No rows.
Processing: 88150615 2024-08-01
No rows.
Processing: 88150615 2024-09-01
No rows.
Processing: 88150615 2024-10-01
No rows.
Processing: 88150615 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 88150615 2024-12-01
No rows.
Processing: 88150615 2025-01-01
No rows.
Processing: 88150615 2025-02-01
No rows.
Processing: 88150615 2025-03-01
No rows.
Processing: 88150615 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88150615_all_months_standard_clean.csv Rows: 2

===== Player 772/1000: 33461066 =====
Processing: 33461066 2024-05-01
No rows.
Processing: 33461066 2024-06-01
No rows.
Processing: 33461066 2024-07-01
No rows.
Processing: 33461066 2024-08-01
No rows.
Processing: 33461066 2024-09-01
No rows.
Processing: 33461066 2024-10-01
No rows.
Processing: 33461066 2024-11-01
No rows.
Processing: 33461066 2024-12-01
No rows.
Processing: 33461066 2025-01-01
No rows.
Processing: 33461066 2025-02-01
No rows.
Processing: 33461066 2025-03-01
No rows.
Processing: 33461066 2025-04-01
No rows.

===== Player 773/1000: 531059198 =====
Processing: 531059198 2024-05-01
No rows.
Processing: 531059198 2024-06-01
No rows.
Processing: 531059198 2024-07-01
No rows.
Processing: 531059198 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 531059198 2024-09-01
No rows.
Processing: 531059198 2024-10-01
No rows.
Processing: 531059198 2024-11-01
No rows.
Processing: 531059198 2024-12-01
No rows.
Processing: 531059198 2025-01-01
No rows.
Processing: 531059198 2025-02-01
No rows.
Processing: 531059198 2025-03-01
No rows.
Processing: 531059198 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531059198_all_months_standard_clean.csv Rows: 7

===== Player 774/1000: 48748234 =====
Processing: 48748234 2024-05-01
No rows.
Processing: 48748234 2024-06-01
No rows.
Processing: 48748234 2024-07-01
No rows.
Processing: 48748234 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 48748234 2024-09-01
No rows.
Processing: 48748234 2024-10-01
No rows.
Processing: 48748234 2024-11-01
No rows.
Processing: 48748234 2024-12-01
No rows.
Processing: 48748234 2025-01-01
No rows.
Processing: 48748234 2025-02-01
No rows.
Processing: 48748234 2025-03-01
No rows.
Processing: 48748234 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/48748234_all_months_standard_clean.csv Rows: 10

===== Player 775/1000: 88132056 =====
Processing: 88132056 2024-05-01
No rows.
Processing: 88132056 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 88132056 2024-07-01
No rows.
Processing: 88132056 2024-08-01
No rows.
Processing: 88132056 2024-09-01
No rows.
Processing: 88132056 2024-10-01
No rows.
Processing: 88132056 2024-11-01
No rows.
Processing: 88132056 2024-12-01
No rows.
Processing: 88132056 2025-01-01
No rows.
Processing: 88132056 2025-02-01
No rows.
Processing: 88132056 2025-03-01
No rows.
Processing: 88132056 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88132056_all_months_standard_clean.csv Rows: 8

===== Player 776/1000: 537000870 =====
Processing: 537000870 2024-05-01
No rows.
Processing: 537000870 2024-06-01
No rows.
Processing: 537000870 2024-07-01
No rows.
Processing: 537000870 2024-08-01
No rows.
Processing: 537000870 2024-09-01
No rows.
Processing: 537000870 2024-10-01
No rows.
Processing: 537000870 2024-11-01
No rows.
Processing: 537000870 2024-12-01
No rows.
Processing: 537000870 2025-01-01
No rows.
Processing: 537000870 2025-02-01
No rows.
Processing: 537000870 2025-03-01
No rows.
Processing: 537000870 2025-04-01
No rows.

===== Player 777/1000: 33480427 =====
Processing: 33480427 2024-05-01
No rows.
Processing: 33480427 2024-06-01
No rows.
Processing: 33480427 2024-07-01
No rows.
Processing: 33480427 2024-08-01
No rows.
Processing: 33480427 2024-09-01
No rows.
Processing: 33480427 2024-10-01
No rows.
Processing: 33480427 2024-11-01
No rows.
Processing: 33480427 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 33480427 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33480427 2025-02-01
No rows.
Processing: 33480427 2025-03-01
No rows.
Processing: 33480427 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33480427_all_months_standard_clean.csv Rows: 15

===== Player 778/1000: 48753912 =====
Processing: 48753912 2024-05-01
No rows.
Processing: 48753912 2024-06-01
No rows.
Processing: 48753912 2024-07-01
No rows.
Processing: 48753912 2024-08-01
No rows.
Processing: 48753912 2024-09-01
No rows.
Processing: 48753912 2024-10-01
No rows.
Processing: 48753912 2024-11-01
No rows.
Processing: 48753912 2024-12-01
No rows.
Processing: 48753912 2025-01-01
No rows.
Processing: 48753912 2025-02-01
No rows.
Processing: 48753912 2025-03-01
No rows.
Processing: 48753912 2025-04-01
No rows.

===== Player 779/1000: 531086950 =====
Processing: 531086950 2024-05-01
No rows.
Processing: 531086950 2024-06-01
No rows.
Processing: 531086950 2024-07-01
No rows.
Processing: 531086950 2024-08-01
No rows.
Processing: 531086950 2024-09-01
No rows.
Processing: 531086950 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 531086950 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 531086950 2024-12-01
No rows.
Processing: 531086950 2025-01-01
No rows.
Processing: 531086950 2025-02-01
No rows.
Processing: 531086950 2025-03-01
No rows.
Processing: 531086950 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531086950_all_months_standard_clean.csv Rows: 4

===== Player 780/1000: 429071356 =====
Processing: 429071356 2024-05-01
No rows.
Processing: 429071356 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 429071356 2024-07-01
No rows.
Processing: 429071356 2024-08-01
No rows.
Processing: 429071356 2024-09-01
No rows.
Processing: 429071356 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 429071356 2024-11-01
No rows.
Processing: 429071356 2024-12-01
No rows.
Processing: 429071356 2025-01-01
No rows.
Processing: 429071356 2025-02-01
No rows.
Processing: 429071356 2025-03-01
No rows.
Processing: 429071356 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/429071356_all_months_standard_clean.csv Rows: 12

===== Player 781/1000: 547063432 =====
Processing: 547063432 2024-05-01
No rows.
Processing: 547063432 2024-06-01
No rows.
Processing: 547063432 2024-07-01
No rows.
Processing: 547063432 2024-08-01
No rows.
Processing: 547063432 2024-09-01
No rows.
Processing: 547063432 2024-10-01
No rows.
Processing: 547063432 2024-11-01
No rows.
Processing: 547063432 2024-12-01
No rows.
Processing: 547063432 2025-01-01
No rows.
Processing: 547063432 2025-02-01
No rows.
Processing: 547063432 2025-03-01
No rows.
Processing: 547063432 2025-04-01
No rows.

===== Player 782/1000: 429090407 =====
Processing: 429090407 2024-05-01
No rows.
Processing: 429090407 2024-06-01
No rows.
Processing: 429090407 2024-07-01
No rows.
Processing: 429090407 2024-08-01
No rows.
Processing: 429090407 2024-09-01
No rows.
Processing: 429090407 2024-10-01
No rows.
Processing: 429090407 2024-11-01
No rows.
Processing: 429090407 2024-12-01
No rows.
Processing: 429090407 2025-01-01
No rows.
Processing: 429090407 2025-02-01
No rows.
Processing: 429090407 2025-03-01
No rows.
Processing: 429090407 2025-04-01
No rows.

===== Player 783/1000: 88181383 =====
Processing: 88181383 2024-05-01
No rows.
Processing: 88181383 2024-06-01
No rows.
Processing: 88181383 2024-07-01
No rows.
Processing: 88181383 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 88181383 2024-09-01
No rows.
Processing: 88181383 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 88181383 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 88181383 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 88181383 2025-01-01
No rows.
Processing: 88181383 2025-02-01
No rows.
Processing: 88181383 2025-03-01
No rows.
Processing: 88181383 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88181383_all_months_standard_clean.csv Rows: 20

===== Player 784/1000: 537019228 =====
Processing: 537019228 2024-05-01
No rows.
Processing: 537019228 2024-06-01
No rows.
Processing: 537019228 2024-07-01
No rows.
Processing: 537019228 2024-08-01
No rows.
Processing: 537019228 2024-09-01
No rows.
Processing: 537019228 2024-10-01
No rows.
Processing: 537019228 2024-11-01
No rows.
Processing: 537019228 2024-12-01
No rows.
Processing: 537019228 2025-01-01
No rows.
Processing: 537019228 2025-02-01
No rows.
Processing: 537019228 2025-03-01
No rows.
Processing: 537019228 2025-04-01
No rows.

===== Player 785/1000: 33365776 =====
Processing: 33365776 2024-05-01
No rows.
Processing: 33365776 2024-06-01
No rows.
Processing: 33365776 2024-07-01
No rows.
Processing: 33365776 2024-08-01
No rows.
Processing: 33365776 2024-09-01
No rows.
Processing: 33365776 2024-10-01
No rows.
Processing: 33365776 2024-11-01
No rows.
Processing: 33365776 2024-12-01
No rows.
Processing: 33365776 2025-01-01
No rows.
Processing: 33365776 2025-02-01
No rows.
Processing: 33365776 2025-03-01
No rows.
Processing: 33365776 2025-04-01
No rows.

===== Player 786/1000: 531014380 =====
Processing: 531014380 2024-05-01
No rows.
Processing: 531014380 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 531014380 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 13
Processing: 531014380 2024-08-01
No rows.
Processing: 531014380 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 531014380 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 531014380 2024-11-01
No rows.
Processing: 531014380 2024-12-01
No rows.
Processing: 531014380 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 531014380 2025-02-01
No rows.
Processing: 531014380 2025-03-01
No rows.
Processing: 531014380 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531014380_all_months_standard_clean.csv Rows: 28

===== Player 787/1000: 33451826 =====
Processing: 33451826 2024-05-01
No rows.
Processing: 33451826 2024-06-01
No rows.
Processing: 33451826 2024-07-01
No rows.
Processing: 33451826 2024-08-01
No rows.
Processing: 33451826 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 1
Processing: 33451826 2024-10-01
No rows.
Processing: 33451826 2024-11-01
No rows.
Processing: 33451826 2024-12-01
No rows.
Processing: 33451826 2025-01-01
No rows.
Processing: 33451826 2025-02-01
No rows.
Processing: 33451826 2025-03-01
No rows.
Processing: 33451826 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33451826_all_months_standard_clean.csv Rows: 1

===== Player 788/1000: 33330824 =====
Processing: 33330824 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 33330824 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 15
Processing: 33330824 2024-07-01
No rows.
Processing: 33330824 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33330824 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 7
Processing: 33330824 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 14
Processing: 33330824 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 13
Processing: 33330824 2024-12-01
No rows.
Processing: 33330824 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 10
Processing: 33330824 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33330824 2025-03-01
No rows.
Processing: 33330824 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33330824_all_months_standard_clean.csv Rows: 80

===== Player 789/1000: 537020447 =====
Processing: 537020447 2024-05-01
No rows.
Processing: 537020447 2024-06-01
No rows.
Processing: 537020447 2024-07-01
No rows.
Processing: 537020447 2024-08-01
No rows.
Processing: 537020447 2024-09-01
No rows.
Processing: 537020447 2024-10-01
No rows.
Processing: 537020447 2024-11-01
No rows.
Processing: 537020447 2024-12-01
No rows.
Processing: 537020447 2025-01-01
No rows.
Processing: 537020447 2025-02-01
No rows.
Processing: 537020447 2025-03-01
No rows.
Processing: 537020447 2025-04-01
No rows.

===== Player 790/1000: 531048668 =====
Processing: 531048668 2024-05-01
No rows.
Processing: 531048668 2024-06-01
No rows.
Processing: 531048668 2024-07-01
No rows.
Processing: 531048668 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 531048668 2024-09-01
No rows.
Processing: 531048668 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 531048668 2024-11-01
No rows.
Processing: 531048668 2024-12-01
No rows.
Processing: 531048668 2025-01-01
No rows.
Processing: 531048668 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 531048668 2025-03-01
No rows.
Processing: 531048668 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/531048668_all_months_standard_clean.csv Rows: 17

===== Player 791/1000: 33392170 =====
Processing: 33392170 2024-05-01
No rows.
Processing: 33392170 2024-06-01
No rows.
Processing: 33392170 2024-07-01
No rows.
Processing: 33392170 2024-08-01
No rows.
Processing: 33392170 2024-09-01
No rows.
Processing: 33392170 2024-10-01
No rows.
Processing: 33392170 2024-11-01
No rows.
Processing: 33392170 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 6
Processing: 33392170 2025-01-01
No rows.
Processing: 33392170 2025-02-01
No rows.
Processing: 33392170 2025-03-01
No rows.
Processing: 33392170 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33392170_all_months_standard_clean.csv Rows: 6

===== Player 792/1000: 547070439 =====
Processing: 547070439 2024-05-01
No rows.
Processing: 547070439 2024-06-01
No rows.
Processing: 547070439 2024-07-01
No rows.
Processing: 547070439 2024-08-01
No rows.
Processing: 547070439 2024-09-01
No rows.
Processing: 547070439 2024-10-01
No rows.
Processing: 547070439 2024-11-01
No rows.
Processing: 547070439 2024-12-01
No rows.
Processing: 547070439 2025-01-01
No rows.
Processing: 547070439 2025-02-01
No rows.
Processing: 547070439 2025-03-01
No rows.
Processing: 547070439 2025-04-01
No rows.

===== Player 793/1000: 88146103 =====
Processing: 88146103 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 88146103 2024-06-01
No rows.
Processing: 88146103 2024-07-01
No rows.
Processing: 88146103 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 5
Processing: 88146103 2024-09-01
No rows.
Processing: 88146103 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 88146103 2024-11-01
No rows.
Processing: 88146103 2024-12-01
No rows.
Processing: 88146103 2025-01-01
No rows.
Processing: 88146103 2025-02-01
No rows.
Processing: 88146103 2025-03-01
No rows.
Processing: 88146103 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/88146103_all_months_standard_clean.csv Rows: 16

===== Player 794/1000: 33490643 =====
Processing: 33490643 2024-05-01
Rows: 9
Processing: 33490643 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 14
Processing: 33490643 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33490643 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 20
Processing: 33490643 2024-09-01
No rows.
Processing: 33490643 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 33490643 2024-11-01
No rows.
Processing: 33490643 2024-12-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 19
Processing: 33490643 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33490643 2025-02-01
No rows.
Processing: 33490643 2025-03-01
No rows.
Processing: 33490643 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33490643_all_months_standard_clean.csv Rows: 96

===== Player 795/1000: 25985230 =====
Processing: 25985230 2024-05-01
No rows.
Processing: 25985230 2024-06-01
No rows.
Processing: 25985230 2024-07-01
No rows.
Processing: 25985230 2024-08-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 14
Processing: 25985230 2024-09-01
No rows.
Processing: 25985230 2024-10-01
No rows.
Processing: 25985230 2024-11-01
No rows.
Processing: 25985230 2024-12-01
No rows.
Processing: 25985230 2025-01-01
No rows.
Processing: 25985230 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 13
Processing: 25985230 2025-03-01
No rows.
Processing: 25985230 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25985230_all_months_standard_clean.csv Rows: 27

===== Player 796/1000: 25138189 =====
Processing: 25138189 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 10
Processing: 25138189 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 24
Processing: 25138189 2024-07-01
No rows.
Processing: 25138189 2024-08-01
No rows.
Processing: 25138189 2024-09-01
No rows.
Processing: 25138189 2024-10-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 25138189 2024-11-01
No rows.
Processing: 25138189 2024-12-01
Rows: 8
Processing: 25138189 2025-01-01
Rows: 9
Processing: 25138189 2025-02-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 25138189 2025-03-01
No rows.
Processing: 25138189 2025-04-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25138189_all_months_standard_clean.csv Rows: 77

===== Player 797/1000: 25690078 =====
Processing: 25690078 2024-05-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 9
Processing: 25690078 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 16
Processing: 25690078 2024-07-01
No rows.
Processing: 25690078 2024-08-01
No rows.
Processing: 25690078 2024-09-01
No rows.
Processing: 25690078 2024-10-01
No rows.
Processing: 25690078 2024-11-01
No rows.
Processing: 25690078 2024-12-01
No rows.
Processing: 25690078 2025-01-01
No rows.
Processing: 25690078 2025-02-01
No rows.
Processing: 25690078 2025-03-01
No rows.
Processing: 25690078 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25690078_all_months_standard_clean.csv Rows: 25

===== Player 798/1000: 564033341 =====
Processing: 564033341 2024-05-01
No rows.
Processing: 564033341 2024-06-01
No rows.
Processing: 564033341 2024-07-01
No rows.
Processing: 564033341 2024-08-01
No rows.
Processing: 564033341 2024-09-01
No rows.
Processing: 564033341 2024-10-01
No rows.
Processing: 564033341 2024-11-01
No rows.
Processing: 564033341 2024-12-01
No rows.
Processing: 564033341 2025-01-01
No rows.
Processing: 564033341 2025-02-01
No rows.
Processing: 564033341 2025-03-01
No rows.
Processing: 564033341 2025-04-01
No rows.

===== Player 799/1000: 25677772 =====
Processing: 25677772 2024-05-01
No rows.
Processing: 25677772 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 3
Processing: 25677772 2024-07-01
No rows.
Processing: 25677772 2024-08-01
No rows.
Processing: 25677772 2024-09-01
No rows.
Processing: 25677772 2024-10-01
No rows.
Processing: 25677772 2024-11-01
No rows.
Processing: 25677772 2024-12-01
No rows.
Processing: 25677772 2025-01-01
No rows.
Processing: 25677772 2025-02-01
No rows.
Processing: 25677772 2025-03-01
No rows.
Processing: 25677772 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/25677772_all_months_standard_clean.csv Rows: 3

===== Player 800/1000: 33365318 =====
Processing: 33365318 2024-05-01
No rows.
Processing: 33365318 2024-06-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)
/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 11
Processing: 33365318 2024-07-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 33365318 2024-08-01
No rows.
Processing: 33365318 2024-09-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 33365318 2024-10-01
No rows.
Processing: 33365318 2024-11-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 4
Processing: 33365318 2024-12-01
No rows.
Processing: 33365318 2025-01-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 8
Processing: 33365318 2025-02-01
No rows.
Processing: 33365318 2025-03-01

/var/folders/31/z67rs8rx6cx41cfsvty5nm180000gn/T/ipykernel_91517/3598714000.py:106: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  opponent_df["opponent_title"] = opponent_df["opponent_title"].replace("", np.nan).infer_objects(copy=False)

Rows: 2
Processing: 33365318 2025-04-01
No rows.
Saved player file: /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_months/33365318_all_months_standard_clean.csv Rows: 33

===== Player 801/1000: 88128199 =====
Processing: 88128199 2024-05-01
No rows.

CancelledError:

#### Note: Stopped at 801th iterations as I had started a parallel process for rest of 200 players

#### 8. Combine all extracted player-month files
After extraction, combine all non-empty files.

In [75]:
#combine from both folders.
# Set both folders:
from pathlib import Path
import pandas as pd
from pandas.errors import EmptyDataError

clean_dir_1 = Path.home() / "Downloads" / "fide_history" / "fide_calculation_pages" / "clean_player_months"

# Change this to your second parallel process folder
clean_dir_2 = Path.home() / "Downloads" / "fide_history" / "fide_calculation_pages_1" / "clean_player_months_1"

all_clean_files = sorted(list(clean_dir_1.glob("*_standard_clean.csv")) + 
                         list(clean_dir_2.glob("*_standard_clean.csv")))

print("Total files from both folders:", len(all_clean_files))

Total files from both folders: 12625

In [77]:
# Now combine safely and remove duplicate player-month files
file_rows = []

for f in all_clean_files:
    parts = f.name.split("_")
    fide_id = parts[0]
    period = parts[1]
    
    file_rows.append({
        "fide_id": fide_id,
        "period": period,
        "file_path": f,
        "file_name": f.name,
        "file_size": f.stat().st_size,
        "modified_time": f.stat().st_mtime
    })

file_index = pd.DataFrame(file_rows)

# If same player-month exists in both folders, keep the larger file;
# if same size, keep the most recently modified.
file_index = file_index.sort_values(
    ["fide_id", "period", "file_size", "modified_time"],
    ascending=[True, True, False, False]
)

file_index_dedup = file_index.drop_duplicates(
    subset=["fide_id", "period"],
    keep="first"
).copy()

print("Raw files:", file_index.shape[0])
print("Unique player-month files:", file_index_dedup.shape[0])

Raw files: 12625
Unique player-month files: 12624

In [79]:
# Check duplicate count

duplicates = file_index[file_index.duplicated(["fide_id", "period"], keep=False)]

print("Duplicate player-month files:", duplicates.shape[0])
display(duplicates.head(50))

Duplicate player-month files: 2

        fide_id      period                                                                        file_path                               file_name  file_size  modified_time
9377   88128199  2024-05-01  /Users/arunkumar/Downloads/fide_history/fide_calculation_pages/clean_player_...  88128199_2024-05-01_standard_clean.csv          1   1.778247e+09
12405  88128199  2024-05-01  /Users/arunkumar/Downloads/fide_history/fide_calculation_pages_1/clean_playe...  88128199_2024-05-01_standard_clean.csv          1   1.778226e+09

In [81]:
# Now read only deduplicated files

combined_parts = []
empty_files = []
failed_files = []

for f in file_index_dedup["file_path"]:
    try:
        if f.stat().st_size == 0:
            empty_files.append(str(f))
            continue

        df = pd.read_csv(f)

        if df.empty:
            empty_files.append(str(f))
            continue

        combined_parts.append(df)

    except EmptyDataError:
        empty_files.append(str(f))

    except Exception as e:
        failed_files.append({
            "file": str(f),
            "error": repr(e)
        })

print("Unique files to read:", len(file_index_dedup))
print("Non-empty data files:", len(combined_parts))
print("Empty/no-data files:", len(empty_files))
print("Failed files:", len(failed_files))

if combined_parts:
    fide_calc_all_players = pd.concat(combined_parts, ignore_index=True)
else:
    fide_calc_all_players = pd.DataFrame()

print("Combined shape:", fide_calc_all_players.shape)
display(fide_calc_all_players.head(20))

Unique files to read: 12624
Non-empty data files: 2459
Empty/no-data files: 10165
Failed files: 0
Combined shape: (24204, 24)

     fide_id      period  rating_type                                                          tournament_name event_location_fed event_start_date event_end_date  event_rc  event_ro  event_score  event_games  event_chg  event_k  event_k_chg              opponent_name opponent_title  opponent_rating  rating_difference_over_400_flag opponent_fed  score  n   chg     k  k_chg
0   14350670  2024-05-01            0                           Tamil Nadu State Women Chess Championship 2024     Kovilpatti IND       2024-04-24     2024-04-28    1577.0    1426.0          1.0            4      -0.21       40         -8.4       Ananya, Manisundaram            NaN           1621.0                            False          IND    0.0  1 -0.25  40.0  -10.0
1   14350670  2024-05-01            0                           Tamil Nadu State Women Chess Championship 2024     Kovilpatti IND       2024-04-24     2024-04-28    1577.0    1426.0          1.0            4      -0.21       40         -8.4               Lakshanaa, R            NaN           1633.0                            False          IND    0.0  1 -0.23  40.0   -9.2
2   14350670  2024-05-01            0                           Tamil Nadu State Women Chess Championship 2024     Kovilpatti IND       2024-04-24     2024-04-28    1577.0    1426.0          1.0            4      -0.21       40         -8.4                Sandhana, D            NaN           1531.0                            False          IND    0.0  1 -0.36  40.0  -14.4
3   14350670  2024-05-01            0                           Tamil Nadu State Women Chess Championship 2024     Kovilpatti IND       2024-04-24     2024-04-28    1577.0    1426.0          1.0            4      -0.21       40         -8.4                 Rithika, M            NaN           1522.0                            False          IND    1.0  1  0.63  40.0   25.2
4   14350670  2024-06-01            0       Tamil Nadu State Under 17 Girls FIDE Rated Chess Championship-2024    Arupukottai IND       2024-05-01     2024-05-05    1530.0    1418.0          2.0            6      -0.20       40         -8.0          Shanmathi, Sree S            NaN           1818.0                             True          IND    0.0  1 -0.08  40.0   -3.2
5   14350670  2024-06-01            0       Tamil Nadu State Under 17 Girls FIDE Rated Chess Championship-2024    Arupukottai IND       2024-05-01     2024-05-05    1530.0    1418.0          2.0            6      -0.20       40         -8.0                  Janani, J            NaN           1536.0                            False          IND    0.0  1 -0.34  40.0  -13.6
6   14350670  2024-06-01            0       Tamil Nadu State Under 17 Girls FIDE Rated Chess Championship-2024    Arupukottai IND       2024-05-01     2024-05-05    1530.0    1418.0          2.0            6      -0.20       40         -8.0             Madhavi, Sri V            NaN           1480.0                            False          IND    0.5  1  0.09  40.0    3.6
7   14350670  2024-06-01            0       Tamil Nadu State Under 17 Girls FIDE Rated Chess Championship-2024    Arupukottai IND       2024-05-01     2024-05-05    1530.0    1418.0          2.0            6      -0.20       40         -8.0                  Anusri, S            NaN           1459.0                            False          IND    0.0  1 -0.44  40.0  -17.6
8   14350670  2024-06-01            0       Tamil Nadu State Under 17 Girls FIDE Rated Chess Championship-2024    Arupukottai IND       2024-05-01     2024-05-05    1530.0    1418.0          2.0            6      -0.20       40         -8.0               Keerthana, V            NaN           1453.0                            False          IND    1.0  1  0.55  40.0   22.0
9   14350670  2024-06-01            0       Tamil Nadu State Under 17 Girls FIDE Rated Chess Championship-2024    Arupukottai IND       2024-05-01     2024-05-05    1530.0    1418.0          2.0            6      -0.20       40         -8.0          Dhashya, Fiance S            NaN           1434.0                            False          IND    0.5  1  0.02  40.0    0.8
10  14350670  2024-06-01            0  36th Tamil Nadu State Under-13 Girls Fide Rated Chess Championship-2024     Kumbakonam IND       2024-05-08     2024-05-12    1501.0    1418.0          0.5            3      -0.65       40        -26.0  Deepthaashri, Ravi Ganesh            NaN           1496.0                            False          IND    0.0  1 -0.39  40.0  -15.6
11  14350670  2024-06-01            0  36th Tamil Nadu State Under-13 Girls Fide Rated Chess Championship-2024     Kumbakonam IND       2024-05-08     2024-05-12    1501.0    1418.0          0.5            3      -0.65       40        -26.0                Deevitha, G            NaN           1482.0                            False          IND    0.5  1  0.09  40.0    3.6
12  14350670  2024-06-01            0  36th Tamil Nadu State Under-13 Girls Fide Rated Chess Championship-2024     Kumbakonam IND       2024-05-08     2024-05-12    1501.0    1418.0          0.5            3      -0.65       40        -26.0                  Anjana, A            NaN           1526.0                            False          IND    0.0  1 -0.35  40.0  -14.0
13  14350670  2024-06-01            0                 Tamil Nadu State Under-15 Girls Chess Championships 2024     Pudukottai IND       2024-05-15     2024-05-19    1583.0    1418.0          0.0            2      -0.57       40        -22.8                 Sananda, R            NaN           1629.0                            False          IND    0.0  1 -0.23  40.0   -9.2
14  14350670  2024-06-01            0                 Tamil Nadu State Under-15 Girls Chess Championships 2024     Pudukottai IND       2024-05-15     2024-05-19    1583.0    1418.0          0.0            2      -0.57       40        -22.8                  Janani, J            NaN           1536.0                            False          IND    0.0  1 -0.34  40.0  -13.6
15  14350670  2024-07-01            0                74th Tamil Nadu State Open State Chess Championship -2024     Coimbatore IND       2024-05-27     2024-05-31       NaN       NaN          1.5            5       0.00     1539          NaN                 Hiren, K G            NaN           2013.0                            False          IND    0.0  1  0.00   NaN    0.0
16  14350670  2024-07-01            0                74th Tamil Nadu State Open State Chess Championship -2024     Coimbatore IND       2024-05-27     2024-05-31       NaN       NaN          1.5            5       0.00     1539          NaN           Stephen, Andrews            NaN           1568.0                            False          IND    1.0  1  0.00   NaN    0.0
17  14350670  2024-07-01            0                74th Tamil Nadu State Open State Chess Championship -2024     Coimbatore IND       2024-05-27     2024-05-31       NaN       NaN          1.5            5       0.00     1539          NaN          Lakshman, Yogeshl            NaN           1663.0                            False          IND    0.5  1  0.00   NaN    0.0
18  14350670  2024-07-01            0                74th Tamil Nadu State Open State Chess Championship -2024     Coimbatore IND       2024-05-27     2024-05-31       NaN       NaN          1.5            5       0.00     1539          NaN                 Harun, B S            NaN           1639.0                            False          IND    0.0  1  0.00   NaN    0.0
19  14350670  2024-07-01            0                74th Tamil Nadu State Open State Chess Championship -2024     Coimbatore IND       2024-05-27     2024-05-31       NaN       NaN          1.5            5       0.00     1539          NaN            Shri, Shivani G            NaN           1555.0                            False          IND    0.0  1  0.00   NaN    0.0

In [83]:
#Save combined result
combined_output = Path.home() / "Downloads" / "fide_history" / "fide_calculations_all_players_standard_clean_combined.csv"

fide_calc_all_players.to_csv(combined_output, index=False)

print("Saved:", combined_output)

Saved: /Users/arunkumar/Downloads/fide_history/fide_calculations_all_players_standard_clean_combined.csv

In [85]:
# Final coverage check
expected_ids = set(player_sample["ID Number"].astype(str).str.strip())
processed_ids = set(file_index_dedup["fide_id"].astype(str).str.strip())

print("Expected sample players:", len(expected_ids))
print("Processed players:", len(processed_ids))
print("Missing players:", len(expected_ids - processed_ids))

missing_players = sorted(expected_ids - processed_ids)
print("Missing player IDs:", missing_players[:100])

Expected sample players: 1000
Processed players: 1000
Missing players: 0
Missing player IDs: []

In [87]:
#And month coverage
expected_months = [p.strftime("%Y-%m-%d") for p in periods]
expected_count_per_player = len(expected_months)

coverage_by_player = (
    file_index_dedup
    .groupby("fide_id", as_index=False)
    .agg(months_processed=("period", "nunique"))
)

incomplete_players = coverage_by_player[
    coverage_by_player["months_processed"] < expected_count_per_player
].copy()

print("Expected months per player:", expected_count_per_player)
print("Incomplete players:", incomplete_players.shape[0])
display(incomplete_players.head(50))

Expected months per player: 12
Incomplete players: 0

Empty DataFrame
Columns: [fide_id, months_processed]
Index: []

In [89]:
print("Rows:", fide_calc_all_players.shape[0])
print("Columns:", fide_calc_all_players.shape[1])
print("Players with opponent data:", fide_calc_all_players["fide_id"].nunique())
print("Unique tournaments:", fide_calc_all_players["tournament_name"].nunique())
print("Periods covered:", fide_calc_all_players["period"].min(), "to", fide_calc_all_players["period"].max())

Rows: 24204
Columns: 24
Players with opponent data: 629
Unique tournaments: 368
Periods covered: 2024-05-01 to 2025-04-01

In [91]:
sample_ids = set(player_sample["ID Number"].astype(str).str.strip())
calc_ids = set(fide_calc_all_players["fide_id"].astype(str).str.strip())

print("Sample players:", len(sample_ids))
print("Players with calculation data:", len(calc_ids))
print("Calculation players not in sample:", len(calc_ids - sample_ids))
print("Sample players without calculation data:", len(sample_ids - calc_ids))

Sample players: 1000
Players with calculation data: 629
Calculation players not in sample: 0
Sample players without calculation data: 371

### Observations:
* Fide calcualtion data is now complete
* The 629 players have detailed opponent/tournament data from FIDE calculation pages.
* The 371 players without calculation data likely had one of these cases:
     * No Standard-rated games in the feature window.
     * They were present in rating lists but did not have monthly calculation details.
     * They had activity captured in monthly Gms, but FIDE calculation page did not expose tables for those months.
     * Their games may be outside Standard format if we only used rating_type = 0.

This is still useful because the main dataset remains the FIDE monthly rating panel, and the calculation-page data becomes an enrichment layer. This aligns well with the capstone’s planned use of FIDE rating history as the core dataset and tournament/opponent variables as enrichment features.